### PR TITLE
Added DrawHoverTextEvent

### PR DESCRIPTION
**Pull request by iLexiconn**
This event can be used to alter the tooltip's text, or completely stop rendering it.
Example mod: http://pastebin.com/Ajs5fE5M
This is my last attempt. Git kept messing up and stuff. This patch should be good to go.

### CODE REVIEW

**Comment by mezz** [comment]
Can you explain the purpose of this?
If you created the element that has a tooltip, you can stop its tooltip.
If you created the `GuiScreen`, you can override `drawHoveringText`.
If you didn't create the element or the `GuiScreen`... I don't really understand what you are doing?

**Comment by iLexiconn** [comment]
I want to use this event for my new mod, so I can change the tooltip backdrop in some guis.

**Comment by squeek502** [comment]
This does have a worthwhile use case, but it needs a few more parameters in the events: `toolTipX`, `toolTipY`, `toolTipW`, and `toolTipH` 

[I use ASM to provide exactly that functionality in AppleCore](https://github.com/squeek502/AppleCore/blob/master/java/squeek/applecore/asm/module/ModuleDrawTooltip.java#L74-L117) so that it is able to [draw icons relative to the bottom of the tooltip](http://i.imgur.com/X9d4BHV.png).

An event that provides the coordinates and dimensions of every tooltip that is drawn would be extremely useful for any mod that draws overlays on the tooltip (e.g. Thaumcraft).

Here's the full render code for the AppleCore tooltip overlay (very messy): https://github.com/squeek502/AppleCore/blob/master/java/squeek/applecore/client/TooltipOverlayHandler.java#L109-L277

**Comment by iLexiconn** [comment]
There's only one problem; I don't think I have access to those fields yet
in the phase this event gets fired. You can always calculate it yourself in
the event.

**Comment by mezz** [comment]
@squeek502 wouldn't you be better off with an improved `ItemTooltipEvent` which already has the `ItemStack` in the event?

@iLexiconn I still have no idea what you're doing. Which tooltips from which GUIs are you changing?

**Comment by squeek502** [comment]
@mezz, any event that provides tooltip coordinates/dimensions would work for the use case I'm talking about. But, the width/height can only be calculated after `ItemTooltipEvent` is fired, as it's impossible to calculate the width/height of a tooltip without first knowing the full string first.

So, a separate event would be necessary, and that separate event would make the most sense if it was fired where the width/height was actually calculated (`GuiScreen.drawHoveringText`).

Here are the specific variables I grab through ASM from within `net.minecraft.client.gui.GuiScreen.drawHoveringText`:

```java
LocalVariableNode x = ASMHelper.findLocalVariableOfMethod(method, "j2", "I");
LocalVariableNode y = ASMHelper.findLocalVariableOfMethod(method, "k2", "I");
LocalVariableNode w = ASMHelper.findLocalVariableOfMethod(method, "k", "I");
LocalVariableNode h = ASMHelper.findLocalVariableOfMethod(method, "i1", "I");
```

**Comment by mezz** [comment]
@iLexiconn Is this PR still needed now that this other one has been pulled? https://github.com/MinecraftForge/MinecraftForge/pull/3034

**Pull request closed without merging**
