### PR TITLE
[1.11.x]Implemented overlay control for stacks and armor models

### PR DESCRIPTION
**Pull request by RANKSHANK**
Updated/bump version of #3093 for 1.11.x at the request of @mezz

Same thing, allows for manipulation of ItemStack and ArmorModel overlays when hasEffect() returns true. I've changed(and hopefully improved) quite a bit of the internal structure, so peer review is once again necessary.

## Notable Changes
Getters are now located in Item.class. Currently they redirect to their respective ___OverlayManager.get___() methods
Deprecated the map registry methods as the base behavior. Modders are encouraged to directly override the getters to forgoe extraneous map look ups on their own items. Also will help to reduce map lookup cost in large packs in the advent that effect changing becomes commonplace.
The vector methods now pass the required arrays instead of returning them to discourage modder retardation. However modders need to 'reset' these arrays as they are staticly held. This means only the tard's items should come off shonky.
Passes are now hardcoded as singular methods for direct invocation as opposed to multiple calls that are encompassed by frames. *theoretically* more efficient. Byte code looks cleaner at the very least :P
Split the color handling off into its own interface. This means that modders no longer need an overlay handler if they only want the color changed. Unfortunately it means another lookup per item but I've deemed it as a necessary evil.
Added Forge license headers.
Renaming for the sake of clarity.
Moved the classes to their own package in client/overlay. 6 classes seemed to be a bit of a clog.

### TODO
Debating on a custom ResourceLocation implementation for textures that gleans ID's from a map on RSS reload for fast lookup/comparison. Would be very useful for people that batch Item rendering.

### CODE REVIEW

**Comment by mezz** [comment]
Looking pretty good.
If the armor getter stuff has been relocated to `Item` and isn't armor-specific, can you rename them to sound more generic? If it is armor-specific, shouldn't it go on `ItemArmor`?

**Comment by RANKSHANK** [comment]
Ahh bit of a derp there. The LayerArmorBase class does an instanceof check for ItemArmor.

I've moved the corresponding methods to the ItemArmor class.

**Comment by mezz** [comment]
>Deprecated the map registry methods

Using `@Deprecated` on methods like that is a code smell, something's not quite right.
Having two ways to do this isn't a very good idea imo.

You can use `IdentityHashMap` for higher performance on your maps that use unique keys like the item delegate.

Can you explain your TODO more?

**Comment by RANKSHANK** [comment]
The `@Deprecated` methods are there only for overriding Items without handlers (predominately vanilla items) without using a substitution. It's something that'd be easy to remove as it's only there as an additional avenue at the moment.

Thanks for the tip on the maps, will definitely apply a change if they're decided to be necessary or not.

As far as the todo, I was thinking of having a wrapper for RssLocs that'd be assigned an int base ID value. The overlay managers would only accept these wrapped locs, and the Id's would allow for easy comparison, and also allow for the GlTextureId's to be baked in, stepping over additional map lookups in the rendering pipeline.

**Comment by RANKSHANK** [comment]
So after sitting on this for a bit I've realized that the map approach is not functionally robust enough. And thus a new iteration.

This approach uses subscription wrappers. These are stored in the Item instances themselves , removing the need for maps entirely. The wrappers are used when the first handler is subscribed to the item, otherwise the fields only hold a pointer to the default 'vanilla' implementation. When one or more subscriber exists, the wrapper selects the first subscribed handler that accepts the item to handle the overlay.

This will allow, as an example, per enchantment based handlers to be applied to any Items that can receive the enchant.

**Comment by mezz** [comment]
Ok this looks like it's going in the right direction!

Couple things though:
 *  There is no such thing as "holding onto a pointer" in Java.
 *  What's up with this subscription and manager business? Why aren't we just setting a handler?

**Comment by RANKSHANK** [comment]
My bad on the pointer. I should have said reference.

The subscription/wrapper(*probably a bad name but I drew a blank*) system is to allow for cascading handlers. Say Mod A) sets up a handler that renders a different overlay for the fire aspect enchant, and Mod B) adds a combat skill that uses ItemOverrides signify the overcharge of weapons when a trinket is held in the offhand. With a subscription/wrapper all swords in the registry can have both overlays available.

The issue here is the load order becomes important since the overlay will be whichever valid handler was registered first.

**Comment by RANKSHANK** [comment]
Closed as I can't git for shit.

**Pull request closed without merging**
