### PR TITLE
Added a way to save custom data in villages

### PR DESCRIPTION
**Pull request by lumien231**
This is basically like the customEntityData for entitys except for villages. It allows modders to save extra data to villages.

Example Mod: http://pastebin.com/d6MA9Scz
Marks every village that a player visited as "visited".

### CODE REVIEW

**Comment by LexManos** [comment]
Preemptively saying no to this as if this was added it would probably be best to do it in a generic way that supports all structures not just Villages.
If this functionality isn't already supported, Could of sworn there was something like this already in the game.

**Comment by lumien231** [comment]
Maybe i'm missing something but there is nothing like villages in vanilla minecraft right? They are the only "structure" that hold data independently / on top of their representation in the world. Would a generic way just be "something" that exists in the world at specific coordinates that ticks and can save data but is not a block or an entity?

I also wouldn't describe a village as just a structure. In contrast to for example a nether fortress or the stronghold it doesn't just exist "in the world" as blocks but actually holds data like player reputation and village agressors.

**Comment by LexManos** [comment]
Nether fortresses, witch huts, strongholds, they all exist as structures in memory at runtime.
They are all serialized to disk in the structures file.
Everything runs through the same 'MapStorage' functions.
Throwing a generic event in there would allow people to attach data to well.. anything.

**Comment by lumien231** [comment]
So just events like WorldSavedDataEvent.Save & WorldSavedDataEvent.Load ?

**Pull request closed without merging**
