### PR TITLE
[1.13.x] Added tags for small mushrooms and mushroom blocks

### PR DESCRIPTION
**Pull request by mcenderdragon**
I did not edit the recipes by intension, as the mushroom soup is designed to accept only red and brown mushrooms.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Couldn't the red/brown mushroom tags be taken to mean "red and brown mushrooms"? Isn't that the whole point of oredict/tags, to extend the vanilla concept of an item for mods which introduce interchangeable content?

**Comment by mcenderdragon** [comment]
I am not sure what you mean. Currently only block tags are added and not item tags, but I can also add item tags so the item soup can get expanded.

**Comment by LexManos** [comment]
Merge with https://github.com/MinecraftForge/MinecraftForge/pull/5567 and any other PRs for extra tags.
Much like typo fixes I am not going to accept 1,000 minor PRs for tags.
Instead you should speak with everyone and gather a full list that people would like.

**Comment by tterrag1098** [comment]
Manually merged into omnibus: #5609

**Pull request closed without merging**
