### PR TITLE
Added hook for additional TileEntityItemStackRenderer calls

### PR DESCRIPTION
**Pull request by Parker8283**
This is a remake of #1597, though pointed at the master branch. [Here's a more detailed explanation of what this PR is for, what this fixes, and why it should be pulled.](https://gist.github.com/Parker8283/7185768a39450f00842f)

EDIT: Yes, I could've easily typed all the things in the gist linked into this, but I decided to do it there. Don't ask :P

### CODE REVIEW

**Comment by RainWarrior** [comment]
Pros:
  - No need to make custom models for TE inventory icons

Cons:
  - Potentially worse performance
  - Possibility of messing up GL state
  - Need to handle the world object being null in the TESR's TE (and maintain a clear distinction between in-world TE and dummy inventory TE)

Overall: If this does allow something that's not possible with the current system, but is needed - it's worth considering - but only with providing the same functionality to the non-TE blocks and normal items. If not - then the only benefit doesn't outweigh the drawbacks.

**Comment by Parker8283** [comment]
So what do you think would be a good solution to this problem?

**Comment by RainWarrior** [comment]
Don't register TE as a builtin renderer, provide a normal block model.

**Comment by Parker8283** [comment]
So don't extend the vanilla system to modders? How do we render custom chests like vanilla does?

**Comment by RainWarrior** [comment]
Make a static model for the chest. (If you always render the lower bottom with the block model it'll even help with performance)

**Comment by LexManos** [comment]
Fry it may be worth looking into extending a animation based model system to this.
We dont want to expand the 'vanilla system' to modders because this is the legacy vanilla system that is going away, and exposing more direct GL access is bad and just causes modders to break things.
So if a solution can come forward that adds more power but doesn't destroy the GL barrier that'd be awesome.

**Comment by Parker8283** [comment]
When you render as a TESR-only block (like vanilla chests), you use the BuiltInModel. If you look at Vanilla Chests Item model, they just have a parent of `builtin/entity`, which is how it calls the TEISR. Inheriting from a non-existent block model in the item model would cause problems, as, well, the block model doesn't exist in json format.

**Comment by RainWarrior** [comment]
> Fry it may be worth looking into extending a animation based model system to this.

Yes, most vanilla TESRs can be implemented as simple renderings of animated forge models already. It's not a simple 1-liner yet, but I hope it'll be eventually.
> When you render as a TESR-only block (like vanilla chests), you use the BuiltInModel
Don't use that then. There's nothing stopping you from using both TESR and block model, which is what I'm suggesting.

**Pull request closed without merging**
