### PR TITLE
Reuse multipart model instances across variants

### PR DESCRIPTION
**Pull request by bs2609**
This PR changes `ModelLoader` to reuse multipart `IModel` instances which correspond to a single `ModelBlockDefinition`, instead of creating a new version for each variant. This is similar to the vanilla `ModelBakery`'s handling of multipart models.

Resulting change in baked model counts from a clean vanilla+Forge instance:

* `SimpleBakedModel`: 9,259 -> 2,638
* `WeightedBakedModel`: 600 -> 36
* `MultipartBakedModel`: 649 -> 31

`BakedQuad` instances: 52,783 -> 26,619

This brings the numbers into line with vanilla, which has these model counts:

* `SimpleBakedModel`: 3,024
* `WeightedBakedModel`: 36
* `MultipartBakedModel`: 31

`BakedQuad` instances: 36,883

Note: the lower Forge numbers are due to the Forge-specific implementation of item models (384 `BakedItemModel`s containing 10,230 `UnpackedBakedQuad`s).

Memory savings are around 20-30 MB, due to the overlap in the retained heap usage of the various classes it's tricky to give an exact number.

### CODE REVIEW

**Comment by bs2609** [comment]
There's also a slight reduction in bake time: from 0.45-0.5s to 0.3-0.35s.
(due to the reduction in distinct `IModel` instances from 3,340 to 2,722)

**Comment by bs2609** [comment]
See [this gist](https://gist.github.com/bs2609/b85b672bbef7e01ca5311342eb242571) for details of the models affected by this change.

**Comment by covers1624** [comment]
Can we get some stats of this change in a large pack?

**Comment by williewillus** [comment]
^ it's easier to see the benefit in a huge pack (remove foamfix to get an accurate measurement though)

**Comment by LexManos** [comment]
This raises the same concerns as FoamFix does, to a lesser extent. What happens in the case of a mod modifying it's model. It potentially leads to unintended side effects.
So at the very least if this is to be considered there needs to be a way to disable it if user notice side effects.

**Comment by williewillus** [comment]
re: ^ in this specific case, things *should* be okay because `IModel` instances are supposed to be immutable (every call to retexture, process, uvlock, etc. produces a new immutable IModel)

**Comment by bs2609** [comment]
I don't believe this will cause any unwanted side-effects for mods altering models 'correctly'. I also don't think this creates any new side-effects that could not occur currently, it mainly expands on existing opportunities for breakage.

To clarify, the `ModelLoader` code is already written on the basis that multiple model locations can refer to a single model. If it was desired to change the model for a single location only, that location can simply be mapped to a new model.

As this moves closer to Vanilla behaviour rather than diverging from it, I don't think a config is required for strict compatibility reasons. If there is some other problem, I'd be happy to discuss it, but more details would be required, especially as, if there is a genuine use case, it would be better to not rely on a global config option to support it if possible.

**Comment by bs2609** [comment]
With this released, here's some modpack-sized numbers:

Change in baked model counts from Forge 2691 -> 2701:

* `SimpleBakedModel`: 135,515 -> 94,313
* `WeightedBakedModel`: 4,191 -> 375
* `MultipartBakedModel`: 4,014 -> 230

`BakedQuad` instances: 1,342,420 -> 1,090,610

~140MB heap usage reduction.

**Pull request merged**
