### PR TITLE
Fix bar rendering

### PR DESCRIPTION
**Pull request by fewizz**
l1
-->
l12

### CODE REVIEW

**Comment by williewillus** [comment]
what's the difference?
the images are differently sized as well

**Comment by fewizz** [comment]
@williewillus , 3 is not 3.5 (7 / 2)

**Comment by LexManos** [comment]
What? And no, this reintroduces division by zero issues that then line was specifically changed to fix. The current one is fine, it's close enough we don't care

**Comment by fewizz** [comment]
@LexManos , drawBox(b.getSteps() == 0 ? (barWidth - 2) : (((barWidth - 2) \* b.getStep()) / b.getSteps()), barHeight - 2);

**Pull request closed without merging**
