### PR TITLE
Added a brewing recipe registry system

### PR DESCRIPTION
**Pull request by ganymedes01**
This is based on #1786 but with the tweaks requested by Lex. (Tried to squash my commits but failed, so I figured I'd just make a new PR. Sorry.)

Adds a versatile recipe registry for the brewing stand.
Vanilla behaviour is maintained but moved to a separate class.

### CODE REVIEW

**Comment by cabralRodrigo** [comment]
@ganymedes01 First of all, the API looks great :)

But, I've just one question, really exists the necessity of make the api compatible with modded brewing stands?

**Comment by ganymedes01** [comment]
@cabralRodrigo If a mod wants to add an electric brewing stand or something along those lines, it should still be able to use the API if it wants to.

**Comment by tterrag1098** [comment]
Any chance of this being done against the 1.7.10 branch as well? @cpw Would something like this be merged?

**Comment by ganymedes01** [comment]
If this one gets merged I'm making one for the 1.7.10 as well

**Comment by tterrag1098** [comment]
Neato :)

**Comment by ganymedes01** [comment]
Nearly a month's gone by and nothing...

I wonder why people are getting so "shy" when it comes to contributing to forge >_>

**Comment by tterrag1098** [comment]
It's a mystery...

**Comment by LexManos** [comment]
Because this has no explanation of its function.
Doesn't have any test cases.
Doesn't show that it keeps vanilla compatibility on something that is as black magic as potions.

**Comment by ganymedes01** [comment]
I can't fix an issue I don't know about. Feedback is important!

As for the test case: It may be a rule for a while, but no one bothered to put it on the "[If you want to contribute to Forge](https://github.com/MinecraftForge/MinecraftForge/wiki/If-you-want-to-contribute-to-Forge)" page... Where should I put the test case and are there any guidelines on how it should be written?

**Comment by LordIllyohs** [comment]
[CONTRIBUTING.md](https://github.com/MinecraftForge/MinecraftForge/blob/master/CONTRIBUTING.md)

**Comment by ganymedes01** [comment]
Thank you :3

**Comment by ganymedes01** [comment]
Added the test case and documented a bit more.

Anything specifically that needs documentation? The entire API has javadocs explaining how the methods work and the patches have comments that say where the code's been moved to (and there I explain what the code does).

What do you think lex?

**Pull request merged**
