### PR TITLE
Update BrewingRecipeRegistry.java

### PR DESCRIPTION
**Pull request by CrafterKina**
I removed unnecessary conditional expression.
It does restriction of freedom.

### CODE REVIEW

**Comment by ganymedes01** [comment]
You already won't be able to add recipes without items that don't have the maxstacksize set to one because of (this) [https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/brewing/AbstractBrewingRecipe.java]

That second check is there only in case someone doesn't use the AbstractBrewingRecipe (which means the registry wouldn't blow up even if the recipe used inputs with max sizes greater than 1)

**Comment by CrafterKina** [comment]
I know that brewing stand required to be stacksize of the result slot is 1.
However, the maxstacksize can be above 1.
Now specification is inconvenient if modder would like to apply the brewing system other than potions.

**Comment by ThePsionic** [comment]
In that case, the modder should make his own brewing system, not expand on the vanilla one in a hacky way.

**Comment by CrafterKina** [comment]
OK. I understand.
I do it myself.

**Pull request closed without merging**
