### PR TITLE
Add an interface for multipart entity parts

### PR DESCRIPTION
**Pull request by Fadenfire**
Adds an interface that multipart entity parts can implement, allowing for other modders to get the root entity of multipart entity part.

### CODE REVIEW

**Comment by jredfox** [comment]
Same issue can't find entity due to there being no default method for this. 

I don't simply see how changing this would cause all entity parts from various mods be able to get the main entity. Simply editing the ender dragons class won't fix other mods. Your branch needs to work with all other mods for get main entity. Fix otherwise it would be the same thing as hard coding the enderdragon entity part get enderdragon obj. So make it so any entity part modded or vanilla would get the main entity.

**Comment by jredfox** [comment]
Don't just use entity living base use entity living as well just in case a mob is entity living and not entity living base. Fix that up and then maybe forge would add it.

**Comment by jredfox** [comment]
Ok entity would work I guess.

What does changing the ender dragon's class have to do with getting main entity from parts?  I suggest you make the method to get any entity modded or vanilla from it's parts rather then hardcoding vanilla classes.

For example event handler event.target returns part checks then tries to get entity from entity part from method and then it returns the entity. Make it work like that not hard coded.

**Comment by Daomephsta** [comment]
@jredfox 
1. EntityLiving extends EntityLivingBase. Using EntityLiving instead of EntityLivingBase would be more restrictive, not less.
2. What you are asking is physically impossible. There is currently no standard way of making a multipart entity, there are many independent implementations. Because there is no standard it is impossible for Forge to determine which entities are multipart and which are not. This PR adds a standard, which modders will need to implement. It patches EntityDragonPart so that it conforms to this standard. 

@Silly511 
I think this PR should also patch IEntityMultipart to have a getParts method similar to the one in EntityDragon. It should also patch it to use IMultipartEntityPart instead of EntityDragonPart.
This would break binary compatibility though, so the PR would need to be retargeted at the next breaking version of Forge.

**Comment by jredfox** [comment]
Your wrong make forge in such a way that in order to use the multi part entity interface they have to forge's which has the get entity method.  That's the only way. Yes mods will have to update but, this is the easiest way for modders rather then hacks to get the entity.

**Comment by Daomephsta** [comment]
@jredfox 
Are you saying that IEntityMultiPart should have a method like this?
`public IMultipartEntityPart[] getParts();`
That is a good point.

**Comment by Fadenfire** [comment]
@Leviathan143 I was patching IEntityMultiPart with a getParts method until I saw that it took a instance of EntityDragonPart. You are right though, I'll chage it back and @LexManos can merge this into the 1.11 branch when it comes out.

**Comment by LexManos** [comment]
Why not just have entities with multiple parts use subclasses of EntityDragonPart. Yes the name would be a little weird but nothing in that class is explicitly needs the parent to be a dragon.
This would be the simplest method to do this. 
If Vanilla had any other MultiPart entities, I would bet you this class would be renamed to something along the lines of EntitySubPart.

**Comment by jredfox** [comment]
But, if you only kill a part then it won't kill the same thing which is what this idea is for.  You have to make it in a way where it would do something for the entire entity multipart not just the one thing.

**Comment by LexManos** [comment]
Dont 'kill a part' kill the parent. Or in the case of EntityDragonPart it forwards all damage to the parent so this is exactly what you want.

**Comment by mezz** [comment]
There is an MCP issue open to name this dragon part stuff more generically: 
ModCoderPack/MCPBot-Issues#307

**Pull request closed without merging**
