### PR TITLE
Made the slash optional in fml confirm/cancel.

### PR DESCRIPTION
**Pull request by DaemonUmbra**
Missing registries in this case being registries renamed without proper remapping or created by mods that were removed.

### CODE REVIEW

**Comment by LexManos** [comment]
Why did you combine two completely different things?
And why did you remove the slash....

**Comment by DaemonUmbra** [comment]
The combination part was because I found the missing registries issue while working on making the slash optional and didn't think to split the two changes.

The removing the slash part is to make `/fml confirm` and `fml confirm` equivalent.

**Comment by LexManos** [comment]
yes, but the question is why do we WANT them to be equivalent.
A command is a command... It should have a / identifier.

**Comment by DaemonUmbra** [comment]
On a dedicated server the `/` is optional for commands, so when the user is prompted for `fml confirm/deny` they assume the `/` to be optional like it is once the server is running. This has caused confusion when they omit the slash and nothing happens. (#6279)

**Comment by DaemonUmbra** [comment]
The change to RegistryManager is now #6292

**Pull request merged**
