### PR TITLE
Data fixer API and Data Fixer for old forge spawn eggs

### PR DESCRIPTION
**Pull request by diesieben07**
Started in #2587.

### CODE REVIEW

**Comment by LexManos** [comment]
What we SHOULD do is go through and edit the system to keep track of a list of fixes that have run.
And stop this nonsense 'fixer version' thing.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature, Cleanup]

**Comment by diesieben07** [comment]
Based on the discussion (read: mostly monologue) in IRC possible solutions I managed to come up with:

1. Store a list of `int`s (IDs for fixers, maybe via a forge registry?) per "thing" (entity, chunk, itemstack, ...) of fixers that have run for this "thing"'s data.<br>**Issues****:**
    - Possible save-size expansion.
    - How to get this list into every "thing"'s NBT data including custom ´IFixType´s?
2. Keep an ever incrementing forge-data-version number stored in the level.dat alongside with a mapping fixer=>version. Store the number also in every "thing", then we can know which fixers have not been executed for each "thing".<br>**Issues****:**
    - Not sure if this is even correct. It works in my head, but please comment.
    - Same as above, how to get this number stored everywhere?
3. Let mods decide themselves when they want to run, fixers are registered alongside a `Predicate<NBTTagCompound>` (or do an instanceof check on the fixer itself, same deal).<br>**Issues****:**
    - Probably going to slow down save-file loading a good deal since we cannot short-circuit iterating (and checking) every fixer.
4. Ask each mod that wants to use a fixer to provide a version number of their own and store them alongside the vanilla version tag.<br>**Issues:**
    - Possible save-size explosion?

<hr>

I am leaning towards approach 4 since it seems the simplest to implement and it also let's use use the otherwise completely unhelpful `getFixVersion` in `IFixableData` sensibly.

Comments? @LexManos @williewillus

**Comment by williewillus** [comment]
4 sounds sensible but we still have to store a tag per mod per thing
"DataVersion_Botania": 1
etc.

**Comment by diesieben07** [comment]
Yes, hence my one concern with it.

**Comment by williewillus** [comment]
maybe restrict it so that only mods that have opted-in to the fixer system get that tag stored

**Comment by LexManos** [comment]
> Store a list of ints (IDs for fixers, maybe via a forge registry?) per "thing" (entity, chunk, itemstack, ...) of fixers that have run for this "thing"'s data.
There is no need to have this data on anything more then the chunk itself.

**Comment by diesieben07** [comment]
It has to at least exist in every chunk, level.dat and player.dat file. And then we need a ton of patches since this information needs to be passed through to all the methods that currently only take an int. But... if that's fine by you...

**Comment by LexManos** [comment]
Storing on the chunk/level/player is fine. But this can be done in a better way then messing with the functions that pass ints.
See what you can do.

**Comment by cpw** [comment]
This PR is unworkable as you can see. Please rebuild for 1.10.x branch. Also, provide context?

**Comment by diesieben07** [comment]
Yes, I know, I simply forgot to close this. I did not really have time to work on this so I kinda left this abandoned, sorry.
What do you mean by "provide context"?

**Pull request closed without merging**
