### PR TITLE
Changed configuration to work with java streams, File specific

### PR DESCRIPTION
**Pull request by elix-x**
This should allow a lot easier configuration synchronization between server and client, because we have io.netty.buffer.ByteBufInputStream and io.netty.buffer.ByteBufOutputStream.

Also made Configuration not file specific, and save and load methods file specific.
Not 100% sure about that one.

Changes:
-Added java streans read and write methods (InputStream & OutputStream).
-Added file specific save and load methods.
-Depreaceated "file", save and load should be file specific?

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by diesieben07** [comment]
Why not just add a secondary constructor that takes a `CharSource` and `CharSink`? Then you can keep the entire API the same (and the other constructors just redirect through `Files.asCharSource` / `Files.asCharSink`.

**Comment by elix-x** [comment]
It can work, but in here, i want to remove file (or any other source association field) from configuration. I moved all that speification to save and load methods in form of streams (so we, for example, can use ByteBuf streams to sync conigurations between client and server) and you can load and save to same configuration instance.

**Comment by diesieben07** [comment]
That is what I am advocating as well. Instead of a `File` field in Configuration, have `CharSink` and `CharSource`. But then you can still have the load / save methods that exist now and you can keep the existing File constructor (as a convenience thing which just redirects to the source/sink constructor).

**Comment by elix-x** [comment]
I'll do that. Also, should i push new commit here, or create new PR targetting master or 1.9.4?
Also, i will have to remove `.getFile`. This may cause compile problems at first, but private event fields caused more :laughing: .

**Comment by diesieben07** [comment]
You can make `getFile` work for file based configs and throw `UnsupportedOperationException` for non-file based ones.

**Comment by elix-x** [comment]
Ok. So should i keep pushing here or retarget master?

**Comment by diesieben07** [comment]
You might want to target 1.9.4 or master (not sure), but definitely not 1.9.

**Comment by elix-x** [comment]
Ok. I'll add CharSource & Sink and retarget 1.9.4.

**Comment by elix-x** [comment]
From now, refer to #2887.

**Pull request closed without merging**
