### PR TITLE
Fixed TileEntity#getRenderBoundingBox not offsetting correctly causing more TEs to render then needed

### PR DESCRIPTION
**Pull request by mezz**
Backport #3709 to 1.10

### CODE REVIEW

**Comment by liach** [comment]
So weird that you merged it on your own

**Comment by LexManos** [comment]
I told him to, he didn't need to make a PR for it. But meh.
Mezz is trusted, him and a few others are being tried out as members of the team.
He's doing really well as the PR/Issues manager.

**Comment by mezz** [comment]
I removed the forge remote push target from my git client so that I don't accidentally push directly, so it was easier for me to just make a PR.

**Comment by LexManos** [comment]
See, this is why I trust you :P

**Pull request merged**
