### PR TITLE
[1.21.1] Add more `c` fluid tags

### PR DESCRIPTION
**Pull request by PaintNinja**
Adds `c:experience`, `c:potion`, `c:suspicious_stew`, `c:mushroom_stew`, `c:rabbit_stew` and `c:beetroot_soup`.

The experience tag is new, the others are promotions from the `forge` namespace in accordance with our policy for adopting `c` tags, as they are now common across all loaders (including Forge once this PR is merged).

Note: The measurement unit used for experience fluids differ between Neo and Fabric. Neo uses mb, while Fabric uses droplets. I've adopted the mb measurement in the javadoc for this Forge PR to line up with other fluid tags already in Forge.

Syncs with https://github.com/FabricMC/fabric/pull/4134 and https://github.com/neoforged/NeoForge/pull/1573

### CODE REVIEW

**Comment by LexManos** [comment]
Should we setup a standard to just bulk grab these things once a week or something? Or have them all in one PR until it gets merged.
Again this is your section of the project so you're the one authorizing the pull.

**Comment by Jonathing** [comment]
I would also vote in favor of a once-a-week check for c tags, since that's still rather frequent. There will inevitably come some painful week where these common tags have an update on each day.

**Review by Jonathing — APPROVED** [review]

**Comment by PaintNinja** [comment]
Sounds good to me, I'll special-case the review process for tag sync PRs accordingly.

I did multiple PRs because it's easier for me to do stuff in little chunks, but I guess it depends how often the de-facto spec changes. Weekly checks sounds good, especially if we could get some GH Actions automations wired up with CommonTagsDumper to notify us of common tag changes and verify the PRs match.

**Comment by Jonathing** [comment]
Since this PR has not been merged yet, I'm going to hold off on making a port to 1.21.3 for now. Assuming this PR is still targeting 1.21.1 (which it should), I'll make it after it gets merged so I can cherry-pick the merged commit without needing to squash it and still keep up with any changes that need to be made.

**Pull request merged**
