### PR TITLE
Renamed mcmod.info file to mcmod.json

### PR DESCRIPTION
**Pull request by iLexiconn**
Still searches for mcmod.info file if the json file can't be found.

### CODE REVIEW

**Comment by diesieben07** [comment]
This breaks all the things that are not forge which read this file.

**Comment by kashike** [comment]
There is really no point in this.

**Comment by iTitus** [comment]
If you really want to change the naming scheme you have to leave in some backwards compatibility.

**Comment by iLexiconn** [comment]
@iTitus That's what I did. It still loads the mcmod.info file if it can't find the json file.

**Comment by diesieben07** [comment]
Yes, but no mod will be able to adopt the new version without breaking software that still looks for the old one.

**Comment by iLexiconn** [comment]
I guess you're right. but programs can update, right?

**Comment by diesieben07** [comment]
Yes. But forcing this on the community for such a trivial change? Why?

**Comment by iLexiconn** [comment]
Because it _is_ a json file. Every other json file ends with .json, except this one.

**Comment by ThePsionic** [comment]
It's really not worth breaking backwards compatibility over, though.

> On Jan 18 2016, at 6:01 pm, iLexiconn &lt;notifications@github.com&gt;
wrote:  

>

> Because it _is_ a json file. Every other json file ends with .json, except
this one.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/Minecra
ftForge/MinecraftForge/pull/2387#issuecomment-172590571).

**Comment by diesieben07** [comment]
Should we rename [.mcmeta files](http://minecraft.gamepedia.com/Resource_pack#Animation) as well then? Oh and while we are at it, jar files are zip files! Such blasphemy! And so are [OpenDocument](https://en.wikipedia.org/wiki/OpenDocument) files, docx files and so on. You have a lot ahead of you it seems.
/s

**Pull request closed without merging**
