### PR TITLE
[1.9.4] Introduced Capabilities for World

### PR DESCRIPTION
**Pull request by Abastro**
This will allow compatibility between mods in World part.
(PR related with my suggestion #2877, note that server part is not
included here. port of #2913 for 1.9.4)

### CODE REVIEW

**Comment by liach** [comment]
imports in patches are bad.

**Comment by Abastro** [comment]
@liach There are no additional imports in the patches, The 'imports' is 'revealed' since I added  'implements {interface}' to the head of the class.

**Comment by gigaherz** [comment]
Out of curiosity, are the capabilities internally stored as a WorldSavedData? I'm currently at work so I can't spend much time reading the code, but that seems like what I'd have done. ;P

**Comment by Abastro** [comment]
@gigaherz Yes. I couldn't found better way to store it, and some vanilla hijacks like VillageCollection also uses WorldSavedData, so I just benchmarked them.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
