### PR TITLE
[1.12] Add a player sensitive version for Item#addInformation

### PR DESCRIPTION
**Pull request by maxanier**
## Why?
Mojang replaced the EntityPlayer argument in Item#addInformation (as well as Block#addInformation) by a nullable World. (Probably because they did not use it).

The player object might still be relevant for modders. 
For example I would like to only display certain informations to certain players, which fulfill some condition (mostly to keep the tooltip as short as possible as well as not to confuse the players with information they do not understand).  
[I can provide a more detailed example if requested]  

## How?
The Item#addInformation is only called in ItemStack#getTooltip (except for the overriding methods in subclasses). In that method the player is available if a world is available. So I don't see any reason to not pass the (nullable) player instead of the (nullable) world.  

This PR adds player sensitive versions to Block and Item (which call the vanilla ones by default), deprecates the vanilla ones, redirects the call in ItemStack#getTooltip to the new method and adjusts ItemBlock accordingly.  

## Alternative
An alternative to this PR might be to use the Minecraft.player in the mod code, but this is kinda ugly.
You decide if it is worth the patch

### CODE REVIEW

**Comment by kashike** [comment]
I don't see a reason to add this just to get access to the local client player, which is already possible as you said.

**Comment by maxanier** [comment]
I only came up with this workaround while working on this patch, decided to still submit it, so you can decide if it is worth it.

**Comment by williewillus** [comment]
I also think it's quite pointless. This method is SideOnly CLIENT which means it's only called on the one client player, as they're the only one you'd show tooltips to (showing tooltips to an EntityOtherPlayerMP makes no sense).

That being said, passing in the world in also makes no sense since there's only one, but /shrug

**Comment by maxanier** [comment]
Only minor issue with the workaround is, that ItemStack#getTooltip can be called with a null EntityPlayer. In this case the workaround would refer to the ClientPlayer instead of null.
 (No problem with Vanilla itself, because the only time it is called without a player is during startup and minecraft.player is null there anyways, might be a minor issue with other mods using this for stuff)

But after thinking a little bit more about this, I also think that this problem is not worth a patch -> Closing

Edit: The issue above can be avoided by using world==null?null:Minecraft.getMinecraft().player.

**Pull request closed without merging**
