### PR TITLE
Several fixes for PlayerInteractEvent

### PR DESCRIPTION
**Pull request by williewillus**
This PR does ~~three~~ ~~four~~ five things:

* Calling `setCanceled(false)` will no longer interfere with the useBlock/useItem `Result`'s in LeftClickBlock and RightClickBlock
* Fixes `RightClickEmpty` firing even if targeting a block or entity. It is intended to fire when the hand is empty and targeting nothing but currently fires whenever the hand is empty at all.
* Add a `LeftClickEmpty`, an event that fires whenever the player clicks empty space with any itemstack. This is useful for a variety of cases (I need it myself in Botania). Like `RightClickEmpty`, this is clientside-only because server is not aware of this action.

@Zaggy1024 has brought to my attention a (quite severe IMO but shouldn't be too difficult to fix) limitation of how I designed this PIE, but I wanted to do these small fixes in a separate PR before I attack that one (which is going to be pretty big).

### CODE REVIEW

**Comment by williewillus** [comment]
Fourth thing:
* Move hook point for `EntityInteractSpecific` to *after* an interact packet is sent to server. This is how all the other interact events work (client and server operate separately).

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by williewillus** [comment]
Fifth thing:
* Fix missing hook where `LeftClickBlock` should fire clientside in creative.
* Clarified some details about how `LeftClickBlock` behaves in creative mode

**Comment by williewillus** [comment]
I think I'm done adding things to this so bump for pull

**Comment by LexManos** [comment]
Why do we fire anything clientside at all?

**Comment by williewillus** [comment]
1. That's how the old one worked, which I was remaking
2. Desyncs. Changing things serverside and not clientside will make for a disaster because (read next point)
2. Side effect of how MC's interaction works as whole. Let me try to give as concise a rundown as I can

* CLIENT
    * LEFT CLICK (the easy stuff)
        * Is targeting entity? => attack entity, send attack packet
        * Is targeting block? => LeftClickBlock
        * Else fire LeftClickEmpty
    * RIGHT CLICK
        * Sequence of interactions. Minecraft *client* runs through each until it find one that "worked".
        * Try EntityInteractSpecific. SUCCESS? Stop.
        * Try EntityInteract. SUCCESS? Stop.
        * (OR) Try RightClickBlock. Meaningful result from onItemUse/onBlockActivated? Stop.
        * Try RightClickItem. Meaningful result? Stop. (OR) fire RightClickEmpty, noncancelable
        * If nothing has stopped us, loop for all hands

* SERVER => just process whatever client sent us from each discrete stage (entity interact specific, entity interact, right click block, right click item)

The point is that the client is the one responsible for running through all the interactions while the server just listens.

If we just canceled an interaction on the server the client would (first desync, but also) stop when we would logicaly want it to continue (since we just canceled an interaction).

The opposite is also true.
Let's say we right clicked a block in a situation where onBlockActivated is called but returns PASS, meaning interaction continues along the sequence.
However, let's say we listen to RightClickBlock serverside and force UseItem to true and onItemUse returns SUCCESS, a meaningful value. The client should now STOP trying to call RightClickItem, or any interactions for subsequent hands. But it doesn't know, it'll just keep going.

I'm not very sure if that was clear, but hopefully it gets the point across. Right click interaction really is a mess

**Comment by LexManos** [comment]
Screw it, update to master -.-

**Pull request closed without merging**
