### PR TITLE
Add smarter getter for block slipperiness (1.12)

### LINKED ISSUE #1342: Block.slipperiness should have a position sensitive getter
Signature: `(IBlockAccess, int, int, int)float`

Many of the same use cases as #1341. Also only accessed in locations where access to the x/y/z and world exist.

### PR DESCRIPTION
**Pull request by howtonotwin**
Duplicate of #3620 for 1.12.

> Allow a block access to the blockstate, world, position, and entity when getting slipperiness with new `Block::getSlipperiness` method. Change usages of `Block::slipperiness` to `Block::getSlipperiness` in vanilla. Deprecate old field.
> 
> [Boat Blaster](https://gist.github.com/howtonotwin/3ff1260ac20d6befbf0784708e30c14f) test mod gist. As per the name, it adds a block (`boat_blaster:boat_blaster`) that blasts boats at high speed (think a hundred blocks/tick) by using the new getter to give the block a slipperiness of `2` for `EntityBoat`s. It retains the default for other entities. ~~(Don't actually be in the boat when this happens. MC complains about the high speed and everything goes choppy and weird. Works fine as long as anything *but* a player is in the boat.)~~

1.12 has https://bugs.mojang.com/browse/MC-119811 instead, which this PR also patches.

> 
> Resolves #1342.

### CODE REVIEW

**Comment by mezz** [comment]
Tested and if I hop in a boat that's sitting on the test block, it moves very quickly as expected.
When I hop out of the boat and look back at the block, the boat reappears on the block and launches towards me a second time.
If this synchronization issue is vanilla, please link to the issue. Otherwise I think there may be something overlooked in this PR.

**Comment by howtonotwin** [comment]
As far as I can tell, it's just a visual thing. Additionally, If you wait a second before dismounting it doesn't happen, if you never mount in the first place it doesn't happen, and if you set the slipperiness to something sane like `1`, nothing supernatural happens.

**Comment by howtonotwin** [comment]
Any update, @mezz?

**Comment by williewillus** [comment]
The issue is indeed vanilla, if you boat a reasonably far distance in vanilla and dismount, your boat disappears and teleports back in after a few seconds. Not sure what the vanilla ticket is though

**Comment by mezz** [comment]
That's fine then. This PR looks good to me.

**Comment by LexManos** [comment]
File a vanilla bug report for the rubberbanding and link it in the code.

**Comment by mezz** [comment]
@howtonotwin any update?

**Comment by howtonotwin** [comment]
I couldn't reproduce @williewillus's bug, so I did some debugging and made this report instead: https://bugs.mojang.com/browse/MC-119811. I'm not sure where exactly I should comment this issue in the code. Maybe atop `EntityBoat::tickLerp`?

**Comment by mezz** [comment]
Tested and works as intended. Looks good to me.

**Comment by howtonotwin** [comment]
This should be good for merge now.

**Pull request merged**
