### PR TITLE
Use biome specific blockstate for every village structures block

### PR DESCRIPTION
**Pull request by DBLouis**
Modified StructureVillagePieces class  to get biome specific blockstate for every block of village structures. 

I really need this and I think it could help other modders too. Otherwise I have too use reflection or horrible hacks to do what I want.

See this [topic](http://www.minecraftforge.net/forum/index.php?topic=42040.msg223567#msg223567) for more information.

### CODE REVIEW

**Comment by LexManos** [comment]
1) Do not rename local variables, your pr is over 1000 lines and 90% is nothing but variable renaming. Seriously don't do it.
2) DO NOT Start a pr with threatening to hack shit in if we don't accept it. We do no respond nicely to threats, and it makes you look like an ass.
3) pretty sure we've discussed this hook before and the tests showed everything was replaceable. Maybe if you spent a little time and cleaned up this pr we would know exactly what was missing.

**Review by yuuka-miya — CHANGES_REQUESTED** [review]
Please don't rename local variables, it needlessly increases size of patches and basically makes your PR a lot harder to review.

**Comment by DBLouis** [comment]
Sorry about the renaming, I knew it would be a problem. I'm gonna undo it.
This is not a threat, this is just what I was doing before I realized it could be done in a few lines (without the renaming) by editing this patch.
About a third of the blocks are not replaceable. For example the church's cobblestone isn't.

I put the whole file in a [gist](https://gist.github.com/DBLouis/be6b4a1c26f0989ac85d85e128cb1bef), in case you need it.

**Comment by bs2609** [comment]
So [MC-103261](https://bugs.mojang.com/browse/MC-103261) is relevant here (also the image attached shows a good example of unreplaced blocks). Don't know how much the 'fix' for 16w35a actually affects things (has anyone taken a look at snapshot code?).

**Comment by LexManos** [comment]
So ya, more looking into this, we can't really fix it this way on our own because that would mean vanilla world gen is altered by Forge.
This isn't acceptable.
We would have to special-case each of these changes into a 'unless modders say so don't change it'

What vanilla/Mojang SHOULD do is move these strucutres to their schematic system, and use a pallet system that is filled in on a biome bases. It wouldnt be to hard, and it'd move all this hardcoded setblocks away. Making this class like 1/10th the size.

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by mezz** [comment]
I'm closing this for the reasons Lex gave. 
This patch is just too big, unless a cleaner solution can be found I think we should treat this as a vanilla issue.

**Pull request closed without merging**
