### PR TITLE
Save/restore dormant chunk entity data from NBT

### PR DESCRIPTION
**Pull request by bs2609**
This is another possible fix for #3897, and an alternative to #3914.

The dormant chunk handling is modified to save entities as NBT data. On load, the entities are recreated using the same process as in vanilla.

In order to do this, the call to `putDormantChunk()` is made earlier (before the chunk is saved to NBT), and a call to the new `storeChunkNBT()` method is patched in to `AnvilChunkLoader`. This allows us to use the vanilla entity serialisation that already occurs.
After the entity data has been associated with the chunk in the cache, the original entities are cleared from the chunk's data structures,

When a dormant chunk is fetched, it is repopulated with entities from the associated NBT data before being returned.

The advantage of this approach is that it is much closer to vanilla. The tradeoff is the added performance cost.

### CODE REVIEW

**Comment by bs2609** [comment]
Updated the PR to also mark `resetEntityId()` as deprecated - it's no longer needed by `ForgeChunkManager` after these changes, and mods shouldn't be using it directly. It can be removed later if this solution is chosen.

**Comment by williewillus** [comment]
I prefer this patch over the other, just because it's simpler, and is narrower in scope, meaning it won't break potentially as many things. Moving the entire chunk unload somewhere else is bound to break something, while this simply persists more data.

**Comment by williewillus** [comment]
Also, the NBT is still held in memory, which still offers a huge benefit over disk IO, so I don't think the performance hit is as considerable as it seems. (after all, vanilla does NBT ser/de a lot during normal game flow)

**Comment by bs2609** [comment]
One thing that is worth noting is that this does need the chunk entity (de)serialisation code to be maintained wrt vanilla.

On that note, if `AnvilChunkLoader.loadEntities()` were to be made a static instead of an instance method, it could be used instead of the `ForgeChunkManager` substitute.

**Comment by mezz** [comment]
After reviewing both, I think this is a much safer and less invasive approach to solving the issue.
The dormant chunks are a Forge feature, and we shouldn't get too aggressive with pursuing performance.
Can you update this for 1.12?

**Comment by bs2609** [comment]
Any update on this now that #4162 is merged?

**Comment by mezz** [comment]
Looks good, functionally it matches the 1.12 version.

**Pull request merged**
