### PR TITLE
1.12.x advancement load event

### PR DESCRIPTION
**Pull request by kindlich**
This Event is fired twice, once when the Forge hook methof 'Load Advancements'has been called, and once when its finished.
In more detail, the `Pre` event will be called after Vanilla MC has loaded its internal Advancements but before any mods' advancements have been added to the builder map.
The `Post` event will be called after all Vanilla and mods' advancements have been added to the builder map but before any of them were actually added to the advancement Manager.

This Event will expose the Advancement Builder Map which can then be modified if the mods don't want to rely on the JSON formats.

Reason for this PR is that I and others require a way of adding Advancements directly without the need of loading them via JSONs.

As the guideline wants a small example, here's how you would implement that:
```java
@SubscribeEvent
public static void onAdvancementLoad(AdvancementLoadEvent.Post event) {
    event.advancementMap.putAll(myMod.ADDED_ADVANCEMENT_BUILDERS);
}
```

I only changed forge classes, so I don't think I need any patchfiles here (correct me if I'm wrong, first-timer).

### CODE REVIEW

**Comment by kindlich** [comment]
Okay, so now I did change a MC class, because I may need to extend the Advancement Builder some time and the constructor is package-private.
Patchfile is about 790Bytes and simply adds `public` in front of the Constructor

**Comment by canitzp** [comment]
you could try a Access Transformer for the constructor instead of the Patch, but idk if this works

**Comment by kindlich** [comment]
ATs work on constructors?
I tried 
`public net.minecraft.advancements.Advancement$Builder <init> #Builder` which didnt work, but I'm not proficient with Ats...

**Comment by kindlich** [comment]
@canitzp Thanks for your input, seems like I can AT constructors, reverted the commit as its not needed then.

**Comment by Mathe172** [comment]
This is probably relevant: #4354 (along a few others)

**Comment by kindlich** [comment]
@Mathe172 Thank you for the link, I only checked open PRs and Issues :neutral_face: 

So, the usecase for me would be custom advancements that are added via ContentTweaker, a mod from TeamAcronymCoders that uses a ZenScript, a java parser, to allow people to add stuff to the game.
There are of course, other ways of doing that, but none really allow for good custom criterions and stuff, so I wanted to add an advancement Event.

Also, other mods like Reskillable, a mod from CodersAfterDark as continuation of Vazkiis Skillable, might want to hook into that event to check if advancements have been removed/modified during a `/reload` command, because, as of now, there is no easy notification that tells people that the server is reloading the advancements.

**Comment by kindlich** [comment]
Guess you guys don't like that PR then if you didn't even bother rejecting it or suggesting how to improve it, I was hoping for a good discussion...
Well, it was worth a try, have fun living your lives.

**Comment by Daomephsta** [comment]
@kindlich At any given time Forge has 100+ open issues and several dozen open PRs. If your PR hasn't got much attention it's not because it's being ignored. It's just that it's been missed or forgotten amongst all the other issues and PRs. Be patient, and if your PR seems to have been forgotten, ask mezz to take a look at it.

**Comment by kindlich** [comment]
Nah, I also read throught he other PRs and saw that it's not likely to be accepted anyway :stuck_out_tongue:

**Pull request closed without merging**
