### PR TITLE
Improve the warning logged for cascading world generation

### PR DESCRIPTION
**Pull request by bs2609**
This improves the log message generated when recursive chunk population is detected by adding info for the 'source' chunk, as well as the dimension's type name.

### CODE REVIEW

**Comment by mezz** [comment]
While you're doing this, can you check if the code for checking for vanilla with `if (activeModContainer == null)` still works?
Based on the attention vanilla's cascading worldgen has gotten, I'm wondering if Minecraft shows up as an active mod container now.

**Comment by bs2609** [comment]
Still seems to be the case, I put a breakpoint on the `debug` call and it got hit a lot in the nether (without the worldgen fixes).

**Comment by mezz** [comment]
Thanks, I guess people are just checking the full log for it.

**Comment by mezz** [comment]
For the Minecraft case, can you mention the `forge.configgui.fixVanillaCascading` config option? It should fix pretty much all the vanilla cascading issues but it's not easily discovered.

**Comment by bs2609** [comment]
Example log output for vanilla cases (changed to `INFO` here for testing):

```
[08:59:42] [Server thread/INFO] [FML]: Minecraft loaded a new chunk [-13, 18] in dimension -1 (the_nether) while populating chunk [-13, 19], causing cascading worldgen lag.
[08:59:42] [Server thread/INFO] [FML]: Consider setting 'fixVanillaCascading' to 'true' in the Forge config to fix many cases where this occurs in the base game.
```

**Comment by josephcsible** [comment]
I wonder if it's worth trying to do something like #4651 too.

**Comment by mcenderdragon** [comment]
Maybe with a config wich is disabled by default ? Something like cascading.strackTrace = false by default.

**Comment by bs2609** [comment]
Updated, conflicts resolved.

**Pull request merged**
