### PR TITLE
[1.7.10] Change permission levels on ore recipes parameters

### PR DESCRIPTION
**Pull request by ganymedes01**
Makes it easier for modders to extend from them

### CODE REVIEW

**Comment by ganymedes01** [comment]
*tumbleweed rolls past*

**Comment by LexManos** [comment]
Why?
Why would a modder extend these? They are fully implemented recipes.

**Comment by ganymedes01** [comment]
Well, in my case, I added an enchantment-sensitive recipe type but I also wanted it to be ore sensitive.
I had to copy/paste the entire ShapedOreRecipe class and then do my necessary edits just because those parameters are private... So, not like it's stopping modders from doing anything, but it's not really necessary to hide those field away is it?

**Comment by LexManos** [comment]
Eah fine whatever but not for 1.7.10.

**Comment by ganymedes01** [comment]
Fair enough :3
I'll re-do the PR targetting the 1.8 branch when I'm back at my laptop

**Pull request closed without merging**
