### PR TITLE
[1.18.x] move OnDatapackSyncEvent after tags and recipes are synced

### PR DESCRIPTION
**Pull request by Minecraftschurli**

### CODE REVIEW

**Comment by pupnewfster** [comment]
I am 99% sure the entire point of the event was to be before tags and recipes are sent see #7912

**Comment by MelanX** [comment]
Alternative: Pre and Post sub-event. Like a few other events.

**Comment by KnightMiner** [comment]
Yeah, pleaSe absolutely do not move it after. My mod relies on that context syncing first. Explain your usecase for moving it after.

**Comment by Minecraftschurli** [comment]
Closing since it was intended this way

**Pull request closed without merging**
