### PR TITLE
[1.13] Fix Block Registry not replaced by Forge GameData.getWrapperDefaulted

### PR DESCRIPTION
**Pull request by MajorTuvok**
Probably overlooked. I noticed it only because not a single Block Tag could be resolved when using ForgeRegistries.

### CODE REVIEW

**Comment by MajorTuvok** [comment]
Closed in the referenced commit

**Comment by tterrag1098** [comment]
Yo that commit is from 2015.

**Comment by MajorTuvok** [comment]
Whoops

**Comment by MajorTuvok** [comment]
I just saw it as a notification and though it belonged to 1.13 (why did it pop up as a notification anyway?)
(I just confirmed, that this is still valid)

**Comment by MajorTuvok** [comment]
(for reference closed in 7c0d94c)

**Pull request closed without merging**
