### PR TITLE
Dimension registry simplification

### PR DESCRIPTION
**Pull request by Gegy**
This PR simplifies the dimension registry to use just the `DimensionType` instance rather than both that and `ModdedDimension`.
Previously, this separation introduced complexity through having to register through two different events (and in the case of `DimensionType` registry, check to make sure the dimension isn't already registered)
It also caused issues in joining dedicated servers, where the `ClientWorld` could not be created due to the second event only ever being called on server, and never on the client.

Additionally, the `DimensionType` registry is now synced in the standard form removing the need for the specific `dims` tag in the save.

A lot of the previous design confused me. Apologies if I've completely missed the reasoning behind that design. x)

Also, this is a breaking change. But as I understand that should be fine given the beta status of Forge currently.

### CODE REVIEW

**Comment by LexManos** [comment]
Yes, you completely misunderstood the point of having the two different systems.
This doesn't allow for run time dimension creation, it doesn't allow for reuse of the dimension templates {ModDimensions}.
If I wanted to build the system with all the limitations of making the DimensionType registry static I would have.

Yes the old system is kinda stupid, but blame Mojang for that. They have DimensionType and Dimension BOTH being instance specific. It's something they are working on, but hadn't finished in 1.14.

**Comment by kirderf1** [comment]
Here's my experience and interpretation with the current two-part system.
I'd say that the big thing about the design is that the DimensionType, which is connected to a specific dimension, contains just the right parameters to make it possible to save it into data. This in turn is useful and used for two things:
- Send the data defining the DimensionTypes to the client to sync dimensions, removing the need for individual mods to register dimension clientside themselves
- Save the DimensionTypes to the world, which means that individual mods don't have to keep track themselves which dimension that they should register when a world is loaded
This may seem rather unneeded for those mods that always register one specific number of dimensions, and that number only.
But for mods that has a more dynamic approach to dimension (typically by creating new dimensions during gameplay, sometimes without any upper limit to how many can be made), this does a great deal to help sync and save such dimensions in what I'd say is a good and unified manner.

And as for the ModDimension registry: In order to make DimesionTypes possible to save, you'd have to seperate it from anything which can't normally be saves. This applies to the Dimension constructor. For this purpose, the non-saveable Dimension constructor is now instead in a saveable registry entry (ModDimension) which is being registered on both the server side and client side.

Hope this clears up some confusion on the previous design, and that you take this into consideration.

**Comment by Gegy** [comment]
Ah! I see, thanks for the explanations! :)
Sorry about that.
I do think I'll look some more into this, it seems that the `DimensionTypes` are never synced to the client in the current system, which causes an error when the client creates the `ClientWorld`.
Seems `DimensionRegisterMessage` is intended for that, but never used

**Comment by kirderf1** [comment]
On closer inspection, I seem to be getting an error myself now? I can't see how the code had changed, so I might've confused myself on the client sync part.

**Comment by Gegy** [comment]
The error can go unnoticed -- `SRespawnPacket` can fail quietly if the dimension doesn't exist. `SJoinGamePacket` breaks though

**Pull request closed without merging**
