### PR TITLE
Add "type" field to global loot modifier jsons and fix tests.

### PR DESCRIPTION
**Pull request by gigaherz**
To avoid binary breaking, "type" defaults to be the same as the filename.
Still sick so I'm going to need a sanity check on this. :P

### CODE REVIEW

**Comment by gigaherz** [comment]
The key change is 
https://github.com/MinecraftForge/MinecraftForge/pull/6554/files#diff-561423d31c6aff656e3a12b6de08223aR130-R135

**Comment by Draco18s** [comment]
Looks good to me. Thanks for fixing that up.

**Comment by Darkhax** [comment]
It seems good to me as well.

**Comment by Lanse505** [comment]
Looks good to me as well.

**Comment by gigaherz** [comment]
Rebased on top of latest forge, and split into two commits, for ease of review.

**Comment by Draco18s** [comment]
Related, I wrote up some documentation the other day
https://github.com/Draco18s/Documentation/commit/92be3774d6ffc3dc1cd9b78f1e31a2e74d9fa307
https://github.com/MinecraftForge/Documentation/pull/274
That will need to be updated when this PR gets merged.

**Comment by gigaherz** [comment]
Ah, I guess it will need a small mention of this new feature :P

**Comment by Draco18s** [comment]
Feel free to add the necessary details to what I did

**Pull request merged**
