### PR TITLE
Add getMaxExtract and getMaxReceive to IEnergyStorage and EnergyStorage

### PR DESCRIPTION
**Pull request by owmii**
Add `getMaxExtract` and `getMaxReceive` methods to `IEnergyStorage` and `EnergyStorage`

### CODE REVIEW

**Comment by Ommina** [comment]
Am I missing a subtlety here that prevents this from breaking any mod that implements their own `IEnergyStorage` ?

**Comment by KingLemming** [comment]
You are not, this is absolutely an API-shattering change. Useful? Maybe, but will completely mess everything up.

**Comment by Alpvax** [comment]
Could we not make them default methods (return max_int, or maybe -1) until the next breaking change window?

**Comment by KingLemming** [comment]
That would ultimately render them pointless, as they would be unreliable methods.

**Comment by LexManos** [comment]
So this is obviously going to be a no, not only for your completely breaking change, but also because you failed to provide any justification what so ever.
Why not just use maxExtract = extract(MAX_INT, true)?

**Comment by Alpvax** [comment]
I envisioned this more as a maximum if storage was full (e.g. for displaying to the user), rather than the maximum available to actually extract. Not sure what OP meant. That also potentially confuses things further.

**Comment by owmii** [comment]
> 
> 
> So this is obviously going to be a no, not only for your completely breaking change, but also because you failed to provide any justification what so ever.
> Why not just use maxExtract = extract(MAX_INT, true)?

Why i didn't think about it :p, Bdw, thank you!.

**Pull request closed without merging**
