### PR TITLE
Turn the loading status message into a queue. 

### PR DESCRIPTION
**Pull request by gigaherz**

### CODE REVIEW

**Comment by gigaherz** [comment]
With categories:
https://i.imgur.com/NGKLTIN.gifv

Without:
https://i.imgur.com/Ha1Ztae.gifv

**Comment by Niko-sk2x** [comment]
I could clearly see what it's supposed to do without categories, with categories I have no idea how it's supposed to work.

**Comment by gigaherz** [comment]
Yup, that test categorization is too coarse.

**Comment by SquidDev** [comment]
On a side note, is this still thread-safe? From what I understand of 1.14's loading, the statuses will be updated on a separate thread to where they are rendered, and so there's a potential for a CME on the message list.

**Comment by gigaherz** [comment]
Possibly, I didn't talk to cpw about thread-safety yet.

**Comment by Niko-sk2x** [comment]
~~before the vanilla progress bar, there are no threads. Once it switches to vanilla progress bar, the rendering is called from vanilla rendering code, on main thread.~~ I misinterpreted the question.

But it does look like setting message will need to be thread safe.

**Pull request closed without merging**
