### PR TITLE
Allow loading a texture for advancement icon

### LINKED ISSUE #5083: [Enhancement] Add custom icon for advancements
Now you can use `item` key for any item or block (in `icon` in an advancement json). For custom images you need to create a proxy item and register one for each image.
My idea is that it could also handle `image` with `ResourceLocation` so we don't need to create around 20 proxy items (in modpacks this number can grow a lot)

### PR DESCRIPTION
**Pull request by Nightenom**
This PR adds a way to use a texture RL for advancement icon. Now one can use item key for any item or block. For custom images, one needs to create a proxy item and register one for each image (see image below of the problematic method in net.minecraft.advancements.DisplayInfo).
#6010 might help to solve this problem a bit so my not so clean method is replaced by something better looking

Usage:
Edit: superseded by <https://github.com/MinecraftForge/MinecraftForge/pull/6055#issuecomment-522091646>
usage 

Closes #5083

mc_method

### CODE REVIEW

**Comment by LexManos** [comment]
Not a fan of this, firstly you have a lot of TODOs that show the issues with this.
Namely adding a fake item will break vanilla and networking compatibility.
If it wasn't for the limitations over the network, this wouldn't be a bad suggestion.

**Comment by Nightenom** [comment]
Actually, I have to agree that's not the best one, after digging a few days around it I would suggest using some nbt data to be able to change item appearance.
Back to this, the only todo I have to solve (but I don't know where to put it) is to register the item instance properly into item registry.
Then I'm not aware of any other problems (with vanilla compatibility, but will test it) since the icon reference is only used for rendering or advancement data transport (json or packetbuffer).

**Comment by Nightenom** [comment]
Okay, made the nbt solution instead (no fake item required), the fallback is to render an item provided as backing one (backing item has to be damageable otherwise the nbt tag is not read)

**Comment by Nightenom** [comment]
Final version with properties to adjust rendering
Usage: <https://github.com/MinecraftForge/MinecraftForge/pull/6055/files#diff-7e03b9b8f90b7aab025cfbe7e564d82bR39>

**Comment by Draco18s** [comment]
I would definitely utilize a system that allows for arbitrary resource locations. I've registered fake items in the past and haven't ever been happy having to do it.

**Comment by Archengius** [comment]
In fact, with patches provided, you allow changing appearance of ANY item in game based on NBT without usage restriction to only advancement icons. Not sure if this is a good idea. I see it being abused by modders for different kind of things.

**Comment by Nightenom** [comment]
@Archengius I'm aware of it, but I'm not sure how much self-protecting should forge hooks be
edit: and it's just for gui rendering, not entity or hand

**Pull request closed without merging**
