### PR TITLE
Added EnumDyeColor#chatColor AT

### PR DESCRIPTION
**Pull request by LatvianModder**
EnumDyeColor had chatColor field already, but didn't have a getter

### CODE REVIEW

**Comment by diesieben07** [comment]
Since the thing is final, why not make it public with an AT, saves on patches.

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by cpw** [comment]
Why? You can get TextFormatting directly..

**Comment by asiekierka** [comment]
@cpw Easy approximate conversion of in-game colors to chat colors. It's useful for things like tooltips, WAILA or chat logging. I had to do a table for this in Computronics when I was using the feature for dyeing item names in anvils.

**Comment by mezz** [comment]
Please update this PR for the latest forge version so that it can be considered.

**Pull request closed without merging**
