### PR TITLE
Added in Decorate hooks for all Biomes

### PR DESCRIPTION
**Pull request by dmf444**
Covers all Biome that generate blocks before it supers
Also includes an example of how the new code work (It is a hook, I just wanted to make sure)

Basically, if the result is set to false, nothing will gen on the surface of the world, whereas before, pumpkins and roofed forest trees would grow

### CODE REVIEW

**Comment by cpw** [comment]
Please update for 1.8.8. Thanks!

**Comment by dmf444** [comment]
Finished the update to 1.8.9

**Comment by Spartan322** [comment]
Rebase is also needed

**Comment by cpw** [comment]
Please rebase and squash, thanks!

**Comment by cpw** [comment]
Closing, fixed

**Pull request closed without merging**
