### PR TITLE
[1.11] Added a world sensitive version of getRenderType

### PR DESCRIPTION
**Pull request by canitzp**
In my current modding project I need to define the render type of the block with the blockstate of the block, but the blockstate that is given of the normal getRenderType method does not contains the correct values. If I check in another method the state.getActualState method, then I see that it contains the correct property values. With this pr it is possible to get the actual state in the getRenderType method, so that I can solve my problem and maybe other Modder too.

### CODE REVIEW

**Comment by mezz** [comment]
There are many many calls to `state.getRenderType()` in the vanilla code, I'm not sure this is a good idea.

What is special about your block that makes it depend on `getActualState` for this property?

**Comment by canitzp** [comment]
I place more than one of these block at the same time, cause it is a big rail and I use .obj files to render it, but I only need to render the first, so I created a PropertyBool and if this is true it should render the rail. The rendering itself works fine(if I return everytime EnumBlockRenderType.MODEL), but if I get the value of the state in the getRenderType method, it isn't the same as it should be. The Facing and my own state are equal to the default state. If I watch onto the track with F3 the values are correct and also if I print out the values from the actual state it is correct. The only way I see now is to get the actual state from the state that is given from the method, but for this I need a world and a position (world isn't the problem cause Minecraft.getMinecraft().world, but I can't get the position)

**Comment by mezz** [comment]
Can you put your PropertyBool into the portion of the state that gets saved and loaded as meta, instead of in the extended state that is set in `getActualState`?

**Comment by canitzp** [comment]
I do not understand exactly what are you meaning, maybe cause my not good english skills. This is the class with the property and everything I do with it: https://github.com/Traincraft/Traincraft/blob/master/src/main/java/si/meansoft/traincraft/api/AbstractBlockTrack.java

**Comment by RainWarrior** [comment]
Alternative is to use the empty model when SHOULD_RENDER is false, instead of changing the render type.

**Comment by mezz** [comment]
@canitzp I talked to you a while ago outside this issue. Did you find an alternative solution?

**Comment by canitzp** [comment]
I didn't tried it cause I wasn't motivated enough. I try it later today

**Comment by mezz** [comment]
@canitzp any update?

**Comment by canitzp** [comment]
I tried it with RainWarriors idea and it worked, for me I think it would be a better way to set the render type instead of rendering a empty model and I'm interessted why the original method did give a other IBlockState, but my problem is solved. Your decision to close it or merge it.

**Comment by mezz** [comment]
Ok thanks, glad you found a solution.

**Pull request closed without merging**
