### PR TITLE
[1.20.4] Add CPU usage config option to early window

### PR DESCRIPTION
**Pull request by PaintNinja**
Adds the option to toggle CPU usage stats on the early loading window for a cleaner look. Also did a bunch of minor performance improvements and code clean-up.

image

### CODE REVIEW

**Comment by LexManos** [comment]
Would it make sense to just go full bore and toss a config value on each of the other fancy stuff we render?
Memory, animation, and text?
I think the progress bar is the only thing really worth not allowing them to disable as it matches up with vanilla's progress bar IIRC.

**Comment by PaintNinja** [comment]
I was tempted to do that but don't have the time or motivation to figure out cpw code. Memory and CPU text are done in one place, stage updates in another, Forge animation in another, memory progress bar someplace else... Could do some no-ops and if statements littered all over the place but I'd rather stop pointless processing entirely for stuff that'll never be shown if disabled.

**Comment by LexManos** [comment]
Ya not a fan of digging into cpw land either. Im fine with this as is. Was just wondering if it would be simple to do it all in one pass.

**Comment by PaintNinja** [comment]
Been a while and triage seem busy at the moment, so assigning to Lex for review to avoid stagnation.
One thing to note is this PR seems to default to hiding CPU usage.

**Comment by PaintNinja** [comment]
https://discord.com/channels/1129059589325852724/1129095235889270844/1216492534348644474

**Pull request merged**
