### PR TITLE
Add support for stack sensitive food

### PR DESCRIPTION
**Pull request by pupnewfster**

### CODE REVIEW

**Comment by tterrag1098** [comment]
Pretty straightforward, I can see uses, but it does open up the floodgates a bit with making everything stack sensitive.

**Review by tterrag1098 — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Comment by LexManos** [comment]
I'm gunna veto the isFood one, a item should either always been food, or not. The power of that food however could be up for discussion based on the stack.
However, this is a prime canidate for a data driven transfomer: https://github.com/MinecraftForge/MinecraftForge/pull/7418#issuecomment-767250852

**Comment by sciwhiz12** [comment]
Hello! @pupnewfster, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). Note that there is another version of the feature intended by this PR at #7702, so it is your decision whether to continue with your own implementation or collaborate with the author of that PR on one solution. (We suggest the latter so there is a concentration of effort in one PR rather than fragmented across multiple.) If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

**Comment by pupnewfster** [comment]
Not interested as I do not really need this feature myself and due to maintenance overhead it is not going to be merged without something like #7890 being merged first

**Pull request closed without merging**
