### PR TITLE
IS_CAVE Tag for lush and Dripstone Caves.

### PR DESCRIPTION
**Pull request by JT122406**
This is Separate from IS_UNDERGROUND as this does not include the Deep Dark only cave based biomes can be useful for types of ore gen.

### CODE REVIEW

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Please fix the compile error in your changes.

**Comment by JT122406** [comment]
Will do when back at pc

**Comment by JT122406** [comment]
Build errors are now fixed my bad since they even happened

**Review by sciwhiz12 — APPROVED** [review]

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Please modify the `is_underground` tag to include by reference the `is_cave` tag, and also remove the direct references to the caves biomes in the tag.

**Comment by Commoble** [comment]
I agree that it would be helpful to have a tag that includes lush caves and dripstone caves but not deep dark, however "is_cave" doesn't feel like a good name for such a tag as the deep dark is very cavey.

**Comment by JT122406** [comment]
> I agree that it would be helpful to have a tag that includes lush caves and dripstone caves but not deep dark, however "is_cave" doesn't feel like a good name for such a tag as the deep dark is very cavey.

Any ideas?

**Comment by Commoble** [comment]
```
forge:is_cave
  lush_caves
  dripstone_caves
  deep_dark
```
```
forge:is_deep
  deep_dark
```
```
forge:is_underground
  #forge:is_cave
  #forge:is_deep
```
```
forge:no_default_spawns
  deep_dark
  mushroom_island
```

is_cave represents underground biomes with large cavernous spaces you can walk around in unique to that biome (as opposed to the smaller caves that generate everywhere)

is_underground represents all underground biomes, caves or no (this could include things like "high mineral density areas"

is_deep is just the deep dark and not the less-deep caves

no_default_spawns indicates the biome shouldn't have mob spawns present in most biomes added to it (this might warrant more discussion)

https://github.com/MinecraftForge/MinecraftForge/pull/8928 would help a bit here too as it provides "not" holdersets that would let people add things to e.g. "all biomes except no_default_spawns" without needing custom biome modifier serializers

**Comment by JT122406** [comment]
> #forge:is_cave
>   #forge:is_deep

I decided to make some of these changes @sciwhiz12 can look them over and lmk

**Review by sciwhiz12 — APPROVED** [review]

**Pull request closed without merging**
