### PR TITLE
Backport of Registries optimization

### PR DESCRIPTION
**Pull request by SrRapero720**

### CODE REVIEW

**Comment by LexManos** [comment]
Why did you do so much reformatting?

**Comment by SrRapero720** [comment]
@LexManos i do cherrypick and fix changes to 1.20.1. is how was done in 1.20.2

**Comment by PaintNinja** [comment]
Forge can make breaking changes to its APIs on new MC versions, so simply copying over the registry system from 1.20.2 to 1.20.1 could break a lot of mods.

**Comment by SrRapero720** [comment]
@PaintNinja changes aré just change HashMap to FastUtil maps. All public method keeps same name and functionality. Internal methods (package privated) got renamed but doesnt affect internal behavior.

Changes was backported but not doing breaking changes

**Comment by LexManos** [comment]
You do do breaking changes to public methods/fields.
```
20:18:37     Incompatibilities found: 3 errors, 0 warnings
20:18:37     net/minecraftforge/registries/ForgeRegistry:
20:18:37     - error: getMissingEvent(Lnet/minecraft/resources/ResourceLocation;Ljava/util/Map;)Lnet/minecraftforge/registries/MissingMappingsEvent; - API method was removed
20:18:37     - error: loadIds(Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Ljava/util/Map;Lnet/minecraftforge/registries/ForgeRegistry;Lnet/minecraft/resources/ResourceLocation;)V - API method was removed
20:18:37     - error: REGISTRIES:Lorg/apache/logging/log4j/Marker; - Field was made final
```
 But honestly, my main issue was the mudding of the commit because you comingled the formatting changes as well.
makes reading your changes on github really hard.
But meh, go for it.

**Pull request merged**
