### PR TITLE
[1.13] Added 'create'-method for EnumCreatureType

### PR DESCRIPTION
**Pull request by GirafiStudios**
Added since EnumHelper is gone in 1.13 (Thank god for that btw.!)
Personally need it for limiting spawns of a certain mob type in a custom dimension.

### CODE REVIEW

**Comment by liach** [comment]
can you make the default impl throw an exception indicating that a transformer will edit the code?

**Comment by GirafiStudios** [comment]
I've done it the same was as in https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/patches/minecraft/net/minecraft/item/ArmorMaterial.java.patch .
If the type doesn't match you'll get a fatal log warning - https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/fmllauncher/java/net/minecraftforge/common/asm/RuntimeEnumExtender.java#L93-L103

**Comment by liach** [comment]
lol, i mean don't return null. if you return null and the extender broke, bugs may emerge. throw an exception instead.

**Comment by tterrag1098** [comment]
liach, returning null is fine. If the enum ASM fails we have bigger problems. All the other implementations look just like his, this is how it's supposed to be.

**Comment by 0Navis0** [comment]
Returning null in a function is never a good thing, it can cause easily null pointer exception.

**Comment by LexManos** [comment]
We should probably make the standard to throw a IllegalStateException("EnumExtender didnt run on {type}")

However, returning null from functions is PERFECTLY fine. null is a thing that exists and pretending it doesn't makes you a horrible programmer.

As for this PR, you need the associated exec file, and/or javadocs and proper names.

**Comment by GirafiStudios** [comment]
Added it to forge.exc
As for the proper names I tried adding them, but genPatches didn't catch the changes.

**Comment by tterrag1098** [comment]
I think the refactor to throwing an exception can be done later. This looks good now.

**Pull request merged**
