### PR TITLE
Added IElytra and a check for it in EntityLivingBase to be able to make your own Elytra

### PR DESCRIPTION
**Pull request by Minecraftschurli**
changed Elytra check from == to instanceof

### CODE REVIEW

**Comment by maxanier** [comment]
Just want to mention #4476 here. It allows the same function and more as this PR as far as I can tell. It requires some more work though to create a simple elytra item using their implementation. Maybe you could try to convince them to switch to an instance of check in their implementation.

**Comment by HenryLoenwind** [comment]
```
public class ItemDarkSteelArmor extends ItemArmor extends ItemElytra {
```

um, sorry, doesn't compile.

**Comment by kierajreed** [comment]
umm, you can't `extend` several classes

you'd need an `interface` that you can `implement` to add necessary methods

**Comment by maxanier** [comment]
@SkyHawkB I think that was just irony
@HenryLoenwind I think the author just wants to create a custom item (as subclass of ItemElytra) not an amor. 
But as I said #4476 is a lot more powerful and therefore I do not see any real reason for this PR.

**Comment by Minecraftschurli** [comment]
@SkyHawkB yeah didn't think of that. Where shuld I put it and do you have a name suggestion for the interface? I thought of IElytra or IIsElytra.

**Comment by mezz** [comment]
As maxanier said, this feature is already covered by a PR that is waiting for final review here: https://github.com/MinecraftForge/MinecraftForge/pull/4476
Thank you for contributing, but I am closing this PR since it still has some issues to work out and seems to have the same goal as the other PR.

**Pull request closed without merging**
