### PR TITLE
Fix crash from search tree processing invalid recipes

### PR DESCRIPTION
**Pull request by bs2609**
This issue can be seen by attempting to connect to a server while having 'extra' content mods on the client.

Example stacktrace from these crashes:
```
[23:30:47] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_172]
	at net.minecraft.util.Util.runTask(Util.java:51) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1086) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:397) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [Forge_main/:?]
	at GradleStart.main(GradleStart.java:25) [Forge_main/:?]
Caused by: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)

Caused by: java.lang.NullPointerException
	at net.minecraft.client.util.SearchTree.lambda$index$0(SearchTree.java:57) ~[Forge_main/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172]
	at net.minecraft.client.util.SearchTree.index(SearchTree.java:55) ~[Forge_main/:?]
	at net.minecraft.client.util.SearchTree.add(SearchTree.java:50) ~[Forge_main/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_172]
	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:603) ~[Forge_main/:?]
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079) ~[Forge_main/:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772) ~[Forge_main/:?]
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:561) ~[Forge_main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924) ~[Loader.class:?]
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:674) ~[GameData.class:?]
	at net.minecraftforge.fml.common.network.handshake.FMLHandshakeClientState$4.lambda$accept$1(FMLHandshakeClientState.java:161) ~[FMLHandshakeClientState$4.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at net.minecraft.util.Util.runTask(Util.java:50) ~[Util.class:?]
	... 15 more
```

The issue is resolved here by adding a call to `FMLCommonHandler.resetClientRecipeBook()` (which calls `RecipeBookClient.rebuildTable()`), before calling `reloadSearchTrees()`.

### CODE REVIEW

**Comment by bs2609** [comment]
More details:

Within `Minecraft.populateSearchTreeManager`, the recipe search tree is populated from the client recipe book:
```java
RecipeBookClient.ALL_RECIPES.forEach(searchtree1::add);
```
however it uses functions that rely on item registry lookups, as can be seen here:
```java
(p_193991_0_) ->
{
    return (List)p_193991_0_.getRecipes().stream().map((p_193992_0_) -> {
        return Item.REGISTRY.getNameForObject(p_193992_0_.getRecipeOutput().getItem());
    }).collect(Collectors.toList());
}
```
If the client recipe book contains references to items that are not in the currently active registry, these lookups will fail, causing a `NullPointerException` when methods are called on the result (e.g. in `SearchTree.index`):
```java
(this.idFunc.apply(element)).forEach((p_194039_2_) ->
{
    this.byName.add(element, p_194039_2_.toString().toLowerCase(Locale.ROOT));
});
```
This can occur if the active registry contents have changed since the recipe book was populated, such as when connecting to a server with a different modlist.

Adding a call to `RecipeBookClient.rebuildTable` repopulates the client recipe book from the recipe registry, which should ensure consistency here.

**Comment by HenryLoenwind** [comment]
This may not have been a full fix. bs2609, can you look at this report I just got? It looks like it's in the exact same area...

https://pastebin.com/nz23n0CR  (on Forge 14.23.4.2705)

**Comment by tyler489** [comment]
The above occured after  disabling ae2's ore camouflage as it was causing recipe conflicts

**Comment by bs2609** [comment]
One other point that might be worth considering is if the ordering here should be changed:
https://github.com/MinecraftForge/MinecraftForge/blob/bea02348e2845ef6b1f49b0692f79dbc097d2706/src/main/java/net/minecraftforge/registries/GameData.java#L673-L677

Should `ObjectHolder` references be updated first?

**Pull request merged**
