### PR TITLE
Added Cancelable DimensionPreloadEvent

### PR DESCRIPTION
**Pull request by goreacraft**
By canceling this event will prevent the dimension from being initialized and then you can use DimensionManager.addWorld to add your own custom dimension 
This will make possible to create a proper multiverse server side plugin

Signed-off-by: goreacraft <goreacraft@gmail.com>

### CODE REVIEW

**Comment by liach** [comment]
You are generating patches incorrectly :disappointed: See https://github.com/MinecraftForge/MinecraftForge/wiki/If-you-want-to-contribute-to-Forge

**Comment by liach** [comment]
Moreover, 1.10 is no longer supported. Send pull requests against 1.11.x branch.

**Comment by diesieben07** [comment]
What's also missing for a "proper multiverse plugin" is support for "spoofing" the dimension ID to the client, otherwise the client will try to load a non-existent dimension and crash.

**Comment by HenryLoenwind** [comment]
I don't think you wanted to add that patch file to your PR.

The event javadoc is missing a big "You MUST DimensionManager.addWorld() inside the event if you cancel it!!!"---why doesn't is just have that as return value instead of the cancelling?

**Comment by goreacraft** [comment]
**liach** - Thank you for that link, i will read it and make sure i will do it the right way next time
**diesieben07** - that can be fix server side depending on what outcome you want by either sending player to a different dimension or he will just spawn in the new overridden dimension
**HenryLoenwind** - your are right in case if you rely want to use that dimension to spawn that player in there, but you can just teleport him somewhere else

I added this event here to have the option to use it if you need it as there is no other way to go around it unless using Mixin, and why adding another dependency just for this? (see ForgeEssentials multiverse module.. https://github.com/ForgeEssentials/ForgeEssentials/blob/110/develop/src/main/java/com/forgeessentials/core/preloader/mixin/MixinDimensionManager.java)

I made this particularly for 1.10.x because i think this version will be used for some time ahead by different modpacks as there are lots of mods not updated to 1.11.x yet ( see FTB)

I am learning how to use git as i go , thank you for your patience ;)

**Comment by goreacraft** [comment]
i will remake this commit to make it the right way

**Pull request closed without merging**
