### PR TITLE
Disable frost walker enchantment on anything but vanilla water

### LINKED ISSUE #3904: [Vanilla Bug] The Frostwaker Enchanment breaks Forge Liquids
The Frost Walker Enchanment turn any Block from Material Water into their Ice, wich smelt back to normal Water. This will turn any "modded" liquid into water.

### PR DESCRIPTION
**Pull request by diesieben07**
Fixes #3904.

### CODE REVIEW

**Comment by LexManos** [comment]
If you're just going to hardcode it to Water, then just use Blocks.WATER instead of instanceof/Material checks.

**Comment by diesieben07** [comment]
Except then I need `Blocks.WATER` and `Blocks.FLOWING_WATER`, but whatever you say :D

**Comment by kashike** [comment]
Why hardcode it?

**Comment by diesieben07** [comment]
Other suggestions?

**Comment by liach** [comment]
I suggest using a capability that allows a liquid to get frosted by the enchantment like water.

**Comment by kashike** [comment]
Add a method to `BlockLiquid`? Something like..
```diff
diff --git a/projects/src/main/java/net/minecraft/block/BlockLiquid.java b/projects/src/main/java/net/minecraft/block/BlockLiquid.java
index 8013704..e31927e 100644
--- a/projects/src/main/java/net/minecraft/block/BlockLiquid.java
+++ b/projects/src/main/java/net/minecraft/block/BlockLiquid.java
@@ -367,4 +367,8 @@ public abstract class BlockLiquid extends Block {
     public static float func_190972_g(IBlockState p_190972_0_, IBlockAccess p_190972_1_, BlockPos p_190972_2_) {
         return (float)p_190972_2_.func_177956_o() + func_190973_f(p_190972_0_, p_190972_1_, p_190972_2_);
     }
+
+    public boolean canFrostWalk(World world, IBlockState state) {
+        return this == Blocks.field_150355_j || this == Blocks.field_150358_i;
+    }
 }
\ No newline at end of file
diff --git a/projects/src/main/java/net/minecraft/enchantment/EnchantmentFrostWalker.java b/projects/src/main/java/net/minecraft/enchantment/EnchantmentFrostWalker.java
index b4ca15b..a618ada 100644
--- a/projects/src/main/java/net/minecraft/enchantment/EnchantmentFrostWalker.java
+++ b/projects/src/main/java/net/minecraft/enchantment/EnchantmentFrostWalker.java
@@ -53,7 +53,7 @@ public class EnchantmentFrostWalker extends Enchantment {
                     if (iblockstate.func_185904_a() == Material.field_151579_a) {
                         IBlockState iblockstate1 = p_185266_1_.func_180495_p(blockpos$mutableblockpos1);
 
-                        if (iblockstate1.func_185904_a() == Material.field_151586_h && ((Integer)iblockstate1.func_177229_b(BlockLiquid.field_176367_b)).intValue() == 0 && p_185266_1_.func_190527_a(Blocks.field_185778_de, blockpos$mutableblockpos1, false, EnumFacing.DOWN, (Entity)null)) {
+                        if (iblockstate1.func_185904_a() == Material.field_151586_h && ((BlockLiquid) iblockstate1.func_177230_c()).canFrostWalk(p_185266_1_, iblockstate1) && ((Integer)iblockstate1.func_177229_b(BlockLiquid.field_176367_b)).intValue() == 0 && p_185266_1_.func_190527_a(Blocks.field_185778_de, blockpos$mutableblockpos1, false, EnumFacing.DOWN, (Entity)null)) {
                             p_185266_1_.func_175656_a(blockpos$mutableblockpos1, Blocks.field_185778_de.func_176223_P());
                             p_185266_1_.func_175684_a(blockpos$mutableblockpos1.func_185334_h(), Blocks.field_185778_de, MathHelper.func_76136_a(p_185266_0_.func_70681_au(), 60, 120));
                         }
~
```

**Comment by liach** [comment]
@kashike Good suggestion, but mods should be able to determine what will the resulted "frosted block" because frosted ice always reverts to water.

**Comment by diesieben07** [comment]
There you go.

**Comment by liach** [comment]
Thank you @diesieben07. I love this!

**Review by liach — APPROVED** [review]

**Comment by LexManos** [comment]
Its fine to be hardcoded for the bugfix.
But talking on IRC, a nice system of setTemprature(temp, location) would be nice to allow people to properly know when to freeze or thaw themselves. Hell would apply a constant amount when places to cause vaporization, frostwalk would apply enough to freeze water, torches would apply enough to melt water... etc... But thats a system to be better tought out. Out of scope of this particular PR.

**Comment by diesieben07** [comment]
Reverted to hardcoding.

**Pull request merged**
