### PR TITLE
Fix Vanilla Lighting Bug - Fixes Top/Bottom Faces interpolation.

### PR DESCRIPTION
**Pull request by AlgorithmX2**
Corrects a bug in vanilla to enable proper partial lighting on top and bottom faces.

### CODE REVIEW

**Comment by LexManos** [comment]
Going to need a bit more explanation to this.
Thats A LOT of stuff to be adding to a patch file without any reasoning.
This might also be a case where it's better to do a import static for Orientation.* to prevent a lot of code.
Combined with a few new lines to make it look cleaner....

**Comment by AlgorithmX2** [comment]
A lot of stuff? Its 2 lines of code and a comment, the rest is vanilla, I just patched it using the same format as the vanilla code around it since its basically just data.

As for what this fixes,
The top and bottom faces of models in vanilla have incorrect interpolation of lighting, so faces that run into one another are lit based on the full block size, rather then the partial block size, Vanilla already has code that handles this for the sides blocks, this works fine, I simply added the necessary values to the top/bottom faces to complete the implementation that is currently lacking in the base game.

If you want me to reformat the code to not match the vanilla code I can certainly do that, just let me know how you want it formatted, its just a series of arrays.

**Comment by LexManos** [comment]
Screenshots would help.
And your '2 lines' are more like 146 lines.
Remember that 'vanilla code' is decompiled code, run through a automatic formatter. It can be cleaned up a lot in this case something along the lines of 
```java
new Orientation[] { FLIP_WEST, SOUTH, FLIP_WEST, FLIP_SOUTH, WEST, FLIP_SOUTH, WEST, SOUTH }, 
new Orientation[] { FLIP_WEST, NORTH, FLIP_WEST, FLIP_NORTH, WEST, FLIP_NORTH, WEST, NORTH }, 
```
See how much cleaner and less redundant that is?
Start by adding a import static for Orientation.* and see how much smaller the patch file is made.
A comment in there to explain what/how those values were derived would be nice. Right now it just looks like you're pulling things out of thin air.
This is one of the rare occasions where adding a import is preferable for code readability/simplicity.

**Comment by AlgorithmX2** [comment]
A screen shot and a  way to test the issue can be seen on the vanilla bug report:
https://bugs.mojang.com/browse/MC-80148

This report also includes a resource pack to test and demonstrate the original issue.

I'll tweak the patch itself later tonight when I have time.

**Comment by AlgorithmX2** [comment]
The values were derived by reverse engineering the process that mojang used, and implementing it manually and testing the outcome, I then reversed my value back into mojangs format to be used without branching.

**Comment by AlgorithmX2** [comment]
I've reformatted the PR, however the static import won't work for the cardinal directions, since the enum is using those values in that space.

I've also included a link to this PR and to the mojang bug in the patch for clarification.

**Pull request merged**
