### PR TITLE
Store entity data for dormant chunks using NBT (1.12)

### PR DESCRIPTION
**Pull request by bs2609**
1.12 version of #3940.

### CODE REVIEW

**Comment by mezz** [comment]
I talked to Lex about this and he thinks we lose most of the performance benefit by serializing the data to NBT. Considering how sketchy the chunk code is in general, would it be better to remove this chunk caching feature from Forge?

**Comment by bs2609** [comment]
The data is serialised to NBT regardless, it's the deserialisation that's new here.

I think it'd be good to try out this and see how it goes with regards to performance. Removing the chunk cache would need to wait until an appropriate time to make breaking changes, so it gives us an oppertunity to try and get some feedback on performance changes in the meantime.

**Comment by mezz** [comment]
Can you update this to resolve conflicts?

**Comment by mezz** [comment]
@LexManos I would like to get this in even if it loses performance, the current implementation is broken.

The stuff @bs2609 uncovered here makes me think Mojang's chunk implementation is a bit too broken/messy to optimize right now. I think we should consider removing the chunk cache feature in 1.13 unless someone can take the time to improve its performance in a safe way.

**Pull request merged**
