### PR TITLE
Add Tool-type tags to forge tag list

### PR DESCRIPTION
**Pull request by chorman0773**
Add various tags to the forge domain/namespace which represent the different types of tools, weapons, etc.

### CODE REVIEW

**Review by MajorTuvok — COMMENTED** [review]
If I'm not mistaken, then these should have a data generator and should be created by that right? (Also are you sure that all of them are correct, because sometimes it says _value_ and sometimes _values_ - I don't know the spec that well, it just seems weird to me that both are allowed)

**Comment by chorman0773** [comment]
I created these by hand. Also thanks for the tip on the value/values. I’ll look into that. It is just values, rather than value.

**Comment by Alpvax** [comment]
Files in a folder called "generated" probably shouldn't be created by hand (although I don't know if they will get overwritten, so it might not be an issue).

**Comment by tedstardev** [comment]
These should not be made by hand.  They should be coded into `src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java`  and generated with the `forge_data` Gradle task.

**Comment by chorman0773** [comment]
I can't do any direct java dev due to issues with setup tasks on my computers. I also don't see an issue with doing such, as they will provably have the same effect as the generated tags.

**Comment by LexManos** [comment]
Hand crafted jeans will not be accepted, and will be overwritten on the next generate run.

**Comment by tedstardev** [comment]
The reason they should be included in the generator is because it provides a programmatic interface to the tags.  Suppose a mod wanted to check if an item is in the `armor/helmets` tag.  As it stands, the mod would have to create the tag from the resource location (which could change), rather than if they were in the generator it could just use the API `Tags.Items.ARMOR_HELMETS`.

**Comment by chorman0773** [comment]
I can attempt to include them in the generator, but cannot make any guarantees about the capability to do so.

**Comment by LexManos** [comment]
If you don't want to put the effort into doing things correctly, then get someone else to.
Specify exactly what things you wish to suggest, and have someone else do it.

**Pull request closed without merging**
