### PR TITLE
Added ItemStack sensitive version of getFoodProperties

### LINKED ISSUE #7701: Add ItemStack sensitive version of Item.getFoodProperties(), called from FoodStats.eat(...)
When eating an item `PlayerEntity.eat(World, ItemStack)` calls `this.getFoodData().eat(...)`, which takes the `Item` and `ItemStack` versions of the same food item.

`FoodStats.eat(Item, ItemStack)` gets the food properties by calling `Food food = item.getFoodProperties();`

This means that only one set of food stats can be defined for an item type.

It would be desirable if `Item.getFoodProperties` could take ItemStack and have the ItemStack passed into it so that information such as NBT data can be taken into account

e.g.

```
@Nullable
public Food getFoodProperties(ItemStack stack)
{
    return this.foodProperties;
}
```
Called as

```
// In FoodStats' method, eat(...)
Food food = item.getFoodProperties(itemStack);
```

### PR DESCRIPTION
**Pull request by queekusme**
Fixes #7701 

This PR adds an ItemStack sensitive version of `getFoodProperties`.
This allows custom Items to override the `Food` class data so that the output can be modified before the data is used.

- Existing calls have been updated to use the ItemStack sensitive version.
- The new method calls the existing method by default so that existing behaviour can be retained.
- The existing method has been left unchanged except for a Deprecation annotation with a comment indicating to use the ItemStack sensitive version of the function.

### CODE REVIEW

**Comment by loordgek** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/7638

**Comment by queekusme** [comment]
> #7638

From what I can see that PR doesn’t have any modifications required to support the feature here yet,

If changes are added to that PR to accommodate the feature then I shall close this PR

**Comment by loordgek** [comment]
what is missing?

**Comment by queekusme** [comment]
> what is missing?

PR 7638 doesn't add any itemstack sensitive variants of `getFoodProperties`

**Comment by TheCurle** [comment]
This PR conflicts directly with #7543. I suggest you collaborate.

**Comment by sciwhiz12** [comment]
Hello! @queekusme, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). Note that there is another version of the feature intended by this PR at #7543, so it is your decision whether to continue with your own implementation or collaborate with the author of that PR on one solution. (We suggest the latter so there is a concentration of effort in one PR rather than fragmented across multiple.) If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

**Comment by queekusme** [comment]
The PR has been inactive as I was hoping that other PRs mentioned would implement changes desired however since the inception of the PR this doesn't appear to be the case. Other PRs appear to be stale as well.

I am more than happy to update the PR to 1.18 (although I am short for time until the new year so changes would be implemented after New Years) however since I am no longer working on the mod which desires these changes, would prefer if alternative PRs which provide more features than this alone were given the energy to reach a point of merge.

If this cannot be reached then I will make the necessary changes and resubmit against the 1.18 branch.

**Comment by queekusme** [comment]
Closing as this has now been implemented in another PR

**Pull request closed without merging**
