### PR TITLE
Fix little typo. I beleive someone must have forgot it.

### PR DESCRIPTION
**Pull request by Glease**
And I'm not a fool, too. At least I do know people will die if fml is REALLY under gpl2.

### CODE REVIEW

**Comment by cpw** [comment]
I said NO! Please go away. We are reviewing the forge licensing.

**Comment by cpw** [comment]
This "problem" has "existed" since 2013: https://github.com/MinecraftForge/FML/commit/a723aa68606d57b0ee5bac8b1d1905abef440b54
Once we reorganize under a common license, I'll regenerate every source file header.

**Comment by cpw** [comment]
I would suspect a bug in this tool (which I used to generate those headers): https://marketplace.eclipse.org/content/copyright-wizard However, it looks like it's been abandoned since 2012...

**Comment by luacs1998** [comment]
Have you guys considered the use of checkstyle in Forge and its LicenseFormat tool?

**Comment by jk-5** [comment]
Or the gradle license plugin, which automatically adds licenses to files

**Comment by cpw** [comment]
@luacs1998 and @jk-5 we'll be doing a proper overhaul of how we do licenses. TBH, it's silly having a big assed license statement at the top of every file - it's scrolled past every time - probably better would be a simple "LICENSED under LGPLv2.1 by Forge development team and contributors"

**Comment by liach** [comment]
checkstyle? Why ForgeEssentials doesn't use it... Sponge use it. Btw when will forge change to LGPL v2.1 as Lex said?

**Pull request closed without merging**
