### PR TITLE
[1.12] Removed deprecated methods inside GuiScrollingList

### PR DESCRIPTION
**Pull request by sokratis12GR**
Comment says it should have been removed a while ago ? Remove in 1.9.3?

### CODE REVIEW

**Comment by mezz** [comment]
This can be removed when we are moving to 1.13 but not right now. Removing it would be a breaking change.

**Comment by sokratis12GR** [comment]
@mezz the thing is, those removed methods have no usage at all, I don't think anyone actually uses them or if it would break anything

**Comment by mezz** [comment]
It's likely that nobody uses them, but we can't possibly know that for sure. 
The safe policy is to leave them until we decide to intentionally make breaking changes.

**Comment by Alpvax** [comment]
Can we make an issue or PR and flag it as breaking change (i.e. ignore until 1.13) that contains all these deprecations, as many of them seem to have been missed for several major versions.
It would prevent them being missed again and it would simplify the forge team's job somewhat if all of them were in one place.

**Comment by loordgek** [comment]
or make a 1.13 milestone

**Comment by mezz** [comment]
I will make a 1.13 branch at some point to keep track of these things ahead of the actual update.

**Pull request closed without merging**
