### PR TITLE
Stable direction get nearest

### PR DESCRIPTION
**Pull request by Kovak**
This is a port of the downstream fix here: https://github.com/neoforged/NeoForge/pull/26

Since vanilla doesn't actually have any 45 degree normals this issue doesn't come up in vanilla, but it will manifest as documented in #9608 with modded blocks that make use of the calculated normals feature. By biasing ourselves slightly in favor of the earlier enum elements we avoid fighting that occurs around rounding errors in the inverse multiplication  based on small changes in the view matrix that causes the normal Direction#getNearest to return unstable results

### CODE REVIEW

**Comment by LexManos** [comment]
Do you have a video or example verifying the issue and that it is fixed?

**Comment by Kovak** [comment]
The video in #9608 still describes the issue. Technically because of the fixes we did in #9664 this does not manifest in forge anymore, not because it isn't still lurking but because we no longer are modifying vanilla normals during model baking by default and so there are no 45 degree normals in forge anymore without additional mods. However, if you change ForgeHooksClient#fillNormal to always go down the calculate normals branch, you can reintroduce the issue and then if you also have this patch in place you can observe that the issue also appears fixed. We could put together a test mod I suppose that clones the campfire with the calculate normals mode on.

**Comment by Jonathing** [comment]
A test mod like you described or one with a block that somehow needs to use 45-degree normals would be best in this case.

**Comment by Kovak** [comment]
Added a test mod with a single block "calculate_normals_test:fire_accurate_normals_test", this is a copy of the campfire with the major difference that the fire faces have been set to calculate their normals.

I've also made it so the behavior is toggleable in the client config. You can see for yourself how this fix works by placing the new campfire block down and toggling stabilizeDirectionGetNearest to false to see the issue, or true to see the fix.

**Review by Jonathing — APPROVED** [review]
Just ran this PR in IDE. Works great! Your test mod is excellent and to-the-point, and your code looks sane (at least to me).

One quick thing to take note is that if the config `stabilizeDirectionGetNearest` is disabled while in game, when you try to re-enable it while still in game, the fix will not take place. I don't see this as a problem given that the only people who might try to turn this config option on and off are rendering developers like yourself, but if you feel the need to address that you are more than welcome to. I personally don't think it is a problem though.

**Comment by Kovak** [comment]
I was able to see changes to the config value for stabilizeDirectionGetNearest reflected during a single game session with the /reload command

**Review by Jonathing — APPROVED** [review]

**Comment by LexManos** [comment]
Fixes the problem as described and exampled. Not too invasive.

**Pull request merged**
