### PR TITLE
Force mods, to require a name

### PR DESCRIPTION
**Pull request by jamierocks**
This is a port of my pr to FML back in January https://github.com/MinecraftForge/FML/pull/592

### CODE REVIEW

**Comment by matthewprenger** [comment]
I support this, but it will have to be targeted at @ 1.8.8 because backwards compatibility.

**Comment by jamierocks** [comment]
I will update this pr, tommorow (don't have access to pc until then)

**Comment by LexManos** [comment]
Why? Also this doesn't force them to do anything 'human readable'.
ModID should be sufficient, why is it not?

**Comment by cpw** [comment]
Nope. Adding a default here just means people won't populate it.

**Comment by matthewprenger** [comment]
Uhh what? He removed the default, which would force people ***to*** populate it...

**Comment by cpw** [comment]
Yes, got that backwards, making it even worse. It breaks compatibility for trivia.

**Comment by jamierocks** [comment]
When has Forge ever cared about backwards compatibility?

**Comment by williewillus** [comment]
Uh, always?

**Comment by cpw** [comment]
When possible yes I do care. This change breaks compatibility for zero net benefit.  If there was a good cause to do it I would. Names have had sensible defaults in code since I wrote @mod 3 years ago. There is zero reason to change that that I can see.

**Comment by liach** [comment]
@jamierocks If you do not care about backwards compatibility, mods that use forge will hurt a lot. In the other way, a mod that is compiled against 10.13.0 could never work on 10.13.4 if you do not care about it. In my opinion, your change would be big enough to bump version from 11 to 12.

**Comment by DanielHuisman** [comment]
Why do you even need this patch?
It chances literally nothing and would certainly not be enough for a major version bump.

**Comment by Spartan322** [comment]
This breaks a lot of mods and provides absolutely nothing in return, and mod names aren't guaranteed to be human-readable.

**Pull request closed without merging**
