### PR TITLE
Suppress firing events at load time if an error has already occurred

### PR DESCRIPTION
**Pull request by bs2609**
Similar to 603903db507a483fefd90445fd2b3bdafeb4b5e0, which skips firing registry events if an error occurred previously, this skips firing `ModelBakeEvent` if the `ModelLoader` has skipped initialisation due to errors (#3772):
https://github.com/MinecraftForge/MinecraftForge/blob/4242f89c75d3d4a38737848a37383561eed8ec27/src/main/java/net/minecraftforge/client/model/ModelLoader.java#L159-L160

### CODE REVIEW

**Comment by bs2609** [comment]
Checks have also been added to the colour handler registration events.

I think those are the only other events that would cause problems here, unless anyone else can think of something?

The section concerned is in `Minecraft.init()`, between the calls to `beginMinecraftLoading` and `finishMinecraftLoading`. It's important to try to do as little as possible in the event of an error here, mainly to avoid a 'cascade' of errors making troubleshooting difficult.

**Comment by mezz** [comment]
Looks good to me.
Is there some better solution for this? We keep adding cases to this logic without doing anything more general.

**Comment by bs2609** [comment]
A possible more general solution would be to have something like an `EventBus.shutdown()` method. This could then be called by `LoadController.checkErrors()` for the main event bus, preventing any subsequent events from being fired. Any thoughts?

**Comment by mezz** [comment]
I think the issue is that we are collecting mod errors so we can display a bunch, instead of just crashing right away.
For some stuff like version mismatches and missing mods, it makes sense to collect up and display those all at once. Trying to continue running at all after an unknown crash from a mod doesn't really make sense to me.

**Comment by bs2609** [comment]
This is for those kind of things though?

As far as I'm aware, loading only continues here to display an error screen in those cases where it's useful.

In order to actually get to display that screen, though, we need to not crash in the meantime. If some initialisation is skipped, but later initialisation isn't, that becomes much harder to achieve reliably.

**Comment by AEnterprise** [comment]
right now any and all errors are caught during a phase, and all depending mods are skipped for that phase
after the phase ends and the error is critical (like a nullpointer) forge rethrows the exception (and collected any others that may have been thrown)

**Comment by mezz** [comment]
We can check version mismatches and missing mods before any modded code is run, so those are reasonably safe to collect together into one big error screen and we should display it as soon as those checks are complete, and completely halt the game before any mods start to load or events are fired.

I think catching any other errors during other phases while the mods are actually starting up is not safe to do.

The error screen is pretty simple, I am not sure what part of the game it needs loaded but it would be worth looking into the bare requirements there so we can display it immediately and stop the game.

**Pull request merged**
