### PR TITLE
[1.13] Check canSustainPlant for valid ground in BlockBush

### PR DESCRIPTION
**Pull request by Adubbz**
As per title

### CODE REVIEW

**Comment by liach** [comment]
in my opinion, we should refactor the plant system. plant type is still an enum instead of an interface; plantable does not indicate which side the plant will grow on on the source block, nor does it pass item stack information for plant items.

**Comment by Shadows-of-Fire** [comment]
Stack information may no longer be necessary unless people are using nbt subtype plants, which would be rather unusual.

**Comment by Chocohead** [comment]
For a mod like Agricraft where crops have properties that can change between generations it doesn't seem unreasonable to have limitations that would only be apparent via the stack

**Comment by tterrag1098** [comment]
I also think that IPlantable/IGrowable could use a rewrite, but someone would need to create an RFC for it, probably someone with farming mod experience.

**Comment by Buuz135** [comment]
Yes, there needs to be methods to know easily if its mature and how to harvest it

**Comment by Shadows-of-Fire** [comment]
Ideally we have a world with IPlantable, IHarvestable, and IGrowable, along with better context and more valid methods for determining proper soils

**Comment by Buuz135** [comment]
Yeah, it wouldnt hurt to have something separate that way it would increase customization.

**Pull request merged**
