### PR TITLE
Add World#isFakeWorld() for modded customized worlds

### PR DESCRIPTION
**Pull request by gabizou**
This patch is to provide a useful cross mod understanding when a custom `World` is not to be considered for various processing and what not where `Player` objects are traditionally not exposed to traveling to, and therefor not associated with the `DimensionManager`. In the specific case with SpongeForge and Buildcraft, there is an issue where Sponge's internal processing to track block changes and other transactions taking place in a `World` are being tracked because Buildcraft has no way to signify the world is a "fake" world if only to manually perform block changes and gather other information based on pre-existing block mechanics, such as block drops, or performing pastes, and what have you, such that Sponge cannot sanely determine that their `FakeWorld` is not to be tracked for those transactions.

An excerpt from SpongePowered/SpongeForge#1527:
>for now there is no ticking going on so there should be no real issues atm yet
>the current use of the fake world is to check requirements of blocks for the snapshots in what blocks are required to place them (getting pickblock) but this world is also used for displaying the content of them in your inventory
>as for possible compat modifications: since 1.12 is arround the corner it might be worth adding a function to world in forge: isRealWorld or something like that, would default to true but mods with fake worlds that are completely not accesable by players could return false there, this would allow other mods and things like spongeforge to know this and addapt (for example any permission and logging mods/plugins could just disregard that world)

Tagging the possibly interested parties: @AlexIIL @AEnterprise @Zidane @bloodmc 

Of course, since 1.12 has not yet been released, this could do with some discussion.

### CODE REVIEW

**Comment by liach** [comment]
Adding a FakeWorld class is better. For EntityPlayer, there is no isFake method like this.

**Comment by raoulvdberge** [comment]
Why is it better?

**Comment by AEnterprise** [comment]
i'm working on a fakeworld implemntation for BC that extends worldserver if that would be the preferable solution to this i would gladly submit it with a PR once i get the dimension stuff for it sorted

as for EntityPlayer: why would that need a isFake method? this method is only for allowing others to detect fake worlds used by mods like BC to simulate things in

**Comment by LexManos** [comment]
Creating entire worlds are rather costly, why is BC building a fake one?
Also, I'm rather opposed to this, as it shouldn't be needed. Or at least the current situation is not properly explained.
If you must hack around something then you can use DimensionManager to check if the dimension is registered that that world to determine if it's fake.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Feature]

**Comment by HenryLoenwind** [comment]
Because there are plenty of methods that absolutely need a World as parameter. We ran into those problems, too, and I have to say, having to construct a fake World is a pain. IWorld anyone?

**Comment by LexManos** [comment]
IWorld already exists it's called IBlockAccesss
And "we ran into things" isn't an explanation. WHY did you run into things.

**Comment by HenryLoenwind** [comment]
Things like other mods not expecting a World to be fake. (e.g. https://github.com/SleepyTrousers/EnderIO/issues/4217 )

And what we use it for: Damaging a hoe needs a World and BlockPos---at least if you want to be compatible to modded hoes and not just increase the stack's damage manually. Same goes fro harvesting Natura berries---if you want to capture the berries. And basically everything that takes a FakePlayer and potentially does something with the player's world.

**Comment by LexManos** [comment]
Hoes you should just directly damage the itemstack, as for harvesting things, they need to be in the world already.. so where does the fake world come into play?
As for that example in EIO, that's Sponge hacking in things that they shouldn't not really a need for fake worlds...
Looking at your fake world, all it does is catch entity spawns... That's exactly what the EntityJoinedWorldEvent is for...  There is no need for a fake event.

Side note about your understanding of java:
Calling non-final methods/objects in the constructor IS supported, it's just something you as the caller, or the implementor need to be careful of. This is more just a reason coremods are bad, not a java fundamentals issue.

**Comment by AEnterprise** [comment]
about the use for the BC fake world: we use it for 2 things: setting the block in the fake world to then determine the requirements to rebuild said block, currently we just use pickblock but some other checks are planned to attempt to support for other modded blocks without dupe bugs

We also use it to create and re-create the blueprint for rendering inside the players inventory so he can see what the blueprint actually contains

**Comment by LexManos** [comment]
Rendering should be able to dbe cone with IBlockAccess/ChunkCache like vanilla does it's threaded rendering.
As for rebuilding? Not exactly sure what you mean there. Got more details?

**Comment by AlexIIL** [comment]
Primarily for blueprints - similar to ````net.minecraft.world.gen.structure.template.Template````, but usable in survival. Essentially you can create a schematic for one area of the world, take that schematic to a different world or server, and rebuild that area in a different place. To ensure that we don't have any dupe bugs we need to first get all of the requirements for that schematic.

**Comment by LexManos** [comment]
I'm not seeing how you'd get "dupe bugs" structure files give you the block states you need. I could see issues trying to associate itemstavks with blockststes, but wouldn't really see that as dupe bugs.... why does this need a fake world? Why not just use the server world.

**Comment by AEnterprise** [comment]
yes sometimes there can be issues tying blocks to itemstacks but for the most part it works fine

the fake world's primary usage is extracting data from blocks where a world param is required, some of those (primarely facades) need to be determined before MC has loaded (so we can register the facade in the registry or not), in this case there is no world and that is required for properties like what block sides are solid and the pickblock (for the recipe)

we also need the fake world to determine the blueprint required stacks again when we are re-creating the blueprint as we can't store itemstack in the blueprint itself, we can only save what block and it's state but not the stack itself, we thus need to be able to place the block somewhere and get the pickblock again

but the most important reason is we need to be able to do all of the checks and data extraction that needs a world away from the real world to avoid contamination. If we extract data we need to protect the real world from mods affecting the world. A mod might decide that the blockstate we are testing is a primed nuke and blow up half the world around whatever position we parse into it

**Comment by afdw** [comment]
@LexManos Because we are calculating required for building items and fluids when player inserts snapshot in builder (and probably there is no already built snapshot in world at all, so we build it in fake world and use it to calculate requirements), not when recording snapshot in architect table, because snapshot can go through clients and we can't guarantee that players are not cheating. Also blueprint editing, yes.

**Comment by LexManos** [comment]
Ya, no that still doesn't explain it. You can do all of that from the structure format itself no need for fake worlds.
Anyways this isn't really a discussion for the need of fake worlds existing, This is a request for a flag to signify that a world is 'Fake'
The term 'fake' has no real meaning. And honestly nothing here has explained why a 'fake' world needs to be treated any different than a 'real' one. 
Nobody on IRC seems to be able to figure out what the issue is either.
There is one idea that did come up that we may entertain that is tangentially related to this.
And that is to allow a World level flag for 'ticking'. So that anyone who DOES need a 'fake' world can just register a normal dimension and disable the world level ticking which would disable TEs/Entities/Blocks/...

But ya, so i'm going to close this as unneeded.
The initial issue was a conflict with Sponge's coremods and EIO doing something it didn't need to do. 
It's on Sponge's end to keep the 'contracts' that Vanilla classes have in place. I do not see any need for a 'fake' flag on anything as fake means nothing. So ya, closing this.

**Comment by AEnterprise** [comment]
The mentioned EiO issue is something comletely unrelated to this.

We cannot use the vanilla structure format unless we manually specify all the checks and options for every modded block, that is just not possible

And the need for the 'false' tag is purely for permission mods and similar to know they can ignore the world and not log block changes for every check we do

**Comment by afdw** [comment]
So if it will be droped, we will need manually specifying all requirements for all blocks, not just specifying ways how to get them.

**Comment by LexManos** [comment]
In order to replicate things in world you have to special case everything anyways because itemstacks can't be directly set to specific states. I don't think you're articulating what exactly you're talking about very well. All i'm getting is "We need to do it because we're doing it this way" There is no garentee that anything you're simulating with your 'fake world' would actually get you the real resource for that spot.

Anyways like I said, the fake flag means nothing, there really isn't a reason for 'permission mods and similiar' to ignore these fake worlds. You world should just be a normal dimension. No different then other worlds.

**Comment by AlexIIL** [comment]
We currently call ````Block.getDrops```` in order to get the itemstacks required for specific tile entities - such as the contents within chests. (This requires a world object with the tile entity set). Yes, we also need to use a lot of special cases to make this work even with vanilla blocks.

Note that this doesn't necessarily require ````world.isFakeWorld```` to work (we can work our particular issue with sponge in a different way, This is probably a miscommunication from me -> sponge as BC can be changed to work properly rather than workarounds added in sponge or forge). It might be a problem in the future, however as we don't register the dimension we can probably work around this separately with sponge.

**Comment by LexManos** [comment]
getDrops does NOT require a world object, it requires a IBlockAccess which has a getTileEntity function.
But the case still stands that there is no difference between your fake dimension and a real dimension.

**Comment by liach** [comment]
If we really make a fake world, this method should not be a part of world class, but should be retrieved via some sort of capability, etc.

**Pull request closed without merging**
