### PR TITLE
Added IItemHandler.getSlotLimit

### LINKED ISSUE #2740: IItemHandler needs a public slot limit method in order to support comparators
cc @rwtema - in case you had a rationale for not including this

This is a request for the modification of the public interface of IItemHandler to have some sort of "get slot limit" method like what is on IInventory.

Why?
- This is _necessary_ for any inventory that wants to support comparators. Comparators are implemented by dividing the current stack size by min(item's max stack size, inv.slotlimit(slot)).
  It is impossible to implement the vanilla comparator formula for IItemHandler at the moment because although ItemStackHandler has such a method, it is protected and not part of the interface.

Where?
- Add getSlotLimit(int, ItemStack): int to the IItemHandler interface. Retrofit ItemStackHandler.getStackLimit.

Implications?
- 1.9 only since we are still in the breaking changes phase

If this gets a nod, I will proceed with a PR

### PR DESCRIPTION
**Pull request by williewillus**
Closes #2740, please read that issue for my full rationale.

Added IItemhandler.getSlotLimit(int slot);
Retrofitted into all IItemHandler implementations

Breaks binary compat but I feel it's merited because
1. 1.9.x is not out of beta yet (alternatively, we can hold off til 1.9.3?)
2. IItemHandlers cannot use comparators at all which is a pretty big flaw (see issue for more details)

### CODE REVIEW

**Comment by mezz** [comment]
I view IItemHandler as an interface between mods. If you want comparator support, can't you have that as part of your internal class that implements IItemHandler? Why does it need to be exposed in the capability?

**Comment by williewillus** [comment]
So the comparator logic doesn't have to be duplicated across every single case where you need it. (Anonymous subclasses mess, duplicated code, etc.)

If this got added to interface then I can implement the default vanilla comparator algorithm on any IItemHandler, even something like the player's inventory. Right now, you'd have to use the IInventory form of the player inv to compute a comparator value off the player

Besides the comparator argument, more generally, I think an inventory interface should have some semblance of how "big" each slot is. Right now it's very up in the air (usually falling back to the stack or the backing IInventory if the handler is a wrapper)

**Comment by mezz** [comment]
Pulling or pushing items with `IInventory` should depend 100% on simulating the action and then executing it, knowing the slot limit should not be a consideration and may encourage poor item handling implementations. 
I think it would make sense if `getSlotLimit` was part of a new interface that the Forge `IInventory` wrappers implemented instead. `IInventoryInternal extends IIinventory` or something.

**Comment by williewillus** [comment]
that still doesn't solve my original problem of wanting comparator implementations for all IItemHandlers.

We can look at it another way.
Presently to get a quick comparator implementation:
1. Implement IInventory on TE
2. Override the necessary methods in Block then call Container.calcRedstoneFromInventory
3. Done.

To do it with caps:
1. Create implementation/subclass of IItemHandler, that has some sort of slot limit awareness. Guess what that slot limit is, or just fall back to the stack
3. Override necessary block methods, and then
4. I am forced to create an implementation of calcRedstoneFromInventory that casts the result of getCapability (IItemHandler) back into the concrete type I created in order to retrieve the slot limit. Even then, that slot limit is a guess
5. Not extensible in general case to all IItemHandlers

**Comment by mezz** [comment]
Alright fair enough, since the inventory is on the tile and the override is on the block that will get annoying.

To avoid duplicate/wrong code, can you add a helpers like the `Container.calcRedstone` and `Container.calculateRedstoneFromInventory` methods that work on `IItemHandler` in the PR somewhere?

**Comment by williewillus** [comment]
Yeah sure, I'll stick it in ItemHandlerHelper

**Comment by williewillus** [comment]
Added

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by williewillus** [comment]
Should I expect this to be pulled for 1.9.4 or nah?

**Comment by LexManos** [comment]
Not for 1.9.4.

**Comment by williewillus** [comment]
is 1.10.x still new enough to get this in or should I wait another major version :P

**Comment by LexManos** [comment]
1.10 has kept 99.9% of binary compatibility so it doesnt give us the usual clean break so ya.
If you can think of a way of doing this without breaking binary compatibility let me know.

**Comment by williewillus** [comment]
mmm it'd need to be in the interface to do any good

Let me know the next update this can comfortably go in

**Comment by loordgek** [comment]
@williewillus you missed SlotItemHandler#getSlotStackLimit

**Comment by covers1624** [comment]
Any more news on this? Seems like 1.11 may be our chance to get this in, or is there a possibility of doing a major breaking compact update for some of the more important things?

**Comment by williewillus** [comment]
Let me know if this is viable for 1.11 (esp with the itemstack changes I think this is a good chance) 
and I'll retarget to the correct branch

**Comment by williewillus** [comment]
@loordgek slotitemhandler simulates an insertion on the IItemHandler to get its result, so as long as the backing IItemHandler implements correctly it'll be fine

**Comment by loordgek** [comment]
any news on this ??

**Comment by mezz** [comment]
You should update this to target 1.11.x, 
Lex's complaint was that is breaks binary compat, and Forge is doing that in 1.11.x right now.

**Comment by williewillus** [comment]
will do right now, would be great to have this in 1.11

**Comment by williewillus** [comment]
#3445

**Pull request closed without merging**
