### PR TITLE
Add tags supports_beacon and supports_conduit and modify Beacon and Conduit to use these tags

### LINKED ISSUE #6262: Blocks that power the conduit are hardcoded
**Minecraft Version:** 1.14.4
**Forge Version:** 28.1.61

**Description of issue:**
The types of blocks that are valid to power up the Conduit block are hardcoded. You can find the array as `field_205042_e` in `ConduitTileEntity`. To allow for mod extension, this should be a tag.

### PR DESCRIPTION
**Pull request by DaemonUmbra**
Adds Tag compatibility for Conduits and Beacons

Also, sorry for murdering the comment history of the mentioned issue, I forgot GitHub would mention the reference.

### CODE REVIEW

**Comment by williewillus** [comment]
is there any problem with changing the default isBeaconBase impl to check the tag though? that shouldn't affect anyone overriding the method, and the tag handles vanilla

**Comment by DaemonUmbra** [comment]
And in case anyone needs proof of testing:

with [Dirt Beacons.zip](https://github.com/MinecraftForge/MinecraftForge/files/3759496/Dirt.Beacons.zip)

**Comment by ichttt** [comment]
Why did you add item tags when only the block tags are used?

**Comment by DaemonUmbra** [comment]
From what I could see every block tag has a corresponding item tag whether it's used or not, I was just repeating the pattern I saw

**Comment by pupnewfster** [comment]
> From what I could see every block tag has a corresponding item tag whether it's used or not, I was just repeating the pattern I saw

This is not actually the case if you look at vanilla's tags

**Comment by DaemonUmbra** [comment]
I was looking at Forge's tags

**Comment by LexManos** [comment]
there is nothing wrong with having the item equivalent, it just means you can have recipes that require that item.
Most forge's block tags are meant for recipe consumption, which is why it has a Item counter part... Really it's more like the Blocks are the counterpart to the Item's tags.
But either way it doesn't matter.

**Comment by williewillus** [comment]
with the generators it's easy to add and only has positive benefits (being able to use in recipes) so I don't see why not

**Pull request merged**
