### PR TITLE
Add a way to get a list of registered biome types

### LINKED ISSUE #4684: There is no official way to get a list of the BiomeDictionary.Types
There is currently no official way to get a list of existing biome types (unless I'm blind). These are the current options that I've found:

- `BiomeDictionary.Type.byName` is a private field that maps biome types with their names. I could use `setAccessible` to use it anyway. (this is what I'm currently doing)

- `BiomeDictionary.getTypes` returns only types that match a given biome. I could loop through the results for every biome returned from `getBiomes` to build a map on my end.

- `BiomeDictionary.Type.getType` returns an existing type, or a new one, if it doesn't exist. I need to use the type if it exists, but do nothing if it doesn't. So new types are created that won't ever be used.

None of these are a great solution. It would be nice if there was a method to return a map of the current biome types (or even just making `byName` public), so that I don't have to jump through these hoops.

### PR DESCRIPTION
**Pull request by ChiriVulpes**
Fixes #4684.

### CODE REVIEW

**Comment by jabelar** [comment]
Out of curiosity, why would a modder want to know all types at runtime? I'm all for making more fields public, but we also need to focus PRs on things that are commonly of interest to modders...

**Comment by ChiriVulpes** [comment]
I'm using `byName` in my mod currently with `setAccessible`, I use it for a custom ore vein generator which works via a json config. See #4684 and [where I use it in my mod](https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/world/OreVein.java).

I'm still not a Java expert so I probably won't be doing PRs that expand forge in a major way any time soon. Someday ;)

**Comment by jabelar** [comment]
If you're already using reflection to make the byName hashmap accessible then you would have the list right there (by simply getting the keys)?

Also, the list of types is available at compile time. So while it is a mild nuisance it would only take a minute to make your own list of strings. And I don't think many mods make new types and even if they do I'm not sure your mod would "know" what to do with it.

**Comment by ChiriVulpes** [comment]
I’m using reflection at the moment, but that’s jumping through a hoop for something that could be changed very easily. 3 lines of additional forge code? See the other potential ways I could resolve this, again, in #4684.

The point of doing the config this way is that it supports all vanilla types and any potential other types without having to hardcode anything. I’m not sure what you mean by “knowing what to do with it”, my mod wouldn’t use them by default, but it’s a json config. You can add in any ore veins for any modded block in any modded biome type. I make complex, powerful features like this because I can and they may help someone at some point.

If this were a patch to minecraft code I would understand the pushback, but it’s literally just a helper in forge code for getting something that is accessible in most other registries.

**Comment by LexManos** [comment]
First off your reflection is doing things wrong, it doesn't take into account the lazy loading nature of things.
Also https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/world/OreVein.java#L80 could just be changed to getType.
Forge typically doesn't add '1 line helper functions'.  Also your name for the function is just wrong. getAll would imply that it returns all Type's. Or you could go the standard Map esq naming of getKeys and getValues.
Also, for performance reasons it'd be worth caching the return of this function as a Unmodifiable set *should* be auto-updating if the backing set is changed. Creating once in the BiomeDictionary constructor would help performance.

**Comment by ChiriVulpes** [comment]
> https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/world/OreVein.java#L80 could just be changed to getType.

As mentioned in #4684:
> `BiomeDictionary.Type.getType` returns an existing type, or a new one, if it doesn't exist. I need to use the type if it exists, but do nothing if it doesn't. So new types are created that won't ever be used.

`getType` is a method that has a side effect. What if I wanted to make my config have a boolean that would cause logging when using a non-existent biome type? That could be useful for pack devs. With `getType` there's no way to know if the type was created in the query itself or already existed. 

I know the workarounds. I looked into it for an hour before I made the issue. None of the workarounds are as simple as just returning the map or the values from it. See #4684 for a list of the workarounds that I found.

As for the rest of your comment:

> First off your reflection is doing things wrong, it doesn't take into account the lazy loading nature of things.

That is something that I didn't think about, thanks. I don't remember why I wrote it this way (It's been like this for like 8 months I think)

> Also your name for the function is just wrong. `getAll` would imply that it returns all Type's.

It does?

> Forge typically doesn't add '1 line helper functions'.

I'm not sure what you mean here. I could probably list off hundreds of these that exist in the current forge code. In just `BiomeDictionary` alone there's `getBiomes`, `getTypes`, `hasType`, `hasAnyType`. Am I misunderstanding something here?

> Or you could go the standard Map esq naming of getKeys and getValues.

I don't really care how this works, as long as it works. If this is the form this PR should be in that is the most likely to be accepted, I am all for it.

> Also, for performance reasons it'd be worth caching the return of this function as a Unmodifiable set *should* be auto-updating if the backing set is changed. Creating once in the BiomeDictionary constructor would help performance.

Sounds good. If this PR can move forward and needs to be changed to return something different, I will change it to work that way then.

**Comment by ChiriVulpes** [comment]
Please let me know what changes I need to make to get this merged.

**Comment by mezz** [comment]
I think you just need to store the result of `Collections.unmodifiableCollection` in a field.

**Pull request merged**
