### PR TITLE
Added @Nullable to fluid interface

### PR DESCRIPTION
**Pull request by laci200270**
Same as #2199 but for 1.8.8

### CODE REVIEW

**Comment by diesieben07** [comment]
What is a null value even supposed to mean here? That should definitely go into the JavaDocs.

**Comment by laci200270** [comment]
Added javadocs

**Comment by diesieben07** [comment]
How does interdimensional transfer mean you don't know the side?  Honestly I highly disagree with this approach, maybe there could be a defaultSide method in the interface or something like that. In any way I think specifying a side should not be optional.

**Comment by laci200270** [comment]
We've discussed this in #2033 and #2014

**Comment by diesieben07** [comment]
Yes. And Lex brought up this point 5 months ago: https://github.com/MinecraftForge/MinecraftForge/pull/2014#issuecomment-122611616
It was ignored. And no other usecases have been presented by anyone.

**Comment by mezz** [comment]
This PR can be closed.
This interface has been removed in 1.11.x and the new interface has correct null annotations.

**Pull request closed without merging**
