### PR TITLE
Allow registries to be handled before BLOCKS and ITEMS (fixes #4987)

### LINKED ISSUE #4987: [1.12] Allow (select) registries to operate before Blocks & Items
I'd like it if I could harness the power of registries for things a ends up registering blocks & items for.

I'm willing to write the PR, I believe it would require about 10~20 lines of code over 4 files (RegistryBuilder, RegistryManager, ForgeRegistry, and finally GameData). Most of these would just be passing the boolean down to the registry.

In GameData, I'd change `fireRegistryEvents`:

```java
// Sorting unchanged

for (ResourceLocation rl : keys)
{
    if (!filter.test(rl)) continue;
    if (rl == BLOCKS || rl == ITEMS) continue;
    Registry reg = RegistryManager.ACTIVE.getRegistry(rl);
    if (!reg.preBlocks) continue;
    MinecraftForge.EVENT_BUS.post(reg.getRegisterEvent(rl));
}
ObjectHolderRegistry.INSTANCE.applyObjectHolders(); // inject the preBlocks registries

// Blocks & Items unchanged

for (ResourceLocation rl : keys)
{
    if (!filter.test(rl)) continue;
    if (rl == BLOCKS || rl == ITEMS) continue;
    Registry reg = RegistryManager.ACTIVE.getRegistry(rl);
    if (reg.preBlocks) continue;
    MinecraftForge.EVENT_BUS.post(reg.getRegisterEvent(rl));
}
ObjectHolderRegistry.INSTANCE.applyObjectHolders(); // inject everything else

```

**The use case is as follows:**

I'm updating [TerraFirmaCraft to 1.12.2](https://github.com/TerraFirmaCraft/TerraFirmaCraft#readme) and would like to make it easier to write addons that add functionality to the base mod. By letting an addon register for example rock types, it would not have to take care of registering close to 50 blocks and items and integrating them into worldgen and other systems. Same for ores, metals, alloys, tree types, etc.

The infrastructure is all there, I just can't harness it at the moment. It would be a shame to have to write a pile of boilerplate for something already there.

Thanks in advance.

### PR DESCRIPTION
**Pull request by dries007**
See issue #4987 for more details.
The change was so small I decided to make a PR so if approved, it could be merged immediately.

### CODE REVIEW

**Comment by liach** [comment]
i sincerely suggest using a topological sort to handle all cases like this (e.g. potion type and potion registries)

**Comment by MajorTuvok** [comment]
I would agree, that instead of simply allowing weather they are before Blocks and Items we should introduce a kind of sorting system for Registries...

We could for example pass an Comparator Object into the RegistryBuilder which is evaluated when the Registry is added. Like:
- We'd iterate on the currently existing Registries as long as the new Registry say's it doesn't mind being inserted after the current one (Comparator returns 1). 
- If it returns 0 one could check whether the other (already inserted) Registry has any preferences (like f.e. if it would like to be after the newer one) and if this one returns 0 too, proceed as if the new one had returned 1 in the first place. 
- If it returns -1 one we'd insert it at the current Position (regardless what the other Registry at the current Position says)

This provides the benefit of working around any circular dependancys which might occur if both would return 1 or -1 by giving precedence to the one which was added later (and who's mod probably has the other one as a "before" dependancy). One could maybe print out a warning if such a contradiction were to be found.

I'd appreciate any feedback on this approach (If you guys agree with me that something like that or something similiar would be a good idea, I'll quickly code it...)

**Comment by dries007** [comment]
This version of the implementation has been rejected. Last I saw Skyboy was implementing proper topological sorting. I'm sure we'll see a better PR on that once ready.

**Comment by MajorTuvok** [comment]
It's just, I don't know whether my idea wouldn't be too much...
What are you referring to with Skyboy?

**Comment by liach** [comment]
well that'd be a good chance for me to review his toposort.

**Comment by MajorTuvok** [comment]
I reviewed the toposort used for sorting Mods and [adapted it for Registries](https://github.com/MajorTuvok/MinecraftForge_RegistrySorting/tree/1.12.x/src/main/java/net/minecraftforge/registries)... I'd apreciate any comments (though I don't have time to write about all the things which are still missing...)

**Comment by dries007** [comment]
I'm refering to this: https://github.com/skyboy/MinecraftForge/commits/registry-sort 
I'm sure @skyboy'll PR it when it's ready.

**Comment by MajorTuvok** [comment]
Ah ok, thx...
So I won't have to do that...

**Pull request closed without merging**
