### PR TITLE
[1.16.x] Add possibility to create custom Game Rule and Category

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
This PR adds the possibility of creating custom Game Rules as well as the categories that go with it.

A test mod is included

### CODE REVIEW

**Comment by diesieben07** [comment]
The problem with this is that game-rules are not namespaced, so there will be conflicts. The question is, why does this need to exist at all? The equivalent in mods would be configs. A command to modify mod configs would be much more useful instead, no?

**Comment by Mysterious-Dev** [comment]
Yes it is a good idea for the command but the only problem is that it applies to all the worlds of the game, while a Gamerule only applies to the world. The two solutions can be complementary

**Comment by diesieben07** [comment]
There are world-scoped configs as of 1.13.

**Comment by Mysterious-Dev** [comment]
Oh okay, I didn't know that

**Comment by Mysterious-Dev** [comment]
But then in this case we could make a gui like the gamerules screen for the creation world.

**Comment by Mysterious-Dev** [comment]
What do you think @diesieben07 ?

**Comment by diesieben07** [comment]
Sure, that would be cool. There have been efforts to port forward the config GUI.

**Comment by Mysterious-Dev** [comment]
But in this case it would be a GUI at the creation of the world.

**Comment by diesieben07** [comment]
Same idea, the most of the work that needs to be done is actually building a GUI for the configs.

**Comment by ExpensiveKoala** [comment]
I don't agree with @diesieben07 that this is useless because per-world configs exist.
Making it so you need a custom command to change your config is how you get hundreds of commands that just clutter /help anyways.

If you mean for there to be a system to dynamically create commands for the configspecs, then that in itself seems redundant. Which is why a pre-world create config screen was suggested. That doesn't work for values people want to change multiple times throughout the playthrough. Especially so if the point is to make it command block accessible, or even allowing a questing book mod to run the command on completion.

A gamerule extension cuts the command clutter, significantly reduces the overhead needed to create those commands.

Also, the suggestion that it not being namespaced which causes clashes can easily be solved with a slightly bigger patch.

There are also many enums that were extended, but didn't include making them namespaced. Like: https://github.com/MinecraftForge/MinecraftForge/pull/5464

I can definitely see the other side of the argument that configs do everything that gamerules already do, but is that enough of a reason to locking out modders from extending upon vanilla behavior?

**Comment by Darkere** [comment]
Someone already made a mod to change any config (except for client-configs) via command. https://www.curseforge.com/minecraft/mc-mods/commands4configs

This means modders don't even need to implement a command, which is a much better solution IMO.

**Pull request closed without merging**
