### PR TITLE
GuiHandler BlockPos update

### PR DESCRIPTION
**Pull request by 28Smiles**
The GuiHandler now also uses BlockPos instead of int x, y, z

### CODE REVIEW

**Comment by diesieben07** [comment]
Some people use these numbers for stuff that are not coordinates (e.g. an entityID).

**Comment by Lunatrius** [comment]
It also breaks existing mods (method signature is different).

**Comment by 28Smiles** [comment]
@Lunatrius 
what if i use both method signatures in two Interfaces so the Modders can use what they prefer? the old and the new one, a smooth change.

@diesieben07 
you also have those three numbers now just packed.

**Comment by Lunatrius** [comment]
It wouldn't be all that smooth. For one, you're changing the network protocol. Instead of sending 3 ints (96 bits) you're sending a long (64 bits). Different versions of Forge on the server and client will just blow up.

As for the numbers, no, they're not the same. X and Z are trimmed to 26 bits and Y to the remainder (12 bits).

**Comment by 28Smiles** [comment]
Ok i got it

**Comment by cpw** [comment]
I doubt we'd ever change this. The numbers have other utility.

**Comment by LexManos** [comment]
Agreed, they are named x/y/z because thats the most common usage and 'data1/data2/data3/ just sounds ugly.

**Pull request closed without merging**
