### PR TITLE
Added CriticalHitEvent

### PR DESCRIPTION
**Pull request by mcenderdragon**
Adds an Event to control the behauvior if an Player does an critical hit.

This is a retargeting of #2935 and solves #2871 .

Also an example:https://gist.github.com/mcenderdragon/b2e11c054dca08c566934a860087d881

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by iLexiconn** [comment]
Update to 1.10 :P

**Comment by mcenderdragon** [comment]
@iLexiconn I see what you did there :P

by-the-way: if #3023 gets merged this PR will have a merge conflict and viseversa. Is there anyway I can prevent this from happening ? (Or is this mess normal for the patch files?)

**Comment by tterrag1098** [comment]
It's pretty normal. You'll just have to wait and see. If the other one gets merged first, just pull and regen your patches.

**Comment by mcenderdragon** [comment]
1.10.x is now the main branch, should I retarget or will it get merched into the master branch?

**Comment by RANKSHANK** [comment]
The master branch format has been 'dropped' in favor of version named branches.  Just target the 1.10.x branch and all will be jazzy

**Comment by tterrag1098** [comment]
@mcenderdragon Please rebase to 1.10.x branch to see this reopened.

**Comment by mcenderdragon** [comment]
ok ( #3190  )

**Pull request closed without merging**
