### PR TITLE
Add isServer and isClient methods to LogicalSide

### PR DESCRIPTION
**Pull request by darkevilmac**
A small change, better matches ```Dist``` and makes code a bit easier to read.

### CODE REVIEW

**Comment by loordgek** [comment]
the javadoc is wrong

**Comment by darkevilmac** [comment]
> the javadoc is wrong

Not sure how I fucked that up. Fixed.

**Review by tterrag1098 — APPROVED** [review]

**Comment by LexManos** [comment]
I can not overstate how I hate these functions. They are noting but helper functions that cost more cpu cycles then a simple != or ==. You can try and decrease the performance penalty by making them final and hoping the JITer inline them. {Which yes it's specifically designed to do, so it's not that big of a deal} But then you also went the route of making isServer a nested function call. Which pretty much guarantees it will never get inlined. All for what? What benefit does this serve? I know it matches Dist, but that has a purpose, as it was intended to be expanded to things like BUKKIT/SPIGOT/SPONGE. But that never came to be.

**Comment by raoulvdberge** [comment]
There are only 2 sides, so what function do these helper methods serve? Won't a ```side == LogicalSide.CLIENT``` accomplish the exact same thing?

**Comment by MajorTuvok** [comment]
@raoulvdberge that is true, but using Methods on the enums allows one to get away from hardocding enum matches, aka nicer code... 

Also if one would pass a boolean to the constructor which would  then cache **2** booleans, to be returned in the Methods, would that be ok for you Lex? 
Though I honestly don't get the performance concerns on the function level, yes Methods add a little bit of overhead, but that is a very neglible constant...

**Comment by darkevilmac** [comment]
I can switch to using a direct comparison in both of the methods if that works better than using ```!isClient()``` the code was literally copy pasted with adjustments to use the correct field names and documentation.

As for the reason I even made this PR it's really simply readability and consistency, LogicalSide and Dist are both enums that represent the server and client side (Yes I know the difference between the actual dedicated server and an integrated server, that's why there's more than one enum). That and when I'm programming I find it a lot nicer to use a method to check the side than checking if the value matches a predefined enum.

**Pull request merged**
