### PR TITLE
[1.16.x] Render local player when the renderViewEntity is not the local player

### PR DESCRIPTION
**Pull request by XFactHD**
This is the same as #6945 because I blew that one up...

# Description
This PR modifies the render check for entities in WorldRenderer to make the local player entity render when it is not a spectator and is in the field of view of another entity that is currently set as the renderViewEntity. I have also included a test mod to show it working.

# Use-cases
This is useful in any case where another entity that might see the local player entity is set as the renderViewEntity.
My specific use case is a camera system where the renderViewEntity is set to a dummy camera entity. After trying what I described on the [Forge forums](https://forums.minecraftforge.net/topic/87254-1152-force-drawing-local-player-entity/) this seemed like the safest and most sane solution to me.

### CODE REVIEW

**Comment by XFactHD** [comment]
This PR is now ready for 1.16.2.

**Comment by XFactHD** [comment]
@OrionDevelopment Would you mind taking a look at this again? I blew up the original PR because of a stupid mistake...

**Comment by XFactHD** [comment]
Rebased onto latest changes

**Comment by Earthcomputer** [comment]
Maybe add a comment in the patch saying what's changed?

**Comment by XFactHD** [comment]
Done

**Comment by diesieben07** [comment]
Lex voiced some concern on Discord regarding this.
I have deciphered this mess of a condition. It boils down to this, in vanilla:
An entity is rendered if all of the following is true:

1. The entity is inside the view frustrum or is being ridden by or riding the player.
2. The entity is not the view entity or, if it is, third person mode is active or the entity is sleeping.
3. The entity is not a player or is the view entity.

The last point is changed here to not filter out the client player, but only if they are not a spectator. The spectator check is needed to preserve vanilla behavior (you cannot see spectator mode players who are spectating an entity).

**Pull request merged**
