### PR TITLE
[1.12.x] Added BucketUse event to ForgeUniversal Bucket

### LINKED ISSUE #4436: [1.11/1.12] Forge Universal Bucket dont post Events
While the vanilla Bucket uses `ForgeEventFactory.onBucketUse` and post (even if full) the Fill BucketEvent (wich should be renamed to BucketEvent), the Forge Bucket does this not. This results in absolutly no way to prevent Fluid Placement from Modded fluids.

I think we should just add the onBucketUse call like in the Vanilla Bucket (the code is almost the same in both buckets)

### PR DESCRIPTION
**Pull request by mcenderdragon**
This fixes #4436.

I is just the same as in ItemBucket.

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
On first look it seems that you are editing on GitHub (compile issues!), but you are not.

**Comment by mezz** [comment]
Universal bucket also subscribes to `FillBucketEvent`. 
Isn't that going to do very weird things?

**Comment by mcenderdragon** [comment]
@mezz possible let me check this...

Edit: we may need to check if the bucket realy is an empty vanilla bucket.

Edit 2: the only think happening is it tries to fill an alredy full bucket, this can beusefull if yiu have a bucket with more than 1000mB

**Comment by mezz** [comment]
It looks like the event already checks that the bucket is the vanilla empty bucket.
This raises more questions though.

The way the forge bucket works right now, the empty bucket is already the vanilla empty bucket.
You should never really see or use an "empty" forge bucket.
So I don't think this PR does anything...

Can you explain what you are seeing differently?

**Comment by mcenderdragon** [comment]
as stated in #4436, the " FillBucketEvent" is also used as "EmtpyBucket" event, so you can currently only block (or  notice) the placement from vanilla fluids (lava + water) and the pick from any fluid. This PR fixes this so you can detect & change the placement of modded fluids using the forge bucket.

**Comment by mcenderdragon** [comment]
no @stale this can get merged ;P

**Pull request merged**
