### PR TITLE
Villager Registry stuff updated to the 1.8.9 stuff.

### PR DESCRIPTION
**Pull request by Thutmose**
#2219 but for master branch, with the merge conflict dealt with.

### CODE REVIEW

**Comment by 61352151511** [comment]
In your PR #2219 CPW last said he had worked on it in his dev environment and would hopefully be able to push it over christmas break. So far I haven't seen it be pushed but hopefully it gets done soon.

**Comment by gabizou** [comment]
Out of curiosity, any chance on getting some sort of update on this?

**Comment by Thutmose** [comment]
Well, at least it still claims to be merge compatible, so hopefully it will be looked at soon...

**Comment by LexManos** [comment]
The last time this came up @cpw was working on re-writing the entire registry system and the villager registry included. He said this was done do it's feasible to look into it. But need to poke him about this.

**Comment by gabizou** [comment]
Is there any sort of progress either on the registry rewrite or towards accepting this PR?

**Comment by kashike** [comment]
@gabizou https://github.com/MinecraftForge/MinecraftForge/pull/2625

**Comment by cpw** [comment]
Yeah, I am finishing up the api right now. Should push tomorrow.

**Comment by williewillus** [comment]
Basically done, pending #2823 and some other bugs, so closing

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Pull request closed without merging**
