### PR TITLE
Release assets on Github too

### PR DESCRIPTION
**Pull request by Osiris-Team**
The workflow release.yml must be executed manually by pressing a button when you wish to create a release.
It builds the jar files, creates a release, and uploads the assets. It should also contain a changelog (simply commit history) I think.

Only thing I need to know is the location of the jar files. See `TODO_FIND_PATHS/...` in release.yml.

### CODE REVIEW

**Comment by TheCurle** [comment]
Sorry, but we have no interest in publishing to Github right now.

**Comment by Osiris-Team** [comment]
@TheCurle why if I may ask? Is it because you have to press a button? I could also make it release automatically on a change.

**Comment by TheCurle** [comment]
Because it's of no use to us.

We have a TeamCity build server that publishes to a public and free maven server (https://files.minecraftforge.net), and our build servers regularly exceed the monthly limits for Actions minutes, let alone the storage costs exceeding GitHub's fair usage policy.

It's simply not feasible, nor ethical, to use Github actions to publish Forge.

Additionally, it adds to the maintenance cost of our build server, as now we'd need to keep two separate, distinct and completely unrelated build systems working and up to date, since Actions is not nearly as reliable uptime-wise as our own build servers.

**Comment by Osiris-Team** [comment]
Ok thanks for the details!

**Pull request closed without merging**
