### PR TITLE
Added support for modded forge biomes to the overworld through BiomeLayer

### PR DESCRIPTION
**Pull request by ghost**
Adapted the same patch on 1.15.2 to 1.16.1 Forge to allow modded forge biomes from `BiomeManager` to be used in `BiomeLayer` with weighted lists. Should be straight forward and crucial patch, of course let me know if there are changes required to the styling or similar.

### CODE REVIEW

**Comment by ghost** [comment]
Okay if someone can help me remove Squishling, its just my git and I can't change the author for some reason, this is the second PR of this.  I guess if I can't get this fixed I'll just start a new branch and make the same changes.

**Comment by Yunus1903** [comment]
You should be able to change the author locally then force push

**Comment by ghost** [comment]
I should be able to yes, and I thought thats what I did

**Comment by ghost** [comment]
I'm just gonna close this PR too, make a brand new branch and copy paste my changes into it, because I just can't figure out this git thing.

**Comment by diesieben07** [comment]
Please update your existing PRs instead of making new ones.

**Pull request closed without merging**
