### PR TITLE
[1.20] Add example title to MDK creative mode tab

### PR DESCRIPTION
**Pull request by SizableShrimp**

### CODE REVIEW

**Comment by PaintNinja** [comment]
There should also be a lang file and a comment referencing it

**Comment by SizableShrimp** [comment]
Probably, yes. But that requires setup of datagen and genning the file. I have plans to setup datagen in the MDK to use a separate sourceset; I believe members of the community are already doing this, and it is probably best practice to keep useless stuff like that out of the final jar. It also has the added benefit of not needing datagen able to compile when porting, at least to start.

**Review by marchermans — CHANGES_REQUESTED** [review]
Whether or not we need datagen is not the point I think.
We should at least have a manual file, so it does not look weird, you can add a comment into that file, via some dummy key `"_comment"` to indicate that modders should generate this.

**Comment by LexManos** [comment]
Honestly, it just having a empty display name is fine with me. Adding this opens up the need to explain localization, and data gen as you guys said. The MDK isn't meant to be a code example it's meant to just be the bare bones project. If we are to start making more code examples in the MDK then it necessitates getting the tooling up to check the MDK is still functional during PRs and builds. We've talked about this before, and i'll close this for now until someone feels like going down the gradle side of that requirement.

**Pull request closed without merging**
