### PR TITLE
Added unknown

### PR DESCRIPTION
**Pull request by laci200270**

### CODE REVIEW

**Comment by LexManos** [comment]
Nope, breaks to many things, adds a handful of new blockstates, and just encourages lazy coding. Null exists for a reason guys.

**Comment by KingLemming** [comment]
Lex, if you don't want to extend this, bring back ForgeDirection.

The UNKNOWN state is *very* useful. In fact, I would argue quite necessary.

**Comment by LexManos** [comment]
Explain your case.

**Comment by laci200270** [comment]
@LexManos he said on irc he not want to use a custom enum,  he want to compatibile with IFluidHandler, and  probaly in this case Optional not acceptable

**Comment by laci200270** [comment]
@LexManos if the Optinal is the alternative of unkown, IFluidTanks and such should take Optional<EnumFacing> instead of EnumFacing , isn't it?(this should be introduced only on 1.8.7 because compatibility issuses)

**Comment by LexManos** [comment]
Thats up to KingLemming as he is the one who designed and is in charge of fluids.
However if his intention is to support a 'unknown is valid but null is not' then yes, it should.

**Comment by sham1** [comment]
@laci200270 Thew thing about IFluidHandler is that you most likely don't want to give non-specified to any IFluidHandler methods. 

canFill and canDrain ask the IFluidHandler if the caller can drain/fill from specified direction, so having a not specified direction does not make sense. drain and fill methods drain/fill respectively from specified directions so you can have specific IFluidTanks on different sides, so again the having no direction does not make sense. And same reason as above can be applied with getTankInfo.

So no, Optional<EnumFacing> would not make any sense for IFluidHandler.

**Comment by laci200270** [comment]
If optional value isn't set,  should be a primary tank where it can drain/fill

**Comment by sham1** [comment]
That's the thing though, you as a developer make that choice. But we are getting off-track.

**Comment by laci200270** [comment]
@KingLemming said one example: teleportation across dimensions

**Comment by grum** [comment]
And this could be achieved with either `@Nullable EnumFacing` or `Optional<EnumFacing>`.

**Comment by LexManos** [comment]
Teleporting across dimensions could STILL be done using a direction, as the side that is passed in is the side that it's simulating the filling/interaction.In the case of cross dimension typically the thing doesnt care and just will accept any side. If not then you can specify a specific one.

**Comment by SoniEx2** [comment]
Why we need UNKNOWN: https://github.com/SoniEx2/PowerRouters

**Comment by williewillus** [comment]
You're going to have to explain yourself with more than a link if you want any serious consideration

**Comment by SoniEx2** [comment]
Let's say you have a 3x3x3 box of fluid handlers. Then you place down a router beside any of them.

Now, the router detects there are 6 directions it can use to access the middle fluid handler, 5 for each center piece, 4 for each edge piece, 3 for each corner piece (there's an exception related to where the router is placed but it's not relevant here, assume it's placed on one of the center pieces.).

Which direction do I use for each of them? I don't. This is where UNKNOWN comes in. If I give it `null` best case it crashes, with no way to get back in the world, unless you either remove the router or remove the mod. Worst case it corrupts your world.

**Comment by SoniEx2** [comment]
(I really wish fluids aligned closer to the IInventory/ISidedInventory vanilla's got going on, btw. With slots and stuff.)

**Comment by williewillus** [comment]
You use the direction that it came into the router in the first place (that's what i would expect if I were using this). 
Uhhh no? Passing null to a tile that stupidly doesn't null check will just crash it without a state change - no world corruption unless the tile author was being incredibly dumb.

That "more like isided" thing you're looking for is capabilities.

**Pull request closed without merging**
