### PR TITLE
Add a RenderArmEvent (LTS Backport of #8254)

### PR DESCRIPTION
**Pull request by pupnewfster**

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

**Comment by MrScautHD** [comment]
you should maybe add also the playerModel (for arm Animations, rotations)

**Comment by pupnewfster** [comment]
> you should maybe add also the playerModel (for arm Animations, rotations)

1. This is an LTS backport it doesn't get more features than latest, so you should have brought up maybe passing that on the original PR.
2. It isn't really that big a deal given you can easily just call the same getter vanilla does to retrieve it:
```java
((PlayerRenderer) Minecraft.getInstance().getEntityRenderDispatcher().getRenderer(event.getPlayer())).getModel();
```

**Comment by MrScautHD** [comment]
> > you should maybe add also the playerModel (for arm Animations, rotations)
> 
>     1. This is an LTS backport it doesn't get more features than latest, so you should have brought up maybe passing that on the original PR.
> 
>     2. It isn't really that big a deal given you can easily just call the same getter vanilla does to retrieve it:
> 
> 
> ```java
> ((PlayerRenderer) Minecraft.getInstance().getEntityRenderDispatcher().getRenderer(event.getPlayer())).getModel();
> ```

ya but for animations is it good if you not override it, because for animations of other mods is it gone

**Comment by MrScautHD** [comment]
you should set the event to renderHand then can you make then return the model to it and with a second event can you animate it, so is it mod compatible

**Comment by KnightMiner** [comment]
Let me remind you @MrScautHD of the first thing pupnewfster said

> This is an LTS backport it doesn't get more features than latest, so you should have brought up maybe passing that on the original PR.

If you want more features in this, discuss it on discord or make a new PR for 1.18. Those new features can be backported to 1.16. As it stands this was already merged on 1.16 thus it is too late to redesign it for a backport.

**Pull request merged**
