### PR TITLE
[Omnibus] Add common tags

### PR DESCRIPTION
**Pull request by tterrag1098**
# This Is An Omnibus PR

[Open PRs](https://github.com/MinecraftForge/MinecraftForge/pulls?utf8=%E2%9C%93&q=base%3Anoci-omnibus%2Ftags+is%3Aopen) | [Included PRs](https://github.com/MinecraftForge/MinecraftForge/pulls?utf8=%E2%9C%93&q=base%3Anoci-omnibus%2Ftags+is%3Amerged) | [Submit PR](https://github.com/MinecraftForge/MinecraftForge/compare/noci-omnibus/tags...tterrag1098:noci-omnibus/typos)

### What does this Omnibus target?

This PR is targeting the new tag system, making sure that forge has a good base of default tags for modders to work with and standardize on.

### What does this mean?

An omnibus PR is our new way of combining common, small contributions into a single PR so that they can be merged in a single build, while maintaining the simplicity of contributing small fixes piecewise.

### How can I contribute?

To contribute to this omnibus, you must make your PR at the [source branch](https://github.com/MinecraftForge/MinecraftForge/compare/noci-omnibus/tags...tterrag1098:noci-omnibus/typos). You'll need to switch the source repository/branch when using that link. Once your PR is approved it will be merged to the omnibus branch for later merging into the main trunk.

### CODE REVIEW

**Comment by MajorTuvok** [comment]
A question, would be adding a 'safe_copy' or 'unsafe_copy' Tag be a thing for Forge?
It would represent Blocks who can be fully copied without risking dupe or something - plants (growth stage) or Tiles (with Inventory) for example would not be safe to copy.

I'm pretty sure that any mod which copies (I think mimc blocks might like this too, not so sure though) things around might like it.

[I'm asking that because not that many mods do this and it can easily be shipped as Tag by those that do...]

**Comment by williewillus** [comment]
That's outside forge's scope, imo

**Comment by Darkhax** [comment]
I see that this is past deadline, but hasn't been touched for a while. I don't have time to make a PR right now and I don't know when I will get the chance, but there are a few big things missing. 

The following are from the old oredict system which I can't seem to find in the new system. While some of these were not used that much, I think that slimeball, bone, string, leather, and feather are used quite a lot. 
- slimeball
- enderpearl
- bone
- gunpowder
- string
- leather
- feather
- egg

In Bookshelf for 1.12 I also added a good number of common ore names used across my mods (mainly dark utils and hunting dimension) and other mods like Quark, which are used for crafting equivalency. Here is that list. 
- shulkerbox (all the dyed variants)
- itemStorage (chests and shulker boxes)
- seed (wheat, pumpkin, melon, beetroot, not sure if 1.13+ added more)
- rail (rail, activator, detector, golden)
- arrow (arrow, spectral, tipped)
- bed (the bed colors)
- hopper
- bookshelf
- bone storage block
- netherwart storage block
- magma block
- shulker shell

**Comment by mcenderdragon** [comment]
What is curerently the correct PR this one or #5647 ?

**Comment by tterrag1098** [comment]
@mcenderdragon what do you mean? That is not an omnibus PR. He needs to rebase his changes.

@darkhax These didn't get the attention I was hoping for, there wasn't enough changes to justify merging and starting a new one. We will probably pull whatever there is when we go to start 1.14 dev.

**Comment by mcenderdragon** [comment]
the tags from this PR and the other one where almost the same but I did not check which PR was larger and added more Tags. 
But it seems like as this is the main PR and the other one needs to get merged into this.

**Comment by LexManos** [comment]
If someone wants to go along and add the generator code to this. I can pull it in.

**Comment by LexManos** [comment]
Alright, went through and converted the bulk of these tags into the new generator system.
https://github.com/MinecraftForge/MinecraftForge/commit/2c8c022034ba9967affc7ecf02dc6583f4f3652a#diff-daff4806d5dedaca7371832d9a522c4a

I did NOT port a few of them. As I don't agree with, or don't understand the logic.
Notably the huge/small mushrooms thing.
I also attempted to unify all the naming into plurals like we have been, as well as changed sand/normal to sand/colorless like we have the other colors.

**Pull request closed without merging**
