### PR TITLE
Fix CME on chunk unload in FarmlandTicketManager [1.14]

### PR DESCRIPTION
**Pull request by ichttt**
This fixes the CME observed in 1.12.2 by removing the automatic ticket removal on chunk unload. All the javadocs already note that you should remove the ticket yourself when possible. Also makes the ChunkTicketManager in the map weak, so the can be gced when no ticket references them anymore.

### CODE REVIEW

**Comment by LexManos** [comment]
Instead of removing the auto-culling, why not just add a check for the 'source' chunk of the ticket?

**Comment by ichttt** [comment]
We cannot even get the source chunk currently, as all the needed chunks are just computed based on the AABB given. The entire API would need to be changed to include the concept of a source chunk.

The feature is kind of unneeded now as well, as even if a mod TE forgets to invalidate his ticket when it unloads, it will still be unloaded sooner or later because of the weak reference.
IMO we should just drop it instead of complicating the whole system.

**Comment by LexManos** [comment]
`it will still be unloaded sooner or later because of the weak reference.`
The weak reference is to the ChunkTicketManager which nobody ever has a reference to so it'll almost immediately get culled whenever the GC feels like it making the map completely useless.
If we need to expand the API to have a owner, then go for it.
The other option is to have the ticket give you a list of it's chunks and if they are all unloaded then we can invalidate.

And if i am not making myself clear enough, the answer is no. Just making it weak and calling it good is NOT going to be accepted.

**Comment by ichttt** [comment]
This PR is ready.
Just some notes to the implementation:
- This is currently a breaking change, but not a large one, as it only covers methods that should not be used by many moders, so a pull before RB would be nice
- Auto-Chunk culling is still a thing, and is more robust than before, so the behaviour is consistent and does not produce any CMEs
- The Vec3d with the position is now correctly centered to the block. Previously, two side would have an extra block in the AABB due to the pos not being at the center, but on the egde
- The list now holds weak references to ChunkTicketManagers, so managers that aren't used by any ticket anymore can be gced. This is not a problem, as missing manager is the same as manager with zero tickets

**Pull request merged**
