### PR TITLE
Added MouseMovementEvent

### PR DESCRIPTION
**Pull request by KidsDontPlay**
There is currently no way to detect whether the player is moving the mouse and looking around.
That's why I added an event for that.

### CODE REVIEW

**Comment by pau101** [comment]
I would suggest naming the class simply `MouseMoveEvent`.

**Review by Gamebuster19901 — CHANGES_REQUESTED** [review]
~~I don't believe this event is necessary. LWJGL already provides this functionality~~

~~You can use `org.lwjgl.input.Mouse.getEventX()` and `org.lwjgl.input.Mouse.getEventY()` to determine if the mouse has moved.~~

~~You can also use `org.lwjgl.input.Mouse.getEventDX()` and `org.lwjgl.input.Mouse.getEventDY()` to get the mouse's velocity.~~

**Comment by diesieben07** [comment]
@Gamebuster19901 That is no longer the case with the updated LWJGL version used in 1.14.4.

**Comment by Gamebuster19901** [comment]
@diesieben07 

You're correct about that no longer being the case in 1.14.4, my apologies.

However minecraft in 1.14.4 actually provides this functionality itself. See ```net.minecraft.client.MouseHelper```

It has the following methods

```java
public double getMouseX();
public double getMouseY();
public double getXVelocity();
public double getYVelocity();
```

One can check if the mouse is moving by doing the following:

```java
public boolean hasMouseMoved() {
    MouseHelper mouse = Minecraft.getInstance().mouseHelper;
    return mouse.getXVelocity() != 0d || mouse.getYVelocity() != 0d;
}
```

**Pull request closed without merging**
