### PR TITLE
Created getSunBrightnessFactorBody for code consistency

### PR DESCRIPTION
**Pull request by Abastro**
To make sure that mods do not call native version of getSunBrightnessBody.

### CODE REVIEW

**Comment by LexManos** [comment]
Then add javadocs... not bouncer methods doing exactly nothing.

**Comment by Spartan322** [comment]
What would the purpose be? It seems like a modified javadoc would work out better for everyone

**Comment by Abastro** [comment]
Because modders should not use the method. It is rather primitive method, but i failed to name it as primitive on first PR.

**Comment by williewillus** [comment]
That's what javadoc is for..
There are hundreds of methods in vanilla code that are public yet should never be called by modders

**Comment by Abastro** [comment]
I didn't know that, but this method is easy to confuse modders because conventionally methods in World references same methods in WorldProvider. In this case it is inverted.

**Comment by williewillus** [comment]
Change the Javadoc using the bot then

**Comment by Abastro** [comment]
How to change javadoc using bot? This is method created in forge so not related with MCP.

**Comment by williewillus** [comment]
Oh, then just change the Javadoc :P
Minor change usually don't get accepted individually though

**Comment by Abastro** [comment]
Thats problem.
And this is about my previous mistake.
(The method is given by my PR.)

**Pull request closed without merging**
