### PR TITLE
1.17.1 Add TeamCity workflows & checks and backports some gradle stuff from 1.18.x branch

### PR DESCRIPTION
**Pull request by SrRapero720**

### CODE REVIEW

**Comment by SrRapero720** [comment]
## COMPATIBILITY CHECK FIXED
i already test, modules are correctly shaded, check works and doesn't seems like it have any compat issue with some _overcustomized_ modpack

image
image
image

**Review by PaintNinja — CHANGES_REQUESTED** [review]
Your dependency bumps contain breaking changes - see https://github.com/MinecraftForge/MinecraftForge/pull/9877

**Review by PaintNinja — APPROVED** [review]
Thanks for working on this! :)

One thing to note that was discussed [on Discord](https://discord.com/channels/1129059589325852724/1129095235889270844/1216481400237330462) is the bump from Mixin 0.8.4 to 0.8.5 might be a breaking change, but opens up the possibility of a jarjar backport. Aside from that though, looks great. Approving and assigning Lex to double check.

**Comment by LexManos** [comment]
So, this looks good, minus the lack of ability to test on TC itself.
Tho this needs the crowdin update. Besides that should be fine, might break something somewhere. But what doesn't.

**Comment by SrRapero720** [comment]
crowding done

**Comment by LexManos** [comment]
Whelp lets see if Team City behaves

**Comment by LexManos** [comment]
Looks like it works for the most part, just needs to fixup the S2S tasks
```
19:06:14   :forge:extractRangeMap
19:06:14   Error: LinkageError occurred while loading main class net.minecraftforge.srg2source.ConsoleTool
19:06:14     java.lang.UnsupportedClassVersionError: net/minecraftforge/srg2source/ConsoleTool has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
19:06:16   
```
And figure out why discord says the version is unspecified
https://discord.com/channels/1129059589325852724/1129095997461647402/1235304422058360986

**Comment by SrRapero720** [comment]
Damn team city

**Pull request merged**
