### PR TITLE
Added dependencies and dependency ordering for textures.

### PR DESCRIPTION
**Pull request by RainWarrior**
A different way to do #3660. @bonii-xx, @tterrag1098, @OrionDevelopment, and anyone else who does custom textures, please see if this is sufficient for your purposes.

### CODE REVIEW

**Comment by covers1624** [comment]
Looks good to me.

**Comment by tterrag1098** [comment]
As discussed on IRC, this PR has a shortcoming in that it assumes that the "input" set of textures (that is, those which are to be given dependencies) must be known prior to texture/model load. So if, say, someone wanted to add dependencies which rely on texture metadata, this PR would not help.

That said, it is a good step in the right direction for sure, and I don't see any problems with the actual implementation.

**Comment by marchermans** [comment]
I agree, it is a statebased Approach, of which the state is querried before the registration if I read the Code correctly, and as such a little bit more limited then #3660 i think. But I would need to run some Tests to see if this works for me, to say for sure.

**Comment by bonii-xx** [comment]
Skimmed over it, but looks good. I'm pretty sure I can remove my loading workaround with this. :)

**Comment by asiekierka** [comment]
@tterrag1098 It would be sufficient, I think, if the textures had to be known after model load (not baking!), but before texture load. Do you agree?

**Comment by tterrag1098** [comment]
@asiekierka Yes that's exactly what's missing, a step to compute dependencies based on models or other textures. The only way to do it with this PR's system is to already have a full ICML and IModel structure in place.

**Comment by mezz** [comment]
This has been accepted and merged so that it fit within the breaking changes window for 1.12, any further improvements can most likely be worked on without breaking things as much.

**Pull request merged**
