### PR TITLE
[1.9]Fix #2624 Low spawnRadius causes IllegalArgumentException 

### LINKED ISSUE #2624: [1.9] Low spawnRadius causes IllegalArgumentException upon joining server
Steps to reproduce:
* Set up a server
* Run `/gamerule spawnRadius 0`
* Attempt to join

### PR DESCRIPTION
**Pull request by ken2812221**
Fix #2624

### CODE REVIEW

**Comment by liach** [comment]
Squash commits

**Comment by williewillus** [comment]
patch could be squished into one line using ternary

**Comment by ken2812221** [comment]
Fix it using ternary

**Comment by williewillus** [comment]
Squash

**Comment by williewillus** [comment]
6342bfe

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Pull request closed without merging**
