### PR TITLE
Removed FMLFingerprintViolationEvent

### PR DESCRIPTION
**Pull request by Redstoneguy129**
FMLFingerprintViolationEvent is no longer being posted.
There are no longer plans to revive the Event so it's better off being removed from the source code.

This PR simply removed FMLFingerprintViolationEvent from the Forge FMLLifeCycle.

As FMLFingerprintViolationEvent was never used it will not break any existing code. 
Unless of course some mods accidentally used it.

### CODE REVIEW

**Comment by TheCurle** [comment]
If this event interests you, you may make a PR to revive it. 

I feel like you misunderstood "there isnt any plans to revivie it. But you could add a PR to do so."

**Comment by Redstoneguy129** [comment]
I have'nt misunderstood. DaemonUmbra and LexManos confirmed it themselves, https://discordapp.com/channels/313125603924639766/725850371834118214/741073540379443260

**Comment by LexManos** [comment]
You misunderstood, We ment you could revive it if you wanted to. Not delete it.
Gunna assign @cpw in case he wants to care about this.

**Comment by cpw** [comment]
Will be removed in 1.17 due to breaking change nature of it.

**Pull request closed without merging**
