### PR TITLE
Fix #9874 - DatapackBuiltinEntriesProvider causes issues with forge registries

### LINKED ISSUE #9874: [1.20.4] DatapackBuiltinEntriesProvider from #9848 causes issues with forge registries
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.30

**Logs:** https://gist.github.com/Luis-St/7d431850d2e9c4bf5e0632d4aaf08da1

**Steps to Reproduce:**
 1. Create a RegistrySetBuilder which contains a Forge Registry like:
    `ForgeRegistries.Keys.BIOME_MODIFIERS`
 2. Subscribe to `GatherDataEvent`
 3. Register a `DatapackBuiltinEntriesProvider` with the created `RegistrySetBuilder` 
 4. Run runData
 5. The run will fail because there is no cloner for the registry `forge:biome_modifier`

**Reason of issue:**
The patch of PR #9848 patched the RegistryPatchGenerator as follows:
```java
  RegistryDataLoader.WORLDGEN_REGISTRIES.forEach((p_313050_) -> {
    p_313050_.runWithArguments(cloner$factory::addCodec);
  });
+ RegistryDataLoader.DIMENSION_REGISTRIES.forEach(reg -> reg.runWithArguments(cloner$factory::addCodec));
```
The problem is that RegistryDataLoader.WORLDGEN_REGISTRIES does only include the vanilla registries.
Possible fix:
```java
- RegistryDataLoader.WORLDGEN_REGISTRIES.forEach((p_313050_) -> {
-   p_313050_.runWithArguments(cloner$factory::addCodec);
- });
+ net.minecraftforge.registries.DataPackRegistriesHooks.getDataPackRegistriesWithDimensions().forEach(registryData -> registryData.runWithArguments(cloner$factory::addCodec));
```

### PR DESCRIPTION
**Pull request by Luis-St**
As described in Issue #9874, the use of the DatapackBuiltinEntriesProvider with forge registries leads to an error.

If desired, I would add a TestMod to make sure everything is working properly with this fix.

### CODE REVIEW

**Comment by Jonathing** [comment]
Ugh, what a pain. So this specific method `DataPackRegistriesHooks.getDataPackRegistriesWithDimensions()` includes all registries even though `WORLDGEN_REGISTRIES` only contains vanilla registries not added by Forge. One day, Forge will get the cleanup it truly deserves.

**Comment by Luis-St** [comment]
The test is now working fine

**Comment by LexManos** [comment]
So looking into it, the changes seem fine, makes things simpler. Your test however is broken in eclipse, `this::createFeature` needs to be `c -> this.createFeature(c)` due to generic stupidity.

Also, your test doesnt properly illustrate anything, i reversed some of the changes and dont see errors popping up. So can you please write some comments saying what its testing and what errors you should see if it fails?

**Comment by LexManos** [comment]
So your change added a comment, but it doent acutally tell me how to get that error to show up. So i can't verify your claims.
Also when adding a test mod, the generated files get added to the repository so that we can see if anything changes the datagen when unintended.

**Comment by Luis-St** [comment]
> So your change added a comment, but it doent acutally tell me how to get that error to show up.

Due to the updated patch, there is no way to get the error.
I only added the test mod to make sure that everything really works.
That's exactly what the test mods are for, isn't it?

**Pull request merged**
