### PR TITLE
Fix some issues with the console command completion

### PR DESCRIPTION
**Pull request by Minecrell**
This fixes a few problems with the current console command completion implementation:
- Fixed the space getting removed when completing a subcommand together with the command prefix (https://github.com/MinecraftForge/MinecraftForge/pull/2200#issuecomment-160823029)
- Added support for completing without input (basically shows a list of all commands)
- Added sorting for command completion results

### CODE REVIEW

**Comment by cpw** [comment]
Please squash. Also, a bug I noticed in idea: closing the inputstream (ctrl-d) causes infinite prompt spam.. Could you fix? Thanks..

**Comment by Minecrell** [comment]
Sorry, thought I squashed already. Will do that together with a fix for your issue tomorrow.

**Comment by Minecrell** [comment]
@cpw Sorry for the delay, should be all fixed now, include the issue you mentioned.

**Comment by asiekierka** [comment]
Any other issues?

**Comment by GirafiStudios** [comment]
I noticed a bunch of erros after the previous PR related to jline got merged (1600+), which didn't occur before.

Log: http://pastebin.com/HnxjC8me

**Comment by cpw** [comment]
@GirafiStudios that was a completely unrelated bug. use a much newer build.

**Comment by GirafiStudios** [comment]
@cpw Well I get the same error in every Forge version after 1600 (Yes also with the latest, 1618).

**Pull request merged**
