### PR TITLE
Fix unblockable damage being blocked by armor. (#3933)

### LINKED ISSUE #3933: Armors resist magic damage
I think the merge of #3838 caused this (paging @Flaxbeard)

Reproduction:
1. Put on diamond armor
2. Drink a poison potion
3. Open inventory and watch your armor take damage instead of you
4. Redo in vanilla and notice how you take damage and your armor doesn't

Forge 2309

### PR DESCRIPTION
**Pull request by talandar**
Fix #3933 for 1.11.  

This causes unblockable damage to not perform any armor calculations.  This is similar to how the vanilla call EntityPlayer::applyArmorCalculations does nothing if the damage is marked as unblockable.

A similar patch will be required for 1.12 unless someone cherry-picks the commit or merges the branches.  

Forge Devs:  Should I create the same PR for 1.12.x branch?

### CODE REVIEW

**Comment by williewillus** [comment]
Its not a patch change so it can be cherry picked

**Comment by mezz** [comment]
This looks good.
Please always target the latest version (1.12 now), fixes have to go there first. Once fixes are merged into 1.12, they can be backported to older versions. 
Also willie is right, for simple ones like this I can probably just cherry pick it to 1.11.2.

**Comment by talandar** [comment]
@Mezz should I make a new PR with the same changes for 1.12 and close this one, or should I leave this around?

**Comment by williewillus** [comment]
you can retarget the PR to 1.12 in the github interface, assuming the patch still applies cleanly (I think?)

**Comment by talandar** [comment]
Retargeting the PR causes a number of merge conflicts, apparently.  I know ISpecialArmor hasn't changed, but github seems to want to merge the entire set of changes over since the branch?  Something goes wrong, at any rate.

unless someone can recommend differently, I'll close this out later today and create a new one.  I've left this in the 'bad' state to demonstrate the problem.  I haven't been able to find a way to change the commits present in a pull request (except by adding new ones)

**Comment by talandar** [comment]
Replace with #4106 

Sorry for the issue targeting the wrong branch.

**Pull request closed without merging**
