### PR TITLE
Fix HeavyDiamondSword damage and attack speed

### PR DESCRIPTION
**Pull request by ghost**
before this patch heavy diamond sword had no increased damaged and decreased speed, after this patch it has normal damage and 1s delay (1.6 for usual diamond sword).

this initialization is wrong `super.getItemAttributeModifiers(slot)`
this is right initialization `HashMultimap.<String,AttributeModifier>create()`

-5d for speed is very big, it should be about -3.
12 for damage is normal, but i changed to 20 for fun.

### CODE REVIEW

**Comment by ghost** [comment]
LexManos please check sword damage before patch and after patch.
this initialization is wrong  super.getItemAttributeModifiers(slot)
this is right initialization HashMultimap.<String, AttributeModifier>create()
see this http://www.minecraftforge.net/forum/topic/19465-how-to-set-damage-to-custom-sword/

**Comment by ghost** [comment]
see code before close pull request!

**Comment by SquidDev** [comment]
This is in a test mod - it shouldn't have any impact on actual gameplay.

**Edit:** OK, looked at the linked issue. It might be worth making the intention slightly more clear in your original PR comment.

**Comment by ghost** [comment]
i know but i think this patch will be helpful for those who reading this tests and use them in their mods(like me)

**Comment by ghost** [comment]
" it shouldn't have any impact on actual gameplay."
but why there are this lines about changing damage?
maybe need to remove them?
or to improve them?

**Comment by ghost** [comment]
ok

**Comment by kierajreed** [comment]
And why is it needed to change these numbers again?

**Comment by KingLemming** [comment]
Okay so...I'm guessing you just don't really get how Java works? The original code was fine. It was initialized properly, and the link that you provided is a completely different case.

Look up Object Oriented Programming and Inheritance.

**Comment by ghost** [comment]
KingLemming did you seen damage before patch?
it was 7 like usual diamond sword.
and now it 20 or could be 12 like it must be.

**Comment by ghost** [comment]
maybe you need to test it before patch and after patch, and then to tell me that i bad coder or not

**Comment by ghost** [comment]
SkyHawkB 
when speed -3 minecraft says that speed of heavy diamond sword is less then zero.
and main problem is not in numbers but in initialization, oroginal initialization does NOT work, my initialization work fine.

**Comment by ghost** [comment]
from minecraftforge forum
"BUT BE SURE TO CREATE A NEW HASHMAP, NOT THE ONE ItemSword USES!!!!"

**Pull request closed without merging**
