### PR TITLE
changed method return type of EntityLivingBase#onDeath() to boolean instead of void

### LINKED ISSUE #3477: [1.11] Horses drop inventory after death
In the net.minecraft.entity.passive.AbstractHorse#onDeath() method the LivingDropsEvent is only called in the super() call, but the horse inventory (saddle, armor, etc.) is dropped no matter what the result was.

### PR DESCRIPTION
**Pull request by UpcraftLP**
changed method return type of EntityLivingBase#onDeath() to boolean isntead of void to prevent dropping items when LivingDeathEvent is cancelled. (closes #3477 )

### CODE REVIEW

**Comment by liach** [comment]
This is a horrible approach.

**Comment by UpcraftLP** [comment]
@liach then tell me a better way to prevent Entities like horses from dropping their inventory WITHOUT duplicating either the LivingDropsEvent or the super method in EntityAbstractHorse?

**Comment by liach** [comment]
Just change AbstractHorse. It is worse to remove a vanilla method.

**Comment by UpcraftLP** [comment]
but...
a) all changes are backwards compatible 
b) the changes are automatically applied to any custom living entity that would require this special death handling.

**Comment by diesieben07** [comment]
The changes in this PR are anything but backwards compatible.

**Comment by UpcraftLP** [comment]
they are, according to vanilla and Forge. every method that invokes EntityLiving#onDeath() doesn't expect any return value, so it should be safe to leave them as is.
I know that modders would have to edit their custom entities, but adding a return statement isn't much efford.
I got another solution that wouldn't change the signature of the method, but it'd result in duplicating the LivingDeathEvent/LivingDropsEvent for all entities that override the super method. (I could add another LivingDeathEvent and LivingDropsEvent to all custom onDeath() methods. (see EntityPlayer for example).
Is that solution fine @diesieben07 ?

**Comment by josephcsible** [comment]
> every method that invokes EntityLiving#onDeath() doesn't expect any return value, so it should be safe to leave them as is.

Sadly, this isn't the case. In Java, changing a method's return type is the same as getting rid of the old method and creating a new one in terms of compatibility.

**Comment by AEnterprise** [comment]
i think the better solution would be to fire the LivingDeathEvent before EntityLiving#onDeath() is called and just don't call it if the event is fired, that way it's just shuffeling around some code, means no breaking and no duped code

**Comment by UpcraftLP** [comment]
@AEnterprise that'd duplicate the LivingDeathEvent, as well as the LivingDropsEvent (because I'd need to fire the LivingDeathEvent, then call super (firing both events) and finally fire the LivingDropsEvent to make the drops cancelable. Anyways, I think thats still the right way to go because it seems to be allowed in EntityPlayer#onDeath().

**Comment by UpcraftLP** [comment]
I'll open another PR that includes the new changes.

**Comment by diesieben07** [comment]
You do not need a new PR. You can just change the branch this PR is linked to.

**Comment by UpcraftLP** [comment]
@diesieben07 sadly I'm only allowed to edit the target branch. So I guess I have to..

**Comment by josephcsible** [comment]
You can undelete your branch and push new changes to it. That will automatically update the PR.

**Comment by UpcraftLP** [comment]
@josephcsible ty, I'll reopen when I added all necessary events.

**Comment by liach** [comment]
@diesieben07 This is not backward compatible... When you run in normal obfuscated environment, the code will attempt to call a method named `func_70645_a` (after forge deobf transformer transformed obf mapping to srg mapping) instead of `onDeath`, thus throwing a `NoSuchMethodException`.

**Comment by diesieben07** [comment]
Yes. That is what I said: the changes in this PR are not backwards compatible.
Even if there was an exc added to preserve the obfuscation, return types are part of the method signature.

**Comment by UpcraftLP** [comment]
updated the branch, but can't reopen the issue.

**Comment by mezz** [comment]
Changing the return type of a vanilla method will not be accepted, please find another way and open a new PR.

**Comment by UpcraftLP** [comment]
@mezz already done. #3480

**Pull request closed without merging**
