### PR TITLE
Allow loading of extracted dependencies as coremods

### PR DESCRIPTION
**Pull request by marvin-roesch**
Since Forge's new policies on coremods recommend shipping the coremod as a jar-in-a-jar, modders will need to use FML's automatic dependency extraction feature. However, the implementation in `CoreModManager` currently assumes that extracted dependencies aren't coremods. Although this assumption might be sensible (one could ship the coremod in the "main" jar and let FML extract the actual mod), but generally speaking, you'd want the "real" mod to be in the first-level jar, since some analysis tools might scan for `mcmod.info` files etc. in order to get required information.

This pull request fixes this issue by allowing a single level of recursion (to prevent something like a zip bomb) in the coremod discovery process. If there are any problems with this approach, another route to go down would be passing twice over the coremod folder, but that way would require some more bookkeeping. I'm also pinging @cpw here, since he can probably judge best what happens to the system he initially implemented.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
I don't really understand the point of limiting to single recursion level. If you are adding a coremod to your mods folder, you already give the mod author a lot of access. The "zip bomb" scenario isn't something I would be concerned about, the worst that could happen is java running out of memory, which can already be done in many much simpler ways.

**Comment by LexManos** [comment]
I want to re-write this system to be an early pass before coremods are done. To extract the libraries from a jar into the libraries folder with full maven artifacting.

**Comment by marvin-roesch** [comment]
So the course of action for modders is to keep coremods mixed in with the normal mod until your rewrite is done? If not, merging this (or introducing a variation thereof) as temporary solution would probably be appreciated.

**Comment by marvin-roesch** [comment]
I will rewrite the extraction process to do as Lex outlined in his comment. Considering those changes have a different scope, I will create a new PR for it.

**Pull request closed without merging**
