### PR TITLE
[1.16.x] Render local player when the renderViewEntity is not the local player

### PR DESCRIPTION
**Pull request by XFactHD**
# Description
This PR modifies the render check for entities in WorldRenderer to make the local player entity render when it is not a spectator and is in the field of view of another entity that is currently set as the renderViewEntity. I have also included a test mod to show it working.

# Use-cases
This is useful in any case where another entity that might see the local player entity is set as the renderViewEntity.
My specific use case is a camera system where the renderViewEntity is set to a dummy camera entity. After trying what I described on the [Forge forums](https://forums.minecraftforge.net/topic/87254-1152-force-drawing-local-player-entity/) this seemed like the safest and most sane solution to me.

### CODE REVIEW

**Comment by marchermans** [comment]
I would love to see this in as well.
It is a very usefull change we could use to make animated building in a 3D world possible

**Comment by XFactHD** [comment]
Is there anything I need to fix before this is merged?

**Review by marchermans — APPROVED** [review]
This looks good.

- [x] Functionality seems to be there.
- [x] Formatting of patches seems to be correct.
- [x] Testmod and documentation exists.
- [x] Formatting of changes to none patch files seem to be okey.

**Comment by XFactHD** [comment]
I will redo this PR because I just fucked it up completely...

**Pull request closed without merging**
