### PR TITLE
Modify CommandEvent

### PR DESCRIPTION
**Pull request by BrokenSwing**
This PR annotate the `CommandEvent` with `@HasResult` and removes the `@Cancelable` one. To know why I did this PR, please check the issue #4093.

### CODE REVIEW

**Comment by BrokenSwing** [comment]
As Forge 1.12 will be released today (I hope), I'll modify it to make it a no breaking change

**Comment by Alpvax** [comment]
Just commenting to link this to #4093 properly (You missed the leading #)

**Comment by BrokenSwing** [comment]
Ok, I added it. The `CommandManager`'s patch may seem weird, but I tried to modify as less as possible the previous patch (replaced conditions and moved event declaration).

**Comment by mezz** [comment]
Sorry this seems to have slipped through the cracks. 
Please update this PR for 1.12 so it can be considered.

**Comment by mysticdrew** [comment]
@MFFbrokenSwing do you plan on updating this PR for 1.12.2? I also need this change. I currently change commandhandler with a core mod. But, we all know how much core mods are frowned upon. This change is definitely needed. 

Thanks.

**Comment by mezz** [comment]
Please feel free to port this and submit a new PR @mysticdrew, it is already under Forge's CLA so you can use it as a starting point.

**Comment by mysticdrew** [comment]
Will do, thanks Mezz.

**Pull request closed without merging**
