### PR TITLE
Add new mod management capabilities

### PR DESCRIPTION
**Pull request by ghost**
It is the moral duty of FML to protect users against bad mods

### CODE REVIEW

**Comment by TehNut** [comment]
what

**Comment by ghost** [comment]
Itz vere zimple, doze modz uhre mezzieng wid minecruhft, zo we zhowld protect de uzerz be blockieng dem

**Comment by tterrag1098** [comment]
Nice obfuscation, bro.

**Comment by TehNut** [comment]
`gregtech`
`reika`
`tconstruct`
`micdoodle8`
`botania`
`thaumcraft`

Nice.

**Comment by ghost** [comment]
Sein Pull-Request 529 auf dem FML-Repository wieder

**Comment by Madsthunder** [comment]
Eh... I think I would rather stay out of this controversy...

ClueOrc is referring to [this pull](https://github.com/MinecraftForge/FML/pull/529) by the way.

**Comment by kashike** [comment]
-.-

**Comment by Madsthunder** [comment]
Also I think @williewillus won't be all too happy about his mod being on the blacklist

**Comment by bookerthegeek** [comment]
Duplicate Issue: https://github.com/MinecraftForge/FML/pull/529

Damn, I knew this looked familiar. Can somebody mark as a duplicate and close it please?

**Comment by williewillus** [comment]
mfw 4 of the 6 "blacklisted" mods aren't even on 1.10/11 :P

**Pull request closed without merging**
