### PR TITLE
[1.15.2] Render local player when the renderViewEntity is not the local player

### PR DESCRIPTION
**Pull request by XFactHD**
# Description
This PR modifies the render check for entities in WorldRenderer to make the local player entity render when it is not a spectator and is in the field of view of another entity that is currently set as the renderViewEntity. I have also included a test mod to show it working.

# Use-cases
This is useful in any case where another entity that might see the local player entity is set as the renderViewEntity.
My specific use case is a camera system where the renderViewEntity is set to a dummy camera entity. After trying what I described on the [Forge forums](https://forums.minecraftforge.net/topic/87254-1152-force-drawing-local-player-entity/) this seemed like the safest and most sane solution to me.

If requested, I will also make a PR for this for 1.16.

### CODE REVIEW

**Comment by diesieben07** [comment]
1.15.2 is LTS, new features should go into 1.16 first before being backported.

**Comment by XFactHD** [comment]
> 
> 
> 1.15.2 is LTS, new features should go into 1.16 first before being backported.

Done

**Comment by TheCurle** [comment]
This PR is awaiting #7216.

**Comment by XFactHD** [comment]
I don't need this anymore, the mod this was for has moved on to 1.16.

**Pull request closed without merging**
