### PR TITLE
[1.21.4] Simplify memory usage display on loading screen

### PR DESCRIPTION
**Pull request by PaintNinja**
Simplifies the memory usage display to be easier for novice users to understand:

image

### CODE REVIEW

**Comment by Jonathing** [comment]
Should we make a config value to preserve the old behavior in case it is useful to know the offheap memory?

**Comment by PaintNinja** [comment]
We could at the cost of _slightly_ more complexity, but I can't think of a reason why you'd want to know it

**Comment by Jonathing** [comment]
I don't either, but it's existed in the project for a while. If it's going to add more complexity then I'd rather not.

**Review by Jonathing — APPROVED** [review]
Will backport to other versions after this gets merged.

**Comment by LexManos** [comment]
This is fine as is, but if you want to add the config before pulling feel free. I honestly don't think users know the difference between heap and non, plus the bar only references non. So simplified is better IMO.

**Pull request merged**
