### PR TITLE
[1.13] Extend the Tag System to cover ForgeRegistries

### PR DESCRIPTION
**Pull request by MajorTuvok**
This PR addresses issue #5060 .

This is outdated, I just don't have time this week to do much, so please be patient guys... 
I'll try to apply changes (source code and this description) next weekend. 

### How it is done

In general in order to reduce patching, most things in this PR are if possible done via subclassing.
ForgeRegistries now have a Delegate class called TagProvider which is responsible for managing (and 'providing') Tags. All Vanilla Tasks concerning Block and Item tags are delegated through to the TagProviders own TagCollection (ForgeTagCollection). Block and Item tags are synced via Vanilla Packets, whilst other Tags are synced via Forge Snapshots (if they are not saving to disc) (hopefully, I haven't been able to test and the IDEA tells me that makeSnapshot would always be called with savingToDisc = true - if this is truly the case I'll have to find a different way to sync them, maybe with an modificaition to the ForgeTagManager (subclass of Vanilla's NetworkTagManager)).
There have been no changes to fluid or Function tags.

### Loading
Tags are loaded from the following folders(where [reg-namespace] is the namespace of the Registry and [reg-name] is its name):
if regName.getNamespace().equals("minecraft"):
1. data/[namespace]/tags/[reg-name]
2. data/[namespace]/tags/[reg-namespace]/[reg-name]
3. data/[namespace]/tags/forge/[reg-namespace]/[reg-name]

else:
 1. data/[namespace]/tags/forge/[reg-namespace]/[reg-name]

The second option is there to allow for a better separation of forge-registries and vanilla registries.

Also as proposed at the end of the discussion of #5060 - Tags are collected into Tags with the vanilla namespace. A big advantage of tags is that (like the OreDictionary) one can easily add one's own Items to a Tag. If Tags wouldn't be collected together, it wouldn't be possible to really 'add' Tags together - it would be necessary at Runtime to check wether the Paths are equal and such stuff in order to (f.e.) get all Elements under a certain tag. This way we just fetch the minecraft namespaced Tag, and everything is included.
_Explanation_
Before building the TagMap in ForgeTagCollection#registerUnbuildTags for every Tag there is a dummy tag with the same Path, but the minecraft namespace in ForgeTagCollection#collectToMinecraftTags created. These tags then consist of nothing else, but 1 or more Tag.TagEntries containing the Tags with the same path but different namespaces.

### Utility

This PR also add's a few utility classes (TagHelper, ImmutableTag, SortedTagBuilder, ForgeTagWrapper and UnmodifiableTagWrapper) to help easier working with tags.
ImmutableTag is essentially a Tag backed by an Guava ImmutableSortedSet and an ImmutableList to allow for faster access to the Tags entries (especially the contains Method). It has it's own ImmutableTag.Builder and 7 Factory Methods to create it from tags:
1. copyOf/(2)asTag copy all **Elements** into the SortedSet and re-create the Entries as singleton Tag.List entries - TagStructure is completly lost

2.copyPreserveShallowTagStructure sorts the Tag.Entries and creates ImmutableCollections from them. Notice however, that only the top-most TagStructure level is presevered, every Tag.TagEntry below that will be flattened into singleton Tag.ListEntries

3.copyPreserveTagStructure sorts the Tag.Entries and creates ImmutableCollections from them. Notice that this creates recursively an Immutable copy of all contained Tag.TagEntries

SortedTagBuilder can be used as a TagBuilder to sort the tag, before building it.

ForgeTagWrapper and UnmodifiableTagWrapper are Wrapper classes using the ForgeTagManager to determine, when the backing Tags have to be reloaded. Vanilla Wrappers are made to extend UnmodifiableTagWrapper. 

TagHelper provides general purpose utilities.

### Added Tags

- [x] some Entity Tags, but not as many as I wished there were...
- [ ] all other Registries

Please guys help me... Tagging everything is so much effort: I don't have the time for that. These must either be done in follow up PR's or just post me an issue or PR with a suggestion for a Tag so that I can merge it in here
Also I haven't done any compat so far... Propably won't be able to do that as well...

### Testing

-Loading Tags seems to work as expected
-Cannot test networking code, because Networking isn't finished yet
-Utilities tested and work as epected

### Annotations
I hope my description isn't to confusing - this is my first PR to Forge (and a big one) - please be patient with me.
Also because university starts next week I'll have limited time within the week, but I'll do what I can on the weekend. :)

### CODE REVIEW

**Comment by williewillus** [comment]
> The second option is there to allow for a better separation of forge-registries and vanilla registries.

I don't like adding special cases just for the sake of it
why can't everything just be in `tags/<namespace>/regdomain/regname/*.json`? why `forge` in the path?

**Comment by MajorTuvok** [comment]
So this seems to be mostly done...
Do we need a test mod for this?

**Comment by MajorTuvok** [comment]
@williewillus  (for the case of namespace/tags/reg-domain/reg-name) We need to preserve vanilla compatibilty, which doesn't add regdomains, so that Forge would no longer load vanilla data packs.
As to why Forge (or any reserved keyword) is required - here a summary of @Wyn-Price 's [comment ](https://github.com/MinecraftForge/MinecraftForge/issues/5060#issuecomment-412003957)as I understood it:
Adding forge is required, so that there don't come any Problems from someone creating his/her Registry under the namespace of one of the 'vanilla' Registries (which isn't forbidden, though unlikely).
The possibilty to add reg-domain/reg-name Namespaces is the one which I added additionally, because I like it.

**Comment by williewillus** [comment]
yeah I'm not sure about this, seems like a lot of patching and general complexity to implement this feature, though I haven't reviewed it all yet. 
Is every part of it relevant and critically needed? What's all this immutable tag/sorted tag builder stuff? Why aren't the vanilla builders sufficient?

**Comment by MajorTuvok** [comment]
In Theory there should be quite few patches, but looking at it, it seems like I forgot to exclude changes introduced by #5169 and #5171 resulting in their patches /changes being in here too. (I needed to implement these fixes to get it running)
Also I just noticed that I could reduce Tag's patching a bit more by delegating equals and hashCode trhough to TagHelper.

If I'm correct then (as soon as I've made the Tag patch smaller) it should be something around 30 lines plus the heavy changes to ItemTags.Wrapper and BlockTags.Wrapper.

**Comment by MajorTuvok** [comment]
Whoops

**Comment by MajorTuvok** [comment]
There are 2 major reasons for adding the custom builders:
a) contains checks in vanilla Tags  can be arbitary long, as they cannot take any advantage from Sorted Collections
b) ImmutableTags can safely be used from multiple threads (client/server thread f.e. accessing the same Tag...)
c) I needed a custom Builder subclass anyway to add the MissingEntriesException. (Which is needed, because with vanilla it really is a headache to find out what you did wrong with your tags)

**Comment by MajorTuvok** [comment]
I will remove the unrealated fixes (sry for that, at the time being I forgot that I can exclude things from vcs...) from here, as well as making the Tag patch smaller and making it throw in registerUnbuildTags again (I forgot to remove that, once I was finished testing)

**Comment by MajorTuvok** [comment]
Do we even need UnmodifiableTagWrapper? 
Because everything is backed by ImmutableTags anyway, I guess we don't...

**Comment by MajorTuvok** [comment]
From my side I would consider this finished (I don't think we need more Documentation, do we?).

I know this seems to be really much, but I add around 40 Tags as well as modifying 5-10 to clear out typos, so that the actual code changes are by far smaller then one might think when looking at 2900 additions and 74 changed files

**Comment by MajorTuvok** [comment]
I'm sorry, but why does this close button need to be so close to comment on my mobile phone...? 

From my side I would consider this finished (I don't think we need more Documentation, do we?).

I know this seems to be really much, but I add around 40 Tags as well as modifying 5-10 to clear out typos, so that the actual code changes are by far smaller then one might think when looking at 2900 additions and 74 changed files. Should I move the Tag-Adding changes to a seperate PR?

Also, before anyone wonders, if these changes would be merged into forge, worlds would no longer load, because it first needs vanilla blocks to be registered to ForgeRegistries (and inorder to load the Tags, ModFile DataPacks need to be loaded), which is why I added these other 2 seperate PR's doing that.

@williewillus, does this address your concerns now? Should I put the Tags in a seperate 4th PR for easier review? 
Could someone please review?

**Comment by williewillus** [comment]
Actually, looking at vanilla code again, I don't really see the point of this.

Tags should be an opt-in thing for registries, the mod controlling the registry decides if, when, and how their tags are read and synchronized. Said mods can just construct and control its own `NetworkTagCollection` and sync them themselves. It's dead simple (construct the object, send some  packets if necessary). If you don't need syncing, you literally just hold on to the collection like `FunctionManager` does with its `TagCollection`.

There is *no need* to replicate all of Mojang's weird wrapper/generation logic, which only exists because they want to use static final fields to access those tags and thus they need to handle the backing collection changing. Just look it up in the TagCollection like normal.

As for what folders to use, I think we can, with some documentation, trust modders on this. The `NetworkTagCollection` just takes the prefix as a string, and mods can just pick folder names that are unique, e.g. `tags/botania_subtiles`.

I just want to keep Tags dead simple - it seems like this PR introduces lots and lots of complexity.

**Comment by MajorTuvok** [comment]
Tags are an opt-in for Registries, disabled by default. I just enabled it for all vanilla Registries and was hopting for someone to point me to Registries which don't need Tags... 

Additionally I'm not replicating replicating weird logic - The Wrapper System is quite nice: Construct your Warpper and it will handel Reloads and such stuff for you.

With this PR tags are even more simplified, you don't even need to add code for them, besides calling enableTagging(). After that just put your Tags in the correct Folder and Forge will handel loading and syncing them for you - No need for every mod to write the samd code mutliple times and add even more login Packets. 

I agree a mechanism to enable/disable Tag syncing would be nice, haven't thought of that.

And to why it is needed: a lot of people seemed to want it in #5060.

**Comment by MajorTuvok** [comment]
Are there more peopls who think this should be reduced to separte NetworkTagCollections for all Tags?

We would have to synchronize Mojangs Tags then, because sooner or later there'd come ConcurrentModifications from them...

And provide a mechinsm to add Tags to them...

=>No matter what we'd have to do patching, propably more than I'm doing at the moment

**Comment by MajorTuvok** [comment]
I guess I could remove the SortedTagBuilder, it doesn't provide any additional benefit, besides giving modded Tags their own Builder...?

**Comment by williewillus** [comment]
Yes it makes it marginally easier for modders, but I argue if you need your own forge registry you're already doing complex things anyway, syncing it yourself won't be near to the other things you need to handle .

And I don't understand your last comment at all. Mojang's syncing works perfectly fine right now, and all these patches are definitely not *necessary*.

My bottom line is: simple > easy. Things like the wrappers are a hack for ease, while introducing needless complexity.

**Comment by williewillus** [comment]
Another point to consider is, not many mods have their own forge registries. Code in forge itself should really only be there if it can serve a vast majority of mods' needs. Individual mods can have their own ad hoc solutions for rare cases.

**Comment by MajorTuvok** [comment]
(Why don't they use the ForgeRegistry? Thanks for pointing that out to me though... )

But I think what you're saying is, that they should be backable by someone's own Registry... Right?
So would it be ok if I moved away from the ForgeRegistry approach, to a general TagManager to which you add some kind of 'IRegistry' so that it can be tagged and enable snying for it as needed? (and by default ForgeRegistries with enableTagging are added?)
(The IRegistry would consist of 2-4 Methods: containsValue and getValue, which is all that's needed for Tags, and if you want it to be synched some kind of getID/getByID)

**Comment by MajorTuvok** [comment]
I was talking about the Problem of being unable to add to Tags. Vanilla allows for Tags to be replaced, but not added to. Which is why I added this generate dummy Tag containing Tags with the same path thingy.

As well as the inevitable ConcurrentModificationException as soon as mods start using the Forge/Vanilla provided Tags, if we don't put synchronization to it.

**Comment by MajorTuvok** [comment]
I don't need to remove the extends IForgeRegistryEntry bound then, do I?
Would it hurt mods, to make their entries extend from ForgeRegistryEntry? (I mean they'd have to use ResourceLocations as keys anyway...)

**Comment by williewillus** [comment]
> But I think what you're saying is, that they should be backable by someone's own Registry... Right?

You can already do this with no Forge patches, by just constructing your own `NetworkTagCollection` (which should really be named `RegistryBackedTagCollection`) and using it.

> Vanilla allows for Tags to be replaced, but not added to

if you mean adding in code, this is a completely separate issue from having Tags support forge registries. Tags themselves can be added just by adding jsons and loading them in the code.

Overall I'm not convinced most of this is necessary. Perhaps a lightweight registration layer that lets you opt-in to syncing a specific instance of `NetworkTagCollection` at login time, but nothing more

**Comment by MajorTuvok** [comment]
No, I'm not talking about adding them in code...

You CANNOT add to json tags - you can replace them completly, you can add your own Tags (which might with a lot of trickery and propably Reflection contain already existing Tags), but you CANNOT add to existing Tags - as least as long as you don't abuse loading, by loading tags under someone else's namespace (which (if I remember that ModFileResourcePack code correctly) is prevented by forge)

**Comment by LexManos** [comment]
> You CANNOT add to json tags - you can replace them completly, you can add your own Tags

... You seem to have a fundamental misunderstanding of how tags work. 

Gave the code a general look over and all i can say is that this is a dumpsterfire.
You seem to fundamentally misunderstand the entire vanilla tag system.
The only real thing we need to decide to expand the tag system onto custom registries is to figure out the folder structure we wish to adopt.
But even that is defined by the person creating the tag manager, and not us specifically. So it's more of a community standard then something enforceable in code.

**Comment by liach** [comment]
so define some tag manager standalone from registries but can be used by it?

**Comment by williewillus** [comment]
@liach what he means is you can literally construct a `NetworkTagCollection`, passing your own forgeregistry in, and manage it on your own

**Comment by liach** [comment]
Well, we need to write another thing for syncing because `NetworkTagCollection` only works for vanilla packets.

**Comment by williewillus** [comment]
no? it uses `PacketBuffer`, which is just a thin wrapper around `ByteBuf`, which is what Forge's `IMessage` uses.

to write it would just be 
```Java
/* IMessage */ toBytes(ByteBuf buf) {
    tagCollection.write(new PacketBuffer(buf));
}
```

**Comment by MajorTuvok** [comment]
Ok, what I was referring to was the reload method in TagCollection, which uses a map to deserialize Tags. This is keyed by ResourceLocations, and therefore only if you use an completly equal ResourceLocation (and therefore same namespace) it will be added to the TagBuilder, for this Tag. Otherwise it will create a new one. I just can't see how you'd be able to add to an already existing Tag, if you don't use the same namespace it was defined in (which if I remember correctly someone writing a mod shouldn't do)...

Ok, @LexManos so we should just leave people to passing in a Wrapper of the ForgeRegistry?
Then should this code be reduced to doing exactly that? (And not f.e. using ImmutableTags for Thread safety - just leaving vanilla behaviour everywhere? (That would make my life a lot less complicated...) (I understand how the Tag System works, I just don't understand what you guys want to have...))

(The reason why I wrote it this way, was that I thought you guys wanted to have the most convenient solution, whilst at the same time I didn't know that people are building non-ForgeRegistries which might want to have Tags...)

**Comment by MajorTuvok** [comment]
I guess I'll close it then...
I sadly can't spend time I don't have on rewriting this to a for you guys more appropiate format. Sorry.
If someone else is going to do this, I'll propably (hopefully) be able to submit a PR with all my written Entitiy Tags.

**Pull request closed without merging**
