### PR TITLE
Use ItemStack.hasEffect when rendering armor

### PR DESCRIPTION
**Pull request by diesieben07**
This was using isItemEnchanted directly. hasEffect should be used instead for consistency.

### CODE REVIEW

**Comment by asiekierka** [comment]
I think that's a good idea, yes. 1.8.8?

**Comment by cpw** [comment]
Please explain what the error is this is fixing?

**Comment by diesieben07** [comment]
An armor item that has the enchanted effect but is not actually enchanted will glow in the inventory and everywhere else, except when worn.

**Comment by cpw** [comment]
Please update to 1.8.8 Thanks!

**Pull request closed without merging**
