### PR TITLE
[1.16] Re-enable Global Loot Modifiers

### PR DESCRIPTION
**Pull request by bignelli**
It was probably commented-out during the update and forgotten.

### CODE REVIEW

**Comment by TheCurle** [comment]
This is a simple change, but i need someone to double check this is compatible with mods being ported up.
Can someone chip in?

**Comment by bignelli** [comment]
It does seem to work on my own mod, tested [locally.](https://streamable.com/ljc39u) But if #6849 gets merged, this one will have to change a little bit.

**Comment by TheCurle** [comment]
Okay. Let's yield to the PR with the bigger scope. The changes should be minor, as you said.

**Comment by bignelli** [comment]
Closing in favor of the other one.

**Pull request closed without merging**
