### PR TITLE
Allow blocks to affect the beacon color

### LINKED ISSUE #2949: Blocks cannot specify custom colors for the beacon beam

### PR DESCRIPTION
**Pull request by williewillus**
Better version of #3168. Closes #2949

### CODE REVIEW

**Comment by gudenau** [comment]
Great, this will allow me to remove my coremod component.

**Comment by williewillus** [comment]
Formatting improved as suggested

**Comment by LexManos** [comment]
See HIS PR is actually freaking COMPILEABLE as he didn't edit the damn patch files BY HAND.
Seriously @gudenau Sod off with your ignorant 'ill hack this shit with a coremod because i cant possibly understand how to write a proper PR' attitude.

**Comment by gudenau** [comment]
Note: I did not manually edit the second one, and you did not want to help. So you just banned me because I was getting around you being a jerk.

**Comment by RANKSHANK** [comment]
If you can't follow a project's conventions, don't expect your pulls to get in. If you don't understand the conventions you're very likely not following them, and you definitely shouldn't get all angsty when someone doesn't spoon feed you them.

**Pull request merged**
