### PR TITLE
Add ServerSendChatEvent

### PR DESCRIPTION
**Pull request by shadowfacts**
Remake of #2599 targeting `master`.

### CODE REVIEW

**Comment by ChunHin** [comment]
Why don't you make a class called SendChatEvent
and then create two subclasses inside SendChatEvent called ServerSendChatEvent and ClientSendChatEvent?
That will be a lot nicer.

**Comment by ChunHin** [comment]
Note : You may think ClientChatReceivedEvent can replace ClientSendChatEvent but see this issue : 

#2810 --- Handle ALL chat (local & remote)

ClientChatReceivedEvent only called in EntityPlayerMP.addChatComponentMessage.
EntityPlayerSP.addChatComponentMessage will not fired ClientChatReceivedEvent.
So you may fired ClientSendChatEvent in both EntityPlayerMP.addChatComponentMessage and EntityPlayerSP.addChatComponentMessage.

**Comment by ChunHin** [comment]
Also, ServerSendChatEvent and ClientSendChatEvent need to extend SendChatEvent.

**Comment by shadowfacts** [comment]
#2810 isn't a request for a client send chat event. It's a request for an event that is fired anytime a message is added to the chat.

**Comment by ChunHin** [comment]
Ok...
First, I think the name "message" is better than the name "component".
Note : So the following is based on the name "message".
you may want to create a final variable that holds the original message and create a variable that original set to the the original message.
Then you allow mod to edit the non-final variable.
Like this : 
` private final ITextComponent message;` 
` private ITextComponent resultMessage;`
And then add getMessage() ---> return message;,
setResultMessage(ITextComponent message) ---> resultMessage = message;
and getResultMessage() ---> return resultMessage;
After that in the constructor : 
`public ServerSendChatEvent(ITextComponent message)
 {
      this.message = message;
      this.resultMessage = message;
 }`
At last in the method ForgeEventFactory.serverSendChat(ITextComponent)
`return event.getMessage();`
or
`return event.getComponent()` <--- Your version
need to change to
`return event.getResultMessage()`
or
`return event.getResultComponent` <-- Your version

**Comment by ChunHin** [comment]
And also you may follow the idea that ServerSendChatEvent and ClientSendChatEvent extend SendChatEvent.
Put all the constructor, get method, set method, variable, ServerSendChatEvent and ClientSendChatEvent in the SendChatEvent.
In the ClientSendChatEvent add only a constructor.
In the ServerSendChatEvent add only a constructor.
`super(SendChatEvent's parameters...);` should be in both the ClientSendChatEvent's constructor and ServerSendChatEvent's constructor.
SendChatEvent.
A map for clearer understanding : 
--->Constructor
--->Method
--->Variable
--->ServerSendChatEvent
-------->Constructor Only contains `super(SendChatEvent's parameters...);`
--->ClientSendChatEvent
-------->Constructor--->Only contains `super(SendChatEvent's parameters...);`

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
