### PR TITLE
Improve SlotItemHandlers isItemValid() and getItemStackLimit() methods

### PR DESCRIPTION
**Pull request by rwtema**
Currently, if the slot is not empty, then the slot will reject any itemstacks that are not the same as its contents. This means you can't swap itemstacks with a slot (vanilla behavior).

With the new methods then if the handler is modifiable, the method temporarily sets the slot to empty, performs the relevant check and then restores the slot to it's previous value.

If the handler is not modifiable then the methods are unchanged and will have to be overridden by the mod author.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
This will fix #3059

**Comment by mezz** [comment]
Tested and confirmed that this fixes the Tinker's issue linked above.
The logic looks good to me. Took a while to understand the cases where `isItemValid` is used since the vanilla code around it is a maze.

**Review by mezz — APPROVED** [review]
Tested and confirmed that this fixes the Tinker's issue linked above.
The logic looks good to me. Took a while to understand the cases where `isItemValid` is used since the vanilla code around it is a maze.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by SnowShock35** [comment]
\o/ Thanks Lex :heart:

**Pull request merged**
