### PR TITLE
[1.10] Patch uses of isNormalCube() to position-aware version

### PR DESCRIPTION
**Pull request by bs2609**
This replaces uses of `isNormalCube()` with the Forge-provided version `isNormalCube(IBlockAccess,BlockPos)` to allow for position aware logic. It's implemented by adding a method to `IBlockProperties`/`BlockStateContainer` that calls through to the existing method in `Block`.

### CODE REVIEW

**Comment by LexManos** [comment]
Is this worth the massive amount of base edits that it takes.
Also, there is the incurred incompatibility with editing an interface {IBlockProperties} vs a concrete class.
The other problem is that a lot of these places are not just 'add location' the 'isNormalCube' method is very badly named, 1/2 the time its not used for checking if the block is indeed completely solid, its used on faces or other things.
Also, if you DO kill off an old method its worth deprecating that method in the interface.

**Comment by bs2609** [comment]
The problem I was having that motivated this was with the usage in `EntityPlayerSP.isOpenBlockSpace()` causing you to bounce off of blocks regardless of their collision boxes. The other patches were made to be consistent, but if you feel there are some that are really unlikely to be needed, they can be dropped.

The interface in question already has some Forge methods added, it could be left out, but then there's more patching required elsewhere.

**Comment by mezz** [comment]
`isNormalCube` is already per-block-state. Why do you need the world and pos? Shouldn't the blockstate already have all the relevant information?

**Comment by bs2609** [comment]
Yeah, a call to `getActualState` could be inserted instead of using this method. That would also avoid changing the interface.

I can make that change if you think it's worth having, it's not a major issue for me, so I'm also prepared to close it if you feel it won't be mergeable.

**Comment by mezz** [comment]
Yeah I think just fixing `isOpenBlockSpace` would be the best solution. The other uses of `isNormalCube()` seem less of an issue.

I do find it strange that you have a block does not have the same `isNormalCube` status after calling `getActualState`. Can you describe the block and why it works that way?

**Comment by bs2609** [comment]
The use case that I'm thinking of is blocks that can mimic other blocks, which generally needs more than just metadata to work properly.

**Comment by bs2609** [comment]
Cut down and updated for 1.11 as #3494.

**Pull request closed without merging**
