### PR TITLE
[WIP] Drop native support for scala, other libraries not used by forge and impliment a new way to register LanguageAdapters

### PR DESCRIPTION
**Pull request by 0xilly**
We have been talking about dropping native scala support for a while now, this accomplishes just that.

### CODE REVIEW

**Comment by 0xilly** [comment]
Some of the rational for this is the following

1. Forge doesn't make use of scala
2. There has been talk about dropping scala for a while

To make sure that people who use scala for their mods aren't left behind I have made a [Scala Language Adapter](https://github.com/Illyohs/Scorg) for them to use.

**Comment by williewillus** [comment]
3. shipping scala is expensive on the forge server hosts

**Comment by 0xilly** [comment]
I knew I was forgetting something :D

**Comment by marvin-roesch** [comment]
4. Relying on Forge to keep the Scala version up-to-date is an extra burden for everyone :P

**Comment by LatvianModder** [comment]
5. `scala.actors.threadpool.Arrays` import

**Comment by KingLemming** [comment]
Any chance that we could *not* drop the typesafe config (com.typesafe.config) library? It's actually *extremely* useful for doing more complex config files, such as HOCON.

And it's Java, not Scala. There's not a good reason to remove it.

**Comment by kashike** [comment]
If typesafe-config *is* kept, a bump to the version would be nice.

**Comment by 0xilly** [comment]
I think shading it in a mod would be better than keeping in forge, unless forge moves to using it(but that's another PR :P). I agree it's useful but I don't think forge should ship libraries it doesn't depend on.

**Comment by KingLemming** [comment]
Shading it in a mod has a whole host of other issues - especially if there are multiple mods that end up doing so.

**Comment by shadowfacts** [comment]
Agreed. Enough mods depend on it at this point that it's not practical to have every mod shade it themselves. It would either need to be included in Forge (easiest for players and mod developers) or there needs to be one library mod that exists solely for the purpose of shading it (slightly more annoying for players and developers).

**Comment by marvin-roesch** [comment]
There once were talks about potentially switching to [configurate](https://github.com/zml2008/configurate) as a high level config API. It has optional HOCON support and is used by the Sponge team, so it'd contribute to standardising the modding environment. Maybe it's the right time now to make a move towards it, which would solve the issue of shipping unused libraries *and* it'd open up Forge for better configurations than the current proprietary format. I do agree with illy, however, that shipping the library with Forge is unnecessary.

**Comment by 0xilly** [comment]
I agree that typesafe config a great convenience, maybe we could graft the current config system to use it. But as it stands it's not used in Forge and that's where we should draw the line.

**Comment by KingLemming** [comment]
In that case, you should edit the name of your PR to more accurately describe what it does. You're not removing Scala, you're removing everything that Forge happens to not use right this second.

**Comment by 0xilly** [comment]
Updated the title

**Comment by marvin-roesch** [comment]
Does this have any chance of being pulled before the next major MC version, considering it's technically a breaking change? The general consensus seems to be that this is the right way to go, since Forge has always been reluctant to ship Scala.

**Comment by LexManos** [comment]
Its not being pulled for 1.12. It needs more time, and more specifically it needs more stats on who actually uses scala.

**Comment by delvr** [comment]
Count me in as a Scala modder who would very much like Scala support to remain in some capacity. I don't think it's that much of a maintenance burden as Scala shows up very seldom in changelogs; plus I think the Scala library version was updated once in the history of Forge, is now a whole major release late, and I can live fine with that as long as some version of it is still available. I use it for the [Streams](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346379-streams-real-flowing-rivers) mod and I'd like to continue doing so. Thanks for hearing me out. :)

**Comment by delvr** [comment]
Edit to the above: I somehow missed the link to Illyohs's custom Scala adapter on first read, so I'll go check that out. If it reliably provides at least as much Scala integration as the current Forge then this could work as a replacement.

**Comment by marvin-roesch** [comment]
@delvr: Apart from shipping the libraries, including a Scala language adapter by default was the only direct support for Scala from Forge. Both the libraries and the adapter are addressed by illy's project, so there's no need to worry about continuing modding in Scala when Forge drops "native" support.

**Comment by delvr** [comment]
Good to hear! Thanks.

**Comment by LexManos** [comment]
@Illyohs When you get a chance can you hop on IRC so we can talk about this?
I want to make 'Scorge'  a official system. And see what we can do about retroactively applying it. 
In a manor that will allow us to rebuild the old launchers with Scala as a optional library.

**Comment by 0xilly** [comment]
@LexManos I can come on later tonight

**Comment by kashike** [comment]
go away stale

**Comment by 0xilly** [comment]
This is still very WIP and I sitll have to figure out things with FML

**Comment by mezz** [comment]
I think this is superseded by FML's rewrite in 1.13 so I am closing it.

**Pull request closed without merging**
