### PR TITLE
Allow server to access Potion isBadEffect()

### PR DESCRIPTION
**Pull request by mezz**
Forestry has an apiarist's suit that protects against negative bee effects. Some of the bee effects use potions. I want to use Potion.isBadEffect() to determine if the effect is negative and should be protected against.
```java
if (potion.isBadEffect()) {
	// Reduce effect duration based on the amount of apiarist armor worn
}
 
player.addPotionEffect(new PotionEffect(potion.getId(), duration, 0));
```

### CODE REVIEW

**Comment by LexManos** [comment]
No new PRs for 1.7.10

**Comment by mezz** [comment]
The one against master was open for 7 months so I figured I'd give it a shot here.
This is the simplest fucking thing Lex.

**Comment by LexManos** [comment]
Actually it's not, removing SideOnly on ANYTHING never ends well because there will ALWAYS be something in a mod out there that will not get the memo that SideOnly is removed and keep theirs causing odd functionality. In this case what you want is easily achieved by either reflection or and AT. 
Without introducing a breaking change to what that function means.

**Comment by mezz** [comment]
That's fair.
Forestry already uses reflection for it, but it's the only reflection in the mod. 
I just want a clean solution for the future.

**Pull request closed without merging**
