### PR TITLE
Fix EnumHelper ArmorMaterial.

### PR DESCRIPTION
**Pull request by Vazkii**
They changed it again :D

### CODE REVIEW

**Comment by AtomicBlom** [comment]
Does this work? It looks to me like they removed the textureName property and added durability.

I see you've added durability, but not to the "addArmorMaterial()" method.

**Comment by Vazkii** [comment]
Oh shit I forgot that >_>

And yeah, it does work. The texture name is still there. https://puu.sh/oYivf/795d392acc.png

**Comment by AtomicBlom** [comment]
wait... that's the texture name?
image
No wonder my fix wasn't working :S

**Comment by williewillus** [comment]
first string's the enum name (material name), second's the texture name passed to the ctor

**Comment by AtomicBlom** [comment]
While writing a unit test for this, I learned/confirmed that the first string is always the name of the enum and is not passed to the constructor of the Enum. Therefore, the first parameter is not supposed to be the enum name.

I'm not convinced that textureName is accurate, but it's not the Enum name, and it's not Vazkii's problem.

**Comment by liach** [comment]
@Vazkii Editing on GitHub is very bad!

**Comment by Vazkii** [comment]
Indeed, but I'm not stressing it too much now that you can merge commits when you pull.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/b65b2991a4fd1689cfc675e0831c60c2efb1d907

**Pull request closed without merging**
