### PR TITLE
Fix Redstone Torch memory leak

### PR DESCRIPTION
**Pull request by bs2609**
Remake of #2838 for 1.10

### CODE REVIEW

**Comment by Darkhax** [comment]
While it's hard to demonstrate, this is definitely an issue. That said, it's usually a good idea to provide some sort of debug mod to show that this actually makes a difference, that way Lex doesn't have to re-confirm the issue.

**Comment by williewillus** [comment]
Original ticket already shows gc holding on to world from this/vanilla ticket

**Comment by Actuarius** [comment]
@mezz added labels [Vanilla Bug]

**Comment by mezz** [comment]
Looks like simple, safe fix. The map's value is already always checked for null so there's no issue with making it weak.

**Comment by bs2609** [comment]
Additionally, `World` doesn't override `equals()`, so the only way to retrieve a value from the map is to hold a strong reference to the corresponding key, ensuring the weak reference remains valid.

**Comment by liach** [comment]
If you really want a test then use a map with `Integer` keys representing the dimension IDs of the world. But that is much more mess.

**Comment by bs2609** [comment]
Any update on this?

**Comment by LatvianModder** [comment]
@liach but why would you do `Map<Integer T>` when there is `TIntObjectMap<T>` available? Trove4J ftw

**Comment by bs2609** [comment]
Any comment on this? @LexManos 
Hoping to avoid having to remake again for 1.11

**Comment by liach** [comment]
You can use @ on project manager Lexmanos or cpw. I believe that they have no reason to reject such an important fix.

**Comment by mezz** [comment]
Please create this fix for 1.11.x as well.

**Pull request merged**
