### PR TITLE
[Omnibus] Fix typos and javadocs across code base

### PR DESCRIPTION
**Pull request by TheCurle**
# This Is An Omnibus PR
[Open PRs](https://github.com/TheCurle/MinecraftForge/pulls?q=is%3Apr+is%3Aopen+base%3Anoci-omnibus%2Fcleanup) | [Included PRs](https://github.com/MinecraftForge/MinecraftForge/compare/1.16.x...TheCurle:noci-omnibus/cleanup) | [Submit PR](https://github.com/TheCurle/MinecraftForge/pulls)

### What does this Omnibus target?
This PR is targeting the many typos across the Forge code base; in javadocs, other comments, variables, and other miscellaneous files, along with inaccuracies in javadocs. As long as it does not break binary compatibility, it's a valid fix for this PR.

### What does this mean?
An omnibus PR is our new way of combining common, small contributions into a single PR so that they can be merged in a single build, while maintaining the simplicity of contributing small fixes piecewise.

### How can I contribute?
To contribute to this omnibus, you must make your PR at the source branch. You'll need to switch the source repository/branch when using that link. Once your PR is approved it will be merged to the omnibus branch for later merging into the main trunk.

### CODE REVIEW

**Comment by TheCurle** [comment]
Well, this has merge conflicts on nearly every file in the repo, so this is going to take a while to rebase. 
Apologies if the credit for anyone's contributions are lost in the process.

**Comment by Eric-01** [comment]
I can rebase locally my own commits on top of the current master, but how to push them afterwards without causing even more conflicts?

EDIT: I had cherry-picked my commit and then successfully rebased it on top of the current master (i.e. 1.16.x). You can see it in this branch: https://github.com/Eric-01/MinecraftForge/tree/my-omnibus-commit-rebased

If you have any conflicts between this rebased commit and the others, please let me know. I can willingly help resolve them.

**Comment by Eric-01** [comment]
@sciwhiz12 @TheArcaneBrony
I remember you've had comments about improving the current description of the `alwaysSetupTerrainOffThread` config option. Are you still interested in PR them?

If you've forgotten about it completely, I can give you a link to those comments :)

**Comment by TheCurle** [comment]
Ohno.
 960 files changed, +2,555 −2,525 additions and removals.
 
 1.16 is coming to the end of its' LTS status soon, so there's nay worth the effort attempting to revive this.
 So i'm going to close it.
 
 However, for every change that anyone has made on the corresponding fork, i'm going to try to add it to 1.18 so that all the amazing work and documentation isn't lost.
 
 Going to try, anyway.

**Pull request closed without merging**
