### PR TITLE
Add test mod guidelines (#4620)

### PR DESCRIPTION
**Pull request by Daomephsta**
Adds a README in the test directory with guidelines for writing test mods, as discussed in #4620.

### CODE REVIEW

**Comment by SkyHawkB** [comment]
As in #5026, the license in [this file](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/chunkio/ChunkIOThreadPoolExecutor.java) is incorrect. I think that if you rebase and fix it the Travis build will work fine.

**Comment by liach** [comment]
@Leviathan143 You should put this in the wiki or the forge docs instead.

**Comment by Daomephsta** [comment]
@liach Mezz suggested the current location in #4620. It seemed like a reasonable place to me. RTD is for information about developing Forge mods as far as I'm aware.

**Comment by MajorTuvok** [comment]
@liach I think it should be both in the docs and the packages - not everyone reads the docs, whilst he/she is in development and having it in the package will remind everyone that those guidelines exist...

**Comment by liach** [comment]
people ignore irrelevant files in the package (like me)

**Comment by MajorTuvok** [comment]
But if it is in both, you'll see it eventually... 
(though why are you ignoring README files? The name already says, that one should read them)

**Comment by liach** [comment]
Anyways, I added it to https://github.com/MinecraftForge/MinecraftForge/wiki/Writing-a-Test-Mod---Guidelines so that people have one more way to discover this guideline. Having more ways of seeing a guideline is better than having less.

**Review by liach — APPROVED** [review]
Copied to https://github.com/MinecraftForge/MinecraftForge/wiki/Writing-a-Test-Mod---Guidelines/4e142aed628a2bfb8c549fe5ac8baad1c0d6e389 to notify future test mod makers

**Comment by mezz** [comment]
I think @liach has the right idea actually, it makes sense to have it on the wiki so that it can be updated more easily.

**Comment by mezz** [comment]
How about change the readme so that it links to the wiki?

**Comment by marvin-roesch** [comment]
I think we should consolidate contribution related information in a single place.

Right now, information is spread across the [`CONTRIBUTING.md`](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/CONTRIBUTING.md) file, the [docs](https://mcforge.readthedocs.io/en/latest/forgedev/) and the GH wiki. This will inevitably lead to desynchronization and makes it harder for newcomers to find the "single source of truth".

I personally would suggest that contribution guidelines be moved to the RTD site completely, so as to get maximum consistency, accessibility and nice formatting (admonitions etc.) on top. In fact, I'd be in favour of disabling the wiki completely, since it's gone mostly stale and probably unnoticed by most people (case in point: the FAQ mentions MC 1.2).

**Comment by MajorTuvok** [comment]
Don't close it stale...
This should be discussed...

**Comment by kierajreed** [comment]
This is still relevant because the docs are still in need of unification and updating.

**Comment by MajorTuvok** [comment]
This should not be closed because of inactivity...
We just need to discuss this a bit more

**Comment by MajorTuvok** [comment]
This is still relevant for the same reasons SkyHawk put out last time:
The docs need unification and an update.

**Comment by tterrag1098** [comment]
Since when does this repo have a wiki? Surely that information would be better off on the official docs.

**Comment by liach** [comment]
The wiki has been present since about 2013 (from history), long before the official documents.

**Comment by tterrag1098** [comment]
That doesn't mean it should stay that way.

**Comment by kierajreed** [comment]
Everything should go on the documentation site, and all the documentation is in need of updating. (Maybe make a separate issue for the documentation changes so this one can be closed?) See also: [earlier comment by Paleo](https://github.com/MinecraftForge/MinecraftForge/pull/5027#issuecomment-414289105).

**Comment by Sana36** [comment]
Yes Please! Trying to find all the information needed to help and to know what information is current is currently challenging. I am happy to provide my current 'reading' list if it helps.

**Pull request closed without merging**
