### PR TITLE
[1.18.x] ClientPauseEvent (Re-open of #9761)

### PR DESCRIPTION
**Pull request by SrRapero720**
All requested changes from #9763 are done

### CODE REVIEW

**Comment by Jonathing** [comment]
Next time, you can just re-open the old PR. 👍

**Comment by SrRapero720** [comment]
@Jonathing when a PR is closed by a staff author cannot re-open it
image

**Comment by Jonathing** [comment]
Oh bruh 🤡

**Comment by SrRapero720** [comment]
moved to #9780

**Pull request closed without merging**
