### PR TITLE
[1.12] Removing deprecated registerEntityRenderingHandler method (#4201)

### LINKED ISSUE #4201: [1.11~1.13] Remove the deprecated registerEntityRenderingHandler
Now Forge is already on 1.12 but [this method](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/registry/RenderingRegistry.java#L45) is expected to be removed in 1.11.

### PR DESCRIPTION
**Pull request by sokratis12GR**
Fixes #4201

### CODE REVIEW

**Comment by covers1624** [comment]
The old hash map should also be removed right?

**Comment by mezz** [comment]
We are not making breaking changes right now.

**Comment by mezz** [comment]
Breaking changes must be done on major version updates, so this will have to wait for 1.13.

**Comment by sokratis12GR** [comment]
Alrighty thanks, gonna keep an eye on these for 1.13 :)

**Comment by AEnterprise** [comment]
is there a list somewhere (or could we start one) with planned breaking changes for 1.13 like this? if we know about some of them in advance we could start avoiding those and would give the forge team a list to remove them all at once in the initial port

**Comment by sokratis12GR** [comment]
What if we make a PR, adding `// Forge: Remove in 1.13` for those specific methods that we know will be removed ?

**Comment by mezz** [comment]
So far the only plan is to remove deprecated stuff, which should be easy to avoid. Anything that will be removed should be marked deprecated. Comments stating the version for removal can be nice but usually anything deprecated in forge is fair game for removal during version updates.
I'll probably maintain a separate branch or something to get a head start for 1.13 so we don't have to scramble to remove these things in the small window of time where breaking changes are accepted.

**Comment by HenryLoenwind** [comment]
sokratis12GR, would you add the `Forge: Remove in 1.13` before or after the `* TODO Will be removed in 1.11.` ?

;) *scnr*

**Comment by sokratis12GR** [comment]
just replace it :P

**Pull request closed without merging**
