### PR TITLE
Changed EnumFacing to Optional<EnumFacing> in Fluid stuff

### PR DESCRIPTION
**Pull request by laci200270**
It replaces #2014

### CODE REVIEW

**Comment by sham1** [comment]
Why, just why is this a thing?

**Comment by KingLemming** [comment]
We aren't going to force people up to Java 8 either. Unfortunately, the bad design of EnumFacing is here to stay for now. Gotta let it go.

**Comment by laci200270** [comment]
I not used any of Java8 stuff.I used google's optional which default included in forge.

**Comment by laci200270** [comment]
@LexManos what you think?

**Comment by OvermindDL1** [comment]
Big +1 from me, anything that helps remove possible null pointers and forces people to test is always a boon, but this does not go far enough either and breaks company, so I doubt it will be accepted without a new Minecraft version change, and if that happens then may as well rewrite it properly.

**Comment by laci200270** [comment]
Also this not change much.If this get accepted only 3-4 lines will need to rewrite

**Comment by laci200270** [comment]
@LexManos maybe this in 1.8.8 update?

**Comment by LexManos** [comment]
Maybe, ask @cpw Tho i'm still partial to using the @Nullable annotation as that's got better IDE integration, and doesn't break the API.

**Comment by laci200270** [comment]
This would force modders to check for  this while nullable not.

**Comment by LexManos** [comment]
Actually the entire point of @Nullable is to force them to check at the source level and not as a runtime requirement. Any modern IDE supports @Nullable in code analysis.

**Comment by laci200270** [comment]
Ok. I'll make a PR for that

**Pull request closed without merging**
