### PR TITLE
[1.9.4] Add CooldownSetEvent

### PR DESCRIPTION
**Pull request by asiekierka**
Many users are expressing a desire to be able to tweak cooldown values on items - for instance, disabling them completely if someone doesn't like the new system. I am proposing an event to do so by letting one override cooldown values as they are being set. I believe this is a fairly clean solution.

### CODE REVIEW

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Feature]

**Comment by heldplayer** [comment]
Does this sync nicely with the client?

**Comment by asiekierka** [comment]
Yes. notifyOnSet is called from super.setCooldown() on CooldownTrackerServer, so if the event is cancelled the packet is not sent to the client at all.

**Comment by oitsjustjose** [comment]
I seriously hope this gets implemented - I just tried a really hacky approach using AttributeModifiers, and it almost works, except the original item's damage is lost in the process, and I can put it back - but then it won't be affected by enchanting..

**Comment by williewillus** [comment]
@oitsjustjose
This PR is about the cooldowns like the ones on ender pearls, not the attack cool downs

**Comment by asiekierka** [comment]
@williewillus Generally, item usage cooldowns. There's no item-based variable for some of them (like shields).

I should add events for attack cooldowns...

**Comment by asiekierka** [comment]
Doubt it will be pulled in for 1.9.4. Feel free to take this up.

**Pull request closed without merging**
