### PR TITLE
1.8 Forge Fluid Rendering

### PR DESCRIPTION
**Pull request by Thog**
This code is based on the Vanilla Fluid Render. 
Also the getFluidHeightForRender might need to be rewrite but the render work.

### CODE REVIEW

**Comment by LexManos** [comment]
We already talked about this you should be able to duplicate fluid rendering using models.
Also, 'based on' by that you mean copy pasted entirely with a few lines changed.
No way something this poorly written gets into Forge. We are not a deobfuscated/decompiled project we have no reason whatsoever to have that horrible of code structure/variable names.

**Comment by Thog** [comment]
This is true, we have the model system (Why Mojang doesn't use it for liquids???). 
I will try to write that with the model system. 
Anyway, thanks for your answer, and my apology for this PR.

**Comment by RainWarrior** [comment]
It's not particularly hard - although forge fluid classes need a cleanup since a lot of things changed in 1.8.
fluid screenshot

**Comment by LexManos** [comment]
Mojang is still in transition from internal rendering to models. It's still in development. Fluids being one of those they haven't gotten to yet.
Always remember that Minecraft is in development still :P

**Pull request closed without merging**
