### PR TITLE
Updated Explosion Patch.

### PR DESCRIPTION
**Pull request by covers1624**
I think i did it right..
Fixed compile errors for Explosion.java
 - Vec3 -> Vec3d
Re-Added Forge event hook.

### CODE REVIEW

**Comment by williewillus** [comment]
Usually the forge team does these by themselves :P

**Comment by covers1624** [comment]
Just trying to help out any way i can, no sense letting the entire modding community sit back and watch.

**Comment by liach** [comment]
How about rejected patch removal?

**Comment by covers1624** [comment]
Forgot about that one, will do that when i get home.

**Pull request closed without merging**
