### PR TITLE
Added GetGrowthChanceEvent to control crop crowth rate

### PR DESCRIPTION
**Pull request by elix-x**
Added GetGrowthChanceEvent to change growth chance. Currently fired for all crops and nether warts.

This is #2830, but only with GetGrowthChanceEvent and correctly generated patches.

### CODE REVIEW

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by elix-x** [comment]
Please tell me if i am missing something again.

**Comment by cpw** [comment]
Why is this an event? What is the purpose of turning a constant (growth chance) into an event?

**Comment by elix-x** [comment]
First, it is not constant (in vanilla it's based based on surronding).
Second, to allow modders to add custom crop growth rate modifiers (both positive and negative).

**Pull request closed without merging**
