### PR TITLE
[1.20.6] Alllow for Mods to have a Constructor with IEventBus as a parameter.

### PR DESCRIPTION
**Pull request by RealMangorage**
This PR will allow Mod Devs to have The Mod EventBus passed thru into their mods constructor.,

### CODE REVIEW

**Review by PaintNinja — CHANGES_REQUESTED** [review]
Spring-like constructor dependency injection could be nice, but there's some potential issues with this PR...
1) It fails to properly account for multiple constructors. For example, if you have a no-param ctor that delegates to another ctor, this PR will break that.
2) Ordering is important. The delegation might work if you put the no-arg after the arg one, but this isn't obvious
3) Can there ever be zero constructors?
4) Your PR title and code comments mention IEventBus as a parameter, but FMLModContainer is actually provided

**Comment by LexManos** [comment]
Ya I requested that it be changed to ModContainer as that is what is being accessed in the mod loading context.
It has the event bus context, which is what people are trying to access. but also is a nice place to stick any other information that is needed for the mod.
Passing in this value saves the need for a thread local.
And this comes as a side discussion of wanting to simplify mod loading.
Honestly the mod event bus just needs to die. Being replaced by a limited interface or explicit callback registration.
Its a artifact of a bloated/over engineered system that needs major simplification.
This Pr is a stop-gap/off hand comment until that simplification happens. Honestly, I dont think we should pull this. But it was a good thought exercise.

**Comment by RealMangorage** [comment]
> Spring-like constructor dependency injection could be nice, but there's some potential issues with this PR...
> 
> 1. It fails to properly account for multiple constructors. For example, if you have a no-param ctor that delegates to another ctor, this PR will break that.
> 2. Ordering is important. The delegation might work if you put the no-arg after the arg one, but this isn't obvious
> 3. Can there ever be zero constructors?
> 4. Your PR title and code comments mention IEventBus as a parameter, but FMLModContainer is actually provided


1) That one is a difficult one, could use normal way when there are more then 1 constructor perhaps.
2) Yeah that is important.
3) Yes there can be.
4) Yeah I need to fix that

**Comment by Jonathing** [comment]
> This Pr is a stop-gap/off hand comment until that simplification happens. Honestly, I dont think we should pull this. But it was a good thought exercise.

I disgree. Because various other systems need to be rewritten and/or fixed in the first place, pulling this allows us to begin both a) identify where and why existing systems are a mess and b) can allow us to gut existing code or enhance specific features that desperately need it in the meantime. Despite being smaller in scale, I think #10004 was a good example of this.

**Comment by Ecdcaeb** [comment]
To disambiguate, maybe try this:
Add a `@Mod.Constructor` annotation to mark the Constructor. Forge use it , or the one without parameters when non-match.

**Comment by PaintNinja** [comment]
Superseded by #10074

**Pull request closed without merging**
