### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by RobertHerhold**

### CODE REVIEW

**Comment by RobertHerhold** [comment]
@LexManos Could you give a reason for closing this?

**Comment by kashike** [comment]
@RobertHerhold https://github.com/MinecraftForge/MinecraftForge/pull/2266#issuecomment-164199417

**Comment by RobertHerhold** [comment]
Fair enough.

**Comment by RobertHerhold** [comment]
I hope it is noted though for someone else to change

**Comment by williewillus** [comment]
if someone went through all closed issues and found everything related to typos, reformatting, etc. and lumped it into PR it would probably be taken

**Pull request closed without merging**
