### PR TITLE
AccessTransformer Cleanup

### PR DESCRIPTION
**Pull request by GirafiStudios**
Figured it would be a good time to do a bit of cleanup of Forge's Access Transformers, while 1.14 is still in beta. The PR is mostly removals of now-unnecessary ATs, and updating of broken ATs.

[List of all additions/removals](https://gist.github.com/GirafiStudios/282bf2dfed4c303884e1329c702bdb80)
_Any change not listed in the list above is simply just a fix of the AT_ 

Feedback is very welcome.

### CODE REVIEW

**Comment by LexManos** [comment]
Perhaps add gradle task to verify that each line actually applies so that in the future we can automate this.

**Comment by GirafiStudios** [comment]
That's an excellent idea. I do unfortunately not have much experience with Gradle, outside of basic stuff required to setup a dev workspace.

**Comment by GirafiStudios** [comment]
If anybody wants to do an attempt at the gradle task Lex mentioned, please go ahead and do so :)
Here is a little bit of clarification provided by Lex on Discord:
0KGPzyM
If there is no responses to this in about a week or so, I'll close the PR since there is no reason to have a PR open that won't get merged.

**Comment by GirafiStudios** [comment]
Thanks a lot Lex, really appreciate it!

**Pull request closed without merging**
