### PR TITLE
[1.9] Added BlockPos and World to PotionBrewEvent

### PR DESCRIPTION
**Pull request by Kailari**
Currently, there is absolutely no way to obtain brewing stand's position in world from `PotionBrewEvent`, greatly limiting the options we have for implementing custom brewing logic. However, that is easily fixed by passing `World` and `BlockPos` from `TileEntityBrewingStand` to the `PotionBrewEvent`.

Examples of possible use cases:
- Making brewing stands "aware" of their surroundings, changing their behavior based on blocks around them
- Making certain brewing processes affect surroundings of the brewing stand. e.g. making the stand explode after some weird brew, "toxic fumes" (applying potion effects to nearby entities), killing nearby plants and turning grass to dirt below the stand, etc.
- Playing sound effect after brew completed. Currently, if normal brewing is prevented via canceling the event, no sound is played, and as we don't know the position of the brewing stand, we can't play sound effect either.
- Spawning custom particle effects after certain brews

PR contains the required changes and a sample test mod I used to verify that I could use passed values as intended.

### CODE REVIEW

**Comment by Kailari** [comment]
I resolved the conflicts with that were caused by fixed typos and that deprecated event getting deleted.
...and I suck at using git, so I hope I didn't mess up anything in the process.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by asiekierka** [comment]
Cleaner idea: Put an interface on TileEntityBrewingStand and pass that. More flexible in the long run.

**Comment by mezz** [comment]
If you want to update this for 1.11.x, now is the time for breaking changes on that version.

**Comment by mezz** [comment]
Please update this PR for the latest forge version so that it can be considered.

**Pull request closed without merging**
