### PR TITLE
[1.12] Replace ThrowableImpactEvent with a more generic version

### PR DESCRIPTION
**Pull request by bs2609**
This replaces the original `ThrowableImpactEvent` with a new, more generic `ProjectileImpactEvent`, which serves the same function, but covers other types of projectiles.

Currently, this includes:

* Arrows
* Fireballs
* Thrown items
* Shulker bullets and llama spit

The event is provided as a catch-all 'base' event, with subclasses for the more specific types of impact (which still have a common superclass).

Firing the event is handled by the various overloads of `onProjectileImpact()` in `ForgeEventFactory`.

A test mod is added that just logs the details of impacts.

### CODE REVIEW

**Comment by bs2609** [comment]
~~This is a breaking change, as the old event is removed to avoid confusion.~~ (**Edit:** The old event is now just deprecated, it'll be removed next version instead)

`ProjectileImpactEvent.Throwable` should be pretty much a drop-in replacement, however.

**Comment by bs2609** [comment]
@williewillus, as the author of the original (#3071), does this look ok to you?

**Comment by williewillus** [comment]
Would this be a good use for the generic event system? Aka `ProjectileImpactEvent<EntityArrow>` instead of `ProjectileImpactEvent.Arrow`

**Comment by bs2609** [comment]
That's a good question, and I hadn't initially thought of that. Does anyone know if the generic system would be considered suitable here? There isn't a lot to go on, so I'd like clarification.

**Comment by mcenderdragon** [comment]
A genric version offers better mod intergartion. So a mod can also fire this event for their own throwables

**Comment by mezz** [comment]
I think the generic system would be good here.
We're going to stop breaking changes now in preparation for stable Forge on Wednesday, so please deprecate the old stuff. This PR doesn't seem to require breaking changes to be effective.

**Comment by bs2609** [comment]
I'm not too sure about the generic system for this case. I might be misunderstanding, but as I see it, for this PR, the following will be the only valid event handler signatures:

 * `ProjectileImpactEvent<Entity>`
 * `ProjectileImpactEvent<EntityArrow>`
 * `ProjectileImpactEvent<EntityFireball>`
 * `ProjectileImpactEvent<EntityThrowable>`

with the `<Entity>` event only catching things that aren't covered by the other events, instead of being a catch-all.

It'll mean a reduction in the event code, but it places more burden on the documentation, as the behaviour isn't clear otherwise.

The current uses of generic events all use them for disjoint types (eg `Block`, `TileEntity`, etc).

**Comment by bs2609** [comment]
@mezz, any update?

**Comment by mezz** [comment]
Looks good to me.

**Comment by liach** [comment]
Are mods supposed to fire these events?

**Comment by bs2609** [comment]
Mods that use their own projectile classes should probably fire this event, yes. Anything that extends a vanilla class will have the event fired by default.

I've updated the event javadoc to mention this.

**Comment by LexManos** [comment]
Good enough for now but i'll try and keep a reminder to clean this up to a generic event later. The issue is translating subclasses as the generic events are truly generics. If anyone wants to go and attempt that and provide the performance reports on that, that would be great.

**Pull request merged**
