### PR TITLE
Fix Issues #4031 and # 4023

### PR DESCRIPTION
**Pull request by TechnicianLP**

### CODE REVIEW

**Comment by Choonster** [comment]
Since you've only referenced the issue numbers in the PR title and commit messages and not the PR description, GitHub hasn't added links to this PR from the issue pages.

I'll reference them in this comment to make it more obvious from the issue pages that there's a PR to fix them: #4031 #4023

**Comment by TechnicianLP** [comment]
They are both saying "TechnicianLP added a commit to TechnicianLP/MinecraftForge that referenced this issue 5 hours ago"

**Comment by ghost** [comment]
I'm experiencing that both events: RightClickBLock and LeftClickBLock are called when i left click on a block and when i right click on a block. Will this fix resolve that issue?

**Comment by TechnicianLP** [comment]
This has been merged 6 days ago ... check yourself ... (probably not as this was only intended to fix the packet being sent twice)

**Comment by patr4547** [comment]
It was probably a mechanic anyways, as it happens when i have something in offhand

**Comment by ghost** [comment]
You are right, i should have checked. My issue does not seem to occur.

**Pull request merged**
