### PR TITLE
Add ability for custom detector rail output

### PR DESCRIPTION
**Pull request by williewillus**
Adds an event that detector rails fire whenever they update their comparator output level.

This allows mods to customize comparator output for their own carts, as well as those of vanilla if they so desire.

For example, the I want the mana pool cart to emit a comparator signal like the pool does, and this event would enable me to do so.

### CODE REVIEW

**Comment by LexManos** [comment]
Why does this need to be a event why not just have it as a property of the minecart itself? Why do you NEED to edit vanilla carts comparitor outputs?

**Comment by williewillus** [comment]
I'll change it

**Comment by williewillus** [comment]
If I make a new hook `getComparatorLevel` in EntityMinecart should I move the vanilla logic there or keep it in BlockRailDetector?

**Comment by williewillus** [comment]
Moved it to EntityMinecart. The name is up for change if anyone has trouble with it

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by williewillus** [comment]
Any news on this?

**Comment by cpw** [comment]
Feedback: maybe the command block minecart should use the same code?

**Comment by williewillus** [comment]
Do you mean moving the vanilla logic to my new method?

**Comment by williewillus** [comment]
it does them in a specific order so I didn't want to in case that breaks some edge case in vanilla

**Pull request merged**
