### PR TITLE
IS_TEMPERATE Temperature biome tag

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Mushroom biome, jungle, stony peaks, and swamps are all hot biomes. Not temperate. 

Take a look at the temperature field in the biome json
https://github.com/misode/vanilla-worldgen/tree/master/worldgen/biome

My takeaway:
inclusive 0.8+ is hot
exclusive 0.3 to 0.8 exclusive is temperate
inclusive 0.3- is cold

Beach probably should not be listed since it can spawn in any temperature region except for snowy cold areas. But that's just my opinion

**Comment by JT122406** [comment]
> Mushroom biome, jungle, stony peaks, and swamps are all hot biomes. Not temperate.
> 
> Take a look at the temperature field in the biome json https://github.com/misode/vanilla-worldgen/tree/master/worldgen/biome
> 
> My takeaway: inclusive 0.8+ is hot exclusive 0.3 to 0.8 exclusive is temperate inclusive 0.3- is cold
> 
> Beach probably should not be listed since it can spawn in any temperature region except for snowy cold areas. But that's just my opinion

I used this: https://minecraft.fandom.com/wiki/Biome#Temperate_biomes

**Comment by JT122406** [comment]
What should we use

**Comment by TelepathicGrunt** [comment]
Wiki is wrong lol. I don't trust it for worldgen stuff after I caught it trying to say dungeons, desert wells, icebergs, and forest rocks were structures when they do not show up on /locate nor get disabled when turning off "generate structures". I had to go and fix the wiki for that. 

Think about it, do you consider a Jungle a nice temperate neutral temperature in real life? Not really. It's hot. It's stuffy. That's why Forge put the Jungle in the hot category back in the Biome Dictionary days as well.  https://github.com/MinecraftForge/MinecraftForge/blob/09f1b8d43856643e4ab36d9d64e2176c440a3e72/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L295

Instead, stick with what the game actually is using. The json I linked is the official json export of the biomes from Mojang. You can also verify in code what the biome temperatures are as well. Do not copy the wiki exactly. Do what makes the most sense instead.

**Comment by JT122406** [comment]
Alright I will change it in the morning

**Comment by JT122406** [comment]
> Mushroom biome, jungle, stony peaks, and swamps are all hot biomes. Not temperate.
> 
> Take a look at the temperature field in the biome json https://github.com/misode/vanilla-worldgen/tree/master/worldgen/biome
> 
> My takeaway: inclusive 0.8+ is hot exclusive 0.3 to 0.8 exclusive is temperate inclusive 0.3- is cold
> 
> Beach probably should not be listed since it can spawn in any temperature region except for snowy cold areas. But that's just my opinion

We might need to adjust cold to be <= .5 because cold_ocean is .5

**Comment by JT122406** [comment]
and .8 would mean deep dark is hot

**Comment by TelepathicGrunt** [comment]
Then deep dark is hot. Also, oceans are a special case. Go off of their names. Not their temperature. Warm ocean, lukewarm ocean, ocean, and cold ocean are all 0.5 because mojang didnt fix their temperatures.

**Pull request closed without merging**
