### PR TITLE
Made Villager Registry useful.

### PR DESCRIPTION
**Pull request by Thutmose**
Updated to fix the merge conflicts caused by the compiler warning fixing commit.

see #2207 for the changes added, If you want, I can re-add the test mod as well.

### CODE REVIEW

**Comment by williewillus** [comment]
No need to make a new pr every time :p
Rebase, resolve the merge conflicts then (squash and) force push

**Comment by Thutmose** [comment]
I Hope I just did that properly.

**Comment by Spartan322** [comment]
Your probably going to need to rebase that.

**Comment by Thutmose** [comment]
I thought that is what I did? it says "This branch is up-to-date with the base branch"

**Comment by laci200270** [comment]
You should do it with
```
git reset --soft HEAD~3
```

**Comment by gabizou** [comment]
@Thutmose more than likely, you'll have to `git rebase upstream/1.8.8` since I can imagine that this would be useful for 1.8.8 feature set.

**Comment by Thutmose** [comment]
it says "This branch is up-to-date with the base branch" and "MinecraftForge:1.8.8 from Thutmose:VillagerRegistry", so I assume it is properly merge compatible?

**Comment by cpw** [comment]
Don't worry. I have this as WIP in my dev env. When I get some time (over Xmas I expect) I'll make sure its pushed up..

**Comment by RainWarrior** [comment]
I'll close this since there's an updated PR open.

**Pull request closed without merging**
