### PR TITLE
[1.19.3] Added LivingMakeBrainEvent, to allow a consistent way for modders to manipulate entity Brains

### PR DESCRIPTION
**Pull request by Thelnfamous1**
Currently, while it is already possible to manipulate entity `Brain`s using `EntityJoinLevelEvent`, there is one glaring issue that has no API solution as far as I can tell: 

When an entity's brain is loaded from disk during `LivingEntity#readAdditionalSaveData`, it only uses the vanilla collections of `MemoryModuleType`s and `SensorType`s (which are by default in-lined empty immutable lists) to create the `Codec` used to deserialize the brain's memories from NBT.

This means that even if a modder has changed the entity's brain during EJLE to a new `Brain` instance with a `Codec` capable of serializing additional memory values, they will not get deserialized when loading from disk. This is despite those memory values getting serialized to NBT, so it's a rather glaring inconsistency.

To remedy this, the newly added `LivingMakeBrainEvent` is patched into `LivingEntity` to fire both times the entity's brain is created: once at the end of the constructor of `LivingEntity`, and once during the brain deserialization during `LivingEntity#readAdditionalSaveData`. 

A new class, `BrainBuilder`, is added to facilitate manipulating a copy of the original Brain's state during the event that will be copied to a fresh Brain instance after the event is posted.

Included is a test mod that adds the ability to swim to Piglins using the event.

### CODE REVIEW

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/30d0a630d6fb81494132c49e476a8a7fc940d3a8

**Comment by Tslat** [comment]
Did we just _double_ the required work that every single livingentity goes through when spawning related to its brain?

_Every single_ LivingEntity calls makeBrain, even if it doesn't use a brain
Brain construction is already ridiculously inefficient, with numerous repeated collection creations and discards

This PR just doubled all that by dissasembling the brain every time, then passing it all to yet another object with yet another bunch of collections, then re-create the entire brain again

For every single LivingEntity spawn

Obviously entities that don't use a brain will skip most of the actual insertions & heavier work, but this still more than doubles the work for anything that _does_ use brains, which is proving to be every entity mojang adds at this point

**Comment by LexManos** [comment]
If you have profiling data to backup what you're claiming to be a performance issue im more then willing to look at it. However, unless there is a mod involved a shallow copy of the underlying Brain fields shouldn't be that performance intensive. I'm open to other ideas if you have them, but when it comes to performance arguments I need to see numbers.

**Comment by LexManos** [comment]
Just for clarity sake. The claims here are completely false. Yes this change is not 100% free. However here are a few logs showing that its its essentially irrelevant. 
Without Event: https://spark.lucko.me/beI2GYaKHC 
With Event: https://spark.lucko.me/V6YcBeXxMh
LivingEntity.init 1500ms vs 1668ms
Villager.makeBrain 1296ms vs 1132ms
ForgeHooks.onLivingMakeBrain is 416ms so yes its not free, but we're talking miniscule amounts.
And we're talking an extreme case, of creating 10,000 villagers. 

Ran this 10 times per profile:
```java
    @SubscribeEvent
    public void onServerStarting(BreakEvent event) {
        var level = event.getPlayer().level();
        if (level.isClientSide) return;
        int COUNT = 1000;
        LOGGER.info("Simulating " + COUNT + " villagers");
        for (int x = 0; x < COUNT; x++) {
            EntityType.VILLAGER.create(level);
        }
    }
```

**Pull request closed without merging**
