### PR TITLE
Fix '--assetIndex' version by adding variable into build.gradle

### PR DESCRIPTION
**Pull request by OhYea777**
Forge is currently using the wrong asset index

### CODE REVIEW

**Comment by OhYea777** [comment]
Force-push to change the loader version and minecraft dependency version in the **MDK**'s `mods.toml` file

**Comment by tterrag1098** [comment]
Shouldn't this default to 1.13.2?

**Comment by LexManos** [comment]
No, it *should* be read from the vanilla version.json.
Perhaps a PR to FG to expose this would be in order.

**Comment by OhYea777** [comment]
Closing this PR as I have combined this and MinecraftForge/MinecraftForge#5333 into its own PR: MinecraftForge/MinecraftForge#5482

**Pull request closed without merging**
