### PR TITLE
Always go through the WorldProvider when accessing world time

### PR DESCRIPTION
**Pull request by diesieben07**
This makes the methods `setWorldTime` and `getWorldTime` in `WorldProvider` more useful, allowing for things like a time running separate from "overworld time".

### CODE REVIEW

**Review by liach — COMMENTED** [review]
What is func_72820_D()?

**Comment by Choonster** [comment]
@liach [MCPBot](http://mcpbot.bspk.rs/) says that `func_72820_D` is `World#getWorldTime`.

**Comment by liach** [comment]
Is he adding useless patches?

**Comment by Choonster** [comment]
I don't think he is. Which patches do you think are useless?

**Comment by diesieben07** [comment]
What I am doing is replacing calls to `WorldInfo::setWorldTime` with `World::setWorldTime`. This adds the indirection through the `WorldProvider`, since `World::setWorldTime` calls `WorldProvider::setWorldTime`.
By default that calls back to the `WorldInfo`, but it can be changed in a custom dimension. Same for `getWorldTime`.

**Pull request merged**
