### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Ehem, interact*

**Comment by jcranky** [comment]
Lol, I just now saw that I "fixed it wrong"... 
Now, is this kind of PR desirable?

**Comment by LexManos** [comment]
No it's not desirable. Typo fixes like this isn't helpful it's just grabbing a bit of the commit history of a popular project.
When one of the regular committers cares to update this it'll get fixed.
However, considering we're switching license here soon-ish it doesn't really matter.

**Comment by jcranky** [comment]
Fair enough. Just out of curiosity, what is happening to licensing? Moving away from Open Source, or just changing specifics?

**Comment by LexManos** [comment]
The plan is to go LGPL in 1.8.4 like FML. We're merging the two projects, and having a homebrew license is just.. nasty.

**Comment by cpw** [comment]
No move from OS AFAIK.

**Comment by jcranky** [comment]
Cool, I'm happy to hear/read that, thanks! =)

**Pull request closed without merging**
