### PR TITLE
[1.15.1] Extend the config system and re-implement the config GUI

### PR DESCRIPTION
**Pull request by Cadiboo**
- Adds the mods list button to the in game menu screen
- Fixes some small bugs in the config system
- Adds support for Bytes, Shorts and Floats
- Re-implements the config GUI
- Adds a test mod for the config system
- Mostly re-implements FML's dummy config GUI
- Extends the Javadocs on `ModConfig.Type`
- Adds a Javadoc to `FMLConfig` telling modders to use Forge's system rather than NightConfig directly.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Some screenshots would be nice.

**Comment by Cadiboo** [comment]
> Some screenshots would be nice.

Will do

**Comment by gigaherz** [comment]
> [13:44] Cadiboo: Shit I just noticed some issues with my config’s handling of nested lists & configs
> [13:44] Cadiboo: Is there a way to put a PR on hold or something?
> [13:45] gigaherz: don't think so, but I can just mark it wip if you want
> [13:45] Cadiboo: Yes pls ty

Marked as WIP until you tell us it's ready again.

**Comment by Unnoen** [comment]
Just as a reminder, make sure to check for bugs/issues at different GUI scales *and* fullscreen.

**Comment by ichttt** [comment]
It would be good if you could split this PR in two parts, one with all the breaking changes and one with the actual config gui implementation, so it is more easy to review, and we get the breaking changes merged before the first RB of 1.15.1.

**Comment by Cadiboo** [comment]
> Just as a reminder, make sure to check for bugs/issues at different GUI scales _and_ fullscreen.

The control buttons at the bottom have some issues when the width is small as they can't all fit on screen at the same time. Other than this there are no issues that I could find.

**Comment by Cadiboo** [comment]
The issues with my config gui’s handling of nested lists & configs have been fixed.
Should I now base this on top of [ichttt's PR](https://github.com/MinecraftForge/MinecraftForge/pull/6437)?
Also should I add the ability to sync the server configuration client -> server to allow OPs to change server configs remotely?

**Comment by Cadiboo** [comment]
To make stuff easier to get into the RB and review separately everything is now split up.
This PR is superseded by #6437 for the breaking changes, #6464 for the config system improvements & bug fixes, #6466 for the fixes to Forge's config & translations and #6467 for the Config GUI.

**Pull request closed without merging**
