### PR TITLE
DFU - The second.

### PR DESCRIPTION
**Pull request by marchermans**
### Second version of: #8242 and #8410 
This version of the PR finally fixes the NPEs that where seen yesterday during the initial attempt at this.
I finally tracked them down to the concurrent calculation of the rules while forge rebuilds the types in the schema. So @cpw was right.....again.
This version now also includes a test mod 👍, not sure why I did not include it in the first one.

### Modifiable DFU
This RP adds support for modifying the schema that is used by DFU, up to a certain degree.
To be precise it adds the framework for forge to modify the DFU system at runtime (and rebuild it dynamically when the are mods loaded)

#### Goals
- Provide a way to modify DFU, its Schemas and Rules at runtime
- Provide a way for modders to add their BlockEntities and Entities to any Schema at runtime.
- Increase our understanding of how DFU operates
- Allow 1.17 modded worlds to be updated to 1.18
- Provide better options to debug DFU, up to certain degree.

#### Implementation
Forge now provides a custom DFU that is used at runtime instead.
This DFU is capable of delegating the actual work to an internal wrapped DFU for processing, this internal DFU can be rebuild at will, especially when mods are loaded, and as such can be used to dynamically change what is used to perform the updates.
An event is fired for each schema to allow modders to add their own members to the schema (which is needed for world upgrades)

We use a single line patch, to replace the builder that is used to build the DFU instance that Minecraft uses. This builder then builds the delegating Forge DFU instance and passes al information and control to it. Once mods are loaded, a new ModLoadingState was is invoked to collect the changes to DFU. This state fires an event for each known Schema, which then can be used to adapt it.

To provide better debuggability of DFU (in particular its rule system) it is now also possible to disable the off-thread pre-compute of the REWRITE_CACHE. This allows for the debugging of the rules, exactly from where they are invoked, instead of having to figure out from where they are invoked in the off-thread pre-compute making that a lot easier (they are also then only build for one particular version that is needed at a time, instead of all at once). This also improves DFU's memory footprint in the case of a low-memory situation, since those optimized (and most likely completely unused) rules are not in memory at runtime if the feature is enabled. The feature can be enabled by passing `-Dforge.datafixer.disablePreCompute=true` as a JVM argument at startup.

#### Future:
Provide better controls to allow for the Schemas to be adapted.

#### Usage:
To use the new moddable DFU, a modder can listen to the `ConfigureDatafixSchemaEvent` and register its schema changes to the event. To register more entities and blockentities use the relevant methods on the event it self, and to add more custom types use the methods on the contained `Schema` object.

Several convenience methods are provided in the event to setup the TypeTemplate instance for entities and blockentities.
##### Example:
```java
@Mod.EventBusSubscriber(modid = Constants.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class DataFixSetupHandler
{

    @SubscribeEvent
    public static void onConfigureDatafixSchema(final ConfigureDatafixSchemaEvent event)
    {
        if (event.getSchema().getVersionKey() == DataFixUtils.makeKey(2717)) {
            event.registerSimpleBlockEntity(
              new ResourceLocation(Constants.MOD_ID, Constants.BlockEntityTypes.MATERIALLY_RETEXTURABLE)
            );
        }
    }
}
```
This above code example will register a DFU type for a block entity (just a catch-all-nbt type, nothing fancy) to 1.17 (from 1.18), which is all that is needed to preserve a block entity when DFU updates a 1.17 world to 1.18. Once a type has been registered it will be passed along to all descendants of that schema and added to those as well. Use the relevant remove methods to remove the type from the schema in a later version.

#### A note about version numbers:
The version numbers required here, are the DFU world version numbers, they can be found in the `DataFixers` class and are not directly related to MC Gameversion numbers, as far as I could figure out.

#### Todo:
- [X] Better testing
- [X] More documentation and examples
- [X] Formatting

### CODE REVIEW

**Comment by Raycoms** [comment]
Any news on that?

**Comment by Raycoms** [comment]
Tested it locally with our Schematic World with a lot of mod specific tile entities. Worked great.
Test-code: https://github.com/ldtteam/minecolonies/blob/forge-dfu/src/main/java/com/minecolonies/coremod/MineColonies.java#L120

**Comment by Raycoms** [comment]
A small question on this, why is this not the default (By default all mod tileentities recover correctly)

**Comment by marchermans** [comment]
So the reason why that does not work is related to the usage reason for DFU.
Assume you have two versions A and B.

In A your BlockEntity is called `mod:some_tile_entity` and in B `mod:some_moved_tile_entity` (note this is basically what has happened between 1.17 and 1.18 (The key path from the root of the NBT to list of TileEntities in the chunk/world has changed). If you are in 1.18 how would you know form just the registry names what the value was in 1.17?

This example can even be expanded upon: Howabout you change the layout of how you store items in your NBT?

Yes it would be easy to say: This is stupid busy work and should not be a problem for modders. But it is, Mojang puts great care into making saves compatible between versions, and I personally think modders should to.

**Pull request closed without merging**
