### PR TITLE
[1.13] Fire registry events

### PR DESCRIPTION
**Pull request by gigaherz**

### CODE REVIEW

**Comment by liach** [comment]
cpw already committed  f734e614e430681bd20ea0ef9bcf1e234e8d303f

**Comment by gigaherz** [comment]
👌

**Comment by marchermans** [comment]
@gigaherz Why did @cpw chose to fire the events before PreInit?
This would make any initialization impossible.

**Comment by gigaherz** [comment]
No idea, but I don't personally care.
You have the mod's constructor if you need to initialize something.
Also, remember Lex's stance that you should not decide what to register based on context/config.

**Comment by Phylogeny** [comment]
It seems extreme to claim that there is absolutely no use-case for that kind of conditional registration. How about Flat Colored Blocks, for instance, which avoids TEs by registering blocks with various HSV / glowing / transparency values, depending on config settings? Registering "everything", in that case, is more than MAX_VALUE number of blocks.

**Comment by marchermans** [comment]
We have libraries which handle multiblock logic, and register dummy blocks and other relevant items and blocks for it. This will simply be made impossible because of this, or at least a lot more complicated because of this.

Simply stating that you have the constructor is not really an option. If I want to communicate with other mods I need to know that at least they have been initialized and their event handlers have been registered. Simply saying registration needs to be conditionless is simply really a bad design in my opinion.

**Comment by GoryMoon** [comment]
Also `@EventBusSubscriber` don't work if you use them for `RegistryEvent.Register` as the discovery is run on `preInit`

**Pull request closed without merging**
