### PR TITLE
Fluid Rendering update for 1.8

### LINKED ISSUE #1674: RenderBlockFluid.java
Not sure if this was intended but RenderBlockFluid.java is nothing but comments in 1.8.

Will this get implemented for 1.8 or should it be considered removed from forge?

Thanks

### PR DESCRIPTION
**Pull request by mcenderdragon**
this is a try to get the Fluid rendere working in the 1.8
because the vanila Fluid Renderer needs an BlockLiquid close #1674

### CODE REVIEW

**Comment by RainWarrior** [comment]
BlockForgeFluidRenderer is pretty much a copy of vanilla BlockFluidRenderer, this is definitely not a right way to do it.
Before even looking at that it should be investigated if liquids can be rendered by using normal block models.

**Comment by mcenderdragon** [comment]
no they cant because the Fluids use a custome renderer, for example the fierrent high from the eges cant be created with normal baked models.And I dont like to edit the vanila BlockFluidRenderer to adding the Forge BlockFluidBase

**Comment by LexManos** [comment]
Edge heights can easily be calculated using the ISmartModel system, and copy/pasting vanilla's rendering is not a good idea, as that's just lazy and copywritten code.

A fluid model is fairly simple. Depending on the possible combinations of heights.

**Comment by mcenderdragon** [comment]
ok, are there tutorials how to use the ISmartModel or creating an own fluid model ?

**Comment by LexManos** [comment]
Probably not, but there has to be a first person to do everything.
Should be fairly simple. Fluids are just two quads, top and bottom, with each corner a different height. 
Should be able to figure it out.

**Pull request closed without merging**
