### PR TITLE
Redirect some lighting functions via world provider

### PR DESCRIPTION
**Pull request by bs2609**
This PR adds redirects for `getCombinedLight` and `getLightBrightness`, allowing world provider implementations to have non-default behaviour if desired.

**Update:**
This has been updated to redirect the `Chunk` methods `getLightFor` and `getLightSubtracted` instead. This should allow covering all the call paths listed here (https://github.com/MinecraftForge/MinecraftForge/pull/4575#issuecomment-353581672).

### CODE REVIEW

**Comment by LexManos** [comment]
Why?

**Comment by bs2609** [comment]
As a general explanation: so you can set `hasSkyLight` to false and still have some kind of lighting.

Vanilla's sky lighting can be very laggy if the terrain isn't suited for it - it's off for the nether and the end, but at the moment, you can only have vanilla's computed sky light, or no sky light whatsoever.

This would allow you to have a "fake" skylight layer in your dimension's lighting which can be made easier to compute, or used to provide some other lighting effects.

**Comment by mezz** [comment]
Sounds interesting, but it's pretty tough to test this out. Any ideas?

**Comment by bs2609** [comment]
Feel like making a Forge command for teleporting across dimensions?

**Comment by mezz** [comment]
I think that would be very good to have, but I don't really have the experience with dimensions to implement it properly myself.

**Comment by Drullkus** [comment]
Advocating for this. Twilight Forest is in need of a solution for its poor lighting performance.

**Comment by liach** [comment]
@bs2609 Can you fix the patches?

**Comment by bs2609** [comment]
Some more info:

There's a few different call stacks involved here, with some inconsistent naming thrown in for good measure. Here's what each of the "top level" method implementations look like:

* `World.getLightBrightness`:
  * `World.getLightBrightness(BlockPos)`
  * `World.getLightFromNeighbors(BlockPos)`
  * `World.getLight(BlockPos, boolean)`
  * `Chunk.getLightSubtracted(BlockPos, int)`

* `World.getCombinedLight`:
  * `World.getCombinedLight(BlockPos, int)`
  * `World.getLightFromNeighborsFor(EnumSkyBlock, BlockPos)`
  * `World.getLightFor(EnumSkyBlock, BlockPos)`
  * `Chunk.getLightFor(EnumSkyBlock, BlockPos)`

* `ChunkCache.getCombinedLight`:
  * `ChunkCache.getCombinedLight(BlockPos, int)`
  * `ChunkCache.getLightForExt(EnumSkyBlock, BlockPos)`
  * `ChunkCache.getLightFor(EnumSkyBlock, BlockPos)`
  * `Chunk.getLightFor(EnumSkyBlock, BlockPos)`

**Comment by bs2609** [comment]
Having had some more time to look at this, I think it's better to patch the lower-level `Chunk` functions here - this reduces the amount of patching needed and ensures more consistent behaviour.

**Comment by bs2609** [comment]
As an update, to prevent issues, `World.getLightFor` is patched to call `Chunk.getLightForBody` directly during lighting checks so that `World.checkLightFor` (and by extension `getRawLight`) see the underlying data values. This is to ensure that light updates can reach a consistent state.

**Comment by bs2609** [comment]
Quick example screenshots:

Day:


Night:


With block light:


Just using a simple `NoiseGeneratorSimplex` instance, feeding it scaled x/z coordinates:
```java
public int getLight(net.minecraft.world.chunk.Chunk chunk, EnumSkyBlock type, BlockPos pos)
{
	if (type == EnumSkyBlock.SKY) return getCustomSkylight(pos);
	return chunk.getLightForBody(type, pos);
}

public int getEffectiveLight(net.minecraft.world.chunk.Chunk chunk, BlockPos pos, int skylightReduction)
{
	int sky = Math.max(getCustomSkylight(pos) - skylightReduction, 0);
	int block = chunk.getLightForBody(EnumSkyBlock.BLOCK, pos);
	return Math.max(sky, block);
}

private int getCustomSkylight(BlockPos pos)
{
	double val = noise.getValue(pos.getX() / 16.0, pos.getZ() / 16.0);
	return (int) Math.round(val * 5.0 + 10.0);
}
```

**Comment by williewillus** [comment]
bump on this: some dimension mods really struggle with skylight (but would look way too dim if it were disabled), so this allows us to set a constant brightness and have it be both non laggy and visible

**Comment by mezz** [comment]
Looks good to me.
I tried to find a better way to do this but this seems pretty straightforward when you get down to it. I was kind of reluctant to throw more indirection into the already-slow lighting pipeline but it doesn't seem to have a real negative effect on fps as far as I can tell.

**Comment by Player3324** [comment]
There are IMO several issues with this PR:

1) The approach seems odd, it's disabling skylight propagation somewhat, but not completely and on a very low level. I'd rather expect something that works near the hasNoSky checks and doesn't change the low level vanilla code.

Inside the blocks guarded by WorldProvider.hasSkyLight, it should check whether another flag WorldProvider.hasCustomSkyLight is set and delegate all the initial/gap/setblock light updates to alternative implementations on the world provider. If it isn't set the behavior remains unchanged from what it was before. The WorldProvider can't reuse the vanilla light propagation code for reasons stated below, but a slightly modified copy of it.

2) I doubt this handles all cases, World.checkLight and others make specific assumptions about how skylight propagates through Chunk.getLightFor when it hits null ExtendedBlockStorage instances. There are presumably also broken interactions/assumptions regarding the height map.

3) The changes are very invasive and harm performance on some very hot paths for both vanilla-WorldProvider light updates and chunk redraws. Observing the FPS is not remotely a suitable benchmark, the affected code doesn't execute much in the render path or during steady state. Measuring chunk rebuild times is more appropriate. The environment under test has to represent the worst case with mega-morphic calls to the WorldProvider methods, i.e. multiple different WorldProvider classes with overrides those methods being used.

4) It's generally advised to limit the overhead of corner case hooks by gating them behind a non-virtual call to a final method or a field read and calling the common case directly instead of e.g. funnelling that through WorldProvider as well.

5) The suggested application of providing a certain minimum light level isn't particularly elegant. This can be achieved more easily/cleanly/faster by changing the light map texture to be brighter on the low skylight end - vanilla does that to brighten the nether.

6) Some recent Twilight Forest profiling data implies strongly that it isn't actually suffering from slow skylight propagation, but a bug that prevents the skylight initialization from running in the first place. Handling lighting in mod code is just a workaround.

This initial calculation is one-off per chunk and behind a persisted flag, so only happens after the initial generation. Profiling however shows that initialization is being tried continuously and aggressively and most time being spent on checking whether chunks are loaded - not actually doing light calculations. The reason why these attempts happen is unknown at this point.

Considering all this I advise against the proposed feature until further investigation shows a definitive need, but especially the proposed implementation is questionable. I'll see what I can do about helping debug the issues at hand.

**Comment by mezz** [comment]
@bs2609 can you address Player's concerns?

**Comment by bs2609** [comment]
Hopefully this addresses the main points. If there's some confusion about what's intended here, I hope this clears things up somewhat.

* 1 (and 2): This is intended to provide a way to alter/substitute the lighting values as they are read, it's not intended to alter vanilla's lighting propagation logic, or affect cases where lighting is written. The only way here to alter that is by overriding `hasSkyLight`, which already exists, and is not changed. The hooks are bypassed during light checking, and as far as I'm aware the heightmap only considers the block's opacity.
If you have a specific situation in mind where you think this does affect vanilla lighting, I'll try to fix it.

* 3 (and 4): Performance for light updates shouldn't change, as no redirecting is done in those cases already. For chunk redraws, this could be an issue - if you feel that changing the way the hook works would lead to a measurable performance improvement, I'd be happy to do so. Would something like a `public final boolean` method accessing a protected field be ok? Then either the `WorldProvider` method or the underlying `Chunk` method can be called depending on the result.

* 5 (and 6, slightly): I didn't make that suggestion as a use case. Changing the lightmap will work for some things, but it can't provide anything other than uniform flat sky lighting - it just changes how that looks. The intent here was to allow for simple position-based lighting changes. As an example, making a biome that is "always day", or "always night". As it is, this is not intended to be a way to fully replace vanilla's lighting implementation.

As an aside, you can see [this gist](https://gist.github.com/bs2609/13a4ae146a47348f84892f8c0bcda7c4), which is probably more related to what was suggested. I was looking at that while working on this, but I don't really consider it to be equivalent - it's its own thing.

**Comment by Player3324** [comment]
My points 1, 3, 5 and 6 are hinting at the odd scope of this change. The possible application space is quite limited by keeping vanilla light propagation and binding the feature to the world provider. More specifically it's only really usable by a mod that provides its own dimension. Alternative approaches/tricks like blocking skylight with invisible blocks at y=255, modifying the light map, spawning invisible artificial blocklight sources etc. further challenge the usefulness and are less invasive.

I doubt the intent to use this as some means to better performance as described in the second comment is likely to play out. For other use cases I'd be a lot happier if they weren't hypothetical or only "nice to have". Changing anything around MC's lighting is quite touchy and [my own work](http://files.player.to/tmp/java-64.png) stresses both light propagation and the getCombinedLight path much more than vanilla.

Regarding the performance optimization the suggestion is fine, pretty much like WorldProvider.getHasNoSky(), except that getHasNoSky lacks the final modifier at this point. Without final the benefit disappears quickly if someone decides to override the method instead of writing the field.

**Comment by bs2609** [comment]
Couple of small points:

> More specifically it's only really usable by a mod that provides its own dimension.

See #4692.

Also this:
> The possible application space is quite limited by keeping vanilla light propagation

is in part due to this:
> Changing anything around MC's lighting is quite touchy

It's a tradeoff - this is a difficult area.

**Comment by Player3324** [comment]
Replacing a foreign/vanilla world provider isn't a solution, only a single mod can do this without universally unresolvable conflicts.

**Comment by mezz** [comment]
@sfPlayer1 could you take another look at this?

**Comment by Player3324** [comment]
I believe the current revision is good on a technical level, the usefulness of the feature itself remains questionable however. What is the concrete non-hypothetical application?

**Pull request closed without merging**
