### PR TITLE
1.20.x ForgeConfigSpec revisit

### PR DESCRIPTION
**Pull request by SrRapero720**
thats a collection of changes for ForgeConfigSpec, just to enhance it with some additions

### CODE REVIEW

**Comment by LexManos** [comment]
What is the use of FloatValue vs DoubleValue?
Also MapValue isn't used, and has issues with toml style layout. What are you wanting to use that for?
All the other 'fixes' are just automated code 'cleanup'. Which doesn't really matter.

**Comment by SrRapero720** [comment]
> What is the use of FloatValue vs DoubleValue?

Only purpose was avoid downcasting `java.lang.Double` to `double` and then cast to `float`
you cannot directly cast `java.lang.Double` to `float`
image

> Also MapValue isn't used, and has issues with toml style layout. What are you wanting to use that for?

Thats why i keep this as a Draft, i was looking on `nightconfig` capabilities and i discover it has not support for Map's
i add it just blueprinting any "MapLike" config, but yeah is not doing nothing ATM until i figure out the most optimal way to support `Map`s without really support `Map`s

> All the other 'fixes' are just automated code 'cleanup'. Which doesn't really matter.

Yep

**Comment by SrRapero720** [comment]
i decide to stop from where i was.
i want to backport this, so breaking changes is outside of this PR scope

## SUMARY
- Added FloatValue, ByteValue and ShortValue
- Added primitive cache fields on primitive values + methods with primitive returns (see [Autoboxing](https://docs.oracle.com/javase/1.5.0/docs/guide/language/autoboxing.html))
- Added method to get Ordinal on EnumValues
  - Justification: Allows you to use ForgeConfig directly on render methods with no performance impact (specially if your mod is full client-side rendering based.
- Addec ConfigUpdateHandler, with the only purpose to notify any changes on config values using `ConfigValue#set()`
- Removed hell spaces on brackets
- Usage of Java 17 features (such as `if (specValue instanceof Config specConfigValue) {`)
- Basic cleanup

**Comment by SrRapero720** [comment]
my first intention was add support of ``Map<String, String>`` using a ``List<>`` and custom parsers to store maps as list values (such as `key_string[;]value_string[;]`) but might be a bad idea and honestly looks horrible and no very well understandable

**Comment by SrRapero720** [comment]
i will add some extra changes, but not hard breaking

**Review by PaintNinja — CHANGES_REQUESTED** [review]
There's too many vaguely related features in this one big PR. Please split it up into smaller PRs.

As for getting ordinal on EnumValue directly for render methods, this isn't recommended for performance reasons. You should instead read the enum ordinal from the config once and store it in a static final. You can use the deferred holder class idiom to achieve this in a way that only reads the value on first use:
```java
record MyEnumThing() {
    static final int ORDINAL = ENUM.get().ordinal();
}
static int getEnumThingOrdinal() {
    return MyEnumThing.ORDINAL;
}
```
This allows the JIT to properly inline the value from the start.

**Comment by PaintNinja** [comment]
Labelled as a breaking change because this PR promotes a userdev-only error to also happen in production

**Comment by SrRapero720** [comment]
marked as draft until i have time to address everything

**Comment by Jonathing** [comment]
It looks like this PR has gone stale. Are there plans to resume working on this?

**Comment by SrRapero720** [comment]
this PR was already merged, except the primitive catching (#9947 ). this PR is just redundant

**Pull request closed without merging**
