### PR TITLE
Add Fluid capability (master branch)

### PR DESCRIPTION
**Pull request by mezz**
Updated version of https://github.com/MinecraftForge/MinecraftForge/pull/2923 that points to the master branch.

### CODE REVIEW

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by LexManos** [comment]
@mezz Takes full responsibility for anything that breaks, yell at him.

**Comment by DiMuRie** [comment]
Hahah lol........

**Comment by CovertJaguar** [comment]
Can't be any worse than the current state of Railcraft's fluid handling code. My own attempt to add support for IFluidItemContainer has been less than smooth. ;)

**Pull request merged**
