### PR TITLE
Change universal bucket support to use fluid names instead of instances

### LINKED ISSUE #4863: Logic error with registering for buckets when having duplicate fluids from different mods
"If you have a fluid you don't need to be bucketable, and another mod has the same fluid that needs to be bucketable, YOU must also make buckets for your fluids or the OTHER mod will fail."

The bucket registration is for specific fluid objects, not fluid names. However, mods have to rely that a specific fluid name has a bucket (e.g. when their own fluid loses the election) and the bucket stores the fluid name in its nbt, only. Therefore the bucket fluid list should be fluid names, not fluid objects.

As a side effect of the current implementation, the getter for the bucket fluids will contain many un-identical duplicates (different fluid objects for the same fluid).

TL;DR: `net.minecraftforge.fluids.FluidRegistry.bucketFluids` should be `Set<String>`, not `Set<Fluid>`.

### PR DESCRIPTION
**Pull request by bs2609**
Resolves #4863.

Any thoughts on what to do with `getBucketFluids` - should it be deprecated to be removed/replaced, or left as-is?

### CODE REVIEW

**Comment by liach** [comment]
How about the previous code that modifies the list of fluid in bucket by directly modifying the fluid set?

**Comment by bs2609** [comment]
There isn't any code that does that though?

`getBucketFluids` returned an immutable copy - it doesn't allow modifing the registered fluids.

**Comment by liach** [comment]
That would be good. :+1:

**Review by liach — APPROVED** [review]

**Comment by LexManos** [comment]
Honestly should cache the immutible sets. They can be updated in the backend. Prevents the performance hit of making the new copy every access.

**Comment by bs2609** [comment]
Implemented similarly to the `fluidBlocks` map.

**Pull request merged**
