### PR TITLE
[1.16] Fix being unable to add a custom fluid to vanilla milk buckets

### PR DESCRIPTION
**Pull request by KnightMiner**
Same as #6795, but for 1.16. Description copied below:

----

Forge currently provides a fluid bucket wrapper that adds fluid support for vanilla buckets. However, on the milk bucket the wrapper does not properly work as Forge provides no milk fluid, and unlike in 1.12 there is no longer a global name for milk (#6769). This pull request removes the milk bucket wrapper as Forge has other systems in place that can meet the same need as that code was intended to meet.

To demonstrate the way modders can accomplish a custom milk and to make sure my changes work, this PR adds a test mod that adds a milk fluid and makes the milk bucket support it. You can test picking up milk by using `/setblock ~ ~ ~ milk_fluid_test:milk_block` then picking it up with a bucket. If you enable the fluid handler wrapper in the test mod, you can then right click the bucket and it will return the contained fluid.

### CODE REVIEW

**Review by TheCurle — APPROVED** [review]
Looks good, and a quick fix for a well requested feature

**Comment by ichttt** [comment]
Can you explain a little more why this code was there to begin with and how it is stopping modders to add milk. Is this allowing modders to register a new milk item with the properties of vanilla milk, or overwrite the vanilla milk item?

**Comment by KnightMiner** [comment]
In 1.12 and before, fluids were not namespaced, so it made sense that any mod with a custom milk fluid would be registered as `milk`. Forge took advantage of this and special cased the vanilla milk bucket to return `milk`.

1.14+ has namespaced fluids, so there is no longer one sensible option. However, whoever ported the milk bucket patch decided that fluid buckets should fill from `minecraft:milk` (where mods should never register), and drain as `Fluids.EMPTY` (which makes the whole wrapper useless, this part is due to a lack of case for the milk bucket, in part because there is no sensible choice)

The introduction of capabilities as opposed to the old fluid container system means is now trivial for us to add our own fluid capability to the milk bucket to return our fluid. That is, it's trivial if it does not already have one. In the case of the milk bucket, since Forge added one (which as I said before is currently useless), it takes precedence over anything a mod could add. Thus, if you want to empty a milk fluid from the vanilla milk bucket, your only solution is a registry substitution on the vanilla item.

For the record, I explained most of this in the linked issue #6769 already. Not sure why this was marked "Work in progress" asking me to reiterate it again.

----

This PR is entirely about adding custom capabilities to existing containers, it has nothing to do with removing potion effects or other milk properties.

**Comment by TheCurle** [comment]
This PR is ongoing, and needs further discussion with @KingLemming and the community to see if this feature is more useful over #7294.

**Comment by KnightMiner** [comment]
#7294 was merged as the preferred solution, so closing this.

**Pull request closed without merging**
