### PR TITLE
[1.19.x] Fix fish swim not in custom liquid

### PR DESCRIPTION
**Pull request by MrScautHD**
This PR fix, fish can not swim in Custom Fluid

### CODE REVIEW

**Comment by TheCurle** [comment]
That image is way to dark to see anything.
Please explain what this PR actually does, and the problem it intends to solve, rather than a vague almost perfectly black image that describes nothing.

**Comment by MrScautHD** [comment]
> That image is way to dark to see anything. Please explain what this PR actually does, and the problem it intends to solve, rather than a vague almost perfectly black image that describes nothing.

updated

**Comment by TheCurle** [comment]
That doesn't help anything. You've posted a picture of some fish.

**Comment by DaemonUmbra** [comment]
Is the image intended to show the issue or proof that the fix works?

**Comment by MrScautHD** [comment]
i updated the text too

ah yea the pic is before the fix

**Pull request closed without merging**
