### PR TITLE
Add Tools, Weapons, and Armor Tags the correct way.

### PR DESCRIPTION
**Pull request by chorman0773**
Fixes previous PR, which added the tags manually, to now generate them automatically, with advice from reviewers.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Are there any spots in vanilla code that should reference these tags? We might also want to add some code that overrides loot tables (e.g. checking for shears)

**Comment by chorman0773** [comment]
I'll check over that as soon as I'm done with my lab in class. Thanks for mentioning it. It would certainly be useful to override some code in vanilla to use these forge tags.

**Comment by chorman0773** [comment]
I've inserted appropriate overrides in the code (just waiting on genPatches before commiting and pushing), however looking through the code that generates the vanilla loot tables, I am not confident in my ability to succesfully modify that. I will continue to look into this, and may submit it later.

**Comment by chorman0773** [comment]
It seems I am unable to run the tasks necessary to commit the overrides, so I am going to leave the pr as is. If someone else is able to create the overrides, that would be much appreciated.

**Comment by tterrag1098** [comment]
Can you post at least the changes you made?

**Comment by chorman0773** [comment]
The changes requested were contained to vanilla. I'm not sure how to manually create the patch files, and generating the patches required running a task which seems to throw OutOfMemoryError on my computer.

**Comment by tterrag1098** [comment]
I mean, use your IDE to create diffs of the source files, or at least describe what you did...

**Comment by chorman0773** [comment]
I modified the condition on Line 75 of net.minecraft.block.TripWireBlock to test isIn(Tags.Items.SHEARS) rather than comparison with Items.SHEARS,
 and made a similar modification to Line 23 of net.minecraft.block.PumpkinBlock. These were the only occurances of a reference comparison which made sense to change to a tag check. I was not able to add generators for the LootTables, as I was not able to determine a method of doing so, without regenerating all the vanilla loot tables into forge (the method used for Recipies is not compatible with the system used for generating Loot Tables). I will continue to look into that problem specifically.

**Comment by LexManos** [comment]
If you run into OOM errors in genPatches, provide the log and extra details {system specs, amount of ram allocated, etc} genPatches should be simple enough that even 1GB of ram can process it.

**Comment by issork** [comment]
I already had a similar PR to yours open here; https://github.com/MinecraftForge/MinecraftForge/pull/6236, also based on your initial attempt to implement those tags.

There are a few differences between our PRs, here are my thoughts;
- crossbows and bows shouldn't be under the same "bow" tag IMHO, they need their own "crossbows" tag - they have different enchantments, are used in different recipes etc.
- my PR contains all of the tools/weapons/armors materials as they were present in your initial suggestion, why were they removed?
- shields should be added to the armor tag

**Comment by chorman0773** [comment]
I had bows and crossbows together because the way I classify tools has them together, though there is no reason why the cannot be separated (I would simply note that they should be merged at some level, though having a layer of distinction could be beneficial.
As for why tool materials were removed, I decided that the specificity was not necessary, especially for vanilla tool materials. However as a counterpoint to that decision, mods could add custom tools using vanilla materials.
As for the final point, I disagree. The wearable tag subsumes the armor tag, and shields are not wearable. For example, you can’t put curse of binding on a shield and have it bind to the offhand slot. Additionally, protection-like enchantments may use the armor tag to decide if the enchantment is applicable, and shields aren’t valid candidates for such enchantments.

**Comment by issork** [comment]
Yes, separating them under the ranged weapons tag would be great. The thought regarding the tool/armor materials also crossed my mind. But since mods like Mo'Creatures added variants of the leather armor (or all the gem/metal tools from other mods), I thought it would be useful for some kind of tier indicator. Theres no wearable tag in this PR, if there is in your local repo it does make sense to not have the shield in there. It's something for a new tag then.

**Comment by chorman0773** [comment]
Yeah that seems good. On wearable, I thought I did have a wearable tag in this pr. I might have forgot it. This was derived from a datapack I’m working on the divides items in this way (though has a few more divisions then I provided), and it has a wearable tag. That could probably be added to both imo.

**Comment by chorman0773** [comment]
I'm going to work on porting this forward to 1.15, though the 1.14 version can still follow through.

**Pull request closed without merging**
