### PR TITLE
Added McVersion appendix to jars

### PR DESCRIPTION
**Pull request by AbrarSyed**

### CODE REVIEW

**Comment by matthewprenger** [comment]
Only problem with this is how the maven plugin treats the appendix in repositories. Not sure if having the Minecraft version as part of the artifact id is a good thing.

**Comment by killjoy1221** [comment]
I've been doing this forever. +1

**Comment by LexManos** [comment]
Usually just have it be the official version. Not an appendix....

**Comment by AbrarSyed** [comment]
cpw wants it out of the version field because semver.. had a nice debate as to where to put the MC version

**Comment by LexManos** [comment]
The version internally can still be semver. Hell you could just prefix it for this exact task. like you're doing with the appendix. The goal tho is to have it in this position in the file name. And really only in the file name.

**Comment by matthewprenger** [comment]
What I do that seems to work well is: `[jar, shadowJar, sourceJar]*.version = "$minecraft.version-$project.version"`. That way the project version stays semver compatible, but the artifact versions include the MC version.

**Comment by cpw** [comment]
Lex, the version is populated into the mcmod info file by default. Anyone copying boilerplate to populate a version from gradle into their mod will get this by default. They will fail semver tests I'm implementing as a result. It seems stupid that the primary thing we advocate for a version scheme, soon to have actual code implications, is something we do not adhere to in our primary example.

**Comment by LexManos** [comment]
I thought we had it in our primary example.
We should fix that.
And im fine with doing it in some way that is okay with whatever you plan on implementing.
However, simplest solution:
Add MC version to version:
In Forge: if (version.startsWith(mcVersion+"-")) version = version.substring(mcVersion.length() + 2)
Horribly hacky but works. Also the main reason this is important is to keep the MC version number in a visible place, the file name. If you find a solution you like that isnt being fubared by maven being stupid that'd be cool.

**Comment by cpw** [comment]
What is maven doing with the appendix then? I see you complain that the appendix is bad, but why?

**Comment by Lunatrius** [comment]
He's probably referring to the following:
```
repo/forgetest/ForgeTest-1.8.9/1.2.3/ForgeTest-1.8.9-1.2.3.jar
                        ^^^^^^
```

**Comment by LexManos** [comment]
Yes, it makes it into a different artifact. That is not good.
Matt's solution may be possible. Except we want domain/artifact/mcversion-version/artifact-mcversion-version.ext
Thats how everything in Forge's servers, and the few parts forge cares about it is meant to read.
Patching it in the version itself shouldn't be an issue. As I said we can easily just make FML ignore the MC part.

**Comment by AbrarSyed** [comment]
How about:
```
def modVersion = "1.2.3"

minecraft { .... }

version = "${minecraft.version}-$modVersion"
```

**Comment by Lunatrius** [comment]
Couldn't you add `modVersion` as project property and set `version = <mcVersion>-<modVersion>` as the default in FG (and set the `mcmod.info` version to `modVersion` instead)?

**Comment by AbrarSyed** [comment]
An extra level of backbend magic that I would left not to add. But yes, is within the realm of possibility

**Comment by cpw** [comment]
Don't bother. I can't be bothered to argue this point. We'll be not semver instead, because its obviously too difficult to adhere or advocate any sensible standard..

**Comment by LexManos** [comment]
Abrar, prefix MC version to project version.
We'll deal with the semver issues internally when they arise.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
