### PR TITLE
OBJLoader Updates

### PR DESCRIPTION
**Pull request by shadekiller666**
-Added support for UV processing.
-Added group visibility configurations.
-Added and removed test blocks to better utilize the new system.

-Reworked many of the classes in OBJModel to make the baking process more sane.

-Fixed incorrect String.split() operation in OBJModel.Parser.parse() that prevented the use of vertex indices > 9 if no vt indices were defined. Closes PR #2338.
-Fixed inconsistent caching in OBJLoader. Closes PR #2361.
-Fixed .mtl file parsing code to trim() the current line before processing it. Closes PR #2377.

-See example blocks in ModelLoaderRegistryDebug.java and the corresponding blockstate jsons and model files.

### CODE REVIEW

**Comment by williewillus** [comment]
Probably should note if any things are not backward compatible here or in the examples or somewhere

**Comment by shadekiller666** [comment]
As far as I know, most of the code that has been written based on the current version of the OBJLoader (the released version) should be backward compatible. The parts that will likely have to be changed include: setting group visibilities and/or material color via OBJState; the likeliness of having to change is not 100%. The group visibility handling is the most "visible" (to mod code) part of the changes.

**Comment by williewillus** [comment]
Okay, so the json will all be okay? I feel like we've told many, many people to do "flip-v": true and if we remove that things aren't gonna look good :p

**Comment by shadekiller666** [comment]
Yep, jsons should be fine. I made sure to have "flip-v": true be recognized to not break backward compatibility.

**Comment by grondag** [comment]
Maybe I'm just old-fashioned, but is it constructive to describe these changes as "more sane?"  Any code is cleaner after a refactoring pass, that's why one refractors, but getting it to work the first time is no small feat.  Given the huge contributions Fry has made in building out the rendering capabilities in 1.8, a PR that seems to imply his work was not "sane" just rubs me the wrong way.

Not saying these aren't useful changes.  My comment is on the messaging. I wasn't going to mention it, but I read this a second and it still bothers me.

**Comment by williewillus** [comment]
Its just coder slang for "cleanup" :p
And plus shade wrote the obj loader so he's actually making his own stuff more "sane"

**Comment by BluSunrize** [comment]
Yeah the OBJ stuff is Shade's code as far as I'm aware, and this is basically adding the necessary features it currently lacks, like the ability to set visibility for certain groups.

**Comment by grondag** [comment]
In that case,  I retract my remarks completely.  Programmers crapping on their own code is a time-honored tradition and an effective prophylactic for mental health.  I do appreciate the clarification.

**Comment by BluSunrize** [comment]
@shadekiller666 anotehr possible issue I have noticed is the use of the OBJProperty. Basically when it is applied, the block seems to disregard any other translations and rotations applied through, for instance, an EnumFacing property. @RainWarrior can probably explain this a lot better than me, but the general gist of it is that these modifications are forgotten about during "handleBlockState" in the OBJBakedModel, meaning that rotations and showing+hiding parts doesen't seem to like to work together :/

**Comment by shadekiller666** [comment]
@BluSunrize, this is an issue that ive noticed but hadnt confirmed. I dont think that OBJProperty is the main issue, but could be a part of it, I will look into this and see what I can do.

**Comment by BluSunrize** [comment]
The handleBlockState seems to disregard previous properties assigned, instead starting with the default again. The B3D methods apparently don't do this, though I haven't used B3D so I can't confirm =P

**Comment by williewillus** [comment]
@RainWarrior any update on this?
Specifying group vis without needing code is pretty useful (imo needed)

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
