### PR TITLE
1.16 Fix datagen resolving tags and exploding.

### PR DESCRIPTION
**Pull request by Cyborgmas**
Datagen is currently not working because of an issue with tags (#6857)

From what I understand, the problem is because forge uses actual Tag references in datagen, where vanilla does not. Therefore, vanilla does not generate/update tags.
The way vanilla does it (when running server/client) requires the tags to be there as files ofc and I mimic that somewhat. That is why all the tags have been added. this could be completely wrong though... would require another way to load/manage tags. 

There also was a crash due to now improper reflection in Ingredient, so fixed that.
I also added the clean_data task, was useful to debug stuff, and fixed clean_server as well. 

This is not complete at all. Datagen is running without crashing but it seems to be generating stuff incorrectly.
If anyone can submit tests, I would appreciate it.

### CODE REVIEW

**Comment by pupnewfster** [comment]
This PR is adding a lot of files in `src/main/resources/data` but I believe forge's data generator is supposed to target `src/generated/resources/data`

**Comment by Cyborgmas** [comment]
yeah, but those are not the result of datagen. that are tags needed to make it work. will try to find a workaround because its prob unecessary

**Comment by Cyborgmas** [comment]
Okay, so after a bit more debugging found out that the problem lies in the creation of an Ingredient, forge has an isSimple field that gets every item of the ingredient. when its a taglist ingredient it tries to get the items the tag contains and fails since it was not updated.

**Comment by Cyborgmas** [comment]
Okay, so the isSimple field is not used during datagen (only used if a recipe matches) so i force it to false when running datagen. 
the furnace recipe got deleted because vanilla now has a tag for it, called furnace_material 

The shears tag got deleted for some reason, will check why.

**Comment by pupnewfster** [comment]
My guess is the code behind the shears tag might not have been properly ported due to it getting merged into the 1.15 branch in the final pass before 1.16 was released.

**Comment by Cyborgmas** [comment]
okay just re-added.

**Comment by williewillus** [comment]
Would be great to have this merged, our datagens can't run at the moment as a result of this.

**Pull request merged**
