### PR TITLE
Make EnumFacing events available server-side

### PR DESCRIPTION
**Pull request by rubensworks**
See #2036

### CODE REVIEW

**Comment by liach** [comment]
Is it save and compatible, not crash-causing?

**Comment by rubensworks** [comment]
I tested in both single- and multiplayer, everything seems to work just fine.
There shouldn't be any reason for it to cause crashes I think, it just adds some methods server-side that were previously only available to the client.

**Comment by DanielHuisman** [comment]
Have you tested it outside the development workspace?

**Comment by rubensworks** [comment]
@DanielHuisman Yes, it works in an obfuscated environment outside of eclipse.

**Pull request merged**
