### PR TITLE
TileEntityType: Allow registration via passing an ImmutableSet directly

### PR DESCRIPTION
**Pull request by hanetzer**
Lex was showing me another way of going about this with Suppliers and ResourceLocations,
but as I didn't really understand the subject matter I could not keep up with the edits. This was
my original idea.

### CODE REVIEW

**Comment by diesieben07** [comment]
I am not quite sure which problem this solves.

**Comment by hanetzer** [comment]
[SmelteryBlocks.java#L85](https://github.com/SlimeKnights/TinkersConstruct/blob/bf61f051600f7bbf637ac4d62fa8065f0822d87a/src/main/java/slimeknights/tconstruct/blocks/SmelteryBlocks.java#L85) [SmelteryTileEntities.java#L27](https://github.com/SlimeKnights/TinkersConstruct/blob/1.15/src/main/java/slimeknights/tconstruct/tileentity/SmelteryTileEntities.java#L27)

We create a ImmutableSet of valid smeltery blocks in the first link, used to do the
multiblock creation logic, and in the second one we pass 36 different suppliers to
the TE reg code (12 block variants, fullblock, slab, and stairs variants). With this
commit we could just pass the one ImmutableList.

**Comment by KnightMiner** [comment]
We can just pass an immutable set as the set, it implements set afterall

**Comment by hanetzer** [comment]
> commit we could just pass the one ~~ImmutableList.~~


> We can create an immutable set just as easily.

Typo. ImmutableSet

**Comment by KnightMiner** [comment]
My point is, there is no reason we have to use the builder, we can pass the set directly into the constructor as that appears to be public. Fewer Forge patches needed then, especially for something few people will use.

**Comment by hanetzer** [comment]
I have no idea why I didn't even see that. That is a valid option, as far as I can tell.

**Pull request closed without merging**
