### PR TITLE
Add Block Breaking Animation for ISmartBlockModels

### PR DESCRIPTION
**Pull request by fuami**
Seems when ISmartBlockModel was added someone forgot to handle the breaking Animation.

### CODE REVIEW

**Comment by RainWarrior** [comment]
ForgeHooksClient.renderLayer behavior should be taken into consideration - it should at least be set to null, if nothing else

**Comment by fuami** [comment]
Possibly, I'm not overly familiar with the 1.8 rendering system.. I've only been trying to make a mod with it for a few days, You wrote the original ISmartBlockModel PR; I Believe?, you are most likely considerably more knowledgeable about it then I am.

I set the layer to null, and the the pass to 0, this might be a reasonable state for this, without adding some additional layer.

**Comment by AlgorithmX2** [comment]
I'm pretty interested in getting this PR approved so I can take advantage of it.

I asked Fry about getting this pulled and was told that "setRenderPass is probably unnecessary" and "Add a test mod, checking breaking animation and layer interaction"

For the test mod probably just a block that renders stained glass and cobble at the same time in the two layers.

**Comment by fuami** [comment]
I added a test mod with layers and solved the issues with the layered smart model, I think this should be acceptable?

**Comment by RainWarrior** [comment]
Remove whitespace from empty lines in the patch, and move example mod into the debug folder. Other that that looks good.

**Comment by fuami** [comment]
Okay, should be good now?

**Comment by RainWarrior** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1868/files#diff-bee7ba79487aeb9ab15c1c8e0d274e24R2

**Comment by fuami** [comment]
Ok, serious this time.

**Pull request merged**
