### PR TITLE
Add hook to load custom mrls/rls not attached to a block or item. 

### LINKED ISSUE #5667: [1.14.x] Add way to say "Please load and bake this model for me"
Models are automatically loaded and baked if they're part of a block or item or item json override, but otherwise MC does not touch them.

Before, this could be hacked around by passing extra unrelated MRL's along with an item to `ModelBakery.registerItemVariants`, but that's gone in 1.13 now.

For mods that load and use baked models that aren't tied to any specific block or item, it's useful for them to be able to say "please load and bake this model", similar to how you say "please load and stitch this texture for me" in `TextureStitchEvent.Pre`.

Mojang has a hardcoded line in `ModelBakery` line 311 for the trident_in_hand model, I just want a similar hook point right there so modders can add more models to load.

### PR DESCRIPTION
**Pull request by williewillus**
Closes #5667

Also deletes the old commented code in ModelLoader

### CODE REVIEW

**Comment by tterrag1098** [comment]
Why not have a callback for the model result?

**Comment by williewillus** [comment]
wdym?
if you mean "just expose the rl -> baked model map", that wouldn't do dependency resolution, texture loading and stitching, etc.

**Comment by tterrag1098** [comment]
`ModelLoader.addSpecialModel(MY_RL, renderer::setModel)`

**Comment by williewillus** [comment]
Don't see the point tbh, you can already pull the models out during `ModelBakeEvent` and passing the callbacks around until then would be more work than it's worth.

**Pull request merged**
