### PR TITLE
[1.14.4][Event]: LivingTotemEvent - Totem Handling and Intersection between DamageEvent and DeathEvents

### PR DESCRIPTION
**Pull request by Lanse505**
**What classes/methods does this event add?:**  
This event currently adds 1 event class, 1 method and 2 lines of patches.

**What purpose does this event fill?:**  
This event is created to not only allow handling of the Totem of Protection but also to help intersect the event chain between Damage Taken events and Death Events. This event similarly to the Totem Of Protection itself occurs in the state between the player taking lethal damage, and the player being handled as dead.

Essentially the place this occurs is:
Lethal Damage Taken > Totem Protection Check > Death Handled

And thusly allows people to intervene before the player is handled as dead but after the damage is taken.

**So what does this event provide in terms of capabilities?:**  
Well, it does a few things, let's start by establishing that this event is Result-based and such has 3 states it can inhabit. 

**Allow** = Provides a "hook-in" point for mods to provide event-based custom behavior for the totem event, for example, one can subscribe to the event, check if a player has their "totem" item or whatever you'd not want to check for. And then you'd do the handling and pass Result.Allow.

**Default** = Defaults to the vanilla totem of protection checking behavior, this means you don't insert any overwriting behavior and instead lets the vanilla method run its course. 

**Deny** = Denies all behavior and passes the event forward so the player just dies.

A lot of the functionality of this event is documented using JavaDocs with links.

**THIS IS WHERE THE IFFY OCCURS**  
For whatever reason I haven't been able to get test mods working on my dev environment, what so ever.
Neither on my 1.12 nor my 1.14 branches, so I haven't been able to validate the code myself.
Nothing I've done seems to have worked thus far, I've reached out to a few colleagues for validation.

However, I've had several members of the community chime in on the implementation, documentation, etc to make sure it's all compliant with forge contributing guidelines (outside of testing) and implemented in a way that the community would like for an event like this to work.

### CODE REVIEW

**Comment by Lanse505** [comment]
Shout-Outs to:
@TheCodedOne
@Jaredlll08
@PaleoCrafter 
@Buuz135
@SkySom
@Lyinginbedmon
@Funwayguy

**Comment by Lanse505** [comment]
Here's an image of my attempt at the test mod and also as an example of how it could be implemented:
image

**Comment by pau101** [comment]
Setting the result to "allow" does not clear active status effects and I'm not sure I see that being documented well enough. Currently that test mod wouldn't do so and I hope it would given trying to be a typical example.

**Comment by Lanse505** [comment]
Thanks for the feedback @pau101 
I'll compile a better example and make sure to address the clearing of active status effects on both PRs.

**Comment by pau101** [comment]
Perhaps by default "allow" would clear effects and there would be a function on the event to disable it.

**Comment by Lanse505** [comment]
@pau101 fixed the allow clearing stuff now.
I'll get started on a more up-to-date example :)

**Comment by pau101** [comment]
Oh that implementation prevents event consumers from adding effects now, they'll just be cleared as that occurs after. I would add a function to the event to add an effect and you can apply them all after.

**Comment by Lanse505** [comment]
@pau101 Is the current implementation better?

Also does this example suffice?
image

**Comment by pau101** [comment]
That looks good to me. I would however also extend documentation, instead of just putting javadoc on the internal private fields, it is more convenient to be present on the public methods.

**Comment by Lanse505** [comment]
I can do that, also going to be writing a second example that's a bit more "Realistic" instead of the above randomness 👍

**Comment by Lanse505** [comment]
Here's a second example for the giggles
image

**Comment by Lanse505** [comment]
@pau101 There we go, new JavaDocs added to the methods.

**Comment by LexManos** [comment]
No, you can already do everything you want with the combination of damage and death events.
This literally just adds yet another event 1 if statement above the death event.

**Pull request closed without merging**
