### PR TITLE
[1.14] Added Energy limit bypass overload

### PR DESCRIPTION
**Pull request by DarkGuardsman**
Try 3: Again this is open to discussion and I'm willing to make changes as needed.

Additional Pull to previous https://github.com/MinecraftForge/MinecraftForge/pull/5993

**Pull Itself**
The idea behind this change is to make it possible to bypass limit checks during energy receive and extract calls. While allowing the capability implementation to decide when and how this happens. See the previous pull request for reasons why. 

**Aditional Change**
Provided with this is also the ability to request that the energy capability return an exact match for the request. The goal with this change is for packet driven energy systems that only send or receive set amounts of energy. 

**Unit tests** 
All changes are provided with unit tests. I an add more as needed to bring up the class to 100% coverage.

### CODE REVIEW

**Comment by MajorTuvok** [comment]
I would not call adding **3** booleans simple... Sorry...
Why don't you want to think about a context sensitive energy System, compare for example my [comment](https://github.com/MinecraftForge/MinecraftForge/pull/6027#issuecomment-520182994)... We have enough time to discuss this before submitting 10 PR's, I think

**Comment by DarkGuardsman** [comment]
You can't get any simpler than a boolean in terms of implementation complexity.

**Comment by MajorTuvok** [comment]
You've got 3 of 'em which all need to be passed into this Method. Adding a default Method/overload to pass in default values would make this a little nicer to use, but it' s kind of awful in my opinion - let's see what others have to say about this

**Comment by MajorTuvok** [comment]
Also: no need to mark anything as deprecated, Forge is still in the breaking change phase

**Comment by DarkGuardsman** [comment]
> Adding a default Method/overload to pass in default values would make this a little nicer to use

That is a valid point and would remove the need for the deprecated.

**Comment by raoulvdberge** [comment]
I think converting the parameters to another "parameter class" would be more clean. You could then provide sensible constants of that class to avoid people making new instances constantly.

**Comment by MajorTuvok** [comment]
You could also add a Set of some context-enum to that Parameter class and you'd achieve the context goal again. Of course you could no longer provide all constants without a combinatoric explowion, but people who need the rarer configurations could just have constants of their own for that, if needed.

**Comment by DarkGuardsman** [comment]
@KingLemming can i get your input on this and the ideas in the above

**Comment by LexManos** [comment]
A constantly changing chain of booleans is not going to be accepted.
Enum/EnumSet is probably the way to go.

**Comment by DarkGuardsman** [comment]
I'll be impressed if anything I PR for energy system gets pulled at this point... but I'll take a look at an enum solution if that is preferred. I'm not going to go with what MajorTuvok suggests as that is a permutation nightmare. However, EnumSet or dot style array would work around this.

The only concern would be performance and memory churn. So I'll take a which look at setting something up to see the impact. The big challenge will be scaling for wires but this all might easily be solved with a cache field? Either way might be a bit before another PR as I have 3 interns to train.

**Comment by KingLemming** [comment]
Lex pretty much hit it. I'm looking into EXECUTE/SIMULATE/FORCE as a ForgeAction enum for capabilities as part of the fluid revamp right now. I think it should extend fairly easily to items and energy.

**Comment by DarkGuardsman** [comment]
Ya the previous commit that got instantly closed had coverage for items, and fluids as a class input. I can do the same for this with the enum set if that is ok. Though might wait until giga's fluid changes get pulled first and complete it in a second pass.

**Comment by DarkGuardsman** [comment]
I have an idea I'm going to toy with this week now that my interns are trained. What if instead of a set or array of enums we do a lambda? This would allow the caller implementation to handle the storage of the enum values in any ways they desire. Allowing for the usage an array, list, set, and even a simple boolean statement. It might also solve my concerns about complexity and memory churn. 

How it would work is using a functional interface with a single method `boolean requires(EnumName value)` that would pass in each enum during the processing of the request. For example a simulate check would be replaced with `if(enumFunction.requires(EnumName.SIMULATE))`.

Additionally this means we can also easily catch out common usage in our tiles or in a static location. As the code would be `public static final FunctionalInterfaceName SIMULATE = (value) -> value == EnumName.SIMULATE`

**Comment by LexManos** [comment]
That is a horrible idea, the point is to stabilize the API not make it random lambda soup.

**Comment by DarkGuardsman** [comment]
Then what are my options here. I've been shot down on all other ideas short of just passing in an array or enum set at this point. Which if I do will result in a performance hit and memory churn. The lambda offers the ability to customize how its handled, easily cache the data in any format, and solve the performance concern.

**Comment by MajorTuvok** [comment]
@DarkGuardsman the same is the case for the **very efficient** EnumSet... (which was proposed by Lex)

**Comment by DarkGuardsman** [comment]
I get EnumSets can be efficient if that is what you mean. I'm concerned with developers generating new ones as inputs each call. At least with a lambda if build per code block it would turn into a static method internally so wouldn't take a performance hit.

**Comment by DarkGuardsman** [comment]
Might help to see the WIP code I already have for this https://github.com/DarkGuardsman/MinecraftForge/blob/d379b64ec98e4ace7c74d9ea2dc7fafa3e29e5fe/src/main/java/net/minecraftforge/energy/EnergyStorage.java

**Comment by MajorTuvok** [comment]
I guess lex is referring to is that lambda's can make it harder to read (right?). Anyways Lex (<=> the Forgegod) said you shouldn't do that - so don't. 

Adding a comment that you should cache these if possible, should be sufficient. Those who do need to access the energy cap very often will certainly have read the docs/be already aware of the performance of too many Object Allocations. And if you only need it once in a while it wouldn't even be noticable.

**Comment by DarkGuardsman** [comment]
Problem is I don't see how a lambda is a worst idea then an enum set. As you could easily use an Enumset wrapped in a lambda with my solution if you wanted. Its literally a simple wrapper that could contain any logic and comes built out with common use cases cached. Would effectively work the same as if we had a single enum passed in for the calls. See the JUnit tests included for what I mean.

Honestly, I need lex to elaborate on what he means. As I don't want to write a 6th solution just to be told no when its not exactly what was imagined.

**Comment by raoulvdberge** [comment]
Lambda makes the API much more complicated. I don't see the problem with EnumSet? You can provide constants so a new one shouldn't be generated every call.

**Comment by LexManos** [comment]
why does it need to be a enum set?
Why not just a enum value?
How exactly do you see the the set being used? What does a set of 'simulate' and 'force' even mean? 

You lambda idea.. how would that look, what would it do, how would people use it?

Shows us your idea in code.

**Comment by DarkGuardsman** [comment]
I included a link to the in progress branch for what would have been the PR. It includes Unit tests showing how it would be used https://github.com/DarkGuardsman/MinecraftForge/blob/d379b64ec98e4ace7c74d9ea2dc7fafa3e29e5fe/src/test/java/net/minecraftforge/test/capabilities/EnergyCapTest.java

`storage.receiveEnergy(100, CapabilityEnergy.NORMAL);`

**Comment by DarkGuardsman** [comment]
To address the other questions. I rather avoid an enumset, it was an alt to using an array to pass in several values. As well to avoid looping over said array if we were to use a group of values. The reason for the group is the need to combine values. 

Use cases I have in mind for the current enum options:

Simulate with match exact -> check that the match will work
Math Exact -> packet based energy sending
Simulate -> What we do now
Normal -> Default
Simulate with bypass -> check that the bypass will work

In the future we might want to introduce more that I can't predict right now. Doing a single value means I can only do 1 action at a time. Rather than a combination of actions. 

Say for a random case I want to match exact, bypass limit, and simulate. This way I can pull 1000 value energy packet from a machine that only services 100. A single enum wouldn't work for this as it would need to be a permutation of the argument or lack the feature all together. 

Also in my current branch I'm using bypass limit rather than force. As this makes more sense for naming, and I am open to working on the names to reduce confusion.

**Comment by DarkGuardsman** [comment]
Pull request is not needed anymore as I no longer mod the game and lack the time to complete the updated request. Have fun everyone and feel free to use the code I have left on my fork.

**Pull request closed without merging**
