### PR TITLE
Clean up and unify most top-surface placement code

### PR DESCRIPTION
**Pull request by bs2609**
This aims to clean up and unify the code where the various uses of `IBlockState.isTopSolid` have been patched to provide additional context.

The intent here is to cleanly migrate away from the old `Block.isSideSolid` method while still keeping compatibility with vanilla behaviour.

### CODE REVIEW

**Review by tterrag1098 — APPROVED** [review]

**Review by mezz — APPROVED** [review]

**Comment by mezz** [comment]
This is a lot of patches so it makes me a bit uneasy.
I'm not sure how else we can properly unify this behavior though.

**Comment by tterrag1098** [comment]
This needs an update to resolve conflicts.

**Comment by bs2609** [comment]
This was updated a while ago, can it be re-examined?

**Comment by mezz** [comment]
I talked to Lex about this one, and there has to be a stronger need for it in order to justify the number of patches. 
If it is just cleanup, it's not really in scope. Hopefully Mojang has done some more cleanup in this area for 1.13+.

**Comment by bs2609** [comment]
To be clear, this PR adds only a single patch, to `Block`. All other locations are simply modifications to already existing patches.

While this is mostly cleanup, it also does fix Forge behaviour not matching vanilla in some cases, and this problem will be worse in 1.13 with the removal of `Block.isSideSolid` there.

**Comment by LexManos** [comment]
The problem is that this adds yet another function to block that is already covered in isSideSolid(UP).
The code cleanup is somewhat nice, but honestly it doesn't matter. 
However you claim that Forge and vanilla differen in some cases, articulate those and we can address them. This general thing is not good.

**Pull request closed without merging**
