### PR TITLE
[1.14.x] Replace vanilla recipes with forge tags for all current forge tags

### PR DESCRIPTION
**Pull request by Lykrast**
This simply extends `ForgeRecipeProvider` to do replacement with all current Forge tags (most notably dyes).

For consistency this also changes the nuggets <-> ingots <-> blocks recipes, though maybe that's not desirable (and that would require more changes since Anvils need Blocks of Iron so that would still need to be replaced).

It could also be useful to extend that to smelting recipes since they are also in json now, like for the various ores. I preferred not to mess with that though.

### CODE REVIEW

**Comment by Lykrast** [comment]
"Broken" for the same reason as #6016 after double checking.

EDIT: yup a random commit fixed the merge check!

**Comment by LexManos** [comment]
First, this PR is incomplete, you actually have to RUN it and include all generated json files.
Second, do not replace the nugget <-> ingot <-> block recipes as these are special recipes that could easily not want to be tagged. As you don't want arbitrary conversion of these items. That's why I had excludes for them -.-

**Comment by Lykrast** [comment]
> you actually have to RUN it and include all generated json files.

The data run doesn't like spaces in the path for the workspace (it makes a new folder). I can just move my workspace but it's a thing to note.

> do not replace the nugget <-> ingot <-> block recipes

~~Alright, but some recipes actually use nuggets or ingots (Anvil, Glistering Melon, Golden Carrots), and the current system can only blanket exclude inputs. Replacing the ingots currently also does the ingots -> blocks and ingots -> nuggets recipes.~~

~~I don't know enough about the recipes to make a "exclude recipe if it has this output" or "exclude this specific recipe" but it would fit better. I don't know which of those 2 would be the best. For now I'll just re exclude nuggets and blocks.~~

As I thought I misread the blacklist code. Now it includes the nuggets and blocks without changing the conversion recipes.

**Comment by Lykrast** [comment]
Will need to rebase or something then update with the new tags in 2c8c022034ba9967affc7ecf02dc6583f4f3652a. Will try this afternoon then edit this post once it's commited.

~~EDIT: I have the changes but somehow there are compilation errors on the forge so I can't generate the jsons. Don't know if it's on my end or just bad timing with the rebase but once it's fixed pr should be updated.~~

EDIT 2: it was on my end. Pr updated for new tags.

**Comment by raziel23x** [comment]
is this still relevant or was this dropped for a better solution?

**Comment by Lykrast** [comment]
From what I can tell from the current files and what I know, it's still needed if people want to make their leather/slimeballs/dye/... substitutes.

**Comment by Lykrast** [comment]
With 1.15 out that will need to be updated but I don't have the time yet to do that.

**Pull request closed without merging**
