### PR TITLE
[1.14.x] Add missing --existing argument to MDK data run (fixes #6322)

### LINKED ISSUE #6322: [1.14.4] Mod resources not loaded during data generation
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.90

**Logs:** https://gist.github.com/Choonster/2ee4d06856ca409f85b89728e9ddd47e

**Steps to Reproduce:**
 1. Create a class that extends `BlockStateProvider` and register it during `GatherDataEvent`
 2. In the `registerStatesAndModels` method, call `BlockStateProvider#simpleBlock(Block)` with a block belonging to the mod being developed.
3. The call to `ModelBuilder#texture` (in the methods called by `BlockStateProvider#simpleBlock(Block)`) throws an exception like the following: `IllegalArgumentException: Texture <texture> does not exist in any known resource pack`

See my [test mod](https://github.com/Choonster-Minecraft-Mods/ForgeBlockstateDataGeneratorTestMod) for a full demonstration of this.

**Description of issue:**
Mod resources aren't being loaded during data generation, so `ModelBuilder#texture` throws an exception saying that the texture doesn't exist for texture files that actually do exist.

### PR DESCRIPTION
**Pull request by Choonster**
This adds the missing `--existing` argument to the MDK's data run, allowing mod resources to be loaded correctly during data generation.

This fixes #6322.

### CODE REVIEW

**Comment by tterrag1098** [comment]
This is not correct, self referential data is not needed, and would only result in confusion (a file existing BEFORE data gen is run, and during, but not after). Just add src/main/resources

**Comment by Choonster** [comment]
@tterrag1098 In that case, what's the intended way to generate block item models?

**Comment by LexManos** [comment]
Using --existing, just not including the generated directory.

**Comment by Choonster** [comment]
@LexManos But how does the block item model reference the block model to use it as a parent?

I'm pretty sure that the `existingFile` method would only work if the generated resources are included in the `--existing` argument. I understand that this can lead to weird behavior as tterrag said, but I'm not sure what the alternative is.

Do we need to access the `ModelFile` instances created by the block model provider in the item model provider?

**Comment by LexManos** [comment]
You would use data that you generate, in your further generations, exactly how Forge/Vanilla does.
By keeping a list of files that you have already generated to flag as usable by further generators.
We have a class specifically for that.

**Comment by Choonster** [comment]
I'll have to look into that. I'll make the requested change tonight and figure out the proper way to generate the models later.

**Comment by tterrag1098** [comment]
Just feed the existing files on the code side rather than introducing nondeterministic resources.

https://github.com/Tropicraft/Tropicraft/blob/1.14/src/main/java/net/tropicraft/Tropicraft.java#L178-L180

**Comment by Choonster** [comment]
@tterrag1098 Thanks, I hadn't thought of re-using the `ExistingFileHelper`.

I've reverted back to the initial commit (i.e. only the first resources directory has an `--existing` argument). I'm looking up the resources directory from Gradle rather than hardcoding **src/main/resources**, let me know if you'd prefer the latter.

**Comment by Choonster** [comment]
I've implemented the requested changes, this is waiting on feedback from the Forge team.

**Comment by Choonster** [comment]
This is still waiting on feedback.

**Comment by LexManos** [comment]
I'd rather this be done via documentation instead of a default copypasta value.
As right now it's just a random array index that has no meaning.
It doesn't address WHY it's added and what it does.

**Pull request closed without merging**
