### PR TITLE
Change Block#toString to use getRegistryName instead of getNameForObject

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This allows blocks/items to be replaced by fixing the problems outlined in #5747

### CODE REVIEW

**Comment by bs2609** [comment]
Already covered by #5922.

**Comment by gigaherz** [comment]
Partially. The change in toString still has merit. I chose not to do that change in my PR because it felt out of scope, since the crash is already getting fixed by other means (fixing my bad code).

**Comment by bs2609** [comment]
I believe this is fully covered as far as its stated purpose is concerned (fixing #5747).

If there is a desire to "re-brand" this, then the other change can be persued here on it's own merits.

**Comment by Shadows-of-Fire** [comment]
Updated to only be the changed to Block#toString as the other change is completed in #5922

**Review by gigaherz — APPROVED** [review]
LGTM. 
For reference: this patch makes items show their intended registry name, such that if someone was holding an instance of the old block that was substituted, it will show its intended name instead of `minecraft:air`.

**Review by gigaherz — APPROVED** [review]

**Comment by Draco18s** [comment]
This would also fix issues where when there's a problem with a block registration the log doesn't complain about an invalid action attempted on "{minecraft:air}"

**Pull request closed without merging**
