### PR TITLE
[1.20.1] Prevent mixins from crashing the game when there are missing mods

### PR DESCRIPTION
**Pull request by embeddedt**
In FML versions post-modularization, mixins are still loaded even if there is a missing dependency. Unfortunately, said mixins can attempt to load missing classes (causing a crash), or attempt to access a field that was transformed by an AT, which will not happen when there are loading errors, also causing a crash.

This PR solves the issue by not allowing mod resources to enter the classpath at all, preventing the mixin configs from being loaded which restores the 1.16 behavior. Now, the loading error screen will be properly shown instead of the game crashing with some random `ClassNotFoundException` or `IllegalAccessError`. This issue was particularly aggravating for support Discords as users report a "crash" when it's really just that they haven't installed a mod.

I have made the PR against 1.20.1, as that's the version I was using for testing. The test case I used in production is to install the mod Supplementaries, version 1.20-2.7.14, *without* installing its dependency, Moonlight Lib. Without this PR, the game crashes with `ClassMetadataNotFoundException`. If I replace the fmlloader JAR with one from this PR, the game reaches the loading error screen.

You'll notice that this change is disabled in dev. This is to prevent dev environments using `--mixin.config` from crashing if there is a dependency error due to the mixin file no longer being found. The issue is only really a problem for production environments, where users do not know to read their log and find the missing dependency error.

This change should be applied to all the major versions using modularized FML (i.e. 1.18.2+).

### CODE REVIEW

**Comment by LexManos** [comment]
Any chance I could get you to provide a bespoke test mixin that illustrates the issue? So that I can have a simple reproduction/isolated case.

Quick skim of the changes doesnt make sense to me so I'd have to look more deeply into it when I get time. and having a test would be useful.

**Comment by embeddedt** [comment]
One simple way to cause the issue is to make a mod with one mixin & an AT, and have the code in the mixin access a field widened by the AT. This will cause a crash because the AT is not loaded. That specific example can be solved by loading ATs even if there is a load error, but it's not the only approach that causes the crash. The proper solution is to suppress mixin loading altogether.

I currently don't have the bandwidth to make a manufactured test case for this - that's why I found a single existing mod I can get the issue to happen with, and did the testing in prod.

**Comment by LexManos** [comment]
Okay, havent had time to write the test mod myself. However I did look more into the code itself. Which wasnt easy as it has cpw's trademark 15 levels of indirection. But I think I understand what you're accomplishing even tho your explanation is hyper focused on Mixins.

What is going on is that you're using the sanitized/sorted mod list for the GAME layer. 
This works to fix the error screens because [ModSorter](https://github.com/MinecraftForge/MinecraftForge/blob/f09fd1f05b39df98f6415b44478b13723cee74cd/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java#L51-L74) sets this mod list to the `systemMods` {Just Forge and MC} if a mod sorting error occurs. 

This is basically, "If mod sorting fails, act like there are no mods at all" The only question I have left is why do you make it so complicated and not just do 
```diff
-        return new ITransformationService.Resource(IModuleLayerManager.Layer.GAME, this.candidateMods.stream().map(IModFile::getSecureJar).toList());
+        return new ITransformationService.Resource(IModuleLayerManager.Layer.GAME, this.loadingModList.getModFiles().stream().map(ModFileInfo::getFile).map(IModFile::getSecureJar).toList());
```
The GAMELIBRARY stuff in theory shouldn't be necessary, as that should be in the modFiles. This is why a test case would be useful to see what actually happens in the case you described.

It also leads to a optimization that should be done sometime in the future, using the sorted modlist for the background scanner instead of all candidates.

I'd still like to see a test case for this, just need time to make one.

**Comment by Jonathing** [comment]
## Test Case 

[Following what @embeddedt said in an earlier response](https://github.com/MinecraftForge/MinecraftForge/pull/9833#issuecomment-1872223163), I quickly whipped up this mod jar that has a Mixin injector which calls a transformed static final field (private -> public) which will crash if loaded. 

Lex asked me to test this [in a build of Forge that he created](https://discord.com/channels/1129059589325852724/1129095235889270844/1191529574073372781), so it's likely that this PR will be superseded by his own changes if he chooses to push them. If this happens, I or Paint Ninja will likely do the work to backport this to 1.20.1, as this is where the PR was originally targeted to (unless Lex does this himself as well). I am unable to make this into a test mod within Forge itself, so I've uploaded both the mod jar and sources zip below.

- [Test Mod JAR](https://cdn.moddinglegacy.com/469037770448597781-testcase9833-1.0-SNAPSHOT.jar)
- [Sources ZIP](https://github.com/MinecraftForge/MinecraftForge/files/13807026/TestCase9833.zip)

**Pull request closed without merging**
