### PR TITLE
[1.13]  Update MDK based on MinecraftForge/ForgeGradle#546

### PR DESCRIPTION
**Pull request by OhYea777**
Currently the way that **ExplodedDirectoryLocator** works is assuming that there is only a single resource directory, because of this the first path in the **MOD_CLASSES** environment variable is considered as the resources directory. A result of this is that, if you have different mods in different sourcesets, they are not loaded. If you specify the first source as a sourceset that has no _**mods.toml**_, in its resources directory, then it just kills the locator. Alternatively, if any of the specified paths in the **MOD_CLASSES** environment variable don't exist, it also kills the locator. Essentially, if you don't order things right or have any empty resources or classes in any sourceset it will fail at said point.

The provided solution for not existent paths is to just filter them out.

The provided solution for the locating would is to scan all of the directories in the **MOD_CLASSES** environment variable, however, there is one issue: because it tries to separate the resources and classes, if two files exist in two sourcesets, e.g: _**test/resources/META-INF/mods.toml**_ & _**main/resources/META-INF/mods.toml**_ then whichever is in the sourceset that is referenced first will be the one that is loaded.

This fix essentially just allows it to find the mod, independent of the ordering, however the above issue still applies. Any feedback or suggestions are definitely appreciated.

### CODE REVIEW

**Comment by LexManos** [comment]
Please provide a zip with a example setup for this/multi-project builds to be tested. We need something to verify and cpw doesn't have anything.
And yes, two source sets supplying the same resources does not work. It's something we have to figure out a good solution for but haven't yet as we dont have real world test cases or know what people want.

**Comment by OhYea777** [comment]
This pull request depends on MinecraftForge/ForgeGradle#543 and vice versa

**Comment by OhYea777** [comment]
Essentially the fix I found for this is to separate classes and resources into their respective **MOD_CLASSES** and **MOD_RESOURCES** environment variables. It essentially splits the resources and treats each element as the main resource directory, before moving on to the remaining resource and class directories. This means that for every source set, it will have it's own initial point of entry, allowing it to load from multiple sources while still being able to resolve from others

**Comment by OhYea777** [comment]
I will do some more testing later. It seems like the event registering is hit or miss, currently

**Comment by OhYea777** [comment]
So I've ported a couple of the test mods in Forge to 1.13 and they seem to be working fine with this current implementation

**Comment by GoryMoon** [comment]
I have ported the test (that are still relevant) so they compile but I haven't been able to test it properly because I couldn't get them to load.
This would be great to finish them up for a PR.

**Comment by OhYea777** [comment]
I have refactored to work with recent changes to Forge

**Comment by OhYea777** [comment]
[ForgeOCEP-1.13-pre.zip](https://github.com/MinecraftForge/MinecraftForge/files/2794006/ForgeOCEP-1.13-pre.zip)

**Comment by OhYea777** [comment]
Reverted all the test changes, will leave that for a separate PR

**Comment by OhYea777** [comment]
I have refactored this based on feedback for a better system. This is the implementation for the ForgeGradle changes I made in my ForgeGradle PR MinecraftForge/ForgeGradle#546

**Comment by cpw** [comment]
So, I think you've got a bunch of stuff mixed in here. 

I wanted to change modclasses to support this pattern, but not quite this way. Having multiple variables seems like it makes it harder to setup, and introduces a new bug pathway.

I'm gonna talk about this on stream in a bit..

**Comment by OhYea777** [comment]
I originally had it as **MOD_CLASSES** and **MOD_RESOURCES** but changed it to this after talks with @LexManos

**Comment by OhYea777** [comment]
Okay, so since a lot of what I was originally planning has since been implemented into Forge; this essentially just adds more information for the changes I made in my ForgeGradle PR MinecraftForge/ForgeGradle#546. Plus a small fix when firing registry events

**Comment by OhYea777** [comment]
Fix conflicts

**Comment by LexManos** [comment]
Can I get a update on this, is cpw's changes good with this/what he wanted?
Also, any chance I could get you to look into the FG side of Eclipse hacks, to make it work as Eclipse shoves things in directories that arnt the Gradle ones.

**Comment by OhYea777** [comment]
This and my FG pr use cpw's changes. It does the run configs by allowing multi mod definitions in the format that cpw had implemented: _**"modid%%c:\fish\pepper;modid%%c:\fish2\pepper2\;modid2%%c:\fishy\bums;modid2%%c:\hmm"**_. See: [MinecraftForge/ForgeGradle#546](https://github.com/MinecraftForge/ForgeGradle/pull/546). I'll take a look at the Eclipse hacks tomorrow

**Comment by OhYea777** [comment]
Closing this PR as I have combined this and MinecraftForge/MinecraftForge#5471 into its own PR: MinecraftForge/MinecraftForge#5482

**Pull request closed without merging**
