### PR TITLE
Added mushroom block tag

### PR DESCRIPTION
**Pull request by JaisDK**

### CODE REVIEW

**Comment by pupnewfster** [comment]
Personally part of me wonders if the blocks that make up a large mushroom should be part of a mushroom blocks tag

**Comment by marchermans** [comment]
Yeah I looked at the code and other situation where this is prevalent.
I think this should be seeds/mushroom for the two small mushrooms.
And the blocks that make up the large mushroom should be added to relative tags:
mushroom for all blocks
mushroom/red for red mushroom blocks
mushroom/brown for brown mushroom blocks.

**Comment by cech12** [comment]
Maybe a _mushroom/stem_ or _mushroom/trunk_ tag could also be useful for the third mushroom block. 

I added a PR long time ago about mushroom tags: https://github.com/MinecraftForge/MinecraftForge/pull/6620
It was related to coloring like the sand tags. Maybe you can find something useful there. :)

**Comment by JaisDK** [comment]
I don't see why the small mushrooms should be in _seeds/mushrooms_ since there's not even a seeds block tag to begin with. 
The item tag is not split into colored mushroom sub-tags, so it would not make sense to do it here.

Having the solid mushroom blocks makes some sense though as the tag will consist of the blocks that drop what is in the item tag + the stem for completeness.

**Comment by JaisDK** [comment]
@pupnewfster who needs to approve this for it to be taken to the next step?

**Comment by KnightMiner** [comment]
Its useful to be able to tell small and large mushrooms apart, specifically when mods add in extra mushrooms. On the other hand, I do not see much value for identifying all mushrooms of one color. If you just want a list of everything dropping the mushroom, that is possible to find in the loot tag anyways.

To me, I see a tag for the cubes, and possibly making the stem a tag as well (with a common tag containing both). A tag for all small mushrooms seems useful as well, so you can easily identify the plants. However, this all comes without a usage in mind.

Do you have a usage in mind for these tags, to explain why you structured them as you did?

**Comment by JaisDK** [comment]
My own usage is as "flowering" blocks for custom bees. Both small and big mushrooms fit that.

**Comment by JaisDK** [comment]
The goal for me with this PR is not to make a complete tag list for mushrooms, this seems to have been attempted previously without result. I just want a tag that other mods can add their mushrooms to.
It's largely reflecting the exiting item tag which is also not "complete"

**Comment by cech12** [comment]
> 
> 
> Its useful to be able to tell small and large mushrooms apart, specifically when mods add in extra mushrooms. On the other hand, I do not see much value for identifying all mushrooms of one color. If you just want a list of everything dropping the mushroom, that is possible to find in the loot tag anyways.
> 
> To me, I see a tag for the cubes, and possibly making the stem a tag as well (with a common tag containing both). A tag for all small mushrooms seems useful as well, so you can easily identify the plants. However, this all comes without a usage in mind.
> 
> Do you have a usage in mind for these tags, to explain why you structured them as you did?

My usage is that I have a mod that adds multiple mushrooms in different colors. The mushroom cap blocks can be used as wool to craft carpets, beds and other things that are color related. The stem blocks are used as new wood types. So, for me it would be useful to have the color relation and the difference between cap and stem blocks. 

But I understand the point, that this PR only wants to add the missing block tag of the mushroom item tag. :) I thought it would be senseful to think about the existing mushroom tag to enhance it a bit. :)

**Comment by KnightMiner** [comment]
For the record, a tag does not have to exist in Forge for mods to use it, you just need to talk to other mod authors and agree on a convention. Thats what we did for metals like copper, it works for vanilla items too (though having to add them yourself is a bit awkward, there is no harm adding the same item to a tag twice)

To be in Forge is a little more work, probably would help to discuss it a bit more outside the tracker to see what others use. I just know in experience, I have seen mods using small mushrooms similar to the way you use flowers, something the cube ones are not always relevant for

**Comment by JaisDK** [comment]
I'll gladly remove the cube mushrooms and add them myself in my mod as long as we get a block tag in forge. I can write to all mod authors that implement mushrooms, but that's just not a viable solution. If the tag exists, other mod authors will start using it on their own.

@cech12 it sounds like you would want to add colored wool tags instead and override the vanilla recipes to use that. Your stem should probably be in the wood tag.

**Comment by JaisDK** [comment]
Found your mod and I can see that you are already doing that.

**Comment by JaisDK** [comment]
No matter what, we should be able to agree that the two vanilla mushroom belong in a mushrooms block tag. I'll remove the cubes and another PR can be opened to add those and continue the discussion.

**Comment by cech12** [comment]
> I'll gladly remove the cube mushrooms and add them myself in my mod as long as we get a block tag in forge. I can write to all mod authors that implement mushrooms, but that's just not a viable solution. If the tag exists, other mod authors will start using it on their own.
> 
> @cech12 it sounds like you would want to add colored wool tags instead and override the vanilla recipes to use that. Your stem should probably be in the wood tag.

Yes, writing each mod author asking to use a tag is not the best thing. I have done it before and only a few agree on this, others only add forge tags if they are in forge. 

Thats how I do it for my own mod items an blocks. But mushrooms of other mods should also work like this. :)

**Comment by JaisDK** [comment]
Who needs to approve this to take it to the next level?

**Comment by TheCurle** [comment]
Why is this even needed? The tags are two items. Why can't mods use those in lieu of these?

**Comment by JaisDK** [comment]
Because they don't. Modders tend to only use the tags that are defined in Forge. With your reasoning, most forge tags should be removed.

**Comment by JaisDK** [comment]
bump

**Comment by JaisDK** [comment]
Is this being ignored hoping I will close it or is there another reason it's still open?

**Comment by sciwhiz12** [comment]
No, its just that the members of the Triage team also have real life jobs/problems to deal with, and sometimes PRs get forgotten along the way.

To add on, I don't see why these tags shouldn't be included, since they can be useful if other mods add their own mushrooms (e.g. glowshrooms or others).
Also, are you still planning to make a PR for a tag for cube mushroom blocks?

**Comment by DaemonUmbra** [comment]
I personally don't quite see the use of this.
I don't see many mods doing anything major with mushrooms and in the case that they do I don't think it's prevalent enough to warrant a Forge tag.

**Comment by JaisDK** [comment]
I am not planning a tag for mushroom cube blocks, this one is plenty to get some direction for other mods and it corresponds to the existing mushroom item tag.

**Comment by JaisDK** [comment]
For another time, what would be the best way to draw attention to a forgotten PR? Like you I also have life stuff and do modding on the side, so if there's a button to press or a place to post it would be good to know.

**Comment by sciwhiz12** [comment]
If you feel like a lot of time has passed between the last meaningful review of your PR by the Triage Team (or if it hasn't been reviewed by the Triage Team yet), you could post a request to review the PR on The Forge Project discord in the `#general` channel (or `#squirrels` if you want), along with a link to the PR and a brief reason for requesting a review (e.g. "It's been a month since I made it, and it hasn't been reviewed yet").

While the Triage Team do their best, they do have IRL stuff to sort out and PRs are sometimes left unreviewed or forgotten. In those cases, I recommend people (either PR authors or people who want the PR merged for their own reasons) to ask about their PR in the Discord server so Triage team members who are free and see the message can review it (or remember to review it soon).

**Comment by JaisDK** [comment]
I'm a bit confused though about the procedures for PRs. Do you all need to agree whether it's good or not and who gets to click the merge button?

**Comment by sciwhiz12** [comment]
_(disclaimer: not part of the Forge team, but somewhat-knowledgable about the process)_

### (unofficial) Procedures for Pull Requests
 1. **PRs are created by contributors (or to-be-contributors).** 🟢
PRs are usually either enhancements (adding a new feature to Forge) or bugfix (fixing a regression from vanilla behavior).

 2. **PRs are reviewed by the Triage Team, and changes are requested if needed.** 💬
Once the PR is submitted (and it is not a draft PR), then a member of the Triage team will come around to review your PR, checking for mistakes _(wrong logic)_, formatting _(braces on newlines in Forge classes)_, etc. and other needed changes.
They may also locally clone your PR branch and test the changes if needed (especially if they modify existing logic).

    People from the community can also review your PR, adding comments or requesting changes if needed. Usually, the Triage team will take these outside reviews into account if they raise a valid point _(such as formatting, or a concern about some lines of code)_.
     They might also consult with knowledgable members of the commmunity, other Triage team members, or core Forge developers (including Lex the lead maintainer himself, but mostly only for major changes).

 3. **PR is assigned to the core developers.** 🚩
After the Triage team member is satisfied with the state of the PR, it is labelled as `Assigned` and assigned to a core Forge developer (LexManos for the latest branch, and designated devs for LTS, such as gigaherz, tterrag, or covers1624).

     Then, once the assigned core dev has time to review the PR themselves, they can provide feedback or request changes on the PR, either directly in GitHub or through the Triage team (usually the member who assigned them), which means going back to step #&zwj;2.

 4. **PR is merged in.** 🎉
If it satisfies the reviews of the Triage team, the community, and the assigned core dev, then the PR is merged in, and it will be built by the Forge CI within the next minutes for immediate publishing. Hooray! :shipit: 
For some PRs, the Triage team or core developer may also request a backport to the LTS branch if the PR's contents apply there too, such as for critical bugfixes or badly-needed features. For most cases, it is up to the PR author to make an LTS backport PR.

**There are a few rules about PRs:**
 1. PRs should follow the formatting guidelines. _(e.g. braces on newlines, 4 spaces not tabs for Forge classes.)_
 2. PRs with patches to Minecraft classes should follow the patch formatting guidelines. _(e.g. follow the class formatting, minimize as possible without sacrificing readability too much)_
 3. PRs for new features should be made for the Latest branch first, unless they do not apply to the Latest branch and only for the LTS branch.
 4. PRs for new features should have a use-case for the PR's feature, to demonstrate why it should be included in Forge.
 5. PRs must retain compatibility with vanilla clients/servers.
    This means e.g. no usage of tags for determining game logic (such as plant growth, entity tracking, etc.).
 5. If a Recommended Build has been made for that major version, _no breaking changes are allowed_. Breaking changes are changes which change the public-facing APIs, such that already-compiled mods do not work due to the PR's changes.

**Comment by JaisDK** [comment]
Thank you!

From this I can tell that the PR is still on step 2. What happens if the triage team does not think the change is needed, but it still makes sense to have it?

**Comment by sciwhiz12** [comment]
If the Triage team does not think that the change is needed, then either you or other community members should argue for the merging of the change. 
You can ask mod developers who can be affected by the change if they feel that this change is sufficient, and request them to weigh in too. _(You can also join the Forge Project discord and have a conversation there with the Triage team member and the community about your PR too.)_

If enough people from the community agree and the points made are valid enough to overturn the doubts, then the Triage team will usually rethink their position about the PR (but, the Triage team usually also consults with a core dev about PRs, so the core dev's opinion will also affect the PR).

**Pull request closed without merging**
