### PR TITLE
[1.13] Add a RayTraceResult method to Block that can be can be overridden

### PR DESCRIPTION
**Pull request by ShetiPhian**
Prior to 1.13 mods would override Block.collisionRayTrace to change the block outline to highlight interaction zones within a block.
(BuildCraft, EnderIO pipes; EnderStorage, MultiStorage, EnderTanks chest & tank color indicator; and others)

1.13 made it static and it doesn't appear to be a workaround without a patch.

This patch redirects the return from the static method through a new getRayTraceResult method which blocks can override. (did it this way to keep the patch size down)

To convert from 1.12 to 1.13 you would change your block's collisionRayTrace override to this getRayTraceResult method, and any calls to this.raytrace would become ShapeUtils.rayTrace

### CODE REVIEW

**Comment by williewillus** [comment]
> Prior to 1.13 mods would override Block.collisionRayTrace to enable interaction zones within a block.

if I'm not mistaken, the new VoxelShape system provided by vanilla should completely supersede this (see how the vanilla hopper's raytrace hitbox is fancy now), so I don't really see the point of readding the old way.

**Comment by ShetiPhian** [comment]
It didn't provide the player or hit vector, to indicate which sub part was hit
~I did forget to see if VoxelShape used the multi input to set the sub part though, going to check that now.~

Unless I'm overlooking it, all provided VoxelShaps are combined into a single outline.

Sub zones still function as those are processed in onBlockActivated, but it looks like you can no longer show the sub hit outline (I should have been clearer in the first post and will correct that)

**Comment by ShetiPhian** [comment]
You know what, I'm going to close this.
Since the only reason, that I know of, for overriding this method is to render a helpful outline for players, maybe doing it in the RenderWorldLastEvent would be be better then this patch. (Doing so would also allow for more then just a black outline)

If there is another reason to override this, I or someone else will reopen/resubmit the pull request.

**Comment by Phylogeny** [comment]
Just as one might want to know what sub-AABB was hit in 1.12, one might want to know what sub-VoxelShape was hit in 1.13.

**Comment by ShetiPhian** [comment]
Phylogeny is correct, this looks to be needed to set/get the sub VoxelShape that is hit.

**Comment by ShetiPhian** [comment]
*sigh* I manged to break my pull request while fixing merge conflicts

For anyone wondering how: I almost exclusively use commit and push, everything else if basically foreign.
Here is what happened:
I tried to fetch and rebase, but couldn't due to the changes I made so I ran a hard reset on the head to get back to the original Forge commit history. The rebase ran fine after that but I couldn't push, so I force pushed. Then I remade my changes and pushed the commit.
Now my pull request notes no files edited, yet my branch indicates one and prompts to open a pull request.

**Comment by Wyn-Price** [comment]
This method is useful to have. I know I use it for doing custom raytracing. Imo, there absolutely should be a way for the block to do it's own raytracing

**Comment by LumberWizard** [comment]
I think the conversation should be continued on #5354

**Pull request closed without merging**
