### PR TITLE
[1.14.4] Added synchronized modifier to RegionFileCache.loadFile, RegionFileCache.close and RegionFile.func_222662_b to allow safe world save access from any thread, not just server thread, like it used to be in older Minecraft versions.

### PR DESCRIPTION
**Pull request by thexaero**
I really need this back for my map mod. I have temporarily (hopefully) moved some of the work to the server thread to avoid race condition issues but it affects the game performance way too much, especially when the server thread is already loaded.

### CODE REVIEW

**Comment by cpw** [comment]
Why?

**Comment by thexaero** [comment]
I need it for my map mod. Even moving the minimal amount of work to the server thread affects the game performance too much (mostly for people with a lot of mods).
Equivalent methods in the previous Minecraft versions used to be synchronzied. Everything in the RegionFile class is still synchronized, so I think Mojang just forgot to add the modifiers when they rewrote RegionFileCache. It was probably synchronized for mods support in the first place.
EDIT: I should add that Long2ObjectLinkedOpenHashMap is not thread-safe.
EDIT: But I guess the methods themselves aren't either.

**Comment by RainWarrior** [comment]
RegionFile has race conditions with the current API, so vanilla forces it to be accessed only by the main server thread. There are synchronization leftovers there, but it is not remotely ready to be accessed by multiple threads again.

**Comment by thexaero** [comment]
We can add "synchronized" to RegionFile.func_222662_b and that should be it. Everything else seems fine to me.
Or can you give another example of a race condition in RegionFile?

**Comment by RainWarrior** [comment]
it's not about individual methods, it's the class itself; it was about reading the chunk before the old data is finished writing iirc

**Comment by thexaero** [comment]
I don't see how this can happen with the current synchronization, so please give an example.

**Comment by RainWarrior** [comment]
Sadly I'm unable to find it at the moment; what I do remember: 1) it was during the development of 1.13, so the issue existed in 1.12; 2) it was not in the RegionFile class itself, it was where it was use, and multiple operations in sequence had to be done as 1 transaction or it would lead to a race condition (if anything else accessed the storage in between that transaction), and the code outside changed drastically, so that exact issue might not happen anymore, but what matters is that the class was not written as a thread safe class in the first place; if it happens to work at this particular moment in time, there's nothing saying it will stay that way.

**Comment by thexaero** [comment]
I understand how race conditions work, and I'm confident that there shouldn't be any in my latest commit. Every method that accesses the file (or other non-thread-safe stuff) is either synchronized or is called by a synchronized method.
And you're right, the race condition I fixed is also in 1.13. 
EDIT: RegionFile lets you write to the region file, read from it or check if a chunk is saved, which definitely can't cause race conditions if you don't call them in a particular order, so there shouldn't be any issues in the code outside of RegionFile.
EDIT: Btw, your description of the race condition fits perfectly for the one I fixed, but it IS inside RegionFile, not outside.

**Comment by Niko-sk2x** [comment]
The only potential issue I could find in 1.12.2 was this https://bugs.mojang.com/browse/MC-107257. Is that the issue, or was it something else?

**Comment by thexaero** [comment]
I think "1.12" is a typo in RainWarrior's comment. He probably meant 1.13.
The issue you linked doesn't really apply here. It's about AnvilChunkLoader, which I have no reason to use. I don't need to actually load the chunks in the world, I just need to access the files.
RegionFileCache and RegionFile don't ever generate chunks and can't trigger this issue either (because they don't access "chunksToRemove"). 
Reading the file or writing to it "in between" would do no harm in this situation. If anything, if you start writing a chunk (not sure why anyone would do it), it'll only make the issue more rare.
EDIT: Oh, and it's fixed since 1.13 anyway.

**Comment by thexaero** [comment]
I just noticed that func_222662_b isn't even called anywhere except WorldOptimizer (and there's no reason to, as there's a faster alternative), which is probably why it's not synchronized. This wouldn't concurrent with my mod and I can't think of any reason why anyone would want to interfere with WorldOptimizer. Having func_222662_b synchronized won't hurt though as you can still call it if you really want to.
EDIT: So WorldOptimizer actually creates its own RegionFile instances, which means you REALLY shouldn't interfere with it, there's no synchronization there. 
Using RegionFile instances from RegionFileCache should be perfectly thread-safe now though.

**Comment by Spottedleaf** [comment]
> I need it for my map mod. Even moving the minimal amount of work to the server thread affects the game performance too much (mostly for people with a lot of mods).

It seems a better solution is to simply re-add an io thread so that you don't have to worry about the io occurring on the main thread, and neither would anyone else.
1.14 provides api for retrieving a "read-only" chunk (check the EMPTY chunk status, I'm not familiar enough with mcp mappings to point you to the chunk provider where that method exists), which would use the io thread to retrieve chunk data. That interface looks like exactly what you would want - get chunk data without having the chunk impact the server performance by ticking or loading entities. The problem with it currently is as you stated, it does the io on the main thread. 
However with an io thread you would need to add a non-blocking variant of this interface. That is easy given the current blocking interface is made by simply blocking on an internal non-blocking interface, so the logic can be separated - with a minor addition (specifically, adding a ticket + type to ensure the pending load doesn't get cancelled).

Previous versions of minecraft used an io thread, however it was poorly synchronized which appears to be the reason for its removal, although don't quote me on that.
I'd suggest re-adding an io thread that is properly synchronized, and then provide methods to schedule reads and writes from it. I'm not familiar with the forge design philosophy though, so I've no idea if that would be acceptable to PR.

The problem with scheduling writes is that really you should only want those to be scheduled from the main server thread, otherwise you're going to run into race conditions with the main thread saving chunks and the writes you schedule off-main. However that race condition can still happen with your PR as written, and there's little reason to require the scheduling of writes off of the main thread to be MT-Safe anyways, so all you really need to be concerned about is the scheduling of reads and writes and the order they are executed in. The io thread can optionally refuse to schedule writes from threads that are not the main thread.

For scheduling reads off of the main thread, the worst that can happen is that you schedule a read at the same time the server loads/saves a chunk, which means you could get out of date chunk data, but that's **ONLY** if you're scheduling reads while not on the main server thread. As far as vanilla goes, vanilla schedules only from the main thread, and it does do unexpected re-ordering of chunk io (i.e trying to load a chunk before unloading one). Which means you can easily replace the logic, **as long as you can model the behaviour of the replacing logic as occurring synchronously**. This makes using the existing interface to get read-only chunks more attractive, as it will guarantee that you do not get out of date data since it forces main thread scheduling.
Your PR as written, as well as an io thread, would behave as described as above. That is, they wont be able to guarantee that the returned data is up-to-date with chunks that could have been loaded or saved between the time of scheduling the IO and getting it back. But that's fine, vanilla doesn't need those guarantees and neither should any mod given the read-only chunk interface I've previously described.

The most simple io thread that would provide synchronized execution of io, as vanilla currently requires, is a single thread executor, i.e singleton Thread instance or [Single thread ExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newSingleThreadExecutor--). All that would be required is a simple interface to pass a callback for write success or callback for data read, chunk coordinate (including world), and whether it's poi data (poi data is in its own regionfiles). You would need to add logic to "flush" and "close" the io thread in the event of server shutdown (prevent data loss) or world unload (on world unload all regionfiles loaded for that world are closed, so you want all the IO to be done before that to prevent dataloss). This IO thread would be "in control" of the RegionFileCache and RegionFile interfaces. Applying synchronization to them would be enough to simply prevent total failure (i.e corruption of the backing regionfile cache map or the region file on disk) in the event that some mod didn't get the memo (or didn't realise there was a change to the implementation) and decided to use RegionFileCache or RegionFile.

You can go for a far more complicated design that would prioritize some IO over others to assist in cases where the main thread is blocking on a chunk load. I am willing to provide working code for that if wanted as I did PR that very idea to another project. 

However, just having a synchronous executing IO thread on its own is pretty good and certainly miles ahead of vanilla's current solution. It also solves the issue you laid out in this PR, and improves general server performance.

**Comment by thexaero** [comment]
Sounds like a great idea to me! I honestly can't think of a reason why anyone would want to "write" off of the main thread and expect it not to break things.
BTW, I managed to minimize the main server thread work even further. I realized that the only way for a race condition to happen when using RegionFile off of the main server thread is if another mod uses the non-synchronized method func_222662_b that nobody should have a reason to use outside of WorldOptimizer. So all I'm doing on the main server thread now is calling _RegionFileCache.loadFile_ with reflection. 
It obviously isn't perfect though, so I'm still hoping for the proposed change to happen.

**Pull request closed without merging**
