### PR TITLE
Add getter for the world to LootContext

### LINKED ISSUE #2916: [1.9] getWorld() for LootContext
The LootContext object is normally created with a WorldServer, which is then never used in that class. I am in need of world access for a custom LootCondition and suggest that we put in a getter for that world object.

### PR DESCRIPTION
**Pull request by williewillus**
As title, easy enough.

Useful for custom LootFunctions and LootConditions that need the world, but you can't get it because all the entities are null (for example, chest gen tables. No looted entity, no killer either)

Makes it possible to have loot tables that do different things based on the world (raining/nether/etc.)

Closes #2916

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by killjoy1221** [comment]
You'd might as well save yourself a patch and use an AT.

**Comment by williewillus** [comment]
If it benefits many people I don't see the point of not doing this

**Comment by LexManos** [comment]
Seems dumb because of how loots are done but whatever.

**Pull request merged**
