### PR TITLE
Improve GRADLE build Performance

### PR DESCRIPTION
**Pull request by i-Taozi**
[Parallel builds](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:parallel_execution). This project contains multiple modules. Parallel builds can improve the build speed by executing tasks in parallel. We can enable this feature by setting `org.gradle.parallel=true`.

[Configuration on demand](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand). Configuration on demand tells Gradle to configure modules that only are relevant to the requested tasks instead of configuring all of them. We can enable this feature by setting `org.gradle.configureondemand=true`.

[gradle caching](https://docs.gradle.org/current/userguide/build_cache.html). Shared caches can reduce the number of tasks you need to execute by reusing outputs already generated elsewhere. This can significantly decrease build times. We can enable this feature by setting `org.gradle.caching=true`.

=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.

### CODE REVIEW

**Comment by marchermans** [comment]
Please provide proof of speed up in the form of tests and backing data.

Forge is a special project and it pushes Gradle to it's limits which does not always translate well to common techniques to speed up builds

**Comment by sciwhiz12** [comment]
Not only does the commit author not match the PR author (@YunLemon vs @i-Taozi), but the PR author's history is very suspicious: 60+ Pull Requests to many unrelated repositories (other than the common factor of Gradle), where:
 - They all have the same title of `Improve GRADLE build Performance`;
 - Multiple PRs being spaced by not more than 1 minute from each other; 
 - Each checked PR from a random sampling is following the same format: 
   - one paragraph per modification; 
   - a separator of 21 equals signs; and
   - the same sentence: `If there are any inappropriate modifications in this PR, please give me a reply and I will change them.`

This looks to be the behavior of a bot rather than a human being. On this basis, I am closing this PR.

**Comment by i-Taozi** [comment]
> Please provide proof of speed up in the form of tests and backing data.
> 
> Forge is a special project and it pushes Gradle to it's limits which does not always translate well to common techniques to speed up builds

This PR doesn't introduce any bugs. https://jenkins.minecraftforge.net/blue/organizations/jenkins/forge%2Fforge/detail/PR-8187/1/pipeline. According to the jenkins build data, this pr costs 8 minutes, which is much faster than the average build time.

**Comment by i-Taozi** [comment]
> Not only does the commit author not match the PR author (@YunLemon vs @i-Taozi), but the PR author's history is very suspicious: 60+ Pull Requests to many unrelated repositories (other than the common factor of Gradle), where:
> 
> * They all have the same title of `Improve GRADLE build Performance`;
> * Multiple PRs being spaced by not more than 1 minute from each other;
> * Each checked PR from a random sampling is following the same format:
>   
>   * one paragraph per modification;
>   * a separator of 21 equals signs; and
>   * the same sentence: `If there are any inappropriate modifications in this PR, please give me a reply and I will change them.`
> 
> This looks to be the behavior of a bot rather than a human being. On this basis, I am closing this PR.

I'm sorry to make you feel so bad about this PR! 
We do not submit this PR for a bad purpose, and we really hope that this PR can have a positive impact on the project.
As we can see in [Build time](https://jenkins.minecraftforge.net/blue/organizations/jenkins/forge%2Fforge/detail/PR-8187/1/pipeline), it do help to reduce the build time!
Once again, I would like to express my sincere apologies.  I will appreciate if this PR can be reconsidered by you!
Thanks~

**Pull request closed without merging**
