### PR TITLE
Added sensitive ore system and recipe.

### PR DESCRIPTION
**Pull request by hokutoMc**
I improved new ore system.
You can access to new ore System on class "SensitiveOreDict".
1:1 matching except for damage-insensitive checking which returns ItemStack with 0 damage. NBT-sensitive checking which uses only equivalent of values in nbt and given value.

### CODE REVIEW

**Comment by LexManos** [comment]
Pretty sure I already turned this PR down last time it was posted.
The Predicate system is interesting and all but it's a fundamental shift from what the recipe system is. With this predicate system there is no way to determine what the inputs for a recipe are at any give time..
It complicates the OreDictionary which is intended for SIMPLE this item is this!
It slows down a system which is already bogged down because modders are accessing it incorrectly. 
There really is no benefit besides 'Its more abstract because abstraction!'

**Comment by cabralRodrigo** [comment]
@LexManos Can you point me out to a place where I can find a explanation on what the OreDict system is really for? I See a lot of people talk about modders breaking the oredict but nobody (that I see so far) explained exactly what's the purpose of the system.

**Comment by LexManos** [comment]
Its a hacky system put in place because modders can not agree to work together properly.
It it designed Solely for "This item should be treated exactly the same as this other item"
It's a legacy hold over from back in the day when every mod and their mother added, say, a new copper ore and ingot. {Hence the name OreDictionary}
What should be done by modders is simply check if there is already a item they are looking for registered, and if so use that.
```
ores = Dict.getOres("ingotCopper")
if (ores.size() != 0) MyMod.INGOT_COPPER = ores.get(0);
else MyMod.INGOT_COPPER = makeNewIngot() Dict.register("ingotCopper", INGOT_COPPER)
```
Something along those lines.

As for USING The dictionary in its current state.
Examples can be see in the Shaped/Shapeless Ore recipies.
ONCE during construction query the dictionary for the List for your Ore.
That list WILL be updated whenever someone registers a new ore, so there is NO need to continuously query it. Caching that list saves A LOT of CPU time doing a lookup for it in the Dictionary.

Modders 'break' the dict by trying to impose their will on naming schemes. If you hack into the internals of the registry and start moving items around you're doing it wrong. Especially if it's for something as petty as making your item the 'first' in the list. {I wont name names but this is done by a couple popular mods}

If you designed your machine or whatever to constantly call the dictionary directly {getOreIDs(ItemStack), getOreID(String), getOres(String)} you're doing it wrong, because those methods use costly logic that should be aggressively cached because the values will always return the same. There is also the OreRegisterEvent which you can use to update your local cache if it ever changes after your initial queries.

I've seen people do something as stupid as this before in their TE's and Forge gets blamed for being 'slow' because the dictionary shows up as a hotspot in the profiler.
```java
void tick(){
  for (ItemStack i : inputs){
    if (Dict.getOres(i).contains("ingotCopper")) output = DUST_COPPER;
    if (Dict.getOres(i).contains("ingotTin")) output = DUST_TIN;
    if (Dict.getOres(i).contains("ingotIron")) output = DUST_IRON;
    // and so forth
  }
}
```
Now, what's wrong with that? Well first off even if getOres was free, it's still better to cache those calls and only do them once per stack.
Secondly this is done EVERY TICK, far better to only do it when necessary, such as when the inventory changes or something.

**Comment by cabralRodrigo** [comment]
@LexManos Thank you so much for this great explanation!

This is really useful for a lot of people, this issue is already on my favorites!

I only hope that modders do some research before making things, I always research for make my code in a possibly better way even the code is already working.

**Comment by bonii-xx** [comment]
>As for USING The dictionary in its current state.
>Examples can be see in the Shaped/Shapeless Ore recipies.
>ONCE during construction query the dictionary for the List for your Ore.
>That list WILL be updated whenever someone registers a new ore, so there is NO need to continuously query it. Caching that list saves A LOT of CPU time doing a lookup for it in the Dictionary.
Even I did not know this. But at least it explains some of the behaviour I've seen in the OreDictionary. I think there is no actual example or explanation explaining the things in your post. Maybe convert it into a wiki page or something similar that people can find?

**Comment by LexManos** [comment]
Feel free to do that, I can't write documentation, that's what the Documentation repo and PRs are for.

**Pull request closed without merging**
