### PR TITLE
Fix ContainerRepair patch to prevent NPE

### PR DESCRIPTION
**Pull request by bs2609**
Fix for #3548. Also fixes the location of the check.

### CODE REVIEW

**Review by kashike — APPROVED** [review]

**Comment by diesieben07** [comment]
This is not actually a proper fix. This will cause NBT to be set on the empty ItemStack instance. The actual problem is that this if check is too early and that problem exists even as far back as 1.9.4.

**Comment by bs2609** [comment]
Ok, fixed.

**Comment by diesieben07** [comment]
Now you have an extra blank line.

**Comment by bs2609** [comment]
That was in the original patch, do you want it removed?

**Comment by diesieben07** [comment]
While you're at it might as well clean it up, right?
Not that I have any authority here.

**Comment by liach** [comment]
@mezz I hope you can review this.

**Review by liach — APPROVED** [review]

**Comment by mezz** [comment]
Can you add a test mod for this? There is no way to verify because `isBookEnchantable` is true on all vanilla items.

**Comment by bs2609** [comment]
Ok, here's a test (on the right branch this time).
Is this ok for a test?

**Comment by mezz** [comment]
Yeah that should work fine. I'll test this PR now.

**Comment by mezz** [comment]
Tested and it seems to work correctly, no crashes on the anvil.

However this test item is not enchantable at all so it can't be used to test if `isBookEnchantable` works.
Can you make the item enchantable at the enchanting table like a sword or something like that?

Also please give it a name, and make it show up in the creative menu, it should just take something like
```java
private TestItem()
{
    setCreativeTab(CreativeTabs.BUILDING_BLOCKS);
    setUnlocalizedName(MODID + ":" + name);
    setRegistryName(new ResourceLocation(MODID, name));
}
```
No need to localize the name, I just want to be able to find it more easily by searching the creative menu.

**Comment by bs2609** [comment]
Made an update with those changes.

**Comment by mezz** [comment]
Your item still can't be enchanted, I recommend inheriting from `ItemSword`. Please test

**Comment by bs2609** [comment]
Fixed the missing override

**Comment by mezz** [comment]
Forge's MCP mappings have updated, `isItemTool` should now be `isEnchantable`.
https://github.com/ModCoderPack/MCPBot-Issues/issues/263

**Comment by mezz** [comment]
I still can't enchant it in the table.
Please test and show me a screenshot of it working.

**Comment by bs2609** [comment]
Moving it over to its own project helped.

**Comment by mezz** [comment]
Looks good. Tested and works as expected.

**Comment by bs2609** [comment]
This needed redoing due to the 1.11.2 update. @mezz, mind giving this a quick recheck to make sure it's still ok?

**Comment by mezz** [comment]
Tested and looks good.

**Pull request merged**
