### PR TITLE
[1.15.x] Created shears tag (#6514)

### PR DESCRIPTION
**Pull request by yanny7**
See #6514

### CODE REVIEW

**Comment by cech12** [comment]
I would be really happy if this change is integrated. :)

**Comment by SilentChaos512** [comment]
Could we get a review of this, please?

**Comment by ichttt** [comment]
This is missing the data generator classes, I only see the generated data, not the actual generator code

**Comment by yanny7** [comment]
I created that files manually, but if you tell me what script to use, I made also generator for it (python, shell ...)

**Comment by bl4ckscor3** [comment]
Use the vanilla data generator system.

**Comment by cech12** [comment]
Why was that PR closed?

**Comment by yanny7** [comment]
I fucked up merge, I created new fork with applied changes there: #6765

**Pull request closed without merging**
