### PR TITLE
Added EntityEvent.EnteringSection

### PR DESCRIPTION
**Pull request by diesieben07**
Intended as a successor to `EntityEvent.EnteringChunk`

### CODE REVIEW

**Review by marchermans — APPROVED** [review]
Perfect this was indeed missing.

**Comment by LexManos** [comment]
It'd be worth caching if we should fire the event based on the class passed into the constructor.
So that we don't have to do a instanceof that will always be true.

**Comment by diesieben07** [comment]
Added caching for the actual `Entity` instance to avoid instanceof / cast.

**Comment by diesieben07** [comment]
Updated to fire the event after the entity has moved to the new section, not before.

**Pull request merged**
