### PR TITLE
[UNFINISHED] Create ClientChatSendingEvent

### PR DESCRIPTION
**Pull request by ghost**
I have made the event, can someone add the event call to EntityPlayerSP#sendChatMessage and commit this patch? (Note make sure to check if it was cancelled and dont send the packet if it is)

### CODE REVIEW

**Comment by mezz** [comment]
Please coordinate with someone on IRC, in an issue, or on the forums instead, and open a new PR when it is ready.
The PRs section here is for organizing complete ideas to be reviewed, refined, and pulled. This does not qualify yet.

**Comment by ghost** [comment]
@mezz I can't make it complete because there's barely any tutorials on how to set up an environment

**Comment by RANKSHANK** [comment]
There's literally one on the repo's readme.md -_-

**Comment by mezz** [comment]
Feel free to ask and people will help.
Here is a good tutorial: https://www.youtube.com/watch?v=yanCpy8p2ZE

**Pull request closed without merging**
