### PR TITLE
Resolved a few build failures

### PR DESCRIPTION
**Pull request by svenmeys**
Moving object position and Vec3 references updated to the correct classes

### CODE REVIEW

**Comment by luacs1998** [comment]
You might want to change the PR title to something more descriptive.

**Comment by liach** [comment]
Should this be closed?

**Comment by williewillus** [comment]
probably, they handle updates mostly on their own. it's more efficient.

**Comment by LexManos** [comment]
Good effort, but this is just class renames which is actually the easiest part of updating. If you want to help, go after patch rejects. Or make sure that current patches apply to the intended position.

**Pull request closed without merging**
