### PR TITLE
FMLSecurityManager IndexOutOfBoundException

### PR DESCRIPTION
**Pull request by EyZox**
See http://www.minecraftforge.net/forum/index.php/topic,40907.0.html for more info (Blackout == EyZox == me)

### CODE REVIEW

**Comment by cpw** [comment]
No error log? I've never seen this happen. Hypothetical fixes are not accepted.

**Comment by EyZox** [comment]
Well, it is very rare but not hypothetical.
If array.length == 4, array.length > 4 is true but array[4] throws an OutOfBoundException because indexes starts by 0. array.length == 4 means array[0, 1, 2, 3] ...

I'm trying to make a custom JUnit test runner to create automated tests for my mod.
There is my log :
`Exception in thread "main" [22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[22:32:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)`

**Comment by bspkrs** [comment]
I'm failing to see how this is not a valid thing to fix. If the array length is 4 (> 3), then trying to access index 4 will always fail.

**Comment by LexManos** [comment]
Yes we understand that, however we'd prefer a actual usecase that causes the issue so we have some justification beyond theoretical.
So how us it erroring.,

**Comment by cpw** [comment]
Thanks for the valid example. Sorry, we don't pull in people's hypothetical musings. A new test harness isn't hypothetical. Not sure why it's loading the security manager (I would tend to avoid loading anything unnecessary in a unit test framework myself).

**Pull request merged**
