### PR TITLE
Added EntityRegisterEvent

### PR DESCRIPTION
**Pull request by Abastro**
For doing some tasks on Entity Registration.

### CODE REVIEW

**Comment by LexManos** [comment]
What is the point, what is it allowing you to do...

**Comment by Abastro** [comment]
When a mod registers entity, I have to check the type of entity.
I think that an Entity can be registered on PostInit, so I can't do that;
So I want an event.

**Comment by LexManos** [comment]
What do you need to check the type for?
You can access the registry list and loop through it.

**Comment by Abastro** [comment]
Because I have to do that before world loading.

**Comment by LexManos** [comment]
Then do it in WorldEvent.Load.

**Comment by chylex** [comment]
There's also a LoadComplete event that fires after PostInit.

**Comment by Abastro** [comment]
Oh I didn't know there was event for load completion.
 (I can't do it on WorldEvent.Load because it is too late)

**Pull request closed without merging**
