### PR TITLE
Deprecate vanilla getExplosionResistance and add @Nullable to the forge replacement

### PR DESCRIPTION
**Pull request by JamiesWhiteShirt**
#3484 but for 1.11.x. Completely forgot to update the PR.

### CODE REVIEW

**Comment by mezz** [comment]
Deprecating the old method is good.
Are you sure the `exploder` should be `@Nullable`? Vanilla always calls it with a value, is it useful to pass null?

**Comment by covers1624** [comment]
Err, The exploder can be null. Explosion calls `Entity#getExplosionResistance` only if the exploder is not null which essentially bounces to `Block#getExplosionResistance`, other wise it calls `Block#getExplosionResistance` directly passing null as the exploder.

**Comment by JamiesWhiteShirt** [comment]
covers1624 is correct. It is called with `null` as the exploder in `Explosion#doExplosionA`.

**Comment by mezz** [comment]
Thanks, I missed that because I didn't see the second `getExplosionResistance` call on the same line.

**Pull request merged**
