### PR TITLE
Semi-automatic detection for callable classes to be preloaded

### PR DESCRIPTION
**Pull request by diesieben07**
Current list is not complete (`Minecraft$15` for example is missing).

### CODE REVIEW

**Comment by cpw** [comment]
The list is static because it is what's needed to make a functional crash report ( that doesn't have a class loading error in it instead of the original). I think I'd rather keep it static myself.

**Comment by diesieben07** [comment]
How is this list not static? The class that generates the list is designed to be ran to _update_ the list only. At runtime there is only the file being read...

**Comment by LexManos** [comment]
I got Grum to add in a Marker class for all of these so that I can programmatically detect them in the next update.
This is useless.
The current setup is designed to be a stop-gap until the next update.
I pragmatically scanned for the original list so it SHOULD be complete.
If we're missing a class then add the class, don't re-write the whole system.

**Comment by diesieben07** [comment]
Welp, I was trying to be helpful. We'll wait for 1.8.8 then or you do it yourself.

**Pull request closed without merging**
