### PR TITLE
Fixed special mods being ignored by the mod list

### PR DESCRIPTION
**Pull request by Guichaguri**
Special mods (Optifine) are ignored by the mod list since searching and sorting were added.

### CODE REVIEW

**Comment by cpw** [comment]
I wanted to integrate the mod list from other mod sources. I need to revisit a lot of this code..

**Comment by liach** [comment]
There's [an unused method] (https://github.com/MinecraftForge/MinecraftForge/blob/90829a316439efe7ddeb8f03b030e00366d8d03c/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java#L358-L381) in `FMLClientHandler`. That method does nothing actually but I suggest to extend the mod list by editing this method.

**Comment by cpw** [comment]
@Liach that's the failed result of an attempt at other modloaders providing and sharing mod lists with us for display in our lists (and vice versa)..

**Comment by Actuarius** [comment]
@williewillus added labels [Cleanup]

**Pull request closed without merging**
