### PR TITLE
1.10.x vs 1.11x

### PR DESCRIPTION
**Pull request by ghost**
this is adding mo' mods to this. 

- [MinecraftModCooperationAPI-1.11.zip](https://github.com/MinecraftForge/MinecraftForge/files/694228/MinecraftModCooperationAPI-1.11.zip)
[The B.H.D.S. Army Modpack 1.10 Edition..zip](https://github.com/MinecraftForge/MinecraftForge/files/694233/The.B.H.D.S.Army.Modpack.1.10.Edition.zip)

[(Mianite-Mods%2FS4) AutisticMC. 1.10.zip](https://github.com/MinecraftForge/MinecraftForge/files/694236/Mianite-Mods.2FS4.AutisticMC.1.10.zip)

[pastebin_backup_20170107.zip](https://github.com/MinecraftForge/MinecraftForge/files/694240/pastebin_backup_20170107.zip)

blueapple pack
[woodlandmansion10658918.zip](https://github.com/MinecraftForge/MinecraftForge/files/694238/woodlandmansion10658918.zip)

### CODE REVIEW

**Comment by shadowfacts** [comment]
What do you think you're doing?

1. All the commits in your PR are from other people. 
1. Your comment makes no sense.

**Comment by mezz** [comment]
Sorry I don't understand what this is trying to do. 
If you need help please use the forge forum: 
http://www.minecraftforge.net/forum/index.php?board=15.0

**Comment by liach** [comment]
@AutisticMC MinecraftForge is not ForgeCraft. You should look up on reddit or IRC first.

**Comment by MiscMC** [comment]
i have autism it's hard ok ?

**Comment by liach** [comment]
Then be careful. https://github.com/Mojang/LegacyLauncher/pull/11#commitcomment-13879102 At least try to avoid working on MinecraftForge directly next time.

**Pull request closed without merging**
