### PR TITLE
[Forge Animation System] Use doubles instead of floats to correct los…

### PR DESCRIPTION
**Pull request by Aeronica**
…s of precision over time.

#4121

### CODE REVIEW

**Comment by Aeronica** [comment]
I see this is probably a breaking change, Let me add some backward compatibility via the interfaces and the Animation class.

**Comment by LexManos** [comment]
No.
The proper method to fix this would just to localize the time as the float just needs to be an offset in the amination not the full world time.
No need to change from float to double thats just a hack 'solution'.

**Comment by Aeronica** [comment]
Thank you for your comment Lex. Here's my take on your suggestion. This is test code for discussion.

This change stores the total world time in the timeOffset upon the first call to the getWorldTime method and resets it to the new total world time anytime the player changes worlds. This ensures the float returned remains in a usable range without losing decimal precision for relatively short periods of time. That is the typical amount of time a player remains active in a world. typically only a few hours a day. If by chance a user were logged into a world continuously for several days, the effects of precision loss from the long to float cast would be seen.

Doing this removes the need to "hack" the animation system from floats to doubles as I did in this PR. 

```java
public enum Animation
{

    INSTANCE;
    static long timeOffset;
    static Object lastWorld;
    
    /**
     * Get the global world time for the current tick, in seconds.
     */
    public static float getWorldTime(World world)
    {
        return getWorldTime(world, 0);
    }

    /**
     * Get the global world time for the current tick + partial tick progress, in seconds.
     */
    public static float getWorldTime(World world, float tickProgress)
    {
        if (!world.equals(lastWorld))
        {
            timeOffset = world.getTotalWorldTime();
            lastWorld= world;
        }

        return (world.getTotalWorldTime() - timeOffset  + tickProgress) / 20;
    }

    /**
     * Get current partialTickTime.
     */
    public static float getPartialTickTime()
    {
        return Animation.getPartialTickTime();
    }
    
}
```

**Comment by mezz** [comment]
Would it be possible to reset it every Minecraft day or week? I don't imagine normal animations would last that long. Would there be any artifact when the animation time resets?
Also the solution should avoid storing `World` as a field since that can lead to World leaks.

**Comment by Aeronica** [comment]
Resetting the time during the time arbitrarily can causes the state machines to jump or miss a state causing incorrect animations. My suggestion only keeps a reference to the world to track when the player changes worlds/dimensions. Most players are only online a few hours at a time and resetting the world time offset when changing worlds minimizes any chance to cause issues with the state machine.

**Comment by bs2609** [comment]
It'd be better to save the dimension ID as an integer then.

**Comment by Aeronica** [comment]
I agree it's better to get the world hashCode and store it in an integer. 

```java
public enum Animation
{

    INSTANCE;
    static long timeOffset;
    static int lastWorldHashCode;
    
    /**
     * Get the global world time for the current tick, in seconds.
     */
    public static float getWorldTime(World world)
    {
        return getWorldTime(world, 0);
    }

    /**
     * Get the global world time for the current tick + partial tick progress, in seconds.
     */
    public static float getWorldTime(World world, float tickProgress)
    {
        int worldHashCode= world.hashCode();
        if (worldHashCode!= lastWorldHashCode)
        {
            timeOffset = world.getTotalWorldTime();
            lastWorldHashCode = worldHashCode;
        }
        return (world.getTotalWorldTime() - timeOffset  + tickProgress) / 20;
    }

    /**
     * Get current partialTickTime.
     */
    public static float getPartialTickTime()
    {
        return Animation.getPartialTickTime();
    }
    
}
```

**Comment by Niko-sk2x** [comment]
The hashcodes aren't guaranteed to be unique.

**Comment by Aeronica** [comment]
Barteks2x
What would you suggest?

**Comment by bs2609** [comment]
`world.provider.getDimension()`

**Comment by Aeronica** [comment]
bs2609
Thanks for that. world.provider.getDimension()
At this point I'll close this PR and create a new one.

**Comment by Landmaster** [comment]
@Aeronica You did not have to close and re-open the PR; adding commits will automatically update it.

**Comment by Aeronica** [comment]
This PR made a lot of changes to multiple files. I though it would be cleaner for me to start fresh since only one class needs to be changed.

**Comment by LatvianModder** [comment]
```java
@Override
public int compareTo(Event event)
{
    return new Double(offset).compareTo(event.offset);
}
```

What. Use `Double.compare(offset, event.offset);` in future

**Pull request closed without merging**
