### PR TITLE
Update gradle wrapper to 4.10.3

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
There's no point in staying at a 3 year old gradle version, so I updated it to the most recent version that still works (which isn't gradle 5 unfortunately).

### CODE REVIEW

**Comment by LexManos** [comment]
Except it breaks the hell out of ForgeGradle.... Except for that one small little detail!

**Comment by HoldYourWaffle** [comment]
Wait, what? What do you mean it breaks FG? I've been using forge with gradle 4 since basically always, never experienced any problems. Am I missing something obvious here?
I asked on the discord if there was a reason for staying on 2.14, and people said that is was just because nobody bothered to update it. I figured I'd be the one to bother then.

**Comment by LexManos** [comment]
That's news to me, last time we tried to upgrade to 3.x+ FG broke horribly., What with the use of internal APIs and all.
Get a full test suite and prove that it works, Then we can consider it, but like I said, last time we looked into it it broke a lot of things.
And HONESTLY, there isn't much reason to update the wrapper. As that the entire point of the wrapper, to have a single stable functional setup that doesn't interfere with anything else.

**Comment by JamiesWhiteShirt** [comment]
Good defaults are a thing, but they are only good defaults if we can verify that they work. FWIW I'll add that 4.6 has been working fine for me and some others for a while now.

**Comment by LatvianModder** [comment]
Im using 4.9 with no problems (I have only used `setupDecompWorkspace` and `build` though). I heard only 4.10 breaks FG

**Comment by kierajreed** [comment]
Anyways, isn't ForgeGradle 3 using a newer Gradle already?

**Comment by LexManos** [comment]
FG3 will be tightly bound to Gradle version yes, but it is intended to be 4.10.x compatible when released fully.

**Comment by HoldYourWaffle** [comment]
Tightly bound as in can't use with another version or tight bound as in "we're using a lot of deprecated features"?

If there's going to be an update soon anyways there's no point in updating this right now.

**Comment by kierajreed** [comment]
I assume Lex means that FG3 will (when released) use a newer Gradle version (4.10.x) but it will also use many features that may change between versions, so it will then stay at 4.10.x until FG4.

**Comment by kierajreed** [comment]
And assuming FG3 is released soon then yes, this isn't worth the effort. However, if FG3 takes a long time to release this may be worth doing.

**Pull request closed without merging**
