### PR TITLE
Check name used for tile entity registrations

### PR DESCRIPTION
**Pull request by bs2609**
This checks the name used when registering tile entities, as is done for `IForgeRegistryEntry` instances when the registry name is set.

The main reason for performing the check here is due to the fact the method takes a `String` parameter, despite the fact the underlying registry uses `ResourceLocation`s (since 1.11). As a result, some tile entities are still being registered using old names, although they are no longer correct.

The checking code is moved into a separate `GameData` method, rather than being part of `setRegistryName`, so it can be reused here.

This also includes a fix for a test mod which was missing a proper namespace for its TE.

### CODE REVIEW

**Comment by diesieben07** [comment]
If I understand correctly, this will break existing mods that just use un-prefixed names (sadly most of them). Previously that would register them as `minecraft:someId`, whereas now it becomes `modid:someId`, right?

**Comment by covers1624** [comment]
No this wont actually, the existing key is passed through to `TileEntity.register`. All this will do is throw warnings in the console to encourage them to fix registrations. Perhaps a TODO for 1.13 should be added to enforce the changes made by `checkPrefix` on the tile being registered.

**Comment by AlexiyOrlov** [comment]
So, if I have been registering my tile entities with strings like "modid-name", I should change it to "modid:name"?

**Comment by HenryLoenwind** [comment]
Just a general question: Last time I checked, that registration was only used for 2 things: Instantiating the TileEntity when it is loaded from the save file and a reverse lookup for a crash message. However, this instantiating is done after the blocks have been loaded. In all other cases the block is asked to instantiate the TileEntity. So, I have no idea why this registration is needed, can someone enlighten me?

**Comment by covers1624** [comment]
If you have been registering your tiles with `modid-name` then technically on disk your tiles have the id of `minecraft:modid-name`, so yes you should move over to registering with `modid:name`, im not entirely sure on migrating existing tiles in world, haven't needed to look in to it personally.  
That's exactly why tiles are registered, for save files. In theory yes the block could just be fully responsible for creating the tile and no registration would be needed, and knowing mojang is probably legacy code.

**Comment by williewillus** [comment]
a datafixer to fix your bad id's (and only *your* bad id's) could be a way to migrate

**Review by liach — APPROVED** [review]

**Comment by mezz** [comment]
Would it make sense to add a `registerTileEntity` method that takes a `ResourceLocation` instead of `String`?

**Comment by HenryLoenwind** [comment]
I think it'd make more sense than to suddenly warn about something nobody could have expected to take a resource location string...

(On the other hand, what in Forge makes sense? Like registering an entity using the mod instance warns about "doing game activity"...)

**Comment by mezz** [comment]
Sorry didn't see that this was updated.
Looks good to me. 
Should the old String method be deprecated so we can remove it in 1.13, or is there a use for it?

**Comment by bs2609** [comment]
Depends, what do you think about defaulting to the registering mod in 1.13, as suggested here https://github.com/MinecraftForge/MinecraftForge/pull/4681#issuecomment-358587025?

**Comment by HenryLoenwind** [comment]
...or just drop it completely?

**Comment by mezz** [comment]
I think this is fine as-is for now. Assigning to Lex to get his opinion.

**Comment by josephcsible** [comment]
If anyone needs an example of how to fix the warning caused by this change without breaking old saved games, I just updated all of McJty's mods to use a DataFixer to do so.

**Pull request merged**
