### PR TITLE
[1.12] OverlayHandlers for Item and Armor Glint Modification

### PR DESCRIPTION
**Pull request by RANKSHANK**
## Overview
This allows modders to customize the overlays that is rendered over item and armor models when hasEffect() returns true. 

Included test mod attaches overlay handlers to head, chest, and foot leather armors. Enchant them and they're visible in their respective states. 

## Methodology
Mdders create a respective I(Stack/Armor)OverlayHandler singleton, and register it to the item instance. These are stored in a list in an item so that they may be cascaded in the event that multiple OverlayHandlers are viable. The first OverlayHandler to return true for the handleOverlay() check is then used to render the overlay, eventually falling back to the vanilla glint if all handlers fail. This system allows for things such as enchantments to change the overlay when appropriate, without entirely overriding them when not necessary. This also allows for attaching OverlayHandlers to pre-existing items without replacing thier instances. Colors fall under a seperate type of OverlayHandler for ease of manipulation.

## Additional Info
The rendering for the stack overlay pass has been streamlined in a bid to offset performance cost. It now forgoes constant map lookups for IItemColor. This has not been reiterated since the last PR (#3514) , therefor the results from tests on the previous PR should still be relevant.

### CODE REVIEW

**Comment by Samuel-Harbord** [comment]
I'm looking for exactly this at the moment. I couldn't find any way to do this without a CoreMod. I would really like to see this get pulled soon.

**Comment by mezz** [comment]
This is good but I think that in its current state it is waaay way overkill.
I do not see much benefit to having a complicated resolution system for this. I think ideally each item or armor can have one handler, or none to fall back on vanilla.

**Comment by RANKSHANK** [comment]
@mezz  sorry about the delayed response, uni's in full swing at the moment.

The cascading handler is a pretty messy/over the top solution I do agree.  And I'm definitely up for discussion on the matter.

I think this cascaded system is important for instances where modders wish to use non singleton specific metadata such as capabilities or NBT(enchantments) to determine and attach handlers, there needs to be a way to attach handlers that'll allow these forms of metadata to commingle with the preexisting handlers, if there are any. For example, if a mod allows potions to be applied to any sword/axe as a topical toxin, and then applies an overlay to give feedback of the type of potion that is in effect, the mod would have to replace the preexisting handler. Which means that the original overlay that was intended to be used for the item would no longer exist, and thereby prevent the original data from being relayed to the user. EG. in Botania's case, if the manasteel sword implemented mana feedback with an overlay, it would display nothing except for the potion that was applied.

Of course, modders could **theoretically** wrap the preexisting handlers themselves, but as we've seen many times, sensible modding practice is a rarity. I believe it'd be easier to force the wrapping to prevent a flood of things like _'my power armor no longer shows its shield level, I have 300 mods installed'_ from coming in.

**Comment by mezz** [comment]
What you've put together seems to be bigger than just about any other single feature in Forge.
There is something wrong here, I don't think it can be that complicated...

**Comment by RANKSHANK** [comment]
@mezz technically it's a dual feature PR since the effect rendering is handled differently by armor & stacks. I could roughly halve the size by splitting it into separate PR's, but in I think it's easier to cover both of the bases in one go, since they're so similar.

Test class: 175 lines
Copyrights: 114 lines 
Method/Variable Documentation: 164 lines

Nett 'excess' lines: 453 lines
PR sans excess lines: 839 lines
Lines per feature: ~420 lines

I opted to transcribe the respective renderEffectOverlay() for the armor and stacks, as that reduces the patches to the rendering classes to two single line changes. The for loops were removed in the transcribed code, and each pass is set out explicitly, to improve readability. The respective 'manager classes' could be done away with to reduce size, at the cost of larger patches, but I've written it as such for those given reasons.

I've also split each interface into 2 classes, one for animation, one for color, so that modders can opt into just changing the color of things, in cases that they want to use the same animation with different colors or vice versa. This could be squished down to a singular interface; since each interface has its own subscription method, this would shrink the PR by a good handful of lines, and instead relying on inheritance to fine tune these aspects.

**Pull request closed without merging**
