### PR TITLE
Added all `canBeConnectedTo` calls

### PR DESCRIPTION
**Pull request by Wyn-Price**
Changed `FenceBlock`, `PaneBlock` and `WallBlock` to use `IForgeBlockState#canBeConnectedTo` for connection logic. This allows mods to control if a fence/pane/wall can connect to it. 

### Why not Tags?
A cleaner solution for this would be to just use tags for having the blocks be able to connect to the different types. (To connect to fence blocks, add the `FENCE` tag). A problem to this would be if you need more sensitive information, as tags are per block only.

### CODE REVIEW

**Comment by LexManos** [comment]
Why would you want to disable the connection of fences to solid blocks? I am not seeing the need for the ternary result.
Also, this is massive binary breaking, since we have moved to the RB phase of 1.14, this isn't allowed.

**Comment by TeamSpen210** [comment]
In Vanilla fences are disallowed to connect to pumpkin and melon blocks, so them growing doesn't magically change the shape of fences nearby. Additionally leaves and barrier blocks are disallowed. See `Block.cannotAttach()`.

**Comment by LexManos** [comment]
Block.cannotAttach is for backwards compatibility behavior wise with things that were accidentally not connecting that should of been. Pumpkins and melons were originally non-full blocks for some reason, and thats why they are on the list.

**Comment by Wyn-Price** [comment]
`Block#cannotAttach` was my main reason for having the ternary result. If it's just for backwards compatibility purposes, then I could probably just revert to before [e8gd21d](
https://github.com/MinecraftForge/MinecraftForge/pull/6129/commits/e8fd21d6364cf491d8c2a46b8ec87af3b497c6e0)

**Comment by LexManos** [comment]
I am still not convinced that this is needed at all.
My point in the last comment was that the edge cases that vanilla explicitly has is to maintain behavior that was broken when they fixed the initial bugs.
Your current rationalization is "because I want it" and that isn't good enough. I would rather not introduce edge cases that we have to support ad infinitum.

**Comment by Wyn-Price** [comment]
As it stands, there isn't any way to control fence connections based on tile entity data. This wasn't the case in 1.12 and was something I relied on. The point of this PR isn't to allow for fence connection blocking, that was removed in https://github.com/MinecraftForge/MinecraftForge/pull/6129/commits/15bf4c193dac609834166749826daaa7037da3c1, it's point is to allow for tile entity data based fence connections.

**Comment by LexManos** [comment]
Why do you need TE based connectivity?

**Comment by Wyn-Price** [comment]
The main use I have is for secretroomsmod, whereas blocks mirror other blocks. The block that's being mirrored is kept in the tile entity data. Currently, fences won't connect with mirrored fences. Although I do understand that is quite a big patch for something so niche.

**Comment by LexManos** [comment]
It's probably worth categorizing your mimic blocks, into different block states that support the behaviors you want.
Creating a ton of TE derived shunts of vanilla functions is counter to what Mojang is trying to do overall.
Yes, it used to be what Forge did back in the day before BlockStates existed. But we are trying to move Minecraft in the same/better direction as Mojang, not backwards.

**Pull request closed without merging**
