### PR TITLE
[1.12] Clean up patches for calls to profiler using getSimpleName()

### PR DESCRIPTION
**Pull request by bs2609**
This remakes the patch from #3873 to be more like #3887.

It also reduces the overhead of profiling by using a `ClassValue` to cache the result of `getSimpleName()`.

### CODE REVIEW

**Comment by LexManos** [comment]
Do you have a profiler setup for testing how fast ClassValue is? Seems to be interesting... but im curious if it is actually different.

**Comment by mezz** [comment]
I wouldn't bother with the cache, the whole vanilla thing is a bit flawed because vanilla tile entity class names are obfuscated, and modded simple names are not unique enough to identify things accurately.

**Comment by asiekierka** [comment]
Yes, I think getName() should be the one called in all cases involving class names in a modded environment. There can easily be very many BlockPipe classes in one modpack, and this will make it easier to tell them apart in the in-game profiler. (Also, for getName(), the string is cached by Java itself already)

**Comment by bs2609** [comment]
Here's some sampling snapshots taken for performance testing:

Using 'The Void' superflat preset, in creative mode, peaceful difficulty.
Ran `/fill ~-90 ~-1 ~-90 ~90 ~-1 ~90 minecraft:furnace` to create a lot of tile entities.
Fired up VisualVM and took some readings.

`getSimpleName()`:
entities_getsimplename

`getName()`:
entities_getname

`ClassValue.get()`:
entities_classvalue

**Comment by bs2609** [comment]
`getName()` is the fastest option here, and would give some extra context, it's probably better than `getSimpleName()` in a modded environment.

One other possible alternative that can be done using the `ClassValue` approach is to take the registry name of the tile entity and use that as the profiler section name. That might be a little more user friendly in profiling output.

**Comment by mezz** [comment]
I think you should use `getName()` then, as long as the text for the pie chart is still readable on the screen.

**Comment by bs2609** [comment]
`getName()` actually breaks the profiler somewhat, as it uses "." to delimit sections.

See the following `/debug` profiling extracts:

`getName()`:
```
[00] levels - 98.48%/98.48%
[01] |   Forge - 99.89%/98.37%
[02] |   |   tick - 99.91%/98.28%
[03] |   |   |   entities - 88.96%/87.43%
[04] |   |   |   |   blockEntities - 99.85%/87.30%
[04] |   |   |   |   players - 0.09%/0.08%
```

`getSimpleName()`:
```
[00] levels - 97.87%/97.87%
[01] |   Forge - 99.87%/97.74%
[02] |   |   tick - 99.87%/97.61%
[03] |   |   |   entities - 86.24%/84.18%
[04] |   |   |   |   blockEntities - 99.79%/84.00%
[05] |   |   |   |   |   unspecified - 93.69%/78.70%
[05] |   |   |   |   |   TileEntityFurnace - 6.31%/5.30%
[04] |   |   |   |   players - 0.15%/0.12%
```

Registry name:
```
[00] levels - 98.58%/98.58%
[01] |   Forge - 99.92%/98.50%
[02] |   |   tick - 99.92%/98.42%
[03] |   |   |   entities - 91.66%/90.21%
[04] |   |   |   |   blockEntities - 99.87%/90.10%
[05] |   |   |   |   |   unspecified - 87.97%/79.25%
[05] |   |   |   |   |   minecraft:furnace - 12.03%/10.84%
[04] |   |   |   |   players - 0.09%/0.08%
```

**Comment by asiekierka** [comment]
In this case, using cached registry names might be the best option. You should try preparing benchmarks using JMH, however, to get more accurate information about the overhead of each.

**Comment by mezz** [comment]
I agree registry name looks much more useful.
I think you don't really need benchmarking, in your controlled test world the `unspecified` section is measuring the profiler overhead. You can see it's pretty high for `getSimpleName`. I'm a bit surprised it's high for the registry name implementation, but I'm not too worried about it as long as it's only impacting things when the profiler is active.

**Comment by bs2609** [comment]
For further comparison, here's a profile extract just using a hardcoded string, no names at all.

```
[00] levels - 98.69%/98.69%
[01] |   Forge - 99.92%/98.61%
[02] |   |   tick - 99.92%/98.53%
[03] |   |   |   entities - 90.90%/89.56%
[04] |   |   |   |   blockEntities - 99.86%/89.44%
[05] |   |   |   |   |   unspecified - 87.44%/78.21%
[05] |   |   |   |   |   any - 12.56%/11.23%
[04] |   |   |   |   players - 0.09%/0.08%
```

You can see that most of the remaining overhead is due to the `startSection()`/`endSection()` calls themselves.
Based on the proportion of time taken by the actual ticking here, `getSimpleName()` is responsible for about half the profiler overhead, so avoiding it seems like a worthwhile improvement.

**Comment by mezz** [comment]
Tested and looks good to me.

**Comment by LexManos** [comment]
I'd still like to see some profiling of the ClassValue functionality, not in-game, in a unit test compared to other values.
Because at the end of the day it's basically a hashmap wrapped in a crapload of other code. Which can be slow.
If it wasn't for the fact that this is a breaking change i'd pull this right now. You should keep the method in Profiler and just fix the name.

**Comment by bs2609** [comment]
If you want performance data on `ClassValue`, check the [mlvm-dev](http://mail.openjdk.java.net/pipermail/mlvm-dev/) mailing lists. ([April](http://mail.openjdk.java.net/pipermail/mlvm-dev/2016-April/thread.html), [May](http://mail.openjdk.java.net/pipermail/mlvm-dev/2016-May/thread.html) and [June ](http://mail.openjdk.java.net/pipermail/mlvm-dev/2016-June/thread.html) 2016)

**Pull request merged**
