### PR TITLE
Fix #3662

### LINKED ISSUE #3662: [1.11.2] Items render backwards in item frames
If you add an item with the default-item Forge Transform it will render backwards in an item frame. I assume this has to do with the FIXED Transform Type.

Notice how the drip is on the left in my hand but on the right in the frame. 
Forge 13.20.0.2223

### PR DESCRIPTION
**Pull request by williewillus**
Missing case from vanilla's item/generated.json, fixes #3662

### CODE REVIEW

**Comment by LexManos** [comment]
Remember that commit messages == change logs so please be descriptive

**Comment by williewillus** [comment]
okie, fixed

**Comment by liach** [comment]
Will that issue be get closed when this commit is merged? I don't think so since you removed `fix #xxx`

**Review by liach — APPROVED** [review]

**Comment by williewillus** [comment]
I can just close it then

**Pull request merged**
