### PR TITLE
Expose CriteriaTriggers.register, closes #4109

### LINKED ISSUE #4109: [1.12] Can't register new ICriterionTrigger
I want to register new ICriterionTrigger with CriteriaTriggers to use it in advancement-json, but ICriterionTrigger.REGISTRY and ICriterionTrigger.register is private so I can't do it.

### PR DESCRIPTION
**Pull request by williewillus**
Title.

### CODE REVIEW

**Comment by liach** [comment]
Are you sure that's what all we need?

**Comment by liach** [comment]
Yes, this pull is great for now.

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
I will refer to #4109 since that issue is not linked here yet.

**Comment by mezz** [comment]
Can you add a test mod? This is really simple but I want to be able to test that it's all we need.

**Comment by williewillus** [comment]
I don't see the need since many modders have been using this registration call without problems since 1.12 came out, but sure

**Comment by Draco18s** [comment]
Poking my nose in to say that I've been using the modified method without issue and to be notified of changes (so I can stop using reflection when this is merged).

**Pull request merged**
