### PR TITLE
 [1.15.x] Re-implement the Config GUI

### PR DESCRIPTION
**Pull request by Cadiboo**
PR containing only the Config GUI implementation from #6421. 
- Adds the mods list button to the in game menu screen
- Re-implements the config GUI
- Adds a test mod for the config system
- Mostly re-implements FML's dummy config GUI

Screenshots:

### CODE REVIEW

**Comment by Cadiboo** [comment]
I initially planned to implement client -> server config syncing (with authentication obviously) for configs with the `SERVER` type, but I've recently had some recent IRL events limit my free time so I'm submitting this as-is with plans to add server config syncing at a later date

**Comment by lizzyd710** [comment]
So the config button being disabled in the game menu is a Forge problem, not a problem with the mod code?

**Comment by l-Luna** [comment]
Minecraft forge doesn't have a config menu, currently, so mods can't have in-game config

**Comment by DaemonUmbra** [comment]
From what I've seen it's something mods can make, it's just that basically no mods have and Forge doesn't currently provide a default.

**Comment by AzureDoom** [comment]
Any update on this?

**Comment by Cadiboo** [comment]
> Any update on this?

Coming soon:tm:. I've gotten some feedback from the Forge team about this PR and accepting that feedback will require major changes to this PR. Since these changes are so big, I've tried to set something up so I can talk with all them about what their ideal Config GUI design would be, no word back from them yet.

I also needed some feedback from @TheElectronWill on #6464 that I haven't gotten so that needs a cleanup as well. There's also another issue with `List<Enum>` becoming `List<String>` when serialised and then deserialised in NightConfig that causes weird issues with the Config GUI.

**Comment by Minecraftschurli** [comment]
Has anything changed since the last update?

**Comment by Cadiboo** [comment]
No, I've got very little free time, but this is at the top of my list. I think it might be better to wait for 1.16 until I try to tackle this again though.

**Comment by ExpensiveKoala** [comment]
What all needs to be done to this other than porting to 1.16?

**Comment by Cadiboo** [comment]
Based on the feedback from the forge team, I need to rewrite this entirely. 1.16 is here and I’ll be working on it soon (not :tm:)

**Comment by ExpensiveKoala** [comment]
What was wrong with this implementation that prompts a complete rewrite?

**Comment by Cadiboo** [comment]
The widgets design I think

**Comment by jarquafelmu** [comment]
I really hope this gets merged soon and is for the 1.15.2 version of Forge as well, not having this is super painful

**Comment by Cadiboo** [comment]
This PR won’t get merged and I’ve been reimplementing it for 1.16.2 so I doubt it will be made for 1.15. It’s not super hard to get a basic GUI working though. It’s just lists and sub configs (not categories) that are hard because they’re mutable and undoing changes & nesting becomes a headache. https://github.com/Cadiboo/MinecraftForge/tree/config-gui-1.16

**Pull request closed without merging**
