### PR TITLE
added a hook that allows for post rotating the biped model.

### PR DESCRIPTION
**Pull request by AbsolemJackdaw**
need this myself so i can rotate the player's arm to give it a pet animation.
other uses can imply the emote mod, and people trying to make better animations for the player.

### CODE REVIEW

**Comment by AFlyingGrayson** [comment]
This would be very helpful for my mod. Currently you either have to make use of a class transformer, which isn't ideal, or replace each individual ModelRenderer with your own, which is also a hassle.

**Comment by mattmess1221** [comment]
You should expand this to the other entities.

**Comment by AbsolemJackdaw** [comment]
other entities have different models. i'll not be making a pr for every different model out there. not soon at least.

**Comment by shadowfacts** [comment]
Individual PRs shouldn't try to solve multiple problems like this. One feature/fix per PR.

**Comment by AbsolemJackdaw** [comment]
this was not supposed to happen. sorry

edit : fixed it

**Comment by AbsolemJackdaw** [comment]
sorry, I messed up ! new renewed pr comming soon. had trouble with a pull and reinitialized all by mistake ...

**Comment by AbsolemJackdaw** [comment]
had to make a new PR... I'm very sorry I messed up my branch/master git stuff !! 

renewed :
https://github.com/MinecraftForge/MinecraftForge/pull/3350

**Pull request closed without merging**
