### PR TITLE
true/false -> Yes/No in the config gui

### PR DESCRIPTION
**Pull request by ChunHin**
Description already include in the title.

### CODE REVIEW

**Comment by heldplayer** [comment]
Not sure this should be translated, as it's the actual value in the config.

**Comment by ChunHin** [comment]
Yes, I keep the actual value in the code.
I just change the display string

**Comment by GotoLink** [comment]
You could use vanilla "gui.yes/gui.no" or "options.on/options.off", to avoid adding unnecessary translation, and keep in line with other game options.

**Comment by ChunHin** [comment]
gui.yes=Yes
gui.no=No
options.on=ON
options.off=OFF

Before, it will show `true` and `false`.
Probably ok, but will break the translation in the en_US.lang
`forge.configgui.disableVersionCheck.tooltip=Set to` **true** `to disable Forge's version check mechanics. Forge queries a small json file on our server for version information. For more details see the ForgeVersion class in our github.`
I don't want to edit en_US.lang too much but I don't mind if I do so.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
