### PR TITLE
Make vanilla powered rails receive power from mods' custom powered rail subclasses

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by Eragonn1490** [comment]
Did you add an example mod? I can see how this can be useful

**Comment by josephcsible** [comment]
I can, but does every little tweak really need one? We'd quickly end up drowning in them.

**Comment by Eragonn1490** [comment]
I’m not sure how lex feels about small things but I think it’s good practice to do it anyway

**Comment by williewillus** [comment]
I don't think this needs one, it's usually for the bigger or riskier changes

**Comment by liach** [comment]
Can you just take a screenshot showing that this patch allows natura blaze powered rails to power vanilla powered rails?

**Comment by JamiesWhiteShirt** [comment]
Would it be preferable to add a Block method that returns a boolean instead? Puts less restriction on which classes one could use for this.

Maybe not that necessary seeing as the method assumes the blockstate uses the `BlockRailPowered.SHAPE` property, however.

**Comment by liach** [comment]
Your idea might create too many meaningless methods @JamiesWhiteShirt (`isAxe`, `isShear`, `isSword`, `isPickaxe`, etc)

**Comment by josephcsible** [comment]
@liach Sure, I'll post one tonight.

@JamiesWhiteShirt I'm not really a fan of that idea either.

**Review by liach — APPROVED** [review]

**Comment by williewillus** [comment]
as stated in #4772, this changes vanilla behaviour. this probably needs to be reverted, or patched to exclude the case where both rails are vanilla rails.

**Comment by josephcsible** [comment]
Definitely not reverted, as the behavior is clearly wanted in the case of vanilla powered rails to modded powered rails. I'll look into patching it.

EDIT: #4774

**Pull request merged**
