### PR TITLE
Fixed map extension recipie.

### PR DESCRIPTION
**Pull request by strnadpetr**
(cherry picked from commit a7d5820)

### CODE REVIEW

**Comment by covers1624** [comment]
Forge is targeting 1.10. Why are you still on 1.8.9??

**Comment by Dragonkin** [comment]
Because many mods are still not 1.10 compatible and this is a simple cherry pick?

**Comment by strnadpetr** [comment]
Because many mods are still not 1.10 compatible and this is a simple cherry pick?

**Comment by covers1624** [comment]
What mods? It is such a trivial update. If mods haven't moved to 1.10 that's their issue, they should just spend 5 minutes and update.

**Comment by strnadpetr** [comment]
Buildcraft, OpenComputers, ...

And honestly, I don't see what all the fuss is about - it's not like this is a big change. There are two changed lines, in a single commit, which has _already been tested in 1.10_

(To be frank, I would even build and host the modified version of forge somewhere myself, but while 1.10.2 compiles without issues, compilation of 1.8.9 branch fails with `java.io.FileNotFoundException: Inherited json file (null) not found!`)

**Comment by Madsthunder** [comment]
Just saying, you might want to sign the CLA.

**Comment by strnadpetr** [comment]
I did. When I click on it again, it even says that I signed it, but doesn't update here -_-

**Comment by loordgek** [comment]
OC for 1.10 https://minecraft.curseforge.com/projects/opencomputers/files/2320101
and BC is in the works https://github.com/BuildCraft/BuildCraft/tree/8.0.x

**Comment by 0xilly** [comment]
@Dragonkin I suggest you read Lex's comment in this [issue](https://github.com/MinecraftForge/MinecraftForge/issues/3236#issuecomment-245682125) while not 1.7.10 the same rule applies.

**Comment by strnadpetr** [comment]
Yes, BC is in the works. _For Minecraft 1.9.4_ which still has this bug in Forge. Also considering that the "Buildcraft 1.9.4 coming soon™" came in May, I'm not getting my hopes up.

Considering that four people have spent collectively more than half hour saying "no" here, I suppose that building a 1.8.9 branch of Forge is as complicated as is building it locally?

**Comment by LexManos** [comment]
Just update your damn mod there is NO excuse to be on 1.9.4 instead of 1.10.1 THE MODS LITERALLLY JUST WORK no recompile needed. We won't bend over backwards to support you being lazy.

**Pull request closed without merging**
