### PR TITLE
Add a hook to allow continuously using items through stack changes

### PR DESCRIPTION
**Pull request by bs2609**
Adds a new method, `Item.canContinueUsing`, which is called via a hook in `EntityLivingBase.updateActiveHand` to determine if an item can continue to be used.

Currently, there is a strict equality check between the item stack marked as 'active' and the stack in the current active hand. If the stack changes in any way, then `resetActiveHand` is called and the item use is aborted.

With this PR, if the item returns that it can continue to be used, the active stack is updated to the current held item, causing the check to pass and usage to continue.

This hook is similar to the existing `shouldCauseReequipAnimation` method, but is targeted at items that have an "ongoing" use, like the bow.

A test mod is included, which adds an item using this hook. Without it, the item will keep resetting it's "in use" state as it takes damage.

### CODE REVIEW

**Comment by LexManos** [comment]
Why?

**Comment by ChloeDawn** [comment]
Wouldn't it be simpler to just add a `shouldCauseReequipAnimation` hook in `updateActiveHand`, rather than creating a new method?

**Comment by bs2609** [comment]
This isn't quite the same as what `shouldCauseReequipAnimation` controls, although they are related.

I would expect items which override this method to also override `shouldCauseReequipAnimation`, but not necessarily the reverse.

As you can manually stop item use, I don't really think any functionality would be _broken_ by that change, but I don't really think it makes things simpler - the biggest 'saving' is the method on `Item`, which is mostly Javadoc anyway.

`shouldCauseBlockBreakReset` is a seperate method, and I feel this is clearer as one too.

**Comment by KingLemming** [comment]
This can already be done. It doesn't need a hook.

**Comment by ChloeDawn** [comment]
How do you do it?

**Comment by bs2609** [comment]
@KingLemming, mind elaborating?

**Comment by LexManos** [comment]
I dont think this is necessary, you havent explained why its actaully needed to my satisfiaction. And KL said it can be done without this hook so you should be fine.

**Comment by bs2609** [comment]
I do not feel like it has been satisfactorily explained _how_ it can be done without this hook.

I don't think it's fair to reject a PR for not sufficiently explaining its use case, while citing a comment made with no explanation or supporting examples at all.

**Comment by JamiesWhiteShirt** [comment]
The supposed workaround for this is manually setting the held ItemStack in the active hand to the desired ItemStack instance. I don't know how well that works in practice, though. Could be challenging if the client receives a new ItemStack from the server.

**Comment by thiakil** [comment]
The need for it was explained in the OP (emphasis added).

> A test mod is included, which adds an item using this hook. **Without it, the item will keep resetting it's "in use" state as it takes damage.**

If the itemstack changes in a way that affects `equals`, the 'hold to keep using' action stops.

You *can* do a lot of things without support in Forge, but the non-forge solutions to this are hacky and should not be necessary.

**Comment by LexManos** [comment]
Yes, but looking around it should be simple enough if you keep track of what values actually need to be changed and what doesnt. And not storing/updating the NBT until you actually need to.
Beyond that the way this was implemented isn't safe enough for me, as it allows any random things to claim what they want and easily desync the client and server. 
If @KingLemming feels like explaing what he meant he can. But I'm not gunna open up yet another hack to 'fix' the hacks you guys are doing.

**Comment by LatvianModder** [comment]
Do capability changes trigger it? If not then you can just use caps

**Comment by mezz** [comment]
I asked KL and I think he was thinking of re-equip animation so I'm going to re-open this.

**Comment by mezz** [comment]
Please update this to resolve merge conflicts.

**Comment by thiakil** [comment]
@LatvianModder if you change any stored values that you happen to serialise, caps make it easier to come across.

**Comment by brandon3055** [comment]
I have not looked into exactly how it works but we already have shouldCauseBlockBreakReset that I assume does something similar but for block breaking. Wouldn't it be better to just expand the functionality of this method and rename it to something like "shouldCauseItemActionReset"?

**Comment by mezz** [comment]
Please update this to resolve merge conflicts

**Review by tterrag1098 — APPROVED** [review]

**Comment by mezz** [comment]
Please update this to resolve merge conflicts again

**Pull request merged**
