### PR TITLE
Add missing license headers

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR adds license headers to those classes that don't have them, and fixes some of the classes' license headers.

The changes in the commit are the exact results of running the `updateLicenses` task.

### CODE REVIEW

**Review by ramidzkh — APPROVED** [review]

**Comment by ichttt** [comment]
Can you make the `installerJar` task depend on `checkLicenses` so we notice when people don't have the license header?

**Comment by ichttt** [comment]
It seems giga added the headers in 600e68cace29933a0895b66c2ee98f31976a6a87

**Comment by sciwhiz12** [comment]
Shall I close this PR then, or keep it open and change its purpose to solely adding the `checkLicenses` dependency on `installerJar`? I did [ask gigaherz on Discord][gigaherz_comment] about whether this PR should be closed, and he said that the decision to merge this will be up to Lex, because of  the change to `installerJar`.

[gigaherz_comment]: https://discordapp.com/channels/313125603924639766/725850371834118214/747572499231014912

**Comment by sciwhiz12** [comment]
[Closing.][lex]

[lex]: https://discordapp.com/channels/313125603924639766/725850371834118214/748367494691160176

**Pull request closed without merging**
