### PR TITLE
Initialize sources list

### PR DESCRIPTION
**Pull request by techbrew-mc**
Fixes crash NPE thrown by addFile()

### CODE REVIEW

**Comment by matthewprenger** [comment]
:+1: Just noticed this too

**Comment by LexManos** [comment]
What build does this start happening?

**Comment by matthewprenger** [comment]
Commit a703367 from cpw today.

**Comment by techbrew-mc** [comment]
The builds in question are 1604-1606.  1603 is fine.

**Comment by cpw** [comment]
Heh. Stupid missed that.. Sorry.

**Pull request merged**
