### PR TITLE
Bring back versioned subfolder in mods dir

### PR DESCRIPTION
**Pull request by JoJoDeveloping**
It's a feature I particularly liked.
You might argue that one should use different folders for each modded instance, but I often ended up using forge instead of vanilla so I could have optifine and maybe a minimap mod.
Optionally seperating the mods folder per version allows to keep the default minecraft folder with all its worlds around and still use forge without hassle when switching versions.
Edit: what this actually does is that if say "/home/user/.minecraft/mods" is a (the) directory where the ModsFolderLocator loads stuff from, then it will also try to look in "/home/user/.minecraft/mods/\<version\>", eg "/home/user/.minecraft/mods/1.13.2"

### CODE REVIEW

**Comment by cpw** [comment]
No

**Comment by JoJoDeveloping** [comment]
:sob:

**Comment by mattmess1221** [comment]
Versioned mods folders are no longer needed. Instead, you can just create a new profile using the launcher and set the game directory..

**Comment by JoJoDeveloping** [comment]
What if I want to keep the default game directory?

**Comment by DaemonUmbra** [comment]
Why are launcher profiles and separate game directories not a viable option for what you are doing?

**Comment by JoJoDeveloping** [comment]
Because that would mean copying worlds, resourcepacks, the options.txt and possibly other stuff around all the time.

**Comment by LexManos** [comment]
Then you can specify a modlist text via launch arguments. As for your argument about copying worlds and options. this is the exact reason special mods folders are a bad idea. Worlds usually are not cross version/cross modpack compatible. And neither are configs. if any mods add keybindings.

**Comment by timriker** [comment]
This means that keyboard settings, mod caches (ie: tile caches for mapping mods) and other items all need to be duplicated and kept in sync. The mods/<version> was a Good Thing. Here's hoping it returns.

**Pull request closed without merging**
