### PR TITLE
added MDK package

### PR DESCRIPTION
**Pull request by AbrarSyed**
I named it with -mdk for now.. if you still want it -src let me know...

### CODE REVIEW

**Comment by ziggurism** [comment]
What does it mean? I went looking for Minecraft Forge source, but for latest version only find MDK. Is it same thing? What does MDK stand for?

**Comment by diesieben07** [comment]
Mod Development Kit. Source doesn't really make sense, since there is no source included in it.

**Comment by cpw** [comment]
Yup. It's a starter development kit for mods. So "mod development kit" seemed to make sense. The one thing it definitely didn't contain was source code for forge.

**Comment by ziggurism** [comment]
Ok, thanks for clarifying. It's a little confusing for a newbie following the directions at http://www.minecraftforge.net/wiki/Installation/Source (like me). I'll see if I can add a sentence to the wiki.

**Comment by ziggurism** [comment]
i registered an account for the wiki, but was unable to log in. So no update.

**Pull request merged**
