### PR TITLE
Add extented getQuads method with world and block pos arguments

### PR DESCRIPTION
**Pull request by Fadenfire**
I'm making a mod with connected textures, and in my connected textures model I need world and block pos access to check surrounding blocks. This pull adds a second `getQuads` method to `IBakedModel` that has world and block pos arguments.

I know I could use extended states to get the world and block pos but I would like resource pack creators to be able to use my connected textures model on any block, not just blocks I put the extended state on.

### CODE REVIEW

**Comment by Wyn-Price** [comment]
This isn't really needed, assuming you only want to do it for your own blocks. Instead of adding a whole new method, you could just create an extended state with the surrounding blockstates as an IUnlistedProperty, then in IBakedModel just get the blockstate and do whatever you want

**Comment by Fadenfire** [comment]
I know I can do that, but I want to be able to use the model with blocks that aren't mine.

**Comment by tterrag1098** [comment]
The problem you are having is valid, but this is the wrong solution IMO. The model doesn't need to know any more information than the state, I think the issue is the implementation of extended states. There is not really any good reason to have them limited to a predefined set of keys since they are never serialized. If extended states were simply a data bean of key->value pairs, you could just add on to it as you wish. Adding world/pos to the model params is bad separation of concerns and introduces more potential thread safety issues.

Side note, if you'd like to avoid doing the work yourself, I have already accomplished this in my mod CTM

**Comment by LatvianModder** [comment]
Or just use Connected Textures Mod...

**Comment by Fadenfire** [comment]
@tterrag1098 So perhaps an event for adding properties to extended states would be better?

**Comment by loordgek** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4803#issuecomment-373873824

**Comment by tterrag1098** [comment]
@Silly511 I think an event would be far too much overhead (getExtendedState is called once per block per chunk draw - potentially hundreds or thousands of times in a frame). I'm unsure what the best way to handle injecting arbitrary extended state data would be. It's a topic that needs to be discussed further, but until extended states actually *allow* this at all, it's a moot point.

**Pull request closed without merging**
