### PR TITLE
Fix AT for EntitySpawnPlacementRegistry.register again

### PR DESCRIPTION
**Pull request by itsmeow**
It broke, again.

### CODE REVIEW

**Comment by itsmeow** [comment]
I don't know how there's a merge conflict now, what did I miss?

**Comment by GirafiStudios** [comment]
Lex cleaned up the AT file earlier, in this commit https://github.com/MinecraftForge/MinecraftForge/commit/ce28c5794d99a2812bd8cfa4255cb873ab3fe7b5

**Comment by itsmeow** [comment]
Should be fixed.

**Comment by asquared31415** [comment]
That file was redone and had a ton of things removed, including func_209343_a in [a commit](https://github.com/MinecraftForge/MinecraftForge/commit/ce28c5794d99a2812bd8cfa4255cb873ab3fe7b5) 22 hours ago at the time of posting (7:00 PM EST)

**Comment by LexManos** [comment]
@mezz When you get a chance, Omnibus this or collect a bunch together.
Also everyone should run checkATs before making PRs ass that will validate and sort the entries.
This one obviously hasnt been run as the line is not sorted.

**Comment by itsmeow** [comment]
Sorted and cleaned up for merge

**Pull request merged**
