### PR TITLE
Alternative handling of multi-layer models

### PR DESCRIPTION
**Pull request by bs2609**
Changes the handling of blocks which render in multiple layers so it doesn't rely on a global state variable, which can then be removed in a later version.

Feedback from people who use this functionality in it's present form is appreciated, especially if there's any other functions/uses that need to be accomodated for this to be a complete substitute.

### CODE REVIEW

**Comment by covers1624** [comment]
Looks good to me, Having the layer on hand is definitely a lot cleaner than storing it in `ForgeHooksClient`. TE makes heavy use of layered models and i see nothing in here that will break current functionality. I'm curious if it would be less confusing to have the layer passed through `BlockRenderDispatcher` and `BlockModelRenderer` instead of storing it in the buffer.

**Comment by bs2609** [comment]
It might be less confusing, yes. The reason I did it this way was to avoid having to add `BlockRenderLayer` overloads to a bunch more methods.
However, this does require patching `BufferBuilder` and `RegionRenderCacheBuilder`, so it is a tradeoff.

**Comment by covers1624** [comment]
Yeah, i think the best thing to do is convert this to a 1.13 breaking change passing the layer through `BlockRenderDispatcher` and `BlockModelRenderer`, moving the layer to the buffer is no better than the current system, the layer has no buisness being stored there or `ForgeHooksClient`, the only place its needed is in models and the render pipe. More opinions regarding this is probably best.

**Comment by gigaherz** [comment]
Sorry for having neglected this PR for so long. 1.13 turned everything upside down, and then 1.15 turned rendering upside down again, which means the ideas presented here, although they weren't bad ideas, go opposite to how the API is moving. I came up with a system for doing multi-layer items, which I merged into 1.16. I think it will be best, considering how 1.15+ work, to do something similar for multi-layer blocks (starting 1.16).
Sorry again for this, but I feel that at this point the best course of action is to close this PR.

FWIW, my current idea is to add a new method to IForgeBakedModel, 
```java
IBakedModel getLayerModel(BlockState blockstate, RenderType rt, boolean fabulous);
```
and deprecate the setRenderLayer/canRenderInLayer methods.

**Pull request closed without merging**
