### PR TITLE
[1.20.1] Improve mod loading error message for errors inside mod constructors

### PR DESCRIPTION
**Pull request by PaintNinja**
Before
Screenshot 2023-09-03 114324

After
Screenshot 2023-09-03 114810

### CODE REVIEW

**Comment by Jonathing** [comment]
I'd say null-check the causing exception for good measure.
```java
Objects.requireNonNullElse(e.getCause(), e)
```

Exception might have a `hasCause()` method, but I don't remember off the top of my head. Other than that, it works and looks good.

**Comment by PaintNinja** [comment]
> I'd say null-check the causing exception for good measure.
> 
> ```java
> Objects.requireNonNullElse(e.getCause(), e)
> ```

The `instanceof` check will fail if `e` is null, therefore falling back to `e` if `e.getCause()` is null is redundant.

> Exception might have a `hasCause()` method, but I don't remember off the top of my head. Other than that, it works and looks good.

No `hasCause()` method in `Exception` or `Throwable`.

**Review by Jonathing — APPROVED** [review]

**Comment by KnightMiner** [comment]
> The `instanceof` check will fail if `e` is null, therefore falling back to `e` if `e.getCause()` is null is redundant.

The `instanceof` check will fail if `e` is null, the suggested change however was for if `e.getCause()` is null.

**Comment by PaintNinja** [comment]
> > The `instanceof` check will fail if `e` is null, therefore falling back to `e` if `e.getCause()` is null is redundant.
> 
> The `instanceof` check will fail if `e` is null, the suggested change however was for if `e.getCause()` is null.

My mistake, thank you for pointing this out.

**Pull request merged**
