### PR TITLE
Update assets to new Forge brand

### PR DESCRIPTION
**Pull request by marvin-roesch**
Considering we've had the new logo and colour scheme for some time now, I think it's a good idea to actually update the various assets to the new brand.

Changed assets include:

- Forge Logo in the mod list
- Hammering animation for the splash screen (including a high-quality PNG version)
- Icon for the installer

To support the new PNG animation (which is the default for new installations, not sure if we should force it for old ones by changing the config property) this PR also includes a change to the splash screen's texture loader. The commit message explains how an animation strip is detected.

If I've missed any assets, please notify me.

### CODE REVIEW

**Comment by mezz** [comment]
For some reason the logo on the loading screen has jagged edges, I think it has to do with scaling.
This probably affected the old logo too, but you might want to look into it to make your animation look nicer.

jagged-loading

Also, why is there a png *and* a gif in this PR?

**Comment by marvin-roesch** [comment]
The GIF has jagged edges due to the format. There isn't much I can do about that without forcing a background colour.

I included both the GIF in addition to the PNG mostly for compatibility reasons. Since the used image is configurable and the GIF was the old default, I thought including both would be best. Thinking about it, though, just falling back to the PNG if the configured image does not exist is the more sensible solution. I'll address it as soon as I'm home from school.

**Comment by mezz** [comment]
I thought the jagged gif asset was unused, and the png has nice clean edges. Let me know what you find when you have a chance.

**Comment by marvin-roesch** [comment]
I've changed the code to automatically fall back to the built-in PNG if the configured image doesn't exist. The implementation isn't the nicest (e.g. it won't work when `allowRP` is `false`), but considering this is mostly internal Forge code and I didn't want to mess with fry's stuff too much, it works.

**Comment by mezz** [comment]
Alright looks nice and smooth now. 

jagged-loading2

**Comment by mezz** [comment]
Of minor note, this new asset is 258 KB and the old ones are 56.2 KB.

**Comment by mezz** [comment]
It looks like the forge logo gets scaled down to 1/4 size:
```java
                     float fw = (float)forgeTexture.getWidth() / 2 / 2;
                     float fh = (float)forgeTexture.getHeight() / 2 / 2;
```
Could you make the png texture half as big, and change those lines to only scale by half so it looks the same size? It should cut down on the file size and look about the same.

**Comment by mezz** [comment]
Also the logo for the mod info page should be 200x65, that's what it gets scaled to.

**Comment by mezz** [comment]
Looks great, thanks!

logo-load
logo-mod-screen

**Comment by ligma9000** [comment]
put the link for game

**Pull request merged**
