### PR TITLE
Fixes for PlayerDestroyItemEvent

### LINKED ISSUE #3607: PlayerDestroyItemEvent issues
The PlayerDestroyItemEvent isn't being triggered on the server in 1.11 when an itemstack becomes empty in PlayerInteractionManager.tryHarvestBlock (i.e. when placing the last block in a stack).

Also, since 1.9, when a held item (like a sword) gets broken the PlayerDestroyItemEvent is triggered before the held item gets removed, so when a PlayerDestroyItemEvent handler replaces the broken item with a new one the replacement gets removed instead.

### PR DESCRIPTION
**Pull request by bs2609**
Should resolve #3607.

Ensures calls to `ForgeEventFactory.onPlayerDestroyItem()` occur ~~after~~ before the player's held item is modified, not ~~before~~ after, so changes made by event handlers are ~~not~~ overwritten.

Also restores a patch to fire the event in `PlayerInteractionManager.tryHarvestBlock()` - it was removed in the 1.11 update.

### CODE REVIEW

**Comment by bs2609** [comment]
Also fixed a case where a now-invalid `ItemStack` was being passed to the event, it now gets an undamaged copy.

**Comment by LexManos** [comment]
This assumes that allowing you to modify the players hand on a notification event as intended...
Which i'm pretty sure it wasn't. Hence why I wrote it to happen before...

**Comment by bs2609** [comment]
As it currently stands, it happens before in some cases and after in others. (6b8466778e23226e686bcd0c83769804541eac49)

**Comment by bs2609** [comment]
As there have been previous issues with this event (eg #2565, #3243), I'd be interested in hearing what people want behaviour wise.

**Comment by mezz** [comment]
Adding the flexibility to change the held item is kind of interesting and doesn't really break the old functionality. I don't have a very strong opinion but I figured I should comment in the interest of moving this PR along.

**Comment by CrafterKina** [comment]
@bs2609 Why do not you add a hook to ``PlayerInteractionManager#processRightClickBlock`` or ``NetHandlerPlayServer#processTryUseItemOnBlock``?

**Comment by bs2609** [comment]
Ok, updated this to resolve conflicts. Apologies for the double commits, blame my poor gitting >_>

**Comment by mezz** [comment]
Tested it out and it looks good. The behavior for the event is consistent now.

**Comment by LexManos** [comment]
Not a fan of allowing people to arbitrarily edit the players held item without explanation.
Yes, the even is fired both before and after because it was intended to NOT MATTER. 
So explain yourself better, as this sits it is the exact opposite of what should be done. The ones that are fired after the changes should be moved to before.

**Comment by bs2609** [comment]
What should be done in cases where there is no existing change to the inventory? There's no before/after there, as is, any change made in a event will remain.

**Comment by LexManos** [comment]
Then the behavior is undefined, as it is now. You're arguing for us to explicitly define and endorse a functionality of this event that was never defined before. I will not do that without serious explanation.

**Comment by bs2609** [comment]
This has been updated - is this the behaviour you want at present?

I don't have any strong desire for this - it was mainly a response to bug report, so if anyone has a need for that functionality, they can make a PR themselves which explains their use case.

**Comment by mezz** [comment]
Tested and looks good to me.

**Pull request merged**
