### PR TITLE
Add generic type to DataSerializerEntry

### PR DESCRIPTION
**Pull request by thedarkcolour**

### CODE REVIEW

**Comment by tterrag1098** [comment]
Why? Please justify your changes.

**Comment by thedarkcolour** [comment]
It would be helpful to not have to cast DataSerializerEntry.getSerializer() each time I want to use a custom data serializer.

**Comment by thedarkcolour** [comment]
I can't see the error so I'm not sure what's going on.

**Comment by LexManos** [comment]
The error is all the other references to DataSerializerEntry that is not valid anymore now that we must know the type explicitly. It was specifically designed with an unbound type due to restrictions in how the registry system works.

**Pull request closed without merging**
