### PR TITLE
Fix #4772: add an "isActivator" boolean to powered rails

### LINKED ISSUE #4772: vanilla rails show non-vanilly powering behaviour
Power should only be transmitted between rails of same kind, but If you place a golden-rail and an activator rail next to each other and power one of them, the other one does get activated as well.

vanilla 1.12.2
rails_vanilla-1 12 2
forge 1.12.2-14.23.2.2611 (no mods installed)
rails_forge-1 12 2-14 23 2 2611

### PR DESCRIPTION
**Pull request by josephcsible**
Activator rails and non-activator rails won't share power.

### CODE REVIEW

**Comment by williewillus** [comment]
why the need for a new field, can this not be done with new methods?

**Comment by josephcsible** [comment]
Yes, but then we'd need to add a new class to vanilla, either a BlockRailActivator.class or an anonymous subclass where the activator rail is created now. Is there an advantage to doing it that way?

**Comment by williewillus** [comment]
uhh why?
`BlockRailPowered` can just check `this == Blocks.ACTIVATOR_RAIL` or `this == Blocks.POWERED_RAIL` in its implementation of the method and handle both cases at the same time.

**Comment by josephcsible** [comment]
Because then modded powered/activator rails have no way of specifying which they are.

**Comment by ichttt** [comment]
Why not just use a boolean flag called something like receivePower? This is much simpler and leads to the same result IMO.

**Comment by josephcsible** [comment]
Because activator rails are supposed to receive power from other activator rails.

**Comment by ichttt** [comment]
Whoops, you are right, didn't read the old vanilla code correctly

**Comment by LexManos** [comment]
The connection tag is kinds weird way to do it...
It doesn't really give much control to the modder.
Perhaps move the logic of that if statement into a 'canPower' function?
With the default being state instanceof BlockPoweredRail and !instanceof BlockDetectorRail? Or something to that effect.

**Comment by josephcsible** [comment]
The problem is that vanilla powered rails should be able to give power to modded powered rails, but not to modded activator rails. I can't think of a way to write a vanilla function that checks that without a tag. (Part of the problem is that there is no BlockActivatorRail class; both powered and activator rails are just instances of BlockPoweredRail.)

**Comment by LexManos** [comment]
Thats where the function that allows the modded rail to decide comes in.
On top of that, Performance wise alone a function call would be better then a string comparison.
Not to mention strings add a whole nother level of complexity and standards that need to be applied to the community.

**Comment by josephcsible** [comment]
But which side should the function be on? To handle the cases of vanilla -> modded and modded -> vanilla correctly, you'd need to always call both sides' functions. And then how would one modded powered rail be able to tell if another modded rail were a powered or activator rail?

**Comment by MaartenKok8** [comment]
What about an `enum EnumRailType { POWERED, ACTIVATOR }`, that the rails have as field, or if that's too limited, what about some dummy objects instead:
```
public static final object RAIL_TYPE_POWERED = new object();
public static final object RAIL_TYPE_ACTIVATOR = new object();
```
And have the rails have a field referencing one of these types. The generic 'object' type could be:
1. wrapped in some dummy 'RailType' class instead, if preferred, for documentation purposes, or 
2. it could be changed to a Block type instead, where the type is defined by the rail block itself, and the modded powered rail would use Blocks.GOLDEN_RAIL as value.

The checking would come down to reference equality checking at this point.

**Comment by LexManos** [comment]
Possible solution for now is just to make it a boolean instead of a string, as vanilla only has two types of powered rail at the moment.
Not the best solution but better and more performant then what we have now as it doesnt introduce the concept of more types of tracks.

**Comment by josephcsible** [comment]
Are we okay with hamstringing any future mod that wants to add some kind of rail that isn't powered or activator? I guess we can do a Boolean then; it just feels limiting.

**Comment by josephcsible** [comment]
Awaiting a response to my previous post: given it, should I still switch this to just a Boolean?

**Comment by LexManos** [comment]
Just make it a boolean for now we'll see what 1.13 brings.

**Comment by josephcsible** [comment]
Done.

**Pull request merged**
