### PR TITLE
Add LayerHeldItemEvent

### PR DESCRIPTION
**Pull request by Flemmli97**
Adds an event in LayerHeldItem to modify the itemstack being rendered.

### CODE REVIEW

**Comment by williewillus** [comment]
don't see the point, why not just change the held item directly?

**Comment by Flemmli97** [comment]
i am currently using this to render (purely aesthetic) dual weapons. you would need to change a lot more if you want to achieve the same result by changing the items directly.

**Comment by Darkhax** [comment]
Why not replace the layer renderer with your own wrapped version?

**Comment by tterrag1098** [comment]
I'm not sure I see the justification for this, and 2 events per frame for each player render is a not a negligible cost.

**Pull request closed without merging**
