### PR TITLE
adds a postRotation to CameraSetup event.

### PR DESCRIPTION
**Pull request by adoxentor**
The this fixes is gimbal lock in the camera's rotation. some translations are impossible or very without the use of quaternions. my change is as minimal as possible in order to avoid conflicts.

### CODE REVIEW

**Comment by ichttt** [comment]
Can you give some concrete examples where this is needed? What is currently impossible that is possible to do with this PR?

**Comment by adoxentor** [comment]
In the simple planes mod when the plane is doing a flip(pitch =90), and the player is in first person view, there is a flicker coused by the gimble lock, this can be solved using quaternion rotation.

**Comment by ichttt** [comment]
Please update to 1.16.2, otherwise this seems good to me

**Comment by TheCurle** [comment]
Seconded, update & rebase and this can be fully considered.

**Comment by sciwhiz12** [comment]
I am closing this PR as stale. If you or anyone wishes to continue this PR, please update the PR to `1.18.x`. 
Thank you for your contributions. 👋

**Pull request closed without merging**
