### PR TITLE
Add support for context based key bindings

### PR DESCRIPTION
**Pull request by Lunatrius**
The code in the PR is tested and works, but is by no means final, it's merely a **draft/mock-up** for the discussion/feedback that is needed.

Currently only the key press is implemented, however adding key holding should be fairly trivial.

### CODE REVIEW

**Comment by iChun** [comment]
All I can say is... Lol.

**Comment by Lunatrius** [comment]
Well, helpful. I know it's not perfect, but at least it should get the ball rolling - we've been trying to do this for over 2 years now.

**Comment by coolAlias** [comment]
What, exactly, have you been trying to do for years? You can already check if a key (or any combination of keys) is down when another key is pressed...

**Comment by iChun** [comment]
Nah I meant more of the fact that I've had Ctrl/Alt/Shift modifiers for keybinds for the longest of times.

**Comment by Lunatrius** [comment]
@coolAlias Mostly context based key bindings. In larger modpacks you'll easily find 5+ key bindings that essentially do the same thing - toggle the state of an item (RA weapons/tools, IC2 power wrench etc).

Oh... uh. Alright. Was a bit of a vague message, could be taken either way.

**Comment by mezz** [comment]
Oh nice! I just got stuck trying to figure out how I was going to implement hotkeys with modifiers in a user-friendly way. This looks like the best way to me. The alternative I have is either hog up a hotkey that I'm not really using or hide them away in a config file or my own hotkey menu.

**Comment by asiekierka** [comment]
Unifying keybindings across mods is a very good idea. Really.

**Comment by Lunatrius** [comment]
Was just testing a few things, need to pull the key binding loop above the context loop because the key bindings can only be queried once. With the same key binding but different contexts only the first context will be checked.

**Comment by Lunatrius** [comment]
At this point a key binding overhaul will be better in any case. This PR would just add a half done implementation for something, that wouldn't be touched again because "it sorta does the job".

The overhaul has to be compatible with vanilla, which shouldn't be too hard for regular keys. The main problem are the modifier keys used for sneaking/sprinting.

A rather simple scenario: double tap `W` to sprint, then `SHIFT+F` to activate/use *something*. You'd expect to keep sprinting, but pressing `SHIFT` will cancel that out.

Two potential solution would be to blacklist/remove shift/control/alt from the available keys. Sneaking and printing could be then configured either as (*edit: neither of these really fixes the issue described above...*):
 * a separate set of keys for both actions (`W` and `SHIFT-W` would be separate key binds, annoying to check for both, allows customization)
 * use the modifiers when a key is pressed/held down (which doesn't allow the key binding to be changed)

Concerns, ideas, suggestions, questions?

**Comment by iChun** [comment]
Might wanna check out my custom keybind implementation. Mine allows shift
ctrl alt be used as a key including using them with modifiers. They're also
by default specific but are able to trigger without first checking for
modifiers. (tbh I'm only commenting on this still cause I commented earlier
and I'm getting emails on this still)

**Comment by iChun** [comment]
The only thing is though, of course, my implementation does not solve your
scenario either, so that changes nothing in the end.

**Comment by Lunatrius** [comment]
Thanks for the reminder, will make sure to check it once I start working on this.

No implementation can fix that, not sure why I though that it could be fixed (other than just removing the modifiers from the key pool, which is not happening).

**Comment by mezz** [comment]
Any update on this? 
I have hotkeys with modifiers for use in guis and I would love a way to properly register them.

**Comment by Lunatrius** [comment]
Completely forgot about this... I'll see if I can get something that sort of works over the weekend and then gradually improve it.

**Comment by dredhorse** [comment]
I don't see a problem with shift as modifier and shift as a key.... if somebody selects shift as key just remove it from the modifier list, and perhaps display a warning message. Keep in mind though that there are lshift and rshift, and especially alt and alt gr (on german keyboards for example).

Not being able to use shift as a modifier cuts available keys down to 50%, that might have been fine for a "jump and run" minecraft, but for modded minecraft that isn't really feasible.

Don't know if this would also allow for mod based context switching, eg. if I'm in a thaumcraft table k does something different as if I'm in normal gameplay mode. Something like this for mods to hook into would be the icing of the cake, but modifiers by itself would help tremendously.

**Comment by Lunatrius** [comment]
The original plan (half finished code currently in the PR) was to add pretty much that. Holding a wrench from mod A and pressing a key would do some stuff. Switching to a wrench from mod B would do some other stuff. The test mod uses sticks and diamonds to demonstrate that.

The new plan is to rewrite parts of the key binding system to support modifiers and probably use some sort of callbacks, which would allow for something along the lines of a *"key dictionary"*.

**Comment by mezz** [comment]
I worry that this PR is going off the rails.
Building a robust key system with callbacks should be out of scope for this problem. Getting vanilla to follow the rules of any such system is not possible, which negates most of the benefits.

All that's needed is "modifier + key" registrations in the Controls menu, and a boolean setting to say "This hotkey is context-sensitive and does not care about conflicts, please ignore them". It will let the modders, players, and pack makers resolve conflicts.

**Comment by Lunatrius** [comment]
The existing way of doing keybindings wouldn't be removed, the callbacks would offer an alternative (and simpler) way to register keybindings.

```java
class KeyBinding {
    int keyCode;
    boolean control, shift, alt; // modifier keys
    boolean strict; // strictly check modifiers or completely ignore them
}
```

The main issue is the way keybindings are handled - only one of the registered keybindings are ever triggered making context based keybindings impossible to implement/execute.

A possible alternative to the callbacks might be a `wasConsumed` method that defaults to `true` (current behavior). Returning `false` would forward the key press to the next keybinding in the queue. Thoughts?

**Comment by mezz** [comment]
Take a look at how forge events handle it now. They let you cancel the event and then it's not passed on. Why make a new system?

**Comment by Lunatrius** [comment]
I doubt that I'll ever get this done myself due to time constraints. You (as in anyone) are free to submit a new PR to replace this *"RFC"* PR.

**Pull request closed without merging**
