### PR TITLE
Add ability to modify data gen output location

### PR DESCRIPTION
**Pull request by Yamahari**
add ability to modify data gen output location
AT is there for making overriding RecipeProvider#run possible with less copy&paste

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
There are three things that come to mind for this PR that I think you need to address.

1. Why can't you just modify the output location of the generated entries within the FG args in the run block?
2. Why can you just make the registry path of the entry have a slash in it which ultimately does this?
3. If the above two answers are valid, why haven't you done this for **ALL** data providers currently in vanilla and Forge?

There are plenty of ways to implement this without this PR, so I'm unsure what's the reasoning here.

**Comment by Yamahari** [comment]
1. I would have 30 different runs at the current state, only more to come x)
2. because that still doesn't allow me to have a folder "above" data/asset (custom pack)
3. for tags there's already a getPath function, what other providers are that I missed? I would have everything I need with this

**Comment by ChampionAsh5357** [comment]
1. I'm pretty sure you can create a task to run other tasks in gradle.
3. If you're using this for a custom pack, probably all the ones listed on the [docs](https://mcforge.readthedocs.io/en/1.18.x/datagen/intro/).

**Comment by Yamahari** [comment]
I think starting new instance of MC 30 times would take me a long time, 1 run takes like a minute or two to finish.

**Comment by Yamahari** [comment]
I will take a look at the other providers though.

**Comment by Yamahari** [comment]
added the other providers

**Comment by Yamahari** [comment]
something similar can be archieved by creating new data generators at runtime like
```    
private static GatherDataEvent.DataGeneratorConfig getConfig(final GatherDataEvent event) {
   return ObfuscationReflectionHelper.getPrivateValue(GatherDataEvent.class, event, "config");
}

private static DataGenerator makeGenerator(final GatherDataEvent.DataGeneratorConfig config, final String root) {
    return config.makeGenerator(outputPath -> outputPath.resolve(root), true);
}
```
works for my case, but may not be suitable for others (?)

**Pull request closed without merging**
