### PR TITLE
Added DrawHoverTextEvent

### PR DESCRIPTION
**Pull request by iLexiconn**
This event can be used to alter the tooltip's text, or completely stop rendering it.
Example mod: http://pastebin.com/Ajs5fE5M

### CODE REVIEW

**Comment by laci200270** [comment]
Squuash yor commits. And also you don't need  make a new PR you can use force push

**Comment by iLexiconn** [comment]
Well, I completely messed up and git closed the pr :/

**Comment by laci200270** [comment]
You wasn't push any files.Redo your work and simply push

**Comment by iLexiconn** [comment]
Fixed patch, I really should learn how to git. #2216

**Comment by Lunatrius** [comment]
```
git rebase -i HEAD~<number of commits>
-replace 'pick' with 'squash'/'s' on all but the first line-
git push --force
```
or 
```
git reset HEAD~<number of commits>
git add <files>
git commit -m 'lalala'
git push --force
```

**Comment by iLexiconn** [comment]
Tried that.. I only got the text 'noop'.

**Pull request closed without merging**
