### PR TITLE
Switch world without server restart

### PR DESCRIPTION
**Pull request by abauske**
Forge server bootup takes a very long time, especially if you have a lot of mods installed. Once you finally succeeded logging into your game you sometimes realize that you forgot to change "level-name" in _server.properties_ or if you have generated a fresh new world you simply don't like it.
There are many cases where you would like to switch to an other save or generate a new world which currently requires a dead slow server restart.

In this pull-request I implemented an additional forge subcommand:
- `/forge loadworld` which itself contains three subcommands:
- `/forge loadworld load <worldFolderName> [delay] `: loads an existing minecraft save from the server directory. Optional *[delay]* argument allows to set an delay in seconds which will warn all players on the server periodically that the server is going to switch world. The command exits with an exception if world in *\<worldFolderName\>* doesn't exist.
- `/forge loadworld new <worldName> [delay] [seed] [worldType] [generatorSettings]`: generates a world from scratch and saves it in a folder called *\<worldName\>* in server directory. *[delay]* -> see above. *[seed]* is the seed to be used for the map (0 means random if you wish to set the following settings). *[worldType]* is the minecraft world type (default, amplified, superflat, ...). Last but not least: *[generatorSettings]* is a string with all the generator settings as you know them from minecraft's customized settings.
- `/forge loadworld cancel`: Cancels a scheduled load or new lob (one where a delay has been set)

These commands eliminate the need to restart a server in order to launch an other world.

### CODE REVIEW

**Comment by LatvianModder** [comment]
You should use TextComponentHelper in all instances where you use TextComponentTranslation

**Comment by abauske** [comment]
> You should use TextComponentHelper in all instances where you use TextComponentTranslation

Done

**Comment by williewillus** [comment]
Maybe call it `loadSave` instead? The current name sounds like generating a new dimension for the current save

**Comment by abauske** [comment]
> Maybe call it `loadSave` instead? The current name sounds like generating a new dimension for the current save

You are right, `save` is definitely more fitting! Thanks for your suggestion, I've changed it!

**Comment by mezz** [comment]
This is a cool idea but the use-case is extremely specific so I (and Lex) don't think it's a very good fit for Forge.
I think with a little extra work this could be implemented as a nice server utility mod though. Drop by on our [discord server](https://discord.gg/D5f2mB) if you want to brainstorm with other modders about how to implement it.

**Pull request closed without merging**
