### PR TITLE
Add methods to allow loading json constants outside of _constants

### PR DESCRIPTION
**Pull request by temp1011**
Use case: using the constants and conditions system outside of `/recipes/`. Seems that maybe there is a reason that this has it's current visibility. Maybe it's not intended for modders to use this. However, I can't see this causing issues.

### CODE REVIEW

**Comment by liach** [comment]
consider making it varargs.

**Comment by temp1011** [comment]
That seems like a  good idea.

**Review by mezz — CHANGES_REQUESTED** [review]
If you just want to get the constants, it might be a better idea to break that logic off into its own method in `CraftingHelper`. Making this method public is only one part of that.

**Comment by covers1624** [comment]
+1 on this, Currently in Avaritia i call this via reflection. Breaking it off wouldn't help my case, i use the exact same format as Vanilla / Forge recipes and JsonContext is required for constants when parsing ingredients. 
Just making the method public would be nice, or have a helper method inside CraftingHelper that creates and loads JsonContext, if you have concerns about people messing up the state, imo, there isn't much they can break anyway.

**Comment by temp1011** [comment]
I would ideally like to use `JsonContext` in parsing recipes. So I don't really have any use for the constants outside of that. I'm just aiming to keep this as a simple change to give a bit more convenience.

**Comment by LatvianModder** [comment]
Can you also throw in ability to use other mod constants from json with something like `#mod:constant`? I wanted to PR that but kinda forgot

**Comment by temp1011** [comment]
I'm not sure if it would get accepted unfortunately. In https://gist.github.com/LexManos/2a11d4f7aa9d680d861dae4faf9dcfa6 Lexmanos says:
> You can NOT use other mod's constants. I see no reason to hard dep on that you can re-make the constant yourself using the mod its with a few conditionals.

I don't know if his mind has changed since then or not.

**Comment by raoulvdberge** [comment]
Any update on this @temp1011 ?

**Comment by LexManos** [comment]
I would rather not expose internal serialization functions in a data class.
Perhaps a better interface in a more modder facing class.
There is no reason a modder should be working with the JsonObject of things better would just be a loadContext(File) or something.

**Comment by temp1011** [comment]
OK, I will update to change this.

**Comment by temp1011** [comment]
Should I update some of the other methods in `CraftingHelper` too?

**Comment by covers1624** [comment]
Kida defeats the purpose of the method to call loadContext if you pass in an existing instance of JsonContext, The method should really construct JsonContext and load it.

**Comment by temp1011** [comment]
I thought about that, but I'm then not sure what the best way to handle errors is. The current way most crafting stuff seems to fail is just to log the stacktrace and return false. Maybe that's because they're not very modder facing methods though?

**Comment by temp1011** [comment]
@covers1624 this now constructs `JsonContext` too. Hopefully the error stuff is OK. I've tried to clean up some resource use throughout the whole of `CraftingHelper` too.

**Comment by covers1624** [comment]
Should suffice for my use case.

**Comment by covers1624** [comment]
Go away stale, mezz is yet to review after changes.

**Review by mezz — APPROVED** [review]

**Review by tterrag1098 — APPROVED** [review]

**Comment by bs2609** [comment]
This is probably causing issues, see http://www.minecraftforge.net/forum/topic/67602-forgeminecraft-launcher-crashes-while-trying-to-install-forge/.

The `FileSystem` is now closed when this block exits:
https://github.com/MinecraftForge/MinecraftForge/blob/2a5268c6993f2de7612789bfac2b674d04c87e89/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L635-L638

which causes this later code to throw exceptions:
https://github.com/MinecraftForge/MinecraftForge/blob/2a5268c6993f2de7612789bfac2b674d04c87e89/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L645-L652

**Comment by Mgazul** [comment]
> This is probably causing issues, see http://www.minecraftforge.net/forum/topic/67602-forgeminecraft-launcher-crashes-while-trying-to-install-forge/.
> 
> The `FileSystem` is now closed when this block exits:
> [MinecraftForge/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java](https://github.com/MinecraftForge/MinecraftForge/blob/2a5268c6993f2de7612789bfac2b674d04c87e89/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L635-L638)
> 
> Lines 635 to 638 in [2a5268c](/MinecraftForge/MinecraftForge/commit/2a5268c6993f2de7612789bfac2b674d04c87e89)
> 
>  try (FileSystem fs = FileSystems.newFileSystem(mod.getSource().toPath(), null)) 
>  { 
>      fPath = fs.getPath("/assets/" + ctx.getModId() + "/recipes/_factories.json"); 
>  } 
> which causes this later code to throw exceptions:
> [MinecraftForge/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java](https://github.com/MinecraftForge/MinecraftForge/blob/2a5268c6993f2de7612789bfac2b674d04c87e89/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L645-L652)
> 
> Lines 645 to 652 in [2a5268c](/MinecraftForge/MinecraftForge/commit/2a5268c6993f2de7612789bfac2b674d04c87e89)
> 
>  if (fPath != null && Files.exists(fPath)) 
>  { 
>      try (BufferedReader reader = Files.newBufferedReader(fPath)) 
>      { 
>          JsonObject json = JsonUtils.fromJson(GSON, reader, JsonObject.class); 
>          loadFactories(json, ctx); 
>      } 
>  }

same question

**Comment by josephcsible** [comment]
> This is probably causing issues

Yep, this is definitely causing issues. I just confirmed for myself that Forge 2790 and up crash on startup with a ClosedFileSystemException (looks the same as the one @bs2609 linked), and Forge 2789 doesn't.

**Comment by tterrag1098** [comment]
I am diagnosing this now.

**Comment by tterrag1098** [comment]
Will be fixed in 2793

**Pull request merged**
