### PR TITLE
[1.20.4] Fix slightly offset mods screen link positioning

### PR DESCRIPTION
**Pull request by PaintNinja**
Currently the links aren't clickable when hovering over the underline on them due to a bug in the click positioning code. This PR fixes that issue.

### CODE REVIEW

**Comment by LexManos** [comment]
got a before and after screenshot?

**Comment by PaintNinja** [comment]
Red dots indicate clicks that didn't get recognised, green dots indicate those that did. This was nowhere near as pronounced/bad as downstream, but still a bit off.

Before:
image

After:
image

Tried resizing the window and adding stuff to the mods.toml to make it scrollable and still seems to work. Made this a PR to confirm with others who may have different screen resolutions, sizes, GUI scaling etc which might impact this (I don't remember if MC cares about that or not)

**Comment by LexManos** [comment]
Looks good, just wanted that documented

**Review by Jonathing — APPROVED** [review]
oh shit hi, i'm sorry lmao

**Pull request merged**
