### PR TITLE
[1.10] Add method for setting ability to swim

### PR DESCRIPTION
**Pull request by primetoxinz**
Adds a setter and a getter to change whether an EntityLivingBase can swim when isInWater() or isInLava()

### CODE REVIEW

**Comment by asiekierka** [comment]
I'm not sure if this is the best way to implement it - it feels very ugly. I feel an event would be cleaner than this, but maybe there's an even better way?

**Comment by williewillus** [comment]
and shouldn't this be handled through AI?

**Comment by primetoxinz** [comment]
@asiekierka I could make this an event if that would be better
@williewillus this is really intended for a player, but it's handled in livingbase

**Comment by williewillus** [comment]
what does the "ability to swim" mean exactly?

**Comment by primetoxinz** [comment]
when the jump button is pressed and held you get a constant acceleration upwards because you are in water or lava, this makes the water/lava check get skipped and goes directly to the land jump call

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by LexManos** [comment]
This does seem like a very odd way to do this, perhaps moving this check to the innards of the handle methods would be better. 
As that wouldn't have the downsides of causing the jumping effect to happen while under water/lava.

**Comment by primetoxinz** [comment]
> As that wouldn't have the downsides of causing the jumping effect to happen while under water/lava

what do you mean by that?

**Comment by LexManos** [comment]
Causing the final branch of the if-elseif-elseif being fired when we dont want it to.

**Comment by primetoxinz** [comment]
the case I want it for actually needs that final branch, could change this to an event and make that branch optional somehow?

**Comment by LexManos** [comment]
Explain better.

**Comment by primetoxinz** [comment]
My purpose of this is for `jump()` to still be called if `canSwim=false`, but there could be cases where someone doesn't want `jump()` called,which this doesn't currently handle

**Comment by mezz** [comment]
Please update this to resolve merge conflicts and to target 1.11, new features are no longer being merged into 1.10.

**Comment by mezz** [comment]
Any updates @primetoxinz?

**Comment by primetoxinz** [comment]
Probably won't get around to redoing this, can close or someone else can do it

**Comment by mezz** [comment]
Ok, thanks. I'm sure it will come up again eventually.

**Pull request closed without merging**
