### PR TITLE
Replace ItemTags and BlockTags patches with ATs

### PR DESCRIPTION
**Pull request by JDLogic**
These should have been ATs not patches. Also `FluidTags#makeWrapperTag` was missed.

### CODE REVIEW

**Comment by covers1624** [comment]
They _were_ when we were on the private branch.. I blame @illyohs

**Comment by 0xilly** [comment]
I stayed a mile away from that package :P

**Comment by JDLogic** [comment]
Ughh.. going to change this to a patch cleanup PR because I have found other cases like this. I'll update when it is ready.

Also ItemTags was covers and BlockTags was Illy. I have proof :P

**Comment by LexManos** [comment]
Yes, a full cleanup/sanity pass is be needed. This is also a nice spot to toss in the patch validator as well if someone wants to work on it.
Something that checks if patches:
Have tabs
Have Hunks that are JUST whitespace changes. Like the first hunk in BlockTags
Has import changes

**Comment by pupnewfster** [comment]
`EntityTypeTags#func_232896_a_` (makeWrapperTag) was also missed.

**Pull request closed without merging**
