### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SollyW**
Since other modloaders exist I think you should have this edited

### CODE REVIEW

**Comment by OrionDevelopment** [comment]
This is as of this moment not something we currently care about.
Maybe in the future this is something we can take a look at, but at the moment we are currently focussing on getting the mappings into a fully useable up to date state. And pull requests like these take time away from that goal.

**Comment by SollyW** [comment]
Leaving this in is spreading misinformation
You shouldn't be closing it

**Comment by diesieben07** [comment]
Even if we change this text, it is not something that happens via a pull request like this.

**Comment by immibis** [comment]
This is literally what pull requests are for

**Pull request closed without merging**
