### PR TITLE
Fix invalid FastTESR quad ordering (port #3900 to 1.12)

### PR DESCRIPTION
**Pull request by boq**
Original issue: #3900
Test mod: https://gist.github.com/boq/90e65106132fbff695ed566874620f9a

Before:

After:

### CODE REVIEW

**Comment by mezz** [comment]
Please include the test mod as part of the PR, with the other test mods in the `src\test\java\net\minecraftforge\debug` folder.

**Comment by boq** [comment]
Done

**Comment by mezz** [comment]
Test and confirmed, looks good to me. Approved by Fry.

**Comment by tterrag1098** [comment]
I must say I don't understand how this change addresses the problem. @boq would you mind explaining? I'm sure I'm missing something.

**Comment by boq** [comment]
After quads from all FastTESR are collected, they are sorted (via `func_181674_a` == `sortVertexData`), to fix transparency problems.

Pre-PR this line mirrored block rendering, where all quads have absolute coordinates - so offset (this function args) was set to `renderViewEntity` eye (since we want to sort based on distance from viewer).

But for FastTESR (actually, all TESR) quads are already in player-relative coordinates (see `TileEntityRendererDispatcher.renderTileEntity`), so subtracting player offset twice caused quad sorting to break.

**Comment by tterrag1098** [comment]
Aha, that makes sense. Thanks for the explanation.

**Comment by boq** [comment]
Actually, after writing it I realized that TESR may be rendered in coordinate system based on player feet (`staticPlayerX/Y/Z`), but view is sorted based on distance from eyes. Maybe it's missing `Entity.getEyeHeight` somewhere.

**Pull request merged**
