### PR TITLE
Update Example Mod

### LINKED ISSUE #5780: 1.14.2 Forge Error launching the client inside of IntelliJay
The issue is that it says the package for Blocks does not exist. Here is a picture of the issue. Also I have not done anything, this is just the Example Mod packaged with Forge.
Using Forge version 26.0.2

https://imgur.com/a/PH49eZx

### PR DESCRIPTION
**Pull request by marcus8448**
First PR to such a large project, please forgive me if I've messed something up.
Fixes #5780, while also fixing a different crash (https://pastebin.com/1U9qAVhZ) related to the 'Minecraft' dependency still being set to `1.13.2`.

### CODE REVIEW

**Comment by Iuhegi** [comment]
Looks good, hopefully this will get merged soon

**Comment by pulse0ne** [comment]
~~Is there a way to register the entrypoint of a mod without leaking a reference to an incompletely constructed object? Passing `this` out of a constructor is considered dangerous and bad practice because the object is not fully constructed until control reaches the end of the constructor block.~~

I realized that you can construct a separate object and pass that to the event bus register. However, I do recommend doing something similar in the example, as it is definitely bad practice to be leaking `this` from the constructor.

**Comment by gigaherz** [comment]
The issue tracker is not a forum. Questions like that do not belong in a random merged pull request, but rather on the forums, or discord server.

**Comment by pulse0ne** [comment]
The updated comment is not, in fact, a question. It's pointing out the fact that your example directs mod authors to employ bad and potentially dangerous coding practices. I've already seen multiple mods that have (obviously) followed this example that are leaking their `this` reference in their constructors. Have a look for yourself [here](https://github.com/search?utf8=%E2%9C%93&q=MinecraftForge.EVENT_BUS.register%28this%29%3B+extension%3A.java+language%3AJava&type=Code&ref=advsearch&l=Java&l=). I would be happy to post this to the forum as well, or even open my own issue.

**Comment by DaemonUmbra** [comment]
Please move any discussion of this to the Forums or Discord as this Pull Request has already been merged and closed.

**Comment by LexManos** [comment]
Your opinion is slightly valid, however, it's a personal opinion and only an issue if you pass code to places you don't know.
The current system is designed for this specific thing in mind so it's a non issue.

**Pull request merged**
