### PR TITLE
[1.18.2] Add new helper without duplicate neighbor update call

### LINKED ISSUE #9169: Forge calls `updateNeighbourForOutputSignal()` twice, unnecessarily whenever a block entity calls `setChanged()`.
The code is the same in 1.19.x (43.1.65) and 1.18.x (40.1.86) editions of Forge at time of reporting.

In vanilla, the following code is present when a block entity is set changed:

```java
protected static void setChanged(Level level, BlockPos pos, BlockState state) {
    level.blockEntityChanged(pos);
    if (!state.isAir()) {
        level.updateNeighbourForOutputSignal(pos, state.getBlock());
    }
}
```

However, note that Forge *patches* `Level#blockEntityChanged`, adding the following:

```java
public void blockEntityChanged(BlockPos pos) {
    if (this.hasChunkAt(pos)) {
        this.getChunkAt(pos).setUnsaved(true);
    }
    // vv The below line is added by Forge vv
    this.updateNeighbourForOutputSignal(pos, getBlockState(pos).getBlock()); //Notify neighbors of changes
}
```

by the following patch:

https://github.com/MinecraftForge/MinecraftForge/blob/dd8239c255b399720ce38e2b7d3195906521d873/patches/minecraft/net/minecraft/world/level/Level.java.patch#L152

This means that `updateNeighborForOutputSignal` is being called twice, unnecessarily, whenever a block entity is marked change. I noticed this when looking into a profile of a server with a lot of block entities that mark dirty frequently, due to consistently changing their saved data, and noticed this taking up 2.35% of server tick times when none of these calls needed to be there.

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR is an LTS (1.18.2) backport PR of #9234, which fixes #9169 by ~~removing a duplicated updateNeighbourForOutputSignal call in Level. See the original PR for details.~~ adding a new helper, `Level#blockEntityChangedWithoutNeighborUpdates`, which does the function of `Level#blockEntityChanged` without the erroneous call to `Level#updateNeighbourForOutputSignal`.

The two existing calls by vanilla to `#blockEntityChanged` are redirected to the new helper, and that method is deprecated with a matching comment pointing to the new helper, for new mods in 1.18.2 to follow.

### CODE REVIEW

**Review by ChampionAsh5357 — APPROVED** [review]
Yep, literally the exact same.

**Comment by ChampionAsh5357** [comment]
Missed Lex's comment, so putting it here so we don't miss it again:

> The backports will need to just add a helper that doesn't have this call. As removing this can cause modders who rely on the functionality suddenly not saving changes. Which is bad.

**Comment by sciwhiz12** [comment]
Updated PR per comment by adding a new helper, `Level#blockEntityChangedWithoutNeighborUpdates`, which functions the same as `Level#blockEntityChanged` but without the erroneous call to `Level#updateNeighbourForOutputSignal`.

**Review by ChampionAsh5357 — APPROVED** [review]
Ok, now this looks good.

**Review by Matyrobbrt — APPROVED** [review]

**Comment by Matyrobbrt** [comment]
@autoforge shipit

**Pull request merged**
