### PR TITLE
Allow item models to use formats other than ITEM

### PR DESCRIPTION
**Pull request by tterrag1098**

### CODE REVIEW

**Comment by mezz** [comment]
What will you use it for? Please make a basic test mod to show it off.

**Comment by m00nwtchr** [comment]
Can you please add description what it exactly does an a sample mod because i dont really see purpose of this

**Comment by bs2609** [comment]
I think it'd be cleaner to have `renderQuadColor` deal with this; accept quads in any format, and, depending on the format, delegate to either `renderQuadColorFast` or `renderQuadColorSlow` functions to do the actual rendering.

Something like this:
```java
    public static void renderQuadColor(BufferBuilder wr, BakedQuad quad, int auxColor)
    {
        if (quad.getFormat() == DefaultVertexFormats.ITEM)
        {
            wr.addVertexData(quad.getVertexData());
            ForgeHooksClient.putQuadColor(wr, quad, auxColor);
        }
        else
        {
            renderQuadColorSlow(wr, quad, auxColor);
        }
    }
```

**Comment by thiakil** [comment]
Example; Block model uses a different format, so using the same model for the item makes soup.

**Comment by tterrag1098** [comment]
Before:


After:

**Comment by mezz** [comment]
Looks good to me.

**Pull request merged**
