### PR TITLE
Potential userProperties Fix

### PR DESCRIPTION
**Pull request by DaemonUmbra**
This PR *should* fix the serialization issues with userProperties in userdev for people whose accounts have userProperties attached.

I can't test it myself as my account does not return any userProperties during auth, searching for testers.

### CODE REVIEW

**Comment by jamierocks** [comment]
This would fix GH-6563.

> I can't test it myself as my account does not return any userProperties during auth, searching for testers.

I've actually got a branch locally with effectively the same changes, but was also unable to verify it actually fixed launch. Though I am in no real doubt it does.

**Comment by DaemonUmbra** [comment]
I've been burned by "this will definitely work" before...

**Comment by jamierocks** [comment]
> I've been burned by "this will definitely work" before...

That's why I didn't make a pr, I had intended to look at how it used to be implemented to verify - just didn't get around to it.

**Comment by DaemonUmbra** [comment]
Someone [on the forums](https://www.minecraftforge.net/forum/topic/86244-intellij-unable-to-use-minecraft-account/?do=findComment&comment=405587) reports that it works.

**Pull request merged**
