### PR TITLE
Fix translucent areas in loading animation

### PR DESCRIPTION
**Pull request by thecodewarrior**
This change fills in the transparent gaps in the forge loading animation that allow text to show through because I got annoyed by it one too many times. Specifically I filled in the highlights for the rim, the legs, and the transition to the round pointy bit, and I extended the ingot down one pixel so there isn't a translucent gap between the anvil and ingot.

(These screenshots have the icon replaced using gimp because I didn't want to go through the hassle of setting up a whole forge environment just to edit one PNG file, but since it's one PNG file I'm pretty sure there's literally nothing that would cause an issue aside from invalid dimensions for the animation, but the dimensions are unchanged.)

The game before the change:
forgelogotransparentissue

After the change:
forgelogotransparentfixed

A side-by-side comparison:
forgelogotransparentissue_sidebyside

### CODE REVIEW

**Comment by bs2609** [comment]
Using white here has the issue of someone changing the background colour.

**Comment by thecodewarrior** [comment]
The transparent areas are all in places that imply highlights, and the highlights would be white regardless of the background. Just tried it with a blue background and it looks pretty good still to me.
forgelogo_bluebackground

**Comment by bs2609** [comment]
As long as it still looks ok, then that's not an issue - it just needed checking.

**Comment by mezz** [comment]
This image is 119KB and the old one is just 11.2 KB, please make sure it's the correct bit depth and then use lossless png compression on it.

**Comment by thecodewarrior** [comment]
Done, got it down to 9.8 KB.

**Comment by mezz** [comment]
This is not quite right. It doesn't have semi-transparent pixels any more, the edge is jagged. Also the color has changed. Please take your time and include a before/after picture to confirm.

**Comment by pau101** [comment]
I would think the actual issue here is the loading screen could be wrapping text for it to remain readable. Merely changing the appearance of the icon for aesthetic purposes seems counterproductive, and as already mentioned, an alternative background can leave the icon creating just as an unpleasing appearance to some.

**Comment by thecodewarrior** [comment]
... Shoulda' checked that.

Just updated it. Here's the difference between the two (after merging with a white background to reveal opacity changes). The indexed version just has slightly more opaque edges.

forgelogofixed_difference

IMO @pau101, having purple highlights when it's on a purple background would have an unpleasing appearance. They'll feel like holes (which they would be) as opposed to highlights (which they ostensibly are supposed to be).

**Comment by mezz** [comment]
I think I'm still seeing some slight differences 
forge-before-after

I think Paul is on to something, we should avoid changing the image and think harder about the actual problem here. The text goes way too far and draws under the image.

**Comment by liach** [comment]
I agree. wrapping or centralizing the text might help more.

**Comment by ChloeDawn** [comment]
Why should the logo not allow things to be rendered in the spacing? It's intentional logo design. The issue here is that text isn't being wrapped or truncated for rendering.

**Pull request closed without merging**
