### PR TITLE
Tabulate crash report mod list and add signature information

### PR DESCRIPTION
**Pull request by marvin-roesch**
*Note: This is an updated version of #4244. I opted for a new PR since it is quite different in scope.*
There have been cases of mod rehosting sites tampering with mod JARs recently. The changes were causing the game to crash, but the author only found out about the modified files after some troubleshooting with the users. This PR tries to leverage information signing information available about mods and displays it next to the mod file name in crash reports. Although all mods' fingerprints are already written to the log, this information is only available if you get a full log file (i.e. `fml-client/server-latest.log`).
With this PR, a modder can get a basic gist of whether his file has been modified.
Additionally, this PR changes the dumped mod list to be a table instead of a simple list. The generated output can be interpreted as markdown and will yield nice results. If there's no mod with a signature, the column is dropped. If I can gather information about invalid signatures easily, I'll add it to the table under the signature column.
An example of the output can be found in [this gist](https://gist.github.com/PaleoCrafter/ff31c0fc3249ac9b64b219b6ed46bdd4).

### CODE REVIEW

**Comment by liach** [comment]
You'd better not change the input order.

**Comment by liach** [comment]
Uhhh I mean import

**Comment by marvin-roesch** [comment]
I must have accidentally hit the reformat (+ organize imports) key binding. Should be all fine now. Not exactly sure why the Travis builds are failing, though.

**Comment by covers1624** [comment]
How are missing signatures handled in the table?

**Comment by marvin-roesch** [comment]
See the [example gist](https://gist.github.com/PaleoCrafter/ff31c0fc3249ac9b64b219b6ed46bdd4) for the output. I currently don't handle invalid/missing signatures for mods that expect a certain fingerprint as that would require either some passing through of values or re-evaluating the signatures.

**Comment by covers1624** [comment]
Yeah i was more referring to invalid, Ehh i suppose its not really that useful as its already in the log, this should give a really nice overview if my jars have been modified without getting a full log.

**Comment by marvin-roesch** [comment]
Yep, modders should be able to verify their own signatures. Adding an "INVALID" flag or something might still be helpful to see it at a glance. Let's see what Lex thinks about it.

**Review by liach — APPROVED** [review]

**Comment by marvin-roesch** [comment]
Looks like the build is fixed, shame on me for using a local class xD

**Review by covers1624 — APPROVED** [review]

**Comment by marvin-roesch** [comment]
As per Lex' request (on IRC), I've moved the table formatting into its own reusable class with an easy interface for adding/removing columns. It actually made the width adjustment for the columns a lot nicer to look at and could technically be used by mods for all their tabulation needs.
I've updated the [example gist](https://gist.github.com/PaleoCrafter/ff31c0fc3249ac9b64b219b6ed46bdd4) to accomodate for the changes. The only visible difference should be the colons at the start of the header-body separator columns. They're an artefact of my adding full alignment support, which obviously needs to manifest in the generated markdown.
If you want to see some sample output with different alignments, I can add examples to the gist.
For good measure, I've added a few unit tests to ensure the tabulation works correctly. If you want me to cover more, just notify me.

**Pull request merged**
