### PR TITLE
Improve the "Mod rejections" error message when connecting to a server

### PR DESCRIPTION
**Pull request by mezz**
Before:

After:

This can definitely be improved further but I think this change is a solid step in the right direction.

### CODE REVIEW

**Comment by 3TUSK** [comment]
Is there any chance that this screen supports i18n?

**Comment by mezz** [comment]
Unfortunately the text is coming from the server as a simple string rejection message, so I'm sorry but I think I will not localize this right now. It seems like a much larger effort to do it the right way. If this is accepted and you find a good way to localize, I am happy to review a PR to do it.

**Comment by ghost** [comment]
What about letting it look like the multiple error screen in your other PR about mod dependency screens?
I think that would look alot cooler!

**Comment by mezz** [comment]
This message is sent as part of the vanilla handshake process, unfortunately I can only send text and so there's not a lot of ability to format the message nicely.

**Pull request merged**
