### PR TITLE
Implementing latest snapshot particle design to improve performance.

### PR DESCRIPTION
**Pull request by border999**
As of the 1.9 snapshot 15w33b, particles are no longer registered as entities, I am curious as to whether you can do something similar in the coding of Forge. It would be a serious increase on performance in many areas.
I Might also suggest that you find a method to access minecraft's code to better analyze the changes to particle behavior and nature.

### CODE REVIEW

**Comment by simon816** [comment]
No you can't just merge 390 commits from master into 1.7.10...

**Comment by Syer10** [comment]
... wtf

**Comment by LordIllyohs** [comment]
its a troll did the same thing to openblocks https://github.com/OpenMods/OpenBlocks/pull/688

**Comment by cpw** [comment]
This is stupid, and you are a fool for believing that this would ever be accepted..

**Pull request closed without merging**
