### PR TITLE
Avoid caching OBJ and B3D models since they're baked on load now.

### PR DESCRIPTION
**Pull request by Unnoen**
Since all models are baked-on-load, we don't need to cache the files to reduce disk-loading anymore.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Models were never not "baked on load" the purpose of the caches was I believe to avoid reading from the file more than once if the model was referenced by multiple variants. That said I'm not really sure the benefits outweigh the costs here, so this may still be a good change.

**Comment by williewillus** [comment]
Yup, the OS buffer cache should already be speeding up subsequent reads, so unless there's a provable performance gain perhaps making the code simpler is better

**Comment by bs2609** [comment]
Models are not only baked on load, they can be baked at any time. See the animation system for an example of this.

In any case, this code is probably not needed, as models should be being loaded via `ModelLoaderRegistry`, and that already handles this. Do note that as a result, the benefit here is very small - the footprint is only that of the map itself.

From the point of view of cleaning up the code, this is a good change, but it could do with a more proper look over for potential side-effects first.

**Comment by Unnoen** [comment]
Yeah no worries, it was my first real foray into Forge's internals so it's not all that significant. 

In my head I meant "baked-on-load" like pre-1.8, I was under the assumption that models were baked as they were needed, however after 1.8 all models were baked when the game started and thus this wasn't needed anymore.

I seem to be very wrong but it seems it wasn't *all* for nothing and hopefully might bring up some conversation on existing code that should be adjusted.

Thank you for the good feedback however ❤

**Comment by lehjr** [comment]
As I recall, models are loaded twice, once to get the texture references to register them in the stitch event, and once for the model bake event. In between, the cache is dropped and refilled.

**Review by mezz — APPROVED** [review]

**Pull request merged**
