### PR TITLE
[1.10.0] Fixed sound paused/resume issue (Vanilla bug)

### PR DESCRIPTION
**Pull request by CreativeMD**
Already done for 1.9.4 (https://github.com/MinecraftForge/MinecraftForge/pull/2933)

### CODE REVIEW

**Comment by Actuarius** [comment]
@mezz added labels [Vanilla Bug]

**Comment by mezz** [comment]
https://bugs.mojang.com/browse/MC-35856

**Comment by CreativeMD** [comment]
Created another pull request for 1.10.x, because of the "needs update" tag.

**Comment by Actuarius** [comment]
@mezz added labels [Superseded]

**Pull request closed without merging**
