### PR TITLE
Fixed OBJ model loader not trimming lines on .mtl files

### PR DESCRIPTION
**Pull request by simeonradivoev**
Also added automatic replacement of / with the \ character.

### CODE REVIEW

**Comment by heldplayer** [comment]
Why does / need to be replaced with \?

**Comment by simeonradivoev** [comment]
Just a precaution. Most paths generated by 3d software use the \ slash. And OS paths use it as well.

**Comment by RainWarrior** [comment]
Actually, other way around - only Windows use \, but every OS understands /, including Windows.
OS-independent file separator in Java is File.separator, and MC uses '/' in its ResourceLocations, which is what texturePath is.

**Comment by simeonradivoev** [comment]
Good to know. I myself use Windows.

**Comment by shadekiller666** [comment]
I have updates to the OBJLoader sitting in a PR atm, the trimming of both the mtl parser and the obj parser included. Is the '/' vs "\\" thing actually a problem? If not this can be closed.

**Comment by heldplayer** [comment]
I doubt the '/' vs '\' is a problem, as '/' is supported by all OSes, but '\' is not however.

**Pull request closed without merging**
