### PR TITLE
[1.9.4] Added CriticalHitEvent

### PR DESCRIPTION
**Pull request by mcenderdragon**
This adds an event to cancel critical player hits and to modify the bonus damage dealt. This is the 1.9 version of #2878 and adds the feature from #2871.

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by mcenderdragon** [comment]
I am not sure but I think my merge messed everything up :/

**Comment by iLexiconn** [comment]
It did

**Comment by mcenderdragon** [comment]
@iLexiconn but it now has no longer a merge conflict, and it seems nothing get deleted.

**Comment by iLexiconn** [comment]
You added all of the commits that were made after yours to the pr

**Comment by diesieben07** [comment]
Don't merge in PRs, rebase instead.

**Comment by mcenderdragon** [comment]
Ok, the next time I will do it that way. (And I am shure there will be more merge conlikts because its in the EntityPlayer class)

**Comment by mcenderdragon** [comment]
I hvae a question, currently the CriticalHitEvent extends the AttackEntityEvent, does this result in the AttackEntityEvent called twice if its a critical hit ? should i extend from the normal PlayerEvent?

**Comment by mcenderdragon** [comment]
And should I open a new clean pull request ?

**Pull request closed without merging**
