### PR TITLE
[1.10.0] Added PlayerBrewedPotionEvent

### PR DESCRIPTION
**Pull request by MrIbby**
Same as ``ItemCraftedEvent`` and ``ItemSmeltedEvent``, but for potions.

### CODE REVIEW

**Comment by williewillus** [comment]
Docs

**Comment by MrIbby** [comment]
Done

**Comment by Kolatra** [comment]
You should probably squash the commits too.

**Comment by MrIbby** [comment]
GitHub already has the capability of squashing PR's.

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by ghost** [comment]
Why was this closed?

**Comment by williewillus** [comment]
It was autoclosed because the branch 1.10.0 was deleted. 1.10.x is the branch pr's need to target.

**Pull request closed without merging**
