### PR TITLE
Fix a typo in jar detection

### PR DESCRIPTION
**Pull request by liach**
`quava` -> `guava`

### CODE REVIEW

**Comment by asiekierka** [comment]
+1. Why does this have no attention after 9 days?

**Comment by cpw** [comment]
because i've been busy? Sorry, IRL comes first.

**Comment by asiekierka** [comment]
It's fine, it's not personally targetted at you - but you're not the only developer around. Or, in fact, the only person reading the issue tracker.

**Comment by liach** [comment]
By the way, what is IRL?

**Comment by GirafiStudios** [comment]
IRL = In Real Life.

**Comment by liach** [comment]
Thanks

**Pull request merged**
