### PR TITLE
In Material Hooks - For Swimming, Overlays, Boats, and Fishing.

### PR DESCRIPTION
**Pull request by AlgorithmX2**

### CODE REVIEW

**Comment by diesieben07** [comment]
I feel like the Javadocs are a bit... lacking. They don't explain what you can actually affect with these methods.

**Comment by AlgorithmX2** [comment]
I tried to elaborate in the descriptions some.

**Comment by diesieben07** [comment]
I was thinking something like: "Called when the entity is inside this block to check whether any 'inside material' triggers such as breath inside water should be triggered".

**Comment by AlgorithmX2** [comment]
I figure most of that was self explanatory.. but I change it.

**Comment by diesieben07** [comment]
I hate to be that guy, but the javadocs on `isEntityInsideMaterial` don't make sense now.
Yes, it might be self-explanatory but detailed docs are important in my opinion.

**Comment by AlgorithmX2** [comment]
Which part doesn't make sense, it seems fine to me?

Feel free to rewrite the whole thing I'm I'll just copy and paste it in

**Comment by Spartan322** [comment]
It would probably make more sense as 'Called when an entity is inside of the block, may be used to determine actions like breathing, material overlays, or an entity can swim in water'

Also why do you need world, blockpos, and blockstate, wouldn't world and blockpos cover blockstate, seems kind of overkill technically (also blockpos javadoc is actually incorrect, blockpos only represents position).

I think yToTest is slightly incorrect doc'ed (I think it doesn't properly covey the idea of purpose)
testingHead is on the verge of not being understood properly.

I need to ask how this a material hook when it seems more like its an 'inside block' check, and why are you giving them material, I'm pretty blocks already know the material they reference, so wouldn't it be pointless?

**Comment by AlgorithmX2** [comment]
The intention here is to allow MC to query if a block is acting as water for a specific entity, in a given position, for instance if your block has water inside of it, but isn't entirely water, maybe its only bot a small amount of water, or maybe its a multi-block tank you can jump into and swim around in.

Most of the values I'm passing in just happen to be laying around at the call site, I included block state since I already had it and if you want it you don't have to re-request it from the world.

yToTest is weird.. its mostly for when testingHead is true, other wise I'm just sending the Y that the other test uses by default.

the material being passed in is the material that is being tested for, not the block's material, if asking "Are you water?" or "Are you lava?"

So there is the 4th or so revision..

**Comment by Spartan322** [comment]
Why is a material not representing the block being passed into the block? Honestly, I don't get how that makes sense then.

**Comment by AlgorithmX2** [comment]
Because its a question, "Is your block X Material for Y Entity?"

Aka, is your block water? or is it lava? The point is that your blocks actual material is irrelevant.

**Comment by Spartan322** [comment]
That doesn't make sense then, if the block material is irrelevant then why is it being tested on a block, unless I backwards, what is the point of testing a material that your block doesn't cover.

**Comment by AlgorithmX2** [comment]
Its because you can't make a block that has more than one material.

For for instance, going back to my multipart tank thing from eariler. The tank is made of iron, but inside the tank is a level of liquid, so while I'm inside that liquid these tests can return true, to make the inside of an iron tank block act like water, so you can swim inside it and what not, mean while the block isn't actually water, its iron.

The point is that the block can be anythign I need it to be, but still behavior like liquid where I need it too.

**Comment by Spartan322** [comment]
This is a very slim case anyway tbh, so if you want to open the material system up, we might as well allow the material system to be collection (probably list), but then that require one hell of a rewrite, I think it be more useful, but then IDK, it probably be a huge patch.

In the end, this actually only covers a small portion and the documentation does not really describe the intent or real possibility with those functions (though it you want to be truly honest, if you plan to use any system like this, Minecraft is highly inadequate to handle it already)

**Comment by AlgorithmX2** [comment]
What i've done already provides for my use case, I'm not re-writing MC's material system or anything like that, that would be crazy.

I'm trying to make sections of my block have behaviors like liquids, and this patch can accommodate my needs, if no one wants it in forge I'll happy just go make a core mod instead.. Its way easier then getting a PR into forge.

I'm offering this PR cause i've been asked to restrict core-modding as much as possible.

**Comment by Spartan322** [comment]
I'm not saying its not a good idea for a PR, but (not sure about anyone else) I perceived it wrong because the javadoc appears to convey the wrong idea, honestly, Minecraft has a huge inadequate system, and in the end it appears we have hack around until Mojang fixes it. (or if someone was nuts enough to rewrite it, but then it might as well not be Minecraft right?) Either way, I'm just pointing out redundancies, documentation issues, and honestly, and issue with the material system which could be fixed by Forge but possibly/probably shouldn't. Also you might want to capitalize the parameter descriptions, it would look more professional (no need to, just a nitpicky suggestion)

**Comment by GotoLink** [comment]
From your intended usage, it seems like material argument is the most important part...but is placed last and got void documentation. Basically common arguments like World and BlockPos don't need much explained, but those that are specific to the method, do.
Then there is also the "null as ternary value" trick. I would have moved the default behavior in the method. That is the way it is done in other "Block hooks". It would help determine if default behavior is "good enough" for the block, and it would help maintenance.

**Comment by AlgorithmX2** [comment]
I choose to not move the default behavior, because 1, it is in the middle of a loop, and complicates the patch, as well as making the patch larger, this was the more minimal approach which I know is usually the preferred route.

I'm going to hold off any further revisions until someone with forge has a chance to respond.

**Comment by darkhax** [comment]
Just saw this PR, I think it is a great idea. It was described as a slim use case earlier, however there are quite a few mods which could be improved by this, such as TCon and Thaumcraft. I can also think of a few clever uses with this in one of my own mods.

**Comment by heldplayer** [comment]
Seems like a good addition for blocks that can contain multiple materials, not sure if the boxed booleans are a good thing though.

**Comment by AlgorithmX2** [comment]
Updated PR to fix merge issues, also added comments to patch code to describe intention of reach modification.

**Pull request merged**
