### PR TITLE
Created sun height factor to separate height effect from celestial angle

### PR DESCRIPTION
**Pull request by Abastro**
Created sun height factor to separate height effect from celestial angle.
Useful for customizing sun's position.

### CODE REVIEW

**Comment by Abastro** [comment]
Fixed spaces.

**Comment by Abastro** [comment]
I want opinions on this.;

**Comment by LexManos** [comment]
I'm not seeing to much use for this, yes it separates it out but what are the uses the justify the patch?

**Comment by Abastro** [comment]
To customize sun paths,
1. Determine sun position.
   Currently only getCelestialAngle can be used to determine sun position, which is not sufficient.
2. Clarification. getCelestialAngle is currently used for sum height and determine part of the day. It should be used in only expressing part of the day, like clock.
3. To match the global standard. (As hour angle and height)

**Comment by Abastro** [comment]
So.. still insufficient?

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
