### PR TITLE
Improve creative tab page functionality

### PR DESCRIPTION
**Pull request by Grinch**
This aims to resolve scenarios that cause a completely empty tab page to appear (at page that has no creative tabs excluding the search/inventory tab) as well as allow the back/forward buttons to loop.

Signed-off-by: Steven Downer <grinch@outlook.com>

### CODE REVIEW

**Comment by LexManos** [comment]
Never encountered 'blank' pages, and it not looping is intended behavior.

**Comment by Zidane** [comment]
Lex,

While the looping makes sense, if your mod has many tabs (3+ pages) then it will add a blank page of them. I'm having @Grinch re-make this PR without the looping.

**Comment by heldplayer** [comment]
I would like it if the pages looped, I don't like clicking 5 times to get to the last page when using a lot of mods. A simple click to the left on the first page to get to the last page would be amazing.

**Comment by JustGregory** [comment]
I am reminded of the joke, where the patient tells the doctor, "Doc, it hurts when I do this," to which the doctor replies, "Well, don't do that."
In other words, @heldplayer et al, could you try not having so many mods? IMHO, More mods does not equal a better game experience.

**Comment by heldplayer** [comment]
@JustGregory It's the modpacks that do it! Not me! :P

**Comment by Grinch** [comment]
@JustGregory while I agree with that, the issue is still a valid one. :|

**Comment by LexManos** [comment]
Matter of opinion, and sadly the only one that matters in this one is mine :P
There will be 1/2 the community that wants to not cycle, the other 1/2 want it.
I'm of the former opinion so that's how it goes.

**Comment by Mengmoshu** [comment]
As a non-coder I have to ask if someone couldn't just write a mod that makes the creative tabs loop? Or would it require some kind of support from Forge?

**Comment by diesieben07** [comment]
Such a mod is possible and very easy to make.

**Pull request closed without merging**
