### PR TITLE
Fix patches of GuiScreen (#3704) and ItemDye (#3736)

### PR DESCRIPTION
**Pull request by Mathe172**
As the title suggests, this PR fixes the patches of #3704 and #3736 so that you don't have to exclude them from every single commit.

For the future: Could such things be checked by travis?

### CODE REVIEW

**Comment by liach** [comment]
The content looks great, but who authored this commit?

**Comment by PhiProven** [comment]
@Mathe172 and I work together on most coding stuff (mostly not independent but via TeamViewer). This may have the side effect that one of us creates the commit and the other one the PR. (No, we are not schizophrenic ;-) )

**Comment by mezz** [comment]
Looks good, I have seen this issue when creating patches.
I'm not sure how we would get travis to test for this kind of issue.

**Comment by Mathe172** [comment]
I'm not really familiar with the capabilities of travis, but I was thinking of doing something along the following lines if possible: Execute genPatches --> Check whether there are any new changes

**Pull request merged**
