### PR TITLE
Add IForgeRegistry#getDefaultValue

### PR DESCRIPTION
**Pull request by Madsthunder**
Allows modders to get the default value of an IForgeRegistry instance.

### CODE REVIEW

**Comment by williewillus** [comment]
Is this already implemented in subclasses?

**Comment by Madsthunder** [comment]
Yes, but RegistryBuilder#create only creates an IForgeRegistry and not an FMLControlledNamespacedRegistry or RegistryNamespaced.

**Comment by TehNut** [comment]
You can safely cast the provided `IForgeRegistry` to `FMLControlledNamespacedRegistry`

**Comment by Madsthunder** [comment]
Good point, but shouldn't this be a feature in all registries that **only** implement IForgeRegistry?
Example:
If somebody extends RegistryBuilder because they don't want the bulk of FMLControlledNamespacedRegistry or they want to avoid PersistentRegistryManager for some weird reason, then all they would have to do is implement IForgeRegistry and provide the required methods. Besides, extending FMLControlledNamespacedRegistry is impossible due to the invisible constructor.

**Comment by LexManos** [comment]
Dont make me make RegistryBuilder final.
You're not meant to have your own implementations of IForgeRegistry, the interface is soley designed to be a CLEAN UNCLUTTERED interface for dealing with the registries.
We rely far to much on the internals of FMLCNSR{screw long names} for all the 'magic' that happens with registries.

Not sure why anyone in the external world would care about, or NEED to know about the 'default value'
There is a major wall between what you as modders should care about, and what we use internal.
You guys shouldnt care or know if the registry is 'defaulted' or not.

**Comment by AtomicBlom** [comment]
I can't even think of a use case for needing the default object.

If you were trying to use it to compare if an object returned from the registry was the default or not, use "containsKey"

**Pull request closed without merging**
