### PR TITLE
[1.8] Allow server to access Potion isBadEffect()

### PR DESCRIPTION
**Pull request by mezz**
Same as https://github.com/MinecraftForge/MinecraftForge/pull/1920, updated for 1.8

### CODE REVIEW

**Comment by asiekierka** [comment]
noci-1.8.8 might be a better idea as it's close to being released yet not entirely released, meaning that it will break no mods ever and be available relatively soon.

**Comment by cpw** [comment]
Don't target noci- it'll become a real branch when we actually finish the release.. But yes, target 1.8.8 for sure..

**Comment by mezz** [comment]
:pensive:

**Comment by asiekierka** [comment]
1.8.8 is going to hit soon anyway, mezz - really not worth targetting 1.8.

2015-11-18 4:24 GMT+01:00 mezz <notifications@github.com>:

**Comment by cpw** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/8e9feb21fab4387d417ae65a5e7a726f7fd9a186

**Pull request closed without merging**
