### PR TITLE
[1.12] Added sneak right click placement of milk to milk bucket.

### PR DESCRIPTION
**Pull request by P3pp3rF1y**
As the name states this adds shift right click placement of place-able milk fluid to milk bucket. The fluid and its block variant needs to be added by mods (as well as they need to enable universal bucket if they want to be able to pick it back up), but this takes care of the need to add custom milk buckets in mods if those want buckets to be able to place milk in world.

### CODE REVIEW

**Comment by KnightMiner** [comment]
There is an item interact event, can't you just use that to place your fluid by checking for milk and sneak right click?

**Comment by KnightMiner** [comment]
There is an item interact event, can't you just use that to place your fluid by checking for milk and sneak right click?

**Comment by P3pp3rF1y** [comment]
Sure, but that means checking for those conditions on any interaction and that all mods that add milk fluid would need to have milk fluid placement code implemented instead of having forge take care of that as it does for all the other fluids.

**Comment by williewillus** [comment]
Why does this check for sneak? Block interactions already take precedence over item use actions, and water/lava buckets don't need you to sneak before placing.

**Comment by mezz** [comment]
Checking for sneak makes players less likely to accidentally place milk instead of the normal action of drinking it.

**Comment by JamiesWhiteShirt** [comment]
There are several ways a mod might want to add a milk fluid and keep the drinking behavior:
- Drink by default, place fluid when sneaking (this approach)
- Place fluid by default, drink when sneaking
- Make separate items for placeable/drinkable milk.

I feel this unnecessarily forces a specific behavior on the base game and Forge which is why I disagree with this approach.

FYI: When it comes to right click interactions, vanilla Minecraft only uses sneaking for _interaction precedence and nothing else_. Some people might want to respect that.

**Comment by williewillus** [comment]
@mezz all items in minecraft with both block (onItemUse) and item (onItemRightClick) actions have onItemUse triggered *first*. This means that the first takes precedence over the second. Breaking from that using a sneak check is an inversion of the expected behaviour of the rest of Minecraft. 

For example, you don't have to shift to place an ender eye into the frame without throwing it, nor do you have to shift to spawn a firework against a block instead of using it as elytra boost.

The sneak check just seems unnecessary/an overstep of what forge needs to be doing, in addition to the consistency problems I mentioned.

**Comment by P3pp3rF1y** [comment]
So I have discussed this with @mezz  before putting the PR together and basically my understanding out of this was that forge in general doesn't want to change vanilla behavior hence drinking from the milk bucket with right click and thus the need for sneak right click to place the bucket.
@JamiesWhiteShirt given the focus on keeping the vanilla behavior that was the only option, but that doesn't mean that mods can't change the behavior in any other way through interaction events.

**Comment by JamiesWhiteShirt** [comment]
This is fine when it comes to keeping vanilla behavior, it will remain unchanged until a mod triggers this.

Sure, if a mod intends to alter the milk fluid differently from what you have implemented here it has to use interaction events. My concern is this: Why should _this behavior_ be preferred and added to Forge by default? Shouldn't all implementations of the milk fluid/bucket be equally feasible for mods?

If a mod has to implement a _different behavior_ with interaction events, I believe _any behavior_ should be implemented with interaction events.

**Comment by williewillus** [comment]
I don't understand. If you wanted to "keep vanilla behaviour" then you *wouldn't* have the sneak check, because block interactions always go before item interactions in vanilla.
Vanilla: Block before item, sneak skips block and uses item.
This: Item before block, sneak skips item and uses block.
See the reversal?

**Comment by P3pp3rF1y** [comment]
Well, keep vanilla behavior in terms of drinking from bucket. I don't think that coming out of vanilla you would know that you have to sneak right click to drink from it.

**Comment by P3pp3rF1y** [comment]
And really even the options of just place or place without sneak and drink with sneak work for me, at this point it's really a discussion of what takes precedence - consistency with other buckets or vanilla drinking behavior.

**Pull request closed without merging**
