### PR TITLE
Correct the default resource location of potion registry

### PR DESCRIPTION
**Pull request by CrafterKina**
field_185177_b (WATER) is "empty".

### CODE REVIEW

**Comment by TechnicianLP** [comment]
How does changing the default key for a registry fix an incorrectly named (and private/deprecated/unused) field? 
for issues with mcp-mappings visit #mcpbot on irc

**Comment by CrafterKina** [comment]
The problem is not the wrong name but the incorrect default value.
MCP Name -> ModCoderPack/MCPBot-Issues#469

**Comment by TechnicianLP** [comment]
can you elaborate why the current defaultvalue is incorrect?

**Comment by CrafterKina** [comment]
Mojang's original code says the default value is `new ResourceLocation("empty")`.
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/potion/PotionType.java.patch#L12

**Comment by LexManos** [comment]
Right, I think they must of changed it sometime that I missed.

**Pull request merged**
