### PR TITLE
[1.14] Add heuristic for identifying why mods might not have been loaded.

### PR DESCRIPTION
**Pull request by JoJoDeveloping**
A lot of people try to load mods which are not forge mods by throwing them into the mods folder, and then they ask for help on the discord or other places. This PR is intended to explain why a mod cannot be loaded so people realize their mistake without having to ask online.

### CODE REVIEW

**Comment by Unnoen** [comment]
I don't think Optifine or other mods should be mentioned by name, as it's on them to make it compatible and having to remove this later is just a pain. Is there not a way to detect in general?

As for Liteloader, the Liteloader Forge mod can load those lite mods, so what happens when that is updated and people start using that?

**Comment by JoJoDeveloping** [comment]
The hope is that mod files that are actually loaded don't end up in that list, including LiteLoader and Optifine. Since there is currently no other loader integrated into Forge, I don't know how they handle it. If they turn out to handle it wrong, then I'ld add appropiate code.
The reason Optifine is mentioned by name is that it used to and likely still will be a mod that is loaded in it's own way.
Detect *what* in general? a mod's name?
Edit: That being said, this only annotates the already existing list of invalid mod files. If a loader does not handle its mods correctly, they would still end up on that list, but get the default error message, which is "File {2} is not a valid mod file"

**Comment by Unnoen** [comment]
Ah, I didn't realise it was after load, I'm a bit sleep deprived at the moment, ignore me. 😛

**Comment by JoJoDeveloping** [comment]
The mod loading error screen is missing in 1.14 so I'm adding it back. As this changes the source branch, the pull request has to be reopened (see #5379 )

**Pull request closed without merging**
