### PR TITLE
[1.19.x] BiomeTags Fixes/Improvements

### PR DESCRIPTION
**Pull request by Flemmli97**
This PR addresses points made by  sciwhiz12 comment [https://github.com/MinecraftForge/MinecraftForge/pull/8564#pullrequestreview-988572064](https://github.com/MinecraftForge/MinecraftForge/pull/8564#pullrequestreview-988572064) that i didnt manage to fix in time before the previous PR was merged.
It removes redundant duplicate entries for dimension specific tags by using a tag reference instead of copy the contents of the sub tags.

It also fixes `minecraft:sparse_jungle` not being in `is_wet/overworld` cause I accidentally used `is_wet` only there.

Also since I'm not too wellversed in biomes idk if `forge:is_coniferous` and `minecraft:is_taiga` should be treated as equal or not and as such left that as it is now: Atm they are not equal.

~~There is also a pending PR #8684 that, depending of whichever gets merged first, then needs to be addressed too with this change~~

### CODE REVIEW

**Comment by Minecraftschurli** [comment]
could you also address the duplication to the new vanilla provided biome tags (example `BiomeTags#IS_BEACH` and `Tags.Biomes#IS_BEACH`)

**Comment by Ketok4321** [comment]
When it comes to `forge:is_coniferous` tag, I think new, more precise tags for forests could be added, like `forge:is_forest/coniferous` and `forge:is_forest/deciduous`, and also tags for forests of every wood type, like for example `forge:is_forest/oak` and `forge:is_forest/spruce`.

**Comment by JaisDK** [comment]
how about removing `forge:is_savanna` and `forge:is_overworld` as they already exist as minecraft tags.

**Comment by JaisDK** [comment]
`is_end` is also a duplicate, but it would be nice with a tag that includes all the end biomes except the main island `minecraft:the_end`

**Comment by Flemmli97** [comment]
> When it comes to `forge:is_coniferous` tag, I think new, more precise tags for forests could be added, like `forge:is_forest/coniferous` and `forge:is_forest/deciduous`, and also tags for forests of every wood type, like for example `forge:is_forest/oak` and `forge:is_forest/spruce`.

i dont see how this is needed. like i dont see how e.g. non forest coniferous biomes are a thing. but maybe someone else thinks otherwise

**Comment by GirafiStudios** [comment]
Shouldn´t mushroom_field_shore, be in the beach tag as well?

**Comment by Flemmli97** [comment]
updated to resolve merge conflicts

**Review by marchermans — APPROVED** [review]

**Pull request merged**
