### PR TITLE
Add "BlockStates", a helper class with fields for all the vanilla block states.

### PR DESCRIPTION
**Pull request by rwtema**
Adds BlockStates, a class with fields for all the vanilla blockstates.

Also added BlockStatesClassGenerator, that will automatically generate the code for BlockStates, since it would be ridiculous to do this manually.

### CODE REVIEW

**Comment by liach** [comment]
Is it really a good idea to add 3000 lines of code to catalog all blockstates? I will be messed up by such a 300 kb huge file.

**Comment by mezz** [comment]
What is this used for? I don't understand.

**Comment by williewillus** [comment]
^ same here, not sure of the use/purpose

**Comment by LexManos** [comment]
1) Autogenertating code is bad mmkay
2) We already have the states in the table held in BlockStateContainer.
3) WHY!?!?!
No... Just no...

**Pull request closed without merging**
