### PR TITLE
Adds category support to config annotation, and sub objects

### PR DESCRIPTION
**Pull request by Max9403**

### CODE REVIEW

**Comment by TehNut** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3630

**Comment by TehNut** [comment]
Wait ignore me, I read comment, not category

**Comment by LexManos** [comment]
Not described, no information, and annotations on values not holders... no...

**Comment by LexManos** [comment]
This is something that i've been planning on doing for a while, I think this is what you actually want. But as you have no information what so ever meh.
https://github.com/MinecraftForge/MinecraftForge/commit/5cce0545482fb7f2174d21b9c007c0ae037d44d1

**Comment by Max9403** [comment]
That does indeed look like what I had in mind, I didn't realize you needed more than the title to understand what this pull request was for - I'll try be more verbose next time

**Pull request closed without merging**
