### PR TITLE
Block::addRunningEffects, Take 2.

### PR DESCRIPTION
**Pull request by covers1624**
Simple hook that allows blocks to customize running particles, be that with a completely different type of particle, or via some custom particle pipeline.

### CODE REVIEW

**Comment by ShetiPhian** [comment]
Good to see another attempt to get this in;
Just adding something I noticed while adding similar code.

On thinner blocks the default 0.2 offset on the y value causes the block bellow to be used.
To work around this I changed the offset to 1/16 of a block (0.0625) and preformed an air check. If the block was air the 0.2 offset was used instead.

**Comment by HenryLoenwind** [comment]
Maybe something like `!(blockIn.addRunningThroughEffects() || blockOn.addRunningOnTopEffects())`?

**Comment by asiekierka** [comment]
@ShetiPhian If you're performing an air check, is *any* offset really necessary?

**Comment by ShetiPhian** [comment]
@asiekierka 
The original offset stops carpet from creating particles, I figured this is intended, so I just thinned it down to work with 1/16 blocks while still blocking carpet.

If a non-offset position is used for the hook; when addRunningEffects returns false the -0.2 offset probably should be used so vanilla behavior is consistent.

**Comment by mezz** [comment]
> Rabbits on the other hand only call this on the client side.

Why?

**Comment by covers1624** [comment]
They call it for their little jump particles, from a client method, so i guess an answer is "Because Mojang"?
An option could be to force running particles to the client, as the calls to add particles just no-op on the server,

**Comment by mezz** [comment]
Please update this to resolve conflicts.

**Comment by liach** [comment]
is the javadoc on rabbits wrong? why do you mention the use on client twice...

**Comment by mezz** [comment]
Looking into it a bit more, here's what I found:

- Rabbits override `spawnRunningParticles` to do nothing, and then call `createRunningParticles` on the client from `EntityRabbit#handleStatusUpdate`.
Their particle pattern matches the hops, instead of just spawning all the time from walking.
- Slimes do it a completely different way, for some reason.
- Most things don't seem to sprint at all, just ocelots and players... and rabbits sort of.
- Spawning the running particles on the server goes through everything until the very end where the actual `spawnParticle` is a no-op.

Mentioning that rabbits only call it on the client is pretty irrelevant then, since it does basically nothing on the server anyway, as far as I can see.

**Comment by covers1624** [comment]
I've removed the javadoc on rabbits, If there aren't any more comments people have regarding the javadoc ill go ahead and resolve merge conflicts.

**Comment by mezz** [comment]
Looks good, go ahead.

**Comment by covers1624** [comment]
K, after many hours battling git, i finally resolved conflicts.

**Comment by mezz** [comment]
This looks fine, but can you add a test mod so I can make sure it's working as intended?
You can just copy one of the existing ones and have it add custom running particles.

**Comment by covers1624** [comment]
A test mod has been added for all block particle hooks. There actually weren't any existing testmods for particle hooks from what i could see.

**Comment by mezz** [comment]
Tested and looks good to me. The particle test mod is nice, thanks.

**Pull request merged**
