### PR TITLE
Chunk capabilities

### LINKED ISSUE #4213: Chunk capabilities?
Storing and accessing additional data with chunks is tricky. You have to store it externally, typically using `ChunkEvent.Unload`, `ChunkDataEvent.Load` and `ChunkDataEvent.Save` to manage the lifetime and persistence of some map. In my opinion, this is unnecessarily tricky.

The great advantage is that the chunk owns it capabilities; the capabilities attached to the chunk live as long as the chunk. This way it is nearly impossible to screw up attaching data to chunks.

My use case is a simple diagnostics mod that will attach a stack trace to chunks to determine how the chunk was loaded/generated. This is part of an ongoing effort to spread awareness about arbitrary chunk generation.

### PR DESCRIPTION
**Pull request by JamiesWhiteShirt**
Closes #4213 

Chunk capabilities are saved to NBT but do not sync by design as with other capabilities. Saving the capabilities is wrapped in a try/catch to avoid corrupting world data and logs errors similar to other NBT errors.

Implementors should mark the chunk as dirty when its state changes, see the test mod.

The included test mod add a pollution level to chunks, which can be increased by using flint and steel, and decreased by placing saplings.

### CODE REVIEW

**Comment by mezz** [comment]
Looks good to me. @JamiesWhiteShirt can you resolve the merge conflict?

**Comment by JamiesWhiteShirt** [comment]
Resolving the merge conflict was a bit of a mess, but I think I managed to fix it.

I also added a bit to the test mod that I forgot. It would unnecessarily mark chunks as dirty when loaded from files. Chunk capabilities with state sure have some pitfalls.

**Comment by mezz** [comment]
Looks good.
I think this could be more readable if you made a method like this:
```java
void set(int value, boolean markDirty);
```

**Comment by JamiesWhiteShirt** [comment]
Yup, agreed. I myself would consider marking the chunk dirty an implementation detail and not part of the interface, but your suggestion is simpler and fits a test mod.

All good @mezz ?

**Comment by mezz** [comment]
Tested and looks good to me.

**Comment by LexManos** [comment]
I think its kinda dumb to attach caps to everything ever.. but sure whatever... Fix your Conflicts.

**Comment by JamiesWhiteShirt** [comment]
@LexManos Merge conflicts are resolved.

**Pull request merged**
