### PR TITLE
[1.12.x] Allow cancellation of the water splash effect on entities

### PR DESCRIPTION
**Pull request by sokratis12GR**
*Alrighty, as seems the other PR had some issues, this fixed them.*
This PR adds the SplashEffectEvent to the EntityEvent,

> what does the event do ? 

It is a cancellable event which allows the control of where the splash effect when enterring a fluid should appear and because it extends the EntityEvent modders can control over to which entiies that should happen as well as have a control of what effects to be applied (if any).

cc @p455w0rd

### CODE REVIEW

**Comment by covers1624** [comment]
Why an event and not a method on block like every other hook? What cases do you see needing to cancel splash particles on another fluid? Why is there no fluid context in the event?

**Comment by p455w0rd** [comment]
@covers1624 it's for custom particles for custom fluids...see my recent tweet about fluids and bubbles...u can get block and/or material from entity pos..this is in the entity class..if u have a better solution not involving a coremod, I'd love to hear it

**Comment by covers1624** [comment]
I get that but why is it an event? You just described canceling and adding your own particles for your own fluid, this doesn't need to be an event, having it as an event implies that you want to cancel the particles on another mods fluid, that would be backwards from all the `addxEffects` that already exist in block. I'm saying this should be a hook exactly like those, you do not need this to be an event as YOUR fluid can control ITS particles from ITS block.

**Comment by jabelar** [comment]
Note that in the upcoming PR #4619 that the ability to enable/disable splash particles is included. However, they will still be the water default particles. I was planning to follow up with a PR to allow custom particles, but since you're already interested I suggest that you add it directly to the Fluid class.

As covers1624 says, to do this properly you would simply have your fluid generate the particles and hook into the vanilla where the water particles are created.

The event won't hurt, but events are generally intended for modifying the behavior of vanilla or other mods. I suppose one way modders could use it is to modify vanilla if they wanted. So I guess the event could be useful.

In any case, I am glad that a lot of people are interested in fluids at the moment. I plan to follow up after PR #4619 gets accepted (hint hint) with some additional enhancements, such as fluids have custom splash particles but also things like custom ice, etc.

**Comment by p455w0rd** [comment]
@covers1624 ..oh...this is because my custom fluid still uses Material.WATER which is what the entity method checks for...eithout Mayerisl.WATER we don't get the gravity effect or air loss

**Comment by jabelar** [comment]
That is why I mentioned my PR above -- it allows other materials to give you the air loss, pushing effect, etc. Basically separates the effects from needing to have Material.WATER.

Once that is in place, your PR (or I might do it later if you don't) would extend it so there is a method (either in material or in Fluid, needs some debate) to indicate a custom particle is to be used, along with related resources, color, and maybe even generate the particle directly. Then the vanilla would get a "hook" where instead of testing for WATER it would also cover the case where it was a Material/Fluid that had custom particles and then intercept accordingly.

However, as I mentioned above having an event could still be interesting to modders. It would allow people to change vanilla splash particles (not sure how common that is for people to want to do though) as well as any custom Fluids that choose to use Material.WATER.

**Comment by p455w0rd** [comment]
@jabelar Sorry, I haven't been trying to ignore you. Your PR is pretty extensive, and I have been in love with it since you submitted. However, it is such a large PR that it's hard telling if or when it'll get merged. the only person who can really determine how soon your PR would be merged is Lex and this could still be a while. Like you said, this would still be useful for Fluids using Material.WATER (although if/when your PR is merged I would no longer have a use for it myself). This PR is so small that I'm hoping it wouldn't take too long to get merged. I do hope your PR gets merged soon.

**Comment by jabelar** [comment]
Yeah, I understand. Nothing wrong with a few targeted PRs while we wait for an overhaul. I really don't know the likelihood or timing for my PR being accepted. I know the Forge gods are extremely busy. My main hope though is that it seems there are a LOT of PRs related to fluids right now (including your own), so it seems to be of keen interest to modders and therefore hopefully prioritized sometime soon....

**Pull request closed without merging**
