### PR TITLE
Improve Fabric mod error message

### PR DESCRIPTION
**Pull request by Prospector**
I've tried to improve this error message here because "cannot be loaded" is vague and makes it seem like an unexpected error and doesn't tell why it cannot be loaded. This should help with the confusion I think.

### CODE REVIEW

**Comment by pau101** [comment]
This message reads as implying there can be a compatible Fabric mod and this one just happens to be be incompatible. I would think this suffices:
`File {2} cannot be loaded because it is a mod for Fabric, not Forge`

**Review by PoolloverNathan — CHANGES_REQUESTED** [review]
I think the message should be shorter.

**Review by jamierocks — CHANGES_REQUESTED** [review]
Should make the equivalent change for LiteLoader too.

**Comment by Prospector** [comment]
Lex already vetoed this on discord anyway, but IMO this does not read like some fabric mods are compatible at all, rather that them being fabric is the cause for the incompatibility. Perhaps it could've used a comma though.

**Pull request closed without merging**
