### PR TITLE
Issue #4814

### PR DESCRIPTION
**Pull request by panoskj**
Refer to issue #4814 for details. I think it is best to fix this in EntityRenderer after all.

### CODE REVIEW

**Comment by mezz** [comment]
It looks like unascribed found a way to do this in a relatively compatible way, can you check it out and see if it fits what you need? https://www.reddit.com/r/feedthebeast/comments/8dgdo9/ive_just_released_vise_a_mod_that_splits_gui/

**Comment by panoskj** [comment]
Thanks for informing me @mezz. It looks like he sets the global MC scale before each rendering event, then resets it back to whatever it was. I considered this way too. Yet, the simplest and least computationally expensive way would be to fix this inconsistency in MC's code. Otherwise you have to add code that essentially works around this issue.

**Comment by mezz** [comment]
Unfortunately we have to be pretty comfortable with working around inconsistency in MC's code. Adding patches to Forge increase the maintenance burden, every change needs to be updated to new Minecraft versions, so we can't just fix up the Minecraft codebase for ease of use.
In this case I agree that it could be simpler with your patch, but I think that the way Vise does it is pretty reasonable already, without needing changes. If you find you are unable to use that method for your gui then maybe we should revisit this, but otherwise I think it is the way to go.

**Comment by panoskj** [comment]
I realize you want to keep the patches minimal. That's why I suggested adding this fix right before an existing hook. Point is, this piece of code will have to be maintained anyway.

But if that's the reason you won't add this, may I suggest implementing the fix inside ForgeHooksClient.drawScreen? Check https://github.com/MinecraftForge/MinecraftForge/pull/4816/commits/fb223bc53e3d19e36a9d2b108436b2b4bad6bd78, that was my initial approach, because it is compatible with Optifine, but it won't need any maintenance too.

I also believe Vise could make use of this feature to simplify his mod and improve its performance.

**Comment by LexManos** [comment]
This is not going in on 1.12. The fact that you're just arbitrarily changing the definition of what these values are that are passed to the event breaks any existing mods that use those values in the event.
And before you argue that its an incorrect value, its the correct value that everything else in that section of code uses, it's just not the value YOU expect.

**Comment by panoskj** [comment]
The "changed" values are guaranteed to be equal to the "original" values, as long as the current GUI screen's resolution is equal to MC's scaled resolution. The changes I did are not "arbitrary" - I did my research first. I expected different values because I changed the scale of a GUI screen. And I expected those different values for the modded GUI screen ONLY. I haven't heard of any mod doing anything similar, except Vise, which was released just a week ago. So, unless you use such a mod, you won't even be able to tell the difference.

@LexManos you could have tested the code before claiming it will break other mods, but it looks like you didn't even check the code thoroughly. That's really disrespectful. For your info, I have tested it with hundreds of mods already and it worked like a charm. Edit: I just tested it with Vise and it seems to be compatible too. Give me a single example where it doesn't work as advertised and I will shut up.

Finally, reading feedback here: https://www.reddit.com/r/feedthebeast/comments/8dgdo9/ive_just_released_vise_a_mod_that_splits_gui/ it looks like more people would like to use a custom scale for specific GUIs. It will be a great feature in my opinion but you seem eager to reject it.

**Comment by LexManos** [comment]
I have checked the code thoroughly, I do actually understand whats going on.
Just because you can't find a mod that breaks with this doesn't mean there are not ones that exist.
Even if there isn't, it doesn't mean that you can change what the value of that field in the API is. 

You have not provided any compelling reasoning besides you feel this is the correct value.
You *could* provide an example of why this is an issue.
You *could* provide some screenshots showing the issues. Or better yet a test mod exampling the issue.
You *could* show us the filed report with Mojang over this issue, as this appears to actually effect vanilla code as well. {Buttons on scaled GUIs}
You *could* entertain other ways of providing this value to the events you want. 
You *could* But you don't.

**Comment by panoskj** [comment]
I don't simply feel this is the correct value - what I feel is the API should be more consistent. It makes no sense to have one value for mouse position in draw events and another value in click events. And I didn't request this into 1.12. I believe however other mod authors who use these values should become aware of this issue, perhaps in the next major update. We won't achieve cross mod compatibility otherwise. If these aren't compelling reasons for you, then we should close this PR right now.

Now, I did provide an example mod and a screenshot in issue #4814. You commented there too, so I thought you would have checked it. The approach Vise takes doesn't work for this case after all, for your info. Anyway, here is the example mod which uses the feature I suggested: https://github.com/panoskj/CompactStorage/tree/gui-scales-down. You can also test the original mod (without my fix) for comparison. Do you require compiled files? Just tell me.

Moreover, I don't think Mojang would care to fix it, because it doesn't really affect MC without mods. Vanilla doesn't use custom scales for its GUIs. So, I didn't report it to them.

Finally, there always exists a different way to do the same thing, e.g. ASM. How is this relevant? I'm talking about an inconsistent API which could be made more consistent (in the next major update) without even breaking anything.

**Comment by mezz** [comment]
This was brought up to a vanilla dev and they claimed the gui scale is already being handled more consistently in 1.13.
I have decompiled one of the latest snapshots to confirm this.
In the meantime, please use the existing workaround.

**Pull request closed without merging**
