### PR TITLE
Fixed entity navigation to stop entities spinning

### PR DESCRIPTION
**Pull request by Wyn-Price**
Fixed an issue with entities spinning around on the last path node, and not being able to complete the path. This problem especially occurs to entities with large hitboxes, and is caused by the target position, and the checked position being different. I've changed entity offset in the path navigators to match the math in `Path#getVectorFromIndex`, to make the target and checked position the same. ~~This is disabled by default and can be turned on with the config option `fixEntityNavigation`.~~

For testing, I modified the vanilla Zombie entitiy to have a width of 2, and for it's wanding AI to be 4 times as likely.

Before:
forgespinning-before

After:
forgespinning-after

Related issue: https://bugs.mojang.com/browse/MC-94054

### CODE REVIEW

**Comment by Wyn-Price** [comment]
~~One thing I noticed, is that the forge server config only gets loaded/saved on the physical server, while a bunch of values inside the sever config are referenced on both physical client and physical server. If there is a reason why this is the case, then I'll create a Common config spec and put the `fixEntityNavigation` value in it.~~

No longer As issue as I've removed the config option.

**Comment by Wyn-Price** [comment]
This is still an issue with vanilla.

**Comment by LexManos** [comment]
The overall diagnosis sounds fine, but your math seems off. Nowhere else does it add 1 to the width of the entity. Why is that there?

**Comment by Wyn-Price** [comment]
The math is taken from `Path#getVectorFromIndex`
image

**Comment by LexManos** [comment]
Sorry missed that in the main post.

**Pull request merged**
