### PR TITLE
[1.18.x] Catch and aggregate exceptions during NewRegistryEvent

### PR DESCRIPTION
**Pull request by SizableShrimp**
Custom forge registries which throw exceptions during creation will cause `NewRegistryEvent#fill` to prematurely exit and fail to create any registries that come after the failed one.
This issue is compounded by the fact that the fill method is handled from a CompletableFuture, where FML's ModLoadingState system unfortunately silences exceptions.

A similar approach is taken to #8527 with the fix to ObjectHolderRegistry.
This fix both properly logs exceptions and will continue to fill registries even if there is an errored one, to prevent a cascade of dozens of registries not being created due to one erroring registry creation.

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

**Comment by marchermans** [comment]
This works and indeed follows the original precedent set to fix this.
@SizableShrimp What is the actuall swallower? FML or ML?

**Comment by SizableShrimp** [comment]
It's FML and its CompletableFuture state provider stuff

**Comment by marchermans** [comment]
Ahhh right the state providers....

**Comment by SizableShrimp** [comment]
Yes, also know as *hell*

**Pull request merged**
