### PR TITLE
[1.17.1]Fixes client side PartEntity id doesn't matches with server side

### PR DESCRIPTION
**Pull request by XenonDB**
#8188 
Fix shifting first despite other issue causing id mismatch that still exists.

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
I'm currently unsure whether this would be valuable if the [edge case](https://github.com/MinecraftForge/MinecraftForge/issues/8188#issuecomment-962162488) presented in the issue is present. Currently I'm unable to replicate this bug by checking the ids on world join so I'm unsure whether the provided test case is valid.

If the deferred ids are a true issue, then this would not be a valid fix. Please replicate your error along with set up and hardware specs so we can have a decent idea on what is happening since I don't really see anything within the code that may cause this.

**Comment by XenonDB** [comment]
> I'm currently unsure whether this would be valuable if the [edge case](https://github.com/MinecraftForge/MinecraftForge/issues/8188#issuecomment-962162488) presented in the issue is present. Currently I'm unable to replicate this bug by checking the ids on world join so I'm unsure whether the provided test case is valid.
> 
> If the deferred ids are a true issue, then this would not be a valid fix. Please replicate your error along with set up and hardware specs so we can have a decent idea on what is happening since I don't really see anything within the code that may cause this.

Since logger will show which thread it current is in, I made a test below:
未命名
```java
if(!this.level.isClientSide) {
    	  LOGGER.info(this.getClass());
          LOGGER.info(this.id);
}
```

And I found there are other threads creating entity indeed: (these threads are called "Worker-Main-x")
https://paste.ee/p/zeKnD
https://paste.ee/p/0PKSq

These threads seem relative to chunk generation because if I back to screen and join the world again, these threads don't exist.
They are also relative to ender crystal generation.

However, parts id preempted may be a rare situation since I got into the end and let game generate it over 30 times but still don't encounter this situation again.

But, if I make many other entities also compatible with PartEntity system, such as enderman, this issue may be everywhere.

**Comment by ChampionAsh5357** [comment]
So the edge case mentioned above comes from a fully constructed entity being added to a `ProtoChunk`. In these cases, the entity is not initially spawned. Instead, the entity is saved to nbt, and then rebuilt when the chunk becomes loaded. Since chunks are initially generated asynchronously, you could add a number of entities at the same time. They will then be added synchronously to the level once the chunk has finished loading. Since the entity id is an `AtomicInteger`. This wouldn't normally be a problem. However, in the case of multipart entities, this is a different story. In a very specific case when a `ProtoChunk` begins constructing which spawns an entity at the same time a multipart is loaded on the server thread, the entity id could be incremented by the worker causing the entity ids on the server to shift slightly. This could cause a desynchronization from the server to client ids as it is expected that the multipart ids would be in the same increments after the main entity id.

This problem is mostly mitigated by how Mojang handles their ticking structure, but in some extremely specific circumstances this would be very present. I would imagine you could replicate this buggy behavior by replacing every loading entity with that of a multipart entity with 10 parts such that the chance of the issue occurring is higher.

The simple solution to this would be to send all the ids for the multiparts to the client to avoid this issue. Another solution may check the current status of the loaded area and only get and increment the id if the entity will be actually joining the level instead of serialized. Since the entity id is never serialized, we don't need to worry about any collisions.

Since this is fixing part entity desynchronization, this should also be addressed in the PR.

**Comment by XenonDB** [comment]
I think I need to do some research on how server send entity id packet to client.
Because the connection between server side and client side entity is only a entity id, client must set a correct id for a new created entity immediately or server will lost control of it.

**Comment by sciwhiz12** [comment]
Hello! @XenonDB, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

**Comment by XenonDB** [comment]
> Hello! @XenonDB, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity. If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. Thank you for your contributions. 👋

I think I should leave this work to other since I am busy recently.

**Pull request closed without merging**
