### PR TITLE
Add Fluid capability

### PR DESCRIPTION
**Pull request by rwtema**

### CODE REVIEW

**Comment by sham1** [comment]
OMG YES! This is one of those things that is fully needed for forge. Full support.

**Comment by Lordmau5** [comment]
Bumping this up because FluidContainerRegistry seems to be deprecated.

**However:**
The vanilla buckets do not implement IFluidContainerItem yet, making the deprecation kinda useless in my opinion.

**Comment by diesieben07** [comment]
Why does `IFluidHandler` even need to exist anymore? The capability interface already has a `side` argument. So imho you should just expose an `IFluidTank` on the sides that you want to. Especially cause you have code in here already that aggregates multiple tanks into one.

**Comment by LexManos** [comment]
The issue is that IFluidContainerItem needs the ability to switch item stacks, and the way the API in it is currently designed it does not. Except for some hacks and doing it internally.
It's something to look into but I honestly don't care to much about it as everyone and their dog has an opinion on it. If someone wants to take a crack at it let me know.

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Pull request closed without merging**
