### PR TITLE
[1.10] Persist PotionEffect Curative Items

### LINKED ISSUE #1701: Potions and Curative Items
Right: I would like to talk about a rework of potions and specifically curative items - I've given this a reasonable amount of thought and would be happy to submit the PR if this has support.

Currently I think Curative Items are handled poorly, the curative items list is set in the PotionEffects constructor to include the milk bucket. This means that even if you do add a curative item or otherwise modify that list, after the entity has been saved and reloaded, it will revert back to the single Milk list. The only way around this is to do something reasonably dodgy with the `potion.performEffect` method which checks the EntityLivingBase it is passed for the effect that called it and then modify that PotionEffects curativeItems if necessary. This is not ideal as it is a check that must be made every single tick the potion effect is active. Alternatively if you wanted to modify an already existing Potion's default curative items - you would need to create a TickHandler or ASM in something to do this modification.

My proposed solution for this is to move the curativeItems list to the Potion class, redirecting the existing curativeItem methods (get, set, is, and add) to `Potion.potionTypes[this.potionID].get...` - maintaining compatibility with anything that is currently modifying the list in the effects, but also opening up the methods in the Potion class for a cleaner solution.

Alternatively and arguably simpler, adding the curativeItem list to the NBT save/load for the PotionEffect would be a significant improvement as it would allow the modification of the curativeItem list when the effect is first applied and it would be retained through save/load cycles

I'd like to hear any feedback on this if you've got it

### PR DESCRIPTION
**Pull request by williewillus**
Prevents a PotionEffect from losing all of its curative items and reverting to milk on reload.

Resolves #1701, albeit in a different way than that issue suggests.

Serialization uses the getter, so milk is persisted by default. 
I can make it not persist anything if it detects that the PotionEffect is just the default curative items (milk bucket alone), which will save some storage space. Let me know if you think that's better.

Backward compat maintained as the deserialization checks if the tag is present. If not present, leaves the list field null and lets the getter initialize it.

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by LexManos** [comment]
Humm, arnt curative items on the singeltons? If not why arnt they?
One instance of Poision shouldn't be cured by a different item then another.

**Comment by williewillus** [comment]
They're on `PotionEffect` currently, but aren't persisted and revert to milk on relog.

The old issue ticket talks about moving it to `Potion`, but I thought persisting the ones in `PotionEffect` would fix the problem and be simpler.

Should I move it to `Potion` instead?

**Comment by williewillus** [comment]
I don't know why they were on PotionEffect origianlly, legacy reasons?

**Comment by LexManos** [comment]
can you or anyone else think of why itd need to have an instance version? Or if it should, should it not get the defaults from the singelton?
Just thinking what would be best...

**Comment by gigaherz** [comment]
I agree with having defaults on a singleton. A quick survey (`https://www.google.com/#q=getCurativeItems+site:github.com`) seems to indicate the most prominent use cases are all removing the healing items from their harmful effects.

Besides binary compatibility concerns, the only situation in which I can imagine keeping the instance version to be useful, would be for adventure map makers (such as being able to make effects unremovable during certain sections of the map)?

**Comment by LexManos** [comment]
Why not both?

**Comment by mezz** [comment]
Can you update this to target 1.11? New features are no longer being merged into 1.10.

**Comment by mezz** [comment]
Any update @williewillus ?

**Comment by williewillus** [comment]
#3573

**Comment by liach** [comment]
You can edit target branch of the pull like how you edit the title...

**Comment by williewillus** [comment]
TIL

**Pull request closed without merging**
