### PR TITLE
Added FurnaceSmeltEvent

### PR DESCRIPTION
**Pull request by Wyn-Price**
~~Allows NBT and world/position sensitive furnace outputs, as well as allowing modders to do something similar to what vanilla does, where when a sponge is smelted, if a bucket is in the fuel spot, the bucket gets replaced by a bucket of water.~~
Allows for NBT sensitive furnace outputs

### CODE REVIEW

**Comment by ChloeDawn** [comment]
~~You could just add a `TileEntityFurnace` context to `PlayerEvent$ItemSmeltedEvent`, much like how `PlayerEvent$ItemCraftedEvent` provides the `IInventory` context. There really isn't a reason to create a dedicated event for this.~~

Nevermind, that wouldn't be possible without changing the semantics of the existing event.

**Comment by Wyn-Price** [comment]
I've removed the tile entity context from the event, and moved the event firing to allow for modded furnaces to also fire this event.

**Comment by TechnicianLP** [comment]
wouldnt this make more sense to be moved to json like normal recipes?

**Comment by DaedalusGame** [comment]
grabby hands for this absolute lad's contribution
this has usecases other than just implementing nbt sensitive recipes so i don't see why this would be moved to json (right now) apparently we're getting machine recipes for 1.13 so i reckon that the hashtable garbage is gonna go anyway and be replaced with the ingredient system, but this also allows for things such as carrying over an accumulated rot value for cooked items or heating up an iron sword to 1000 degrees without using a bunch of seperate metadata items.

**Comment by savander** [comment]
I was looking for a similar Event in current Forge version, but I didn't find.
It would give possibilities, to change the output from furnace based on item durability. For example, if I would like to add smelting recipe for a chest plate, I would like to make output flexible, so I could change the number of items based on durability.

I could use ItemSmeltedEvent, but it occurs when the player takes the output from a furnace, so it doesn't fit in the given scenario.

I would like to see that event. ;)

**Pull request closed without merging**
