### PR TITLE
Fixed a bug with GuiConfigEntries.SelectValueEntry

### LINKED ISSUE #2114: GuiConfigEntries.SelectValueEntry's list is in the wrong spot if titleLine2 is null
There is an issue where if the user doesn't define a titleLine2 for their GuiConfig, any GuiConfigEntries.SelectValueEntry within the gui will have the list rendered underneath the config option's name, as shown in [this screenshot](http://i.imgur.com/r3rDuBt.png).

The issue is how GuiConfigEntries determines what height its top is at. Specifically, [GuiConfigEntries:77](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java#L77)

titleLine2 is null, but the name of the config option the gui is for, which isn't null, renders below where titleLine2 would be, and this code doesn't check for that.

### PR DESCRIPTION
**Pull request by The-Fireplace**
Fixed a bug with GuiConfigEntries.SelectValueEntry that caused the config option name to overlap with the selectable values, fixes #2114

### CODE REVIEW

**Comment by Spartan322** [comment]
Why are you commiting Minecraft.java.patch without modifying it at all?

**Comment by The-Fireplace** [comment]
It said [https://github.com/MinecraftForge/MinecraftForge/wiki/If-you-want-to-contribute-to-Forge](here) to run gradlew genPatches before submitting a pull request. I figured if what I did caused there to be a change to the patch, then it should be included. I can revert the patch being modified and make another PR, if needed.

**Comment by TehNut** [comment]
Did you not read Lex's comment on the last one which contained literally exactly the same changes?

>And only commit files *you* edit

**Comment by Lunatrius** [comment]
You don't need to open a new PR.
```
git checkout HEAD~1 patches/minecraft/net/minecraft/client/Minecraft.java.patch
git add patches/minecraft/net/minecraft/client/Minecraft.java.patch
git commit --amend
git push --force
```

**Comment by The-Fireplace** [comment]
TehNut: I only saw the first line of it, my mistake.
Lunatrius: It has to be a new PR, it won't let me re-open it because I used force push.

**Pull request closed without merging**
