### PR TITLE
Add a potion registry that handles potion-IDs

### PR DESCRIPTION
**Pull request by bonii-xx**
Gone are the days of manually extending the potions-array and potion conflicts! This PR allows to have up to 256 potions/effects (including vanilla). The PR is split into 3 parts because of the change to the id-logic in the packets/NBT loading.

What the PR does:
* Make potiontypes-array and potions IDs non-final
* Assign a potion ID automatically in the potion constructor. New potions do not (should not) supply their own ID.
* Automatically expand potiontypes-array as needed
* Sync potion-IDs via Snapshots
* Add a test mod that adds random potions to check if the syncing works correctly

Currently not supported:
* The Missing and Remap events do not include Potions. The only effect of removing a potion should be its effect not being applied anymore on entities that currently have the effect (on load). The mod that removed it should also take care of potential items that applied it (vanilla potions).

I currently cannot launch a proper server instance with FG2 so I couldn't test the remapping in SMP yet. Neet to talk to Abrar or cpw about that. However I still put it up here for discussion/review.

### CODE REVIEW

**Comment by Spartan322** [comment]
I was planning on doing a similar thing, except I was planning on separating effects and potions as objects. Also, we probably shouldn't be using an integer id, just a string id would be better

**Comment by Abastro** [comment]
This will break backward-compatibility...

**Comment by williewillus** [comment]
@Abastro I feel like in this case it's something that merits it. And besides, the impact will be minimal because no one is on 1.8 yet :p

**Comment by luacs1998** [comment]
Plenty of people are on 1.8.

**Comment by liach** [comment]
@Abastro So #1881 also breaks but it is acceptable right?

**Comment by Spartan322** [comment]
@liach I don't see how #1881 breaks compatibility.

**Comment by bonii-xx** [comment]
The 256 limitation is due to vanilla packets. No it does not break backwards compatibility. No there's nothing to fix with the constructor, everything fine there. No it does not hurt, it does not break thaumcraft, and after this change it doesn't need to change the array size anymore.

A thing to consider would be to set the array to a fixed 256 size - the resizing was mostly from before I discovered the limitation.

**Comment by Spartan322** [comment]
Actually, with #1881 and a separated Effect system, this would be effectively pointless, and all this really does is delay a problem instead of solving it.

**Comment by bonii-xx** [comment]
This has absolutely nothing to do with brewing, it only concerns the effects. The "problem" will be solved by 1.9.

**Comment by bonii-xx** [comment]
@cpw should be ready now.

**Comment by cpw** [comment]
Any chance of a squash?

**Comment by cpw** [comment]
Also, you're gonna need to fixup for the registry overhaul..

**Pull request closed without merging**
