### PR TITLE
Add EntityItem#getPickupDelay method

### PR DESCRIPTION
**Pull request by elifoster**
Resubmission of #3092 with the base branch changed.

TODO: Resolve merge conflicts and re-generate patches on the master branch rather than off 1.9.4.

### CODE REVIEW

**Comment by iLexiconn** [comment]
1.10.x is the most up-to-date branch, not master

**Comment by elifoster** [comment]
@iLexiconn I was told to target master at #3092.

**Comment by williewillus** [comment]
@elifoster super sorry, I thought 1.10 was in master now D:

Though I guess we are moving to versioned branches now instead of stuffing things in master and getting confused

**Comment by elifoster** [comment]
Is Forge for 1.9 no longer being updated, then? I'm confused. Or are changes to 1.10 getting backported to 1.9 (and vice versa) so that mods can be compatible with both versions (which seems to be a goal right now, looking at most mods on CF/GitHub)?

**Comment by RANKSHANK** [comment]
@elifoster from what I've seen most content made for 1.9 is compatible with the 1.10.x builds. Something about using the same SRG's. So there's little point in maintaining the older version when stuff developed for it works in the newer version anyways. Also 1.10.x is the RB now :)

**Comment by LexManos** [comment]
The only things that get backported are the "This bug will reformat your harddrive, steal your credit cards, breaking into your house and kill you dog" bug fixes.
Everything else, you should update.
As for this in particular, its not really a big deal as we've given normal mods AT access for a long time so reflection wont be needed.

**Pull request closed without merging**
