### PR TITLE
[1.10.x] EntityBlockFalling onEndFalling hook

### PR DESCRIPTION
**Pull request by RANKSHANK**
Adds a slightly more robust (access to the entity if/when necessary) and interface based hook allowing non BlockFalling blocks to handle EntityFallingBlock's call to onEndFalling.

### CODE REVIEW

**Comment by williewillus** [comment]
why an interface?...

I'd just stick it on the block like we do everything else

**Comment by RANKSHANK** [comment]
You have a point :P 

I wasn't sure if it was better spreading the patch across 3 files or not, so I went with the minimalist approach :P

**Comment by RANKSHANK** [comment]
Alrighty all patched up. Opted to make the Entity param generic,

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Pull request closed without merging**
