### PR TITLE
Add EntityPushedByWaterEvent

### PR DESCRIPTION
**Pull request by josephcsible**
Use-case: https://www.reddit.com/r/feedthebeast/comments/7ur4el/is_there_an_enchant_or_boots_that_stop_flowing/

### CODE REVIEW

**Comment by williewillus** [comment]
what are the performance implications of this? entity-water flow happens quite often and we don't want to spam events more than we need to (each one alone is not much but add them up and the impact is significant)

**Comment by josephcsible** [comment]
Hmm. Can you think of any way to do this other than an event?

**Comment by jabelar** [comment]
To reduce event spamming you could limit it to players pushed by water. The problem with an event like this is that it is a lot of spam for something that only a very, very small amount of mods would use.

As an alternative to events, since you asked, you could add a field to Entity with setter and getter for isPushedByLiquid. 

Note I'm a bit nervous about this getting accepted because I have a big PR proposed for fluids that includes custom fluids pushing entities, so ideally this would need to cover custom fluids as well once they can also push.

**Comment by josephcsible** [comment]
> To reduce event spamming you could limit it to players pushed by water. The problem with an event like this is that it is a lot of spam for something that only a very, very small amount of mods would use.

Yes, but then it (obviously) only works on players.

> As an alternative to events, since you asked, you could add a field to Entity with setter and getter for isPushedByLiquid.

This could work.

> Note I'm a bit nervous about this getting accepted because I have a big PR proposed for fluids that includes custom fluids pushing entities, so ideally this would need to cover custom fluids as well once they can also push.

If we go the event route, we could add the fluid in question as a parameter to the event. If we go the setter route, we could make it set a lambda of fluid -> boolean rather than just a boolean.

**Comment by josephcsible** [comment]
@jabelar Any update on your big PR?

**Pull request closed without merging**
