### PR TITLE
Prevent player from dying due to zero max health

### PR DESCRIPTION
**Pull request by asanetargoss**
1.12 version of the following PR:
https://github.com/MinecraftForge/MinecraftForge/pull/3759

### CODE REVIEW

**Comment by mezz** [comment]
Looks good to me.

**Comment by mezz** [comment]
Lex required some further investigation into the magic value you found.
Looking at where it was being used, we found that it gets cast to float and the minimum value that works is `Float.MIN_VALUE` which is `2^-149` aka `1.4012985^-45`.
I commited the fix here: https://github.com/MinecraftForge/MinecraftForge/commit/32dc726df1f1ddd693b5e0f98997382afaf3169d

**Comment by williewillus** [comment]
TIL Float.MIN_VALUE isn't negative

**Comment by mezz** [comment]
Yeah you're not the only one haha. 
It's a bad name, considering `Integer.MIN_VALUE` is negative.

**Pull request closed without merging**
