### PR TITLE
[1.10.2] Add Hook to Get Seed for a Chunk Coordinate

### PR DESCRIPTION
**Pull request by Madsthunder**
This just adds a hook called ForgeHooks#getChunkSeed to calculate the seed for a chunk coordinate

### CODE REVIEW

**Comment by williewillus** [comment]
this is useless without something that calls it :P did you forget to push a patch?

**Comment by Madsthunder** [comment]
This is just for simplicity, letting modders use this to calculate what seed to use without copying and pasting code. Also, if I modified the base classes it would add and/or increase patch sizes, and we don't want that now do we?

**Comment by williewillus** [comment]
I don't quite understand what exactly this is.
Is it exposing a piece of vanilla logic? (if so indicate where)
Is it just a util method? (If so it should be in the utils class or imo not in forge at all. _Definitely_ not in ForgeHooks)
As it stands right now a modder looking at this has no clue what they should use it for, when, where, and why (if they could even find this and recognize it's for modder use is another question). Why can't they add this to their own util class and get on with it? Forge isn't in the business of providing util methods for every little thing under the sun

**Comment by AshIndigo** [comment]
There could be a use for debugging modpacks and or forge for world generation to recreate worlds. I.E Add this to the debug info in logs.

**Comment by williewillus** [comment]
yes but that debugging code should be in the mod. why would it be in forge?

**Comment by AshIndigo** [comment]
:/ Honestly don't have a use car either in Forge I was just throwing out an idea.

**Comment by LexManos** [comment]
Forge does not typically provide 1/2 line helper functions like this.
Its a simple method and anyone who cares can implement it.
Forge already provides the result of this function to all generators, there is no need for pulling that out into a random useless function.

**Pull request closed without merging**
