### PR TITLE
[1.20.6] Bump CoreMods and ASM

### PR DESCRIPTION
**Pull request by Jonathing**
Backport of #10127 to 1.20.6.

### CODE REVIEW

**Comment by PaintNinja** [comment]
- [ ] Need to check transitive dep compatibility with JarCompatibilityChecker

**Comment by Jonathing** [comment]
How do I do that? And can the same be done for the older versions with the old buildscripts? (1.20.1 and older)

**Comment by PaintNinja** [comment]
You clone the compat checker repo, open it in your IDE, manually edit the Gradle buildscript and run a task. Suffice to say, there’s a lot of room for improvement with that tool

**Comment by Jonathing** [comment]
Here is the log output for JarCompatibilityChecker
```
net.minecraftforge:coremods:5.1.6 -> net.minecraftforge:coremods:5.1.13
java.lang.IllegalArgumentException: Class net/minecraftforge/forgespi/coremod/ICoreModProvider was not found in class info cache or JVM classpath
	at net.minecraftforge.jarcompatibilitychecker.core.ClassInfoCache.getClassInfo(ClassInfoCache.java:191)
	at net.minecraftforge.jarcompatibilitychecker.core.ClassInfoComparer.getParentClassNames(ClassInfoComparer.java:380)
	at net.minecraftforge.jarcompatibilitychecker.core.ClassInfoComparer.compare(ClassInfoComparer.java:88)
	at net.minecraftforge.jarcompatibilitychecker.JarCompatibilityChecker.check(JarCompatibilityChecker.java:149)
	at net.minecraftforge.jarcompatibilitychecker.ConsoleTool.main(ConsoleTool.java:68)

org.ow2.asm:asm-commons: 9.7 -> 9.7.1
No incompatibilities found

org.ow2.asm:asm-tree: 9.7 -> 9.7.1
No incompatibilities found

org.ow2.asm:asm: 9.7 -> 9.7.1
No incompatibilities found
```

It looks like this tool crashes when checking the coremods jar because it is depending on an interface in ForgeSPI. CoreMods obviously does not come with ForgeSPI. Do I need to do something else?

Here's what I changed in the buildscript to match the changes I made in this PR:
```diff
diff --git a/build.gradle b/build.gradle
index 8aa1daa..f51d199 100644
--- a/build.gradle
+++ b/build.gradle
@@ -110,7 +110,7 @@ tasks.register('testLibrary').configure {
     doFirst {
         def libs =
             //['cpw.mods:securejarhandler:2.1.10', 'net.minecraftforge:securemodules:2.2.2']
-            ['net.minecraftforge:coremods:5.0.1', 'net.minecraftforge:coremods:5.1.2']
+            ['net.minecraftforge:coremods:5.1.6', 'net.minecraftforge:coremods:5.1.13']
             //['cpw.mods:modlauncher:9.0.24', 'net.minecraftforge:modlauncher:10.1.1']
         def base = getArtifacts(libs[0])
         def input = getArtifacts(libs[1])
```

**Comment by Jonathing** [comment]
This PR is ready to merge. There are no changes in transitive dependencies since the last version of CoreMods that Forge for 1.20.6 has shipped, that being 5.1.6.

**Review by PaintNinja — APPROVED** [review]

**Pull request merged**
