### PR TITLE
Added LivingProcreateEvent

### PR DESCRIPTION
**Pull request by austinv11**
This event is fired when animals mate and attempt to spawn a baby. It is cancelable and allows for modification of the amount of xp dropped and the child spawned.

### CODE REVIEW

**Comment by Eragonn1490** [comment]
Does this change the entity's target for a mate
. So that two different animals can mate? 
Like let's say a cow and a goat (if I got creative) ?

**Comment by austinv11** [comment]
No, this is only fired after the animals mate. The logic for mating is handled a little differently, so it would need hooks in the EntityAIMate#getNearbyMate() and EntityAnimal#createChild() methods.

**Comment by Eragonn1490** [comment]
Would you be able to add it for in my opinion completeness, since you allow changing of the spawned baby? The parents would seem to matter if you could do that?

**Comment by austinv11** [comment]
It would be a little too complicated to add it to this, maybe as two separate events, but I think that would be up to @LexManos if he wanted that.

**Pull request closed without merging**
