### PR TITLE
[1.20] Remove DistExecutor

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR depends on https://github.com/MinecraftForge/MergeTool/pull/8 - otherwise the comment on `FMLEnvironment.dist` is incomplete/incorrect.

`DistExecutor` is rarely used in Forge, and every use of it can be replaced with a simple dist check and proper Dist safety.

DistExecutor is very complex for the average modder to comprehend, and it would be better to instead provide the resources needed to understand when and why dist separation is needed, and how to accomplish it.

Additionally, DistExecutor is not fundamentally safer - the result of improper usage of `safeRunWhenOn` will result in the same error as improper classloading - a crash in both instances. It is arguable that most modders are more likely to understand the classloading error (invalid load on class <x> for side <y>) vs the error from DistExecutor ("Unsafe Referent usage found in safe referent method").

### CODE REVIEW

**Comment by Technici4n** [comment]
What would be the proper way to invoke client code from common code after this PR? In particular, calling client setup code from the common mod constructor.

On Fabric you don't need to perform dist checks because there is a separate client entrypoint, but I believe that's not an option in Forge?

**Comment by tmvkrpxl0** [comment]
@Technici4n I’d say Client Initialization event. If it’s not applicable, call side-only codes in static class that is dedicated for single side, and use that class in common mod constructor

**Comment by Shadows-of-Fire** [comment]
See the linked MergeTool PR - DistExec is a thinly veiled guard around a Dist == xyz check with a lot of added complexity.

**Comment by Technici4n** [comment]
Ah, yes that's fine. Might be nice to deprecate `DistExecutor` for removal already in previous versions.

**Pull request closed without merging**
