### PR TITLE
Added #2411 PreRenderEvent

### PR DESCRIPTION
**Pull request by Alex-the-666**
#2411 gives a decent description why this would be very useful.

### CODE REVIEW

**Comment by iLexiconn** [comment]
Squash commits

**Comment by konwboj** [comment]
+1
Would be even more useful if moved below "this.mainModel.setRotationAngles" call.

**Comment by Alex-the-666** [comment]
Not really as the texture would already be binded, so anything you render would have to have the entities texture.

**Comment by konwboj** [comment]
Is it? I think that the texture is bound in the renderModel method and the event would be called just before it, after setRotationAngles.

**Comment by Alex-the-666** [comment]
Oh sorry, my mistake, you are correct :)

**Pull request closed without merging**
