### PR TITLE
Add PlayerArmorChangeEvent

### PR DESCRIPTION
**Pull request by TheTemportalist**
This event notifies listeners when the player's armor is changed, passing the old stack, new stack, and slot. It would be helpful for mod's whose armor has a special effect, but only does its effect when added to the inventory (like changing the player's health). The reason why this should be an event (as opposed to editing net.minecraftforge.common.ISpecialArmor) is because a mod could be implementing NBT effects on other armor items and has no control over those item classes, merely the NBT data of their stacks.
For some more context, Baubles provides this for its external equipment slots:
https://github.com/Azanor/Baubles/blob/master/src/main/java/baubles/api/IBauble.java#L26-L34
https://github.com/Azanor/Baubles/blob/6dc6951904f4bda090a9c3f78ddf010f066864c9/src/main/java/baubles/common/container/InventoryBaubles.java#L147-L153

See #2329

### CODE REVIEW

**Comment by Spartan322** [comment]
This needs be rebased

**Comment by TheTemportalist** [comment]
Rebase and javadoc in process of being committed and pushed.
I did not make this cancelable, because it isn't integrating far enough to allow whether or not armor will be changed, it is merely a notification event which resides in setInventorySlotContents.

**Comment by Spartan322** [comment]
I don't think there is any item related event that is limited like that.

**Comment by TheTemportalist** [comment]
Sample non-cancelables:
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/entity/player/PlayerEvent.java
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/entity/player/PlayerDestroyItemEvent.java
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/entity/player/PlayerUseItemEvent.java (Finish)

In the rebase, I had to switch to master branch, so I am going to close this event, but keep it linked in the description.

**Comment by Spartan322** [comment]
I changed my answer according to me goofing up for a sec

**Pull request closed without merging**
