### PR TITLE
Fix typo in sky rendering causing tons of BlockPos allocations

### PR DESCRIPTION
**Pull request by tterrag1098**

### CODE REVIEW

**Comment by LexManos** [comment]
Herp

**Comment by kinggoesgaming** [comment]
@LexManos you mean derp? 🤔😅

**Comment by Actuarius** [comment]
@mezz added labels [Bug, Performance]

**Comment by SnowShock35** [comment]
@tterrag1098 I could kiss you good sir!!! ❤

**Comment by DarkGuardsman** [comment]
Maybe I will not run out of memory playing 1.10 anymore \0/

Thank you @tterrag1098

**Comment by williewillus** [comment]
@DarkGuardsman you might want to bump this one then :P Up to 400MB of dead memory in AllTheMods https://github.com/MinecraftForge/MinecraftForge/issues/3246

**Comment by DarkGuardsman** [comment]
@williewillus Sure, ironically AllTheMods was the first 1.10 modpack I tried that ran me out of memory at 12GB

**Comment by tterrag1098** [comment]
This fix probably won't impact the resting memory amount too much. Just the
rate at which it churns while ingame.

**Comment by LexManos** [comment]
This is correct this is a non critical change it just slightly lessens go overhead. The jvm is specifically designed to deal with massive churn of low level short lived objects like this. Don't freak out this isn't the golden fix for everything. BlockPos IS NOT a big of issue as people make it out.

**Comment by tterrag1098** [comment]
Well it could also give a few extra fps but that is really dependant on
system. Point is this change removes a bunch of code from running every
frame, which is always a good thing :)

**Comment by LexManos** [comment]
S/bunch/some

But yes all I'm saying is don't hype it more then it actually does.

**Pull request merged**
