### PR TITLE
Added @Nullable to fluid interace

### PR DESCRIPTION
**Pull request by laci200270**
Same as #2195

### CODE REVIEW

**Comment by williewillus** [comment]
You know you can squash and force push instead of creating a new PR every. single. time, lol

**Comment by laci200270** [comment]
Any news?

**Comment by liach** [comment]
Create a new pr to 1.8.8 might be better

**Comment by williewillus** [comment]
@liach there's no need. this one doesn't change patches, just forge classes so it should work across versions

**Comment by liach** [comment]
@williewillus If you say like this, then there is no need for this pr. If you need this, you should add some test cases, as these annotations are totally useless at runtime.

**Comment by williewillus** [comment]
@liach .... I'm not talking about the usefulness or purpose of the PR. I'm saying that the patch should be portable across 1.8/1.8.8 because it doesn't modify anything critical. It can be merged directly into 1.8.8 from here

**Comment by laci200270** [comment]
@cpw should I create this PR for 1.8.8?
2015.12.07. 22:03 ezt írta ("Vincent Lee" <notifications@github.com>):

**Comment by luacs1998** [comment]
@laci200270 I think you should - it's more work for cpw to merge it into 1.8.8 than for you to open a new PR to retarget.

**Pull request closed without merging**
