### PR TITLE
Move client-only config options to client config (1.12.x)

### PR DESCRIPTION
**Pull request by ichttt**
This moves the properties that are only used in the client to the client configuration while keeping the settings. I also made a 1.11 version, as we would loose the settings otherwise if someone downgrades from 1.12 to 1.11.

### CODE REVIEW

**Comment by mezz** [comment]
Tested and looks good to me.

**Comment by LexManos** [comment]
I don't really see a need but sure...

**Comment by ichttt** [comment]
Well it may confuse users who run a server and see the option in the config under general which doesn't affect anything

**Comment by LexManos** [comment]
ya i dont think thats the case, but whatever.

**Pull request merged**
