### PR TITLE
[1.19.x] Make TutorialSteps enum extensible and add event for changing them

### PR DESCRIPTION
**Pull request by danorris709**
This makes the TutorialSteps enum implement IExtensibleEnum so that mods can add custom TutorialSteps that they can then implement inbetween any of the other tutorial steps using the TutorialStepChangeEvent.

This could be useful for allowing mods to create an easier experience for new players as they explore their mod

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
This needs a lot more forethought before review; though in my opinion, I don't see a reason to hook this in the first place.

First, the tutorial is basically toasts which appear on the screen prompting the user to complete a certain action, opening the next toast when completed. In that regard, you could do the exact same thing with all the hooks that already exist in Forge. This hook would just be completely unnecessary.

Second, an event doesn't make any sense in this context. Imagine if two mods wanted to add a new step to the tutorial at the same point. The only one that would be considered would be whichever is called last. The `TutorialSteps` isn't even being used as an enumerator; the data is set manually by the previous `TutorialStepInstance`, meaning you would need more information than what is currently available. You could use a graph and then merge it all into one list, but then you may have interleaving steps that break each other up between mods, making the flow inconsistent and confusing for beginners. You technically don't even need the extension to `TutorialSteps` as you could literally just add the toast yourself.

As such, I see no reason for this system to be patched when you can add your own toasts and implement a tutorial system yourself without having to deal with the incompatibilities and massive workarounds needed to get a number of mods working together harmoniously.

**Comment by Shadows-of-Fire** [comment]
It would be very hard to get anyone to see something like this - mod packs ship with a mod that disables the tutorial system by default, so any additional tutorial steps would also be hidden.

**Comment by danorris709** [comment]
> This needs a lot more forethought before review; though in my opinion, I don't see a reason to hook this in the first place.
> 
> First, the tutorial is basically toasts which appear on the screen prompting the user to complete a certain action, opening the next toast when completed. In that regard, you could do the exact same thing with all the hooks that already exist in Forge. This hook would just be completely unnecessary.
> 
> Second, an event doesn't make any sense in this context. Imagine if two mods wanted to add a new step to the tutorial at the same point. The only one that would be considered would be whichever is called last. The `TutorialSteps` isn't even being used as an enumerator; the data is set manually by the previous `TutorialStepInstance`, meaning you would need more information than what is currently available. You could use a graph and then merge it all into one list, but then you may have interleaving steps that break each other up between mods, making the flow inconsistent and confusing for beginners. You technically don't even need the extension to `TutorialSteps` as you could literally just add the toast yourself.
> 
> As such, I see no reason for this system to be patched when you can add your own toasts and implement a tutorial system yourself without having to deal with the incompatibilities and massive workarounds needed to get a number of mods working together harmoniously.

So the reason I thought it would make most sense to extend the current system is so that they show up in order with the Minecraft ones. I understand that you **could** make your own system to replicate the behaviour but I thought it would make more sense to extend the existing system so that it would function with the Minecraft ones. That way it would integrate more seemlessly into Minecraft rather than showing up at the same time, potentially, as the Minecraft tutorial toasts.

As for the event this was the only way I could really think to allow inserting tutorial steps inbetween other steps. I'm not really sure how else to go about allowing for people to insert steps anywhere along the chain otherwise. Yes, absolutely mods could cause conflicts and result in weird behaviour but is that not the purpose of the priority system I guess? I'm just not sure what other solution would exist for inserting the tutorial steps.


> It would be very hard to get anyone to see something like this - mod packs ship with a mod that disables the tutorial system by default, so any additional tutorial steps would also be hidden.

I don't think this is a very constructive thing to say because you're assuming that all mod packs ship with that. However, I personally have never heard of the mod you're in reference to...

**Comment by ChampionAsh5357** [comment]
> I understand that you could make your own system to replicate the behaviour but I thought it would make more sense to extend the existing system so that it would function with the Minecraft ones. That way it would integrate more seemlessly into Minecraft rather than showing up at the same time, potentially, as the Minecraft tutorial toasts.

I mean...it would function with the Minecraft ones anyways since you would just be making a toast and then adding it. There's no need to patch into the steps system for it.

> Yes, absolutely mods could cause conflicts and result in weird behaviour but is that not the purpose of the priority system I guess?

What priority system? The event system? Then it'll be whichever event is executed last on the lowest priority. Also, as soon as one mod goes past, no other toasts would activate unless the next toast calls the set method. Even then, no other toasts would activate because they would have no understanding of the other mods that exist.

> I'm just not sure what other solution would exist for inserting the tutorial steps.

I'm pretty sure there's no solution that is extensible and reasonable to implement as part of the Forge API without designing an entire system around it. Even then, I still believe it should be up to the individual mod if they choose to use a toast or do something else (e.g., Tinker's Construct with an intro book).

As an additional thought, if we say 10 mods add in 3 tutorials each, that's 30 tutorials the user now has to deal with at the top right hand corner of the screen. That would be a conservative estimate too assuming people decided to use the system. At that point, it also becomes a user experience issue where they would just receive endless tutorials. In general, it falls into the same category where it makes no sense to patch them.

**Comment by danorris709** [comment]
> I mean...it would function with the Minecraft ones anyways since you would just be making a toast and then adding it. There's no need to patch into the steps system for it.
> 
> >

When I said it would function with the Minecraft tutorial system seamlessly I meant it would not fight with it, and have two (or more) toasts appearing at the same time. If you were to implement your own system that is the risk you face rather than it being a linear progress from (or inbetween) the Minecraft ones.

Then taking your point of each mod should write there own system then it would exaggerate the issue I described above even fruther as you'd end up with even more toasts being shown at one time. For each mod that has it's own system you'd have a new toast that appears at the start of the game rather than it being in the linear progress of the pre-existing system.



> What priority system? The event system? Then it'll be whichever event is executed last on the lowest priority. Also, as soon as one mod goes past, no other toasts would activate unless the next toast calls the set method. Even then, no other toasts would activate because they would have no understanding of the other mods that exist.
> 
> >

Perhaps I could change the event to only fire when it gets set to NONE? That way the linear progression would go Minecraft -> Mod A -> Mod B (etc). Where the order of the mods that show up is based on the priority of the event listener? It's more restrictive but I guess it also makes more sense in that you wouldn't want to jump between two different mod's start tutorials either.



> As an additional thought, if we say 10 mods add in 3 tutorials each, that's 30 tutorials the user now has to deal with at the top right hand corner of the screen. That would be a conservative estimate too assuming people decided to use the system. At that point, it also becomes a user experience issue where they would just receive endless tutorials. In general, it falls into the same category where it makes no sense to patch them.

The tutorials will only show up when they first play the game, and if they are in survival. I don't think it would be too aggregous depending on how the tutorials are used by each individual mod, which is difficult to say and would ultimately fall down to the experience the mod wants to give the user. I don't think it's right for anyone to say that this shouldn't exist just because a mod might exist that might make it a bad experience for the user from our perspective. Is the point not to just give people to tools to extend it as they like? 

Also, if we look at modpacks I believe that they can provide files with their modpack for the user settings. At which point they could turn off the tutorial toasts (in options.yml) or ask the makers of the mod to make the tutorials optional through some sort of configuration toggle. Or one step further, use the mod that was referenced above that completely disables the tutorial.

I think to conclude everything I've said above the most pertitent point for me is that I don't think we should hypothesize about how a mod might make a "worse" (from our perspective) experience for a user, because ultimately it's providing them the tools to create the experience they want.

**Comment by ChampionAsh5357** [comment]
> When I said it would function with the Minecraft tutorial system seamlessly I meant it would not fight with it, and have two (or more) toasts appearing at the same time. If you were to implement your own system that is the risk you face rather than it being a linear progress from (or inbetween) the Minecraft ones.
>
> Then taking your point of each mod should write there own system then it would exaggerate the issue I described above even fruther as you'd end up with even more toasts being shown at one time. For each mod that has it's own system you'd have a new toast that appears at the start of the game rather than it being in the linear progress of the pre-existing system.

That already happens in vanilla anyways when you unlock advancements. Additionally, the idea of the toasts would be locked to being at the beginning of the game, rather than whenever the mod desires to do so as it will stop being called whenever the last toast sets the value.

> Perhaps I could change the event to only fire when it gets set to NONE? That way the linear progression would go Minecraft -> Mod A -> Mod B (etc). Where the order of the mods that show up is based on the priority of the event listener? It's more restrictive but I guess it also makes more sense in that you wouldn't want to jump between two different mod's start tutorials either.

The issue is not with the restrictiveness of it. The issue comes from encounter order. Let's say I, as the player, want to do Mod B first rather than Mod A. I wouldn't be shown the toasts for Mod B's stuff until after I finish Mod A, at which point I may already have done everything in the tutorial, only to do it over again. The more I contemplate this, the more I realize that toasts are just not compatible for step by step instructions where there are millions of branching paths depending on which direction the mod goes.

> The tutorials will only show up when they first play the game, and if they are in survival. I don't think it would be too aggregous depending on how the tutorials are used by each individual mod, which is difficult to say and would ultimately fall down to the experience the mod wants to give the user. I don't think it's right for anyone to say that this shouldn't exist just because a mod might exist that might make it a bad experience for the user from our perspective. Is the point not to just give people to tools to extend it as they like?

We provide an API which is being used by developers which get passed onto the consumers. We need to think about how the system can be reasonably made and maintained, how the developers should use the system, and how the users will get to experience it. It's not 'we add in features because we can'. From my perspective, the benefits of adding in something that hooks into the tutorial system are minimal as it restricts modders into a single implementation to which the user may or may not see depending on how they accomplish their tasks. Additionally, all the data is shown as toasts, and any additional hooks would need to be implemented manually anyways. The most this would do is basically stop the user from making one method call in a different spot.

> Also, if we look at modpacks I believe that they can provide files with their modpack for the user settings. At which point they could turn off the tutorial toasts (in options.yml) or ask the makers of the mod to make the tutorials optional through some sort of configuration toggle. Or one step further, use the mod that was referenced above that completely disables the tutorial.

Ok, but then this is their own system. Why wouldn't the extension you are making be responsible for handling that information and updating the toasts in the correct manner? It's basically delegating all the work to the user while telling them to only use tutorial toasts rather than their own custom toast, which once again they can still add already.

> I think to conclude everything I've said above the most pertitent point for me is that I don't think we should hypothesize about how a mod might make a "worse" (from our perspective) experience for a user, because ultimately it's providing them the tools to create the experience they want.

But the tools already exist; you just want to use a specific implementation that is not patched. And once again, we must always think about the experience along with making it reasonable and maintainable. That is what good API design is.

**Comment by Shadows-of-Fire** [comment]
This is not something we are interested in pursuing / adding to the project, for reasons noted above by ash.

In summary, the tutorial system is poorly designed, and making it extensible does not fix the design issues.

**Pull request closed without merging**
