### PR TITLE
Fix PlayerInteractEvents not working

### LINKED ISSUE #5975: PlayerInteractEvent.RightClickBlock and PlayerInteractEvent.RightClickItem events not working
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.1 - 28.0.18

**Steps to Reproduce:**
 1. Subscribe to the `PlayerInteractEvent.RightClickBlock` event
 2. Subscribe to the `PlayerInteractEvent.RightClickItem` event

**Description of issue:**

The `PlayerInteractEvent.RightClickBlock` and the `PlayerInteractEvent.RightClickItem` event is not working.
I think the problem lies in the `PlayerInteractionManager` class.

The following lines existed in the code [prior to the 1.14.4](https://github.com/MinecraftForge/MinecraftForge/commit/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2) update:

https://github.com/MinecraftForge/MinecraftForge/blob/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2/patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch#L171-L172

https://github.com/MinecraftForge/MinecraftForge/blob/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2/patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch#L150-L151

After the 1.14.4 update they don't exist anymore.

### PR DESCRIPTION
**Pull request by henkelmax**
Fixes #5975

### CODE REVIEW

**Comment by cpw** [comment]
Is this complete? Does it completely restore these events? Or are there still gaps vs older versions?

**Comment by henkelmax** [comment]
I just put the code from prior versions in there.
All PlayerInteractEvents should work like before.

**Comment by wizjany** [comment]
Can confirm that this restores all the previous functionality, tested with worldedit's wands/tools.

There are some somewhat related issues with client velocity resetting when *cancelling* these events: see https://bugs.mojang.com/browse/MC-156451 https://hub.spigotmc.org/jira/browse/SPIGOT-5196
It's possible to alleviate some of this by lying to the client: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7f33c6a2f583e6a2ff68b460969c9cf12cb5f89f (or just modifying client code, since that's accessible here) but that may be out of scope of this issue or even of forge itself. The events being fired is working fine, which as far as I'm concerned at least, is good enough.

**Comment by bl4ckscor3** [comment]
Might want to consider readding the calls to IForgeItemStack#onItemUseFirst as well.

**Comment by Tfarcenim** [comment]
> Might want to consider readding the calls to IForgeItemStack#onItemUseFirst as well.

explains https://github.com/progwml6/ironchest/issues/193 and 1.14.3 metalbarrels having issues with it until I made a workaround

**Comment by wizjany** [comment]
Ok tterag told me that this needs some sort of feedback so:
These events are really important to us and probably quite a few other mods because
```We need the ability to detect left & right clicking air with and without items, and left & right clicking blocks with and without items```
These are not our own custom items, so we can't do something like overriding item use methods. The alternative is like, listening to packets or coremods.
I hope this is informative enough as to why these events are needed.

**Comment by LexManos** [comment]
There are probably about 15 code paths this doesn't cover. But I'm tired of people complaining about this.

**Comment by wizjany** [comment]
Sorry, didn't mean to sound like I was complaining. We were initially just wondering if this needed something more (testing, fixes, etc?), but tterrag said:

```
[10:44 AM] tterrag: even minor versions are a port when stuff breaks
[10:44 AM] tterrag: there's no other reason stuff breaks so this is the time we get to reconsider things
[10:44 AM] tterrag: could we decide it needs to stay as-is? sure
[10:44 AM] tterrag: but not if people don't TELL us that they need it
```

so I explained why we needed it. :upside_down_face:

**Pull request merged**
