### PR TITLE
Hook for Camera Angles, Including Roll

### PR DESCRIPTION
**Pull request by jamioflan**
Commit

### CODE REVIEW

**Comment by Abastro** [comment]
Squash your commits.

**Comment by jamioflan** [comment]
I'm not entirely sure how to do this now that I've pushed and PR'ed

**Comment by Parker8283** [comment]
Google is your friend

**Comment by psxlover** [comment]
Squash and force push. The pull request will be updated automatically.

**Comment by jamioflan** [comment]
Commits squashed

**Comment by clienthax** [comment]
Is it possible for you to add the ability to set the location of the camera ?

**Comment by jamioflan** [comment]
This is possible already through the Minecraft renderViewEntity. For my plane's tail camera I have an EntityCamera that follows the plane and use Minecraft.setRenderViewEntity

**Comment by clienthax** [comment]
In 1.8 mc changes the code for that so that the player isn't rendered if a
alternative view entity is set, so this would be preferable.

**Comment by jamioflan** [comment]
The position transform looks a lot more complicated. I believe Minecraft calculates the difference between each entity and the player and translates by that much, rather than doing an inverse player transform and then entity transformations.

Also, when can I expect the PR to be merged?

**Pull request merged**
