### PR TITLE
Load custom ITransformationServices from the classpath in dev

### LINKED ISSUE #8095: Custom ITransformationServices don't work in development environment
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.53

**Description of issue:**

If I understand this correctly, there is [ModDirTransformerDiscoverer](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java) to find jars with custom transformer services in the mods folder and load them into the service layer, so their transform services can be loaded. However, in development, this does not work as there is no mods folder. So the transform service is just not found.

### PR DESCRIPTION
**Pull request by noeppi-noeppi**
Continuation of #8118 for minecraft 1.18.

This fixes #8095 by adding an `ITransformerDiscoveryServices` to locate transformers from the classpath when launching a development launch target. It works similar to `ClasspathLocator` that locates mod files from the classpath.

Updates modlauncher to `9.0.21` to make use of the changes made in https://github.com/McModLauncher/modlauncher/pull/84

### CODE REVIEW

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Please provide an example project/code that can be used to confirm that this PR fixes the issue. My local testing using breakpoints and code inspection tells me that it should likely work, but I need an example to properly confirm it.

Also, is this PR meant to allow discovery of transformation services from the mod in the development environment itself, or only from mods found on the classpath of the development environment?

**Comment by noeppi-noeppi** [comment]
>  is this PR meant to allow discovery of transformation services from the mod in the development environment itself

No. In my opinion that would make little sense.
Because you can't put a regular mod together with a transformation service in one module, so if you wanted to load a transformation service from a userdev project, you would only have that transformation service, without a mod.
Also even if it should load these, it would probably be better to have something in ForgeGradle similar to [ModConfig](https://github.com/MinecraftForge/ForgeGradle/blob/FG_5.0/src/common/java/net/minecraftforge/gradle/common/util/ModConfig.java) but for transformers.

I also created an example project to confirm that the PR works: https://github.com/noeppi-noeppi/forge8350example

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
> > is this PR meant to allow discovery of transformation services from the mod in the development environment itself
> 
> No. In my opinion that would make little sense. Because you can't put a regular mod together with a transformation service in one module, so if you wanted to load a transformation service from a userdev project, you would only have that transformation service, without a mod. Also even if it should load these, it would probably be better to have something in ForgeGradle similar to [ModConfig](https://github.com/MinecraftForge/ForgeGradle/blob/FG_5.0/src/common/java/net/minecraftforge/gradle/common/util/ModConfig.java?rgh-link-date=2022-02-25T09%3A48%3A00Z) but for transformers.

Fair enough.

---

Confirmed that this works using the provided example project; it functions with the PR, and it does not (results in an `UnsatisfiedLinkError`) without the PR's changes.

Please update the license headers of the following modified file by changing the year of `2021` to the year `2022`:
- `fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java`

**Review by sciwhiz12 — APPROVED** [review]

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Please rebase this PR on the latest commit of the `1.18.x` branch and update the license headers in the following files:
- `fmlloader/src/main/java/net/minecraftforge/fml/loading/ClasspathLocatorUtils.java`
- `fmlloader/src/main/java/net/minecraftforge/fml/loading/ClasspathTransformerDiscoverer.java`
- `fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java`

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
