### PR TITLE
[1.15] Add Event for spreading blocks

### PR DESCRIPTION
**Pull request by cech12**
A new event which fires, when a "spreading" block (grass, mycelium, mushroom, sea pickle) possibly spread to another block.

It is fired when a block tries to check one block for spreading there. So GrassBlock for example tries to spread to 4 blocks at one (random) tick. So when this block checks the first position the Pre event will be fired. The event has a Result, which has following effects:

- Result.ALLOW: all vanilla checks are omitted and the spread will be done (when setBlockState method not failed).
- Result.DEFAULT: all vanilla checks are be done and the spread will be done when all conditions are fullfilled
- Result.DENY: no spreading will be done.

So for GrassBlock the Pre event will be fired 4 times and the Post event will be fired after every successful spread. With this event it is possible to limit or to enlarge the possible spreading of spreading blocks. Examples: grow mushrooms on other grounds, disable spreading of sea pickels, ...
The added test mod shows some other usecases.

Personal use case: I want to create a mod, where vanilla mushrooms can spread on other grounds and with different chances.

See also the discussion about this issue: #6207
See also these PRs: #6214 #6320

### CODE REVIEW

**Comment by variousauthors** [comment]
I can't wait to use this feature!

**Comment by Unnoen** [comment]
New features should be PR'd to the latest current version, currently 1.15.x. Please update this PR for that version. Only then will features be considered for backporting.

**Comment by cech12** [comment]
I updated it to 1.15

**Comment by cech12** [comment]
It is still an active PR. :)

**Comment by variousauthors** [comment]
Yeah, please don't close this it's awesome.

**Comment by cech12** [comment]
It is still an active PR. ;)

**Pull request closed without merging**
