### PR TITLE
Fix #7363 (Removing structures causes worlds to be unsaveable)

### LINKED ISSUE #7363: Removing structures leads to chunks being permanently unsaveable
This is a vanilla issue (MC-194811) but affects modded worlds a lot more often, so a fix should probably be made in forge.

In `ChunkSerializer.unpackStructureReferences`, the structure reference map `field_236365_a_` is queried but the resulting value is not null-checked. The result could be null if the mod that added that structure was later removed.

This means the returned map has a entry with key=null. Later on, when the game tries to save this (`ChunkSerializer.writeStructures`), it doesn't null check the keys of the map and blows up, meaning any progress made in this chunk is never saved.

Recommended solution: Add a null check to `unpackStructureReferences` and just skip it if the structure is not in the registry.

### PR DESCRIPTION
**Pull request by alcatrazEscapee**
See the issue, everything of note is documented there. This simply does as is recommended.

### CODE REVIEW

**Review by 50ap5ud5 — APPROVED** [review]

**Comment by 50ap5ud5** [comment]
This looks good. I can verify the fix works with a test mod I made: https://github.com/50ap5ud5/MinecraftForge/tree/chunk-fix-test. 

The way I tested this was: 

1. I created a new world and found one of my test structures
2. Saved the world save and closed it.
3. Disabled the registration of the structure in the test mod.
4. Opened up the game again and reopened the previous world.
5. The world is able to load successfully despite the console spamming `Unknown structure start: chunk_save_test:log_cabin`.
6. Placed some blocks around the chunk that the structure resided in.
7. Saved the world save and closed the game.
8. Reopen the game and reopen the previous world. Verified that the blocks placed were saved.

**Comment by alcatrazEscapee** [comment]
Lovely! Works for me 👍

**Comment by ichttt** [comment]
Why didn't you follow williewillus' suggenstion to just add a null check? As that's what vanilla seems to do everywhere else where it uses the map except at this place where it crashes

**Comment by alcatrazEscapee** [comment]
A number of reasons:

- Adding a null check would avoid the "illegal structure" message. This is desired as this is fundamentally changing the chunk (i.e. these structures are being removed and won't be regenerated if you enter the world again with the structure mod intact.) Making this loud in the log is good to keep.
- The method in question does not get passed the chunk - and so if a null key is detected, it cannot mark the chunk as modified (which it has been, since the structures have been removed and should be saved)
- This avoids a larger patch in `ChunkSerializer` than adding the null check + possibly modifying logging logic + figuring out a way to set the chunk as modified.

**Pull request merged**
