### PR TITLE
Add a timer for loading mods

### PR DESCRIPTION
**Pull request by ChunHin**
Just add a timer for knowing the time that loading mods take

### CODE REVIEW

**Comment by iTitus** [comment]
You do as lot of unneeded work here. Why don't you just use something like Google's Stopwatch?
Also the timer is a little bit too general. One cannot see what mods took the most time etc.

**Comment by ChunHin** [comment]
For convenience

**Comment by iTitus** [comment]
Furthermore seconds sometimes seem to be a pretty big unit for measuring time and sometimes they are to small. I would suggest to smartly switch between time units. I guess some of the libraries have a utility for that :P

**Comment by AlexIIL** [comment]
How about getting the time when you start loading mods and then subtracting it from the current time when you finish loading? That would stop you from relying on ````Thread.sleep```` keeping perfect time (hint: it doesn't), and removing an endlessly looping thread.

**Comment by iTitus** [comment]
Exactly. Use Stopwatch or the manual time difference approach. But if you are doing a timer, you can do it extensively by getting the loading times of each mod individually.

**Comment by iTitus** [comment]
Then I can finally just stop doing [this](https://github.com/iTitus/GimmeStuff/blob/master/src/main/java/io/github/ititus/gimmestuff/GimmeStuff.java#L40-L43).

**Comment by AlexIIL** [comment]
Forge already has this information in forge-client-latest.log, from the loading screen progress bars.

````
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BuildCraft Lib took 0.030s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BuildCraft took 0.071s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BC Builders took 0.001s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BC Energy took 0.000s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BC Silicon took 0.001s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - BC Transport took 0.001s
[18:35:46] [Client thread/DEBUG] [FML/]: Bar Finished: Initialization took 0.105s
````

(This is amongst the other log lines, I have removed a few of the event firing ones inbetween).

**Comment by iTitus** [comment]
Never had my log set to display DEBUG ;) Thanks.

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Pull request closed without merging**
