### PR TITLE
[1.19.x] BaseFireBlock.java.patch to use IForgeBlockState#isPortalFrame

### PR DESCRIPTION
**Pull request by JT122406**
#9138 is extension to what we talked about below this pr
Tested and working
Screenshot (94)
Screenshot (95)

### CODE REVIEW

**Comment by JT122406** [comment]
Part of plans to allow devs to easily allow custom blocks to be used as portal blocks down the line

**Review by Shadows-of-Fire — APPROVED** [review]

**Comment by JT122406** [comment]
I was wondering If I could remove the BlockGetter and BlockPos Parameters from isPortalFrame since they aren't used and don't need to be passed but lmk if I am ok to make that change

**Comment by pupnewfster** [comment]
For one thing that would be a breaking change, for others the reason they were included in the first place is in case any modded implementations want to make use of those values. Say if a mod wanted to have a block that is only a valid frame for getting out of the nether, but not for entering it.

**Comment by JT122406** [comment]
Yes I know it would be breaking, they can stay I was just looking like we don’t use them but you know

**Comment by KnightMiner** [comment]
Remember that for any method that is expected for mods to override, you cannot make an assumption the parameters are unused. They are added for the sake of overriding methods.

**Comment by JT122406** [comment]
Any eta on when this can/will be merged

**Comment by marchermans** [comment]
This is far from sufficient.
There are i am sure additional checks in the portal block itself so it can check if it needs to break or not which also need to be patched

**Comment by Shadows-of-Fire** [comment]
The other location is already patched (`PortalShape.FRAME`'s lambda)

**Comment by JT122406** [comment]
All of them have been handled or where handled already

**Pull request merged**
