### PR TITLE
[1.17.x] Add Custom Mirror Method Analogous to Rotate method to IForgeBlockstare and block

### PR DESCRIPTION
**Pull request by Raycoms**
As in the description. For certain blocks it is interesting to have the option to also do the mirror with the full world context.

### CODE REVIEW

**Comment by marchermans** [comment]
Good addition, but I think you might want to check if the call to the current method can be redirected.

**Comment by Commoble** [comment]
I agree that block entities need their own standardized way of rotating their data, but this isn't the right way to do it -- the biggest place where this is needed is when that data is being deserialized into a different rotation than what it was serialized into (e.g. structure pieces), which this doesn't help as there's no world context there.

**Comment by Raycoms** [comment]
I think the onlt alternative I can think of, is patching rotate and mirror methods back into the blockentities for 1.17, and then call it from the vanilla structure handler placement - pos placement.

**Comment by ChampionAsh5357** [comment]
To better elaborate, all places where `#mirror` is used has the necessary contexts as provided by the method parameters. The only place in `#rotate` would be for `StructureTemplate#filterBlocks`. From what I can tell, if you backtrace all the calls, you will eventually get the context needed for the level. However, patching all those is an insane idea and way to invasive for what this should be.

I think this may be more useful if this was split into two separate contexts: one for use after world gen when you have the world context fully present, and one for use during world gen where you can get the necessary structure info as required.

**Comment by SkullGamer205** [comment]
В письме от понедельник, 11 октября 2021 г. 00:29:52 +10 пользователь 
ChampionAsh5357 написал:
> To better elaborate, all places where `#mirror` is used has the necessary
> contexts as provided by the method parameters. The only place in `#rotate`
> would be for `StructureTemplate#filterBlocks`. From what I can tell, if you
> backtrace all the calls, you will eventually get the context needed for the
> level. However, patching all those is an insane idea and way to invasive
> for what this should be.
> 
> I think this may be more useful if this was split into two separate
> contexts: one for use after world gen when you have the world context fully
> present, and one for use during world gen where you can get the necessary
> structure info as required.

**Comment by sciwhiz12** [comment]
Hello! @Raycoms, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

**Pull request closed without merging**
