### PR TITLE
[1.9.4] Fixed sound paused/resume issue (Vanilla bug)

### PR DESCRIPTION
**Pull request by CreativeMD**
I recently posted an issue I ran into (https://github.com/MinecraftForge/MinecraftForge/issues/2907).
It should fix the vanilla bug. I recorded and uploaded  the issue, so it's easier to understand:
https://www.youtube.com/watch?v=rT9XxSCjIvU

The list of paused sounds doesn't get cleared after you leave or join a world. Once you rejoin it will continue the paused sounds again.
Unfortunately, this creates some kind of uncontrollable "background" sounds.

To fix this I added "pausedChannels.clear();" to stopAllSounds(). It will remove all paused sounds once you join or leave a world.
That has fixed the issue and hasn't raised any new ones (at least non i know of :D).

In Regards CreativeMD

### CODE REVIEW

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Vanilla Bug]

**Comment by CreativeMD** [comment]
Test it for 1.10. The bug is still present, nothing has changed about it.

**Comment by LexManos** [comment]
Retarget for the 1.10.0 branch.
And be sure to adda  comment to explain why that line is patched in.
If this is is reported on Mojang's bug tracker something like this:
//Forge: MC-##### Fixed paused sounds repeating when switching worlds
Where ##### is the Mojiria id for the vanilla bug.

**Comment by CreativeMD** [comment]
Do you mean i should create another pull request targeted for 1.10.0? I'm sorry, never have done this before.

**Comment by kashike** [comment]
Open a new PR targeted to the `1.10.0` branch.
Your comment should include the [Mojira](https://bugs.mojang.com/) issue id as well.

**Comment by williewillus** [comment]
can we get the fix 1.9.4 as well?

**Comment by CreativeMD** [comment]
@kashike ok, i will create another pull request for 1.10.0, but this bug isn't reported (at least not by me). So there is no Mojang issue id.

**Comment by williewillus** [comment]
this is the closest vanilla ticket https://bugs.mojang.com/browse/MC-35856

**Pull request closed without merging**
