### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by Mazdallier**
Hard job

### CODE REVIEW

**Comment by robin4002** [comment]
All translations are here : https://crowdin.com/project/minecraft-forge 
Please stop the pull request for translations.

**Comment by Mazdallier** [comment]
Ok.
Could you please wrtite this link into your readme.txt ?

**Comment by robin4002** [comment]
I can't unless I do a pull request.
However it would be a shame to lose all that you have done, some of your translations are better than the one on the crowdin project, so you should post them on the crowdin project.

**Comment by Mazdallier** [comment]
I'll take a look when i have time...

**Comment by AegisLesha** [comment]
Damn, you're so better than me Mazdallier... D:

**Pull request closed without merging**
