### PR TITLE
Add missing semi-colon near the Dist import statement.

### PR DESCRIPTION
**Pull request by ghost**
Add missing semi-colon near the Dist import statement.

### CODE REVIEW

**Comment by fbricon** [comment]
That one is a no-brainer. Current MDK cannot compile.

**Review by ChampionAsh5357 — APPROVED** [review]
🤦 for the original owner and all the triage members who missed it.

**Comment by fbricon** [comment]
Ideally, the CI build should have caught it immediately. 
🤷

**Comment by marchermans** [comment]
> Ideally, the CI build should have caught it immediately. 🤷

The CI currently does not build the MDK.
So changes to it are not validated.

**Comment by fbricon** [comment]
> > Ideally, the CI build should have caught it immediately. 🤷
> 
> The CI currently does not build the MDK. So changes to it are not validated.

That was my understanding, maybe something you guys would like to change in the future. But I'm just a bystander, you guys decide whether this is something you want to open a ticket for.

**Comment by LexManos** [comment]
Yes, obviously having more validations so that things like this don't slip through the cracks would be better. Human are human, so they error. However it's just not something that has been written yet. And this particular issue is a bit of a chicken egg scenario as in order to build the MDK we need to have the forge version published. Which requires it to be merged, which requires it to pass validation. There are ways around this yes, they just haven't been written yet.

So it's on the TODO.

As for this particular issue. Ya its a one character missing in a place no sane person would ever screw up. It's kinda understandable that it was missed. Its on the list of minor cleanups.

**Pull request merged**
