### PR TITLE
[1.10.x] ItemStack and Armor Enchantment Overlay Control 

### PR DESCRIPTION
**Pull request by RANKSHANK**
Cleanup & resubmission of my haphazard/retarded gitting of #3076 as per the request of @cpw 
## Overview

This entirely replaces the enchantment effect overlay of ItemStacks and armor models. This allows for modders to control the overlays via the instantiation and registry of IItemOverlay and IArmorOverlay for respective control, defaulting to vanilla appearance if no handler is registered. 
ezgif-1117484056
#### Test mod

Test mod modifies the overlay of vanilla's leather chest armor. Enchant it and the effects will be apparent in item form and when equipped.

### CODE REVIEW

**Comment by mezz** [comment]
I was worried this might hurt performance since it didn't look very efficient, so I did a test. 

### Test setup:
Open inventory full of night vision potions
Uncapped fps
Flat world
Teleported to 4096 Y
Clouds off
Measure number of frames using a FRAPS benchmark over 1 minute.

### Results:
Before PR:
Frames: 25486 - Time: 60000ms - Avg: 424.767 - Min: 409 - Max: 430

With PR:
Frames: 25036 - Time: 60000ms - Avg: 417.267 - Min: 409 - Max: 423

### Interpretation:
This is about a 1.8% loss in performance when rendering overlays and hardly anything else. Forge is already 17% faster than Vanilla in a very similar test after Fry fixed this issue here: https://github.com/MinecraftForge/MinecraftForge/issues/2269. In real gameplay this performance hit will not be noticeable.

**Comment by RANKSHANK** [comment]
Thanks @mezz! I'm definitely glad to see it's not a performance hog :P

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by asiekierka** [comment]
Neat. I think it's worth the tiny decrease in performance.

**Comment by RANKSHANK** [comment]
So now that @RainWarrior is back I'm going to bump this as I'd like to see whereabouts the standing is on this

**Comment by RANKSHANK** [comment]
Any news here?

**Comment by mezz** [comment]
Please update this to target 1.11, new features are no longer being merged into 1.10.
This PR is already tested as working so I think it should be considered soon.

**Comment by RANKSHANK** [comment]
closed for 1.11 bump

**Pull request closed without merging**
