### PR TITLE
Several bugfixes for PlayerInteractEvent

### PR DESCRIPTION
**Pull request by williewillus**
Several minor bugfixes for PlayerInteractEvent.

Remake of #2880 for master, see that PR for details.

### CODE REVIEW

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by LexManos** [comment]
If shit breaks blame @williewillus Still dont think we should be firing ANYTHING client side but whatever.

**Comment by williewillus** [comment]
That's like your phrase now huh :P

**Comment by LexManos** [comment]
For shit that people yell at me about and dont satisfactory explain themselves and then I have to deal witht eh bitching of it.. yes..
Your PR your problem.

**Pull request merged**
