### PR TITLE
Hide Potion effects that have no icon and display no text

### PR DESCRIPTION
**Pull request by bonii-xx**

### CODE REVIEW

**Comment by bonii-xx** [comment]
Reference picture how it looks without the fix: https://i.imgur.com/f3uipRo.png

**Comment by diesieben07** [comment]
This would break mods which render their potion icons manually from their own texture sheet using `renderInventoryEffect`.

**Comment by bonii-xx** [comment]
Hm, right. Didn't see that the hasStatusIcon callback is only used for vanilla icon rendering. Why do potion effects without text exist? :P
Could be solved by either not allowing that or having a separate callback. Not sure which one would be better.

**Comment by laci200270** [comment]
Maybe an interface for this?

**Comment by bonii-xx** [comment]
Simple callback is more flexible and faster.

**Comment by cpw** [comment]
@bonii-xx OK, what do you want to do here?

**Comment by bonii-xx** [comment]
Updated with an additional shouldRender callback to detect hidden potions. Decide what you think about it, then I can squash it.

**Comment by cpw** [comment]
Update for 1.8.8?

**Pull request closed without merging**
