### PR TITLE
[1.19.x] Recipe ID-based grouping between modded and vanilla recipes.

### PR DESCRIPTION
**Pull request by bconlon1**
This PR changes some of ClientRecipeBook's grouping behavior to allow for recipes without set groups to have an internal "group" within the grouping table based on the id of the recipe. This allows for modded recipes to be grouped with vanilla recipes, without having to do any overriding of the vanilla recipe's json to add a group manually, simply by setting a group on the modded recipe that matches the ID of the vanilla recipe.

Attached is the datapack for testing this PR's changes. It contains a new TNT recipe that groups itself with the existing vanilla TNT recipe with the ID `"minecraft:tnt"`: [datapack.zip](https://github.com/MinecraftForge/MinecraftForge/files/9183655/datapack.zip).

Screenshot of the relevant datapack recipe file:
unknown (2)

Screenshots of the datapack in action:
unknown
unknown (1)

### CODE REVIEW

**Review by sciwhiz12 — APPROVED** [review]

**Comment by bconlon1** [comment]
Edited original description to contain the datapack for testing and screenshots of the changes in action.

**Comment by bconlon1** [comment]
Up to date with 1.19.1.

**Comment by LexManos** [comment]
Patch wise it's fine. But I personally think this is a bad idea in of itself. So i'll leave it to others on the team.

**Comment by bconlon1** [comment]
Would you be able to provide elaboration on why you find the idea for this PR bad? Is it the choice of implementation or the feature itself?

**Comment by bconlon1** [comment]
To add more additional information about this PR, here was the relevant Discord discussion about it: https://discord.com/channels/313125603924639766/852298000042164244/997645897901019238

**Comment by TheCurle** [comment]
Sorry for the wait on this one.

**Pull request merged**
