### PR TITLE
Remove deprecated Fluid stuff, update Fluid capabilities and FluidUtil for 1.11

### PR DESCRIPTION
**Pull request by mezz**
This is preparation for the next breaking-change update.

The remaining fluids handling will need more work to support immutable ItemStacks, but this is a starting point.

Tested in-game, and it also passes Forge's FluidHandlerTest.

Without universal bucket:

```
[FML]: Draining 1 Bucket (minecraft) gives no fluid and 1 Bucket (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB Water gives 1 Water Bucket (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB Lava gives 1 Lava Bucket (minecraft)
[FML]: Draining 1 Water Bucket (minecraft) gives 1000mB Water and 1 Bucket (minecraft)
[FML]: Draining 1 Lava Bucket (minecraft) gives 1000mB Lava and 1 Bucket (minecraft)
[FML]: Draining 1 Milk (minecraft) gives no fluid and 1 Milk (minecraft)
```

With universal bucket and forge's debug fluids:

```
[FML]: Draining 1 Bucket (minecraft) gives no fluid and 1 Bucket (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB fluid.testfluid gives 1 fluid.testfluid Bucket (forge)
[FML]: Filling 1 Bucket (minecraft) with 1000mB Water gives 1 Water Bucket (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB fluid.milk gives 1 Milk (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB Lava gives 1 Lava Bucket (minecraft)
[FML]: Filling 1 Bucket (minecraft) with 1000mB fluid.testgas gives 1 fluid.testgas Bucket (forge)
[FML]: Draining 1 Water Bucket (minecraft) gives 1000mB Water and 1 Bucket (minecraft)
[FML]: Draining 1 Lava Bucket (minecraft) gives 1000mB Lava and 1 Bucket (minecraft)
[FML]: Draining 1 Milk (minecraft) gives 1000mB fluid.milk and 1 Bucket (minecraft)
[FML]: Draining 1 fluid.testfluid Bucket (forge) gives 1000mB fluid.testfluid and 1 Bucket (minecraft)
[FML]: Draining 1 fluid.testgas Bucket (forge) gives 1000mB fluid.testgas and 1 Bucket (minecraft)
```

### CODE REVIEW

**Comment by Actuarius** [comment]
@mezz added labels [Cleanup, BreakingChange, Fluids]

**Comment by Daomephsta** [comment]
@mezz 
Unless there's something from Mojang I haven't seen, ItemStacks aren't being made immutable. I decompiled 16w38a and only ItemStack#item has been made final; stackSize, damage, stackTagCompound, etc. are all still mutable.

**Comment by mezz** [comment]
Yes, you're correct.

Unfortunately the fluid handlers actually swap out the `item` in a few places, using `ItemStack.serializeNBT()` and `ItemStack.deserializeNBT()`. This is done for items where the empty and filled versions are different items, like filling a Vanilla bucket with biomass to get Forge bucket.

This will have to be changed to swap the ItemStack held by a player instead of changing the ItemStack itself. Other cases like dispensers and machines that handle the buckets could be more complicated, I'm not sure yet.

**Comment by LexManos** [comment]
Yes, this needs tobe looked into, to see what is nessasary to break int he API to facilitate that itemstack swapping.
We've spoken about that before and the only reason it currently uses the hack-around method is so that it can keep compatibility with older APIs.
In 1.11 we will be breaking this API so that it is standard practice to also be able to return the itemstack that should be the new replacement.

**Comment by mezz** [comment]
Pushed a new commit to Implement fluid item capabilities without item swapping.
It adds a new capability `IFluidHandlerItem` in order to get the ItemStack from the fluid handler after it has been altered, there's no way around it unfortunately.

Passes the fluids tests, I checked dispensers and machines as well as in-world interaction from the player.
Checked stacked buckets, containers that are single-use, and regular single-stack items.
Tested against an experimental Forestry branch here: https://github.com/ForestryMC/ForestryMC/tree/forge-fluid-item

**Comment by mezz** [comment]
Updated version here: #3380

**Pull request closed without merging**
