### PR TITLE
[1.12] Allow the server to handle item-block interaction if onItemUse doesn not return PASS

### PR DESCRIPTION
**Pull request by malte0811**
Port of #3951 to 1.12.

### CODE REVIEW

**Comment by mezz** [comment]
Looks good. Please resolve the merge conflicts.

**Comment by malte0811** [comment]
I've fixed the merge conflict.
I've also changed the behavior of the test item: It no longer has one version with the hacky implementation many mods use to get it partially working and one that always returns `SUCCESS` since the hacky implementation never works correctly (and isn't intended to). There is one variant for every return value now. I call `EnumActionResult.values()` multiple times without caching the result, I don't know whether that is an issue in debug mods.
Unrelated: There are a lot of errors in the log related to `crafting_system_test` and some missing models for other test mods. Are those known/intended?

**Comment by mezz** [comment]
The `crafting_system_test` log is intentional.
The other error messages are not intentional, and only showed up after this PR was merged https://github.com/MinecraftForge/MinecraftForge/pull/4120
I'll work on fixing the messages some time.

**Comment by mezz** [comment]
Tested and looks good to me.

**Pull request merged**
