### PR TITLE
Remove unused lines

### PR DESCRIPTION
**Pull request by ghost**
these lines were supposed to increase the damage, but this lines do not work and has no effect on actual gameplay and can be removed.
before patch:
screenshot from 2018-08-17 13-24-17
and after patch:
screenshot from 2018-08-17 13-26-59

### CODE REVIEW

**Comment by loordgek** [comment]
what are you doing 
you modified the test mod that has nothing to do w/ your heavy diamond sword

**Comment by ghost** [comment]
loordgek  https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/test/java/net/minecraftforge/debug/item/ShieldTest.java#L69

**Comment by loordgek** [comment]
whaat ?? i dont follow you

**Comment by loordgek** [comment]
@LWJGLRobot please take this to http://www.minecraftforge.net/forum/forum/70-modder-support/

**Comment by Jeryn99** [comment]
From my understanding, you've just edited a test mod that has no affect on forge as a whole at all?
You don't seem too sure of what you just edited either with your ``maybe`` in ``maybe these lines were supposed to increase the damage, but this lines does not work and can be removed``

**Comment by ghost** [comment]
yes it has no effect on forge at all.
no i sure that this lines does not need.

**Comment by ghost** [comment]
i said that this lines were supposed to increase the damage, but they do not work and some people said that test modes must not change gameplay and that why i created this pull request.

**Comment by loordgek** [comment]
test mods are for testing the things that got added to forge to prove that it works

**Comment by ghost** [comment]
@loordgek yes it is, but this lines of code do not work.

**Comment by Lunatrius** [comment]
Hint:
```java
if(slot == EntityEquipmentSlot.MAINHAND)
```

**Comment by ghost** [comment]
@Lunatrius 
screenshot from 2018-08-17 17-55-35

**Pull request closed without merging**
