### PR TITLE
Added isItemValidForSlot check

### PR DESCRIPTION
**Pull request by Draco18s**
Adding check to insure the extracted item can actually be inserted into the destination inventory. Allows custom hoppers that have item-restricted slots (e.g. filters) without having to duplicate 230 lines of private hopper code.

### CODE REVIEW

**Comment by Draco18s** [comment]
I don't know why it pulled so much history in, it's just the commits from the previous PR I did for VanillaInventoryCodeHooks. (Nor do I know why the first commit today decided that what I did was remove a line of code, making me do another commit that was my actual change...).

**Comment by AEnterprise** [comment]
the number of commits shouldn't matter anymore as they can be squached by github when merging

**Comment by Draco18s** [comment]
Yeah I know, it was just not something the preview showed me.  Still don't know why my first commit today removed the line entirely (I didn't even notice that it did that until I went to make the PR, went back to Git and saw that it saw new changes and had to make another commit, but no files on my computer had changed).  Was the weirdest thing I've ever seen.

**Comment by mezz** [comment]
I think you should update this for 1.11.x, `VanillaInventoryCodeHooks` was just rewritten.

**Comment by Draco18s** [comment]
@mezz Looks to me like the same alteration I made here would need to be made to the 1.11 one (that is, checking for insert).  The code *around* my change isn't the same, but I am pretty sure the change I made would be identical.  I can certainly do a PR for the 1.11 branch as well, though.

**Comment by mezz** [comment]
I suspect this change is no longer needed because the item handler will check if the stack is valid when the hopper tries to insert it. Please test and see.

**Comment by Draco18s** [comment]
I will do so, but I am making the PR for 1.10

**Pull request merged**
