### PR TITLE
Simple block with item Method 

### PR DESCRIPTION
**Pull request by JT122406**
similar to #9170 but makes a new method that only takes in a block then uses cubeAll to make a model.
Similar to 
public void simpleBlock(Block block) {
        simpleBlock(block, cubeAll(block));
    }

but makes the item with one call making life a little bit easier for modders

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
What benefit does this provide over the previous `#simpleBlockWithItem` you introduced? It constructs the model twice, which is redundant, and provides no greater clarity than using `#simpleBlockWithItem(block, #cubeAll(block))`. I also don't know how it would make life easier for modders since, as shown, the call is something that already had to be previously done.

**Comment by JT122406** [comment]
> What benefit does this provide over the previous `#simpleBlockWithItem` you introduced? It constructs the model twice, which is redundant, and provides no greater clarity than using `#simpleBlockWithItem(block, #cubeAll(block))`. I also don't know how it would make life easier for modders since, as shown, the call is something that already had to be previously done.

So the idea is to be similar to the simpleBlock methods while also creating a item with it and there are 2 simple block methods one that takes in a model file which I made in the last pr and one that just takes in the block and uses cubeAll() this is to go with the second one where the block is cubeAll() automatically instead of having to also add in the cubeAll() when using the message it's more like an enhancement to the current structure.

**Comment by ChampionAsh5357** [comment]
> it's more like an enhancement to the current structure.

But why is it an enhancement? You've yet to explain what is the benefit of this over writing the one line itself. If it's just so you have to write one less argument, I would disagree. Removing the argument for a `#cubeAll` default is less understandable than passing it in yourself. I can agree with the first PR as most blocks do have an item associated with it. However, blocks involved with a mod will probably have states or multiple models making this default not as useful. It's harder to read and understand because of the method name and its general purpose. It is much more understandable to say that this block has this model for its block/item, compared to this block is a cube model for its block/item. Additionally, if I gave you two methods `#simpleBlockWithItem(block)` and `#simpleBlockWithItem(block, cubeAll(block))`, which one is clearer to understand? The first gives no information on what it's doing since 'simple' is unclear while the second provides context.

All in all, this method would probably show up in the forge docs, but I wouldn't consider it an addition to Forge unless oyu address this point.

**Comment by JT122406** [comment]
> > it's more like an enhancement to the current structure.
> 
> But why is it an enhancement? You've yet to explain what is the benefit of this over writing the one line itself. If it's just so you have to write one less argument, I would disagree. Removing the argument for a `#cubeAll` default is less understandable than passing it in yourself. I can agree with the first PR as most blocks do have an item associated with it. However, blocks involved with a mod will probably have states or multiple models making this default not as useful. It's harder to read and understand because of the method name and its general purpose. It is much more understandable to say that this block has this model for its block/item, compared to this block is a cube model for its block/item. Additionally, if I gave you two methods `#simpleBlockWithItem(block)` and `#simpleBlockWithItem(block, cubeAll(block))`, which one is clearer to understand? The first gives no information on what it's doing since 'simple' is unclear while the second provides context.
> 
> All in all, this method would probably show up in the forge docs, but I wouldn't consider it an addition to Forge unless oyu address this point.

I'm not going to lie what you say makes a lot of sense I just thought it was a good idea to match simple block argument method

**Comment by ChampionAsh5357** [comment]
> I just thought it was a good idea to match simple block argument method

That's fine, but typically a PR needs a reason to the benefit to the modder and why an existing alternative is not better when adding a new feature. If every PR was accepted because it was a good idea, then there would be a lot more things in forge, but also a lot more redundancy. That's not to say every idea is bad or that every good idea gets in, there just needs to be some explanation as to why such a thing exists, a triage member who is able to review it, and an admin okay with the addition such that it gets merged in.

**Pull request closed without merging**
