### PR TITLE
Add LoadRenderersEvent

### PR DESCRIPTION
**Pull request by josephcsible**
Intended for mod blocks that want to have fast/fancy renders like
vanilla BlockLeaves (Blocks.field_150361_u and Blocks.field_150362_t).

### CODE REVIEW

**Comment by williewillus** [comment]
you can just do that with `IResourceReloadListener`, right?

**Comment by marvin-roesch** [comment]
Even if the event was required, I'd suggest naming it something different. `LoadRenderersEvent` is way too generic for this specialized usecase.

**Comment by josephcsible** [comment]
@williewillus It looks like only calls to `loadRenderers()` that come from `Minecraft.refreshResources()` will end up calling `notifyReloadListeners()` to do things you register as `IResourceManagerReloadListener`. Many other code paths don't seem to, mainly the one that I specifically care about here: the one where `fancyGraphics` actually gets changed in `GameSettings.setOptionValue()`.

@PaleoCrafter I'm not sure what else to call it, though.

**Comment by williewillus** [comment]
@josephcsible yes but if you set the option directly it wouldn't even work for vanilla leaves. The vanilla option gui triggers a resource reloads every time you toggle Fast<->Fancy. That's the only way the switch actually works.

**Comment by josephcsible** [comment]
Fair enough.

**Comment by josephcsible** [comment]
> The vanilla option gui triggers a resource reloads every time you toggle Fast<->Fancy.

@williewillus I just did a quick test, and that doesn't appear to be the case. `onResourceManagerReload` doesn't get called when I just change fast/fancy; I need to do something drastic like F3+T for it to get called.

**Comment by Niko-sk2x** [comment]
I'm actually not sure why this is even needed...
Different model depending on fast/fancy graphics is entirely possible with a custom baked model.

**Comment by covers1624** [comment]
Vanilla uses this to switch what render layer leaves are on. honestly you could just use Minecraft.isFancyGraphicsEnabled instead of assigning a field like vanilla does.

**Comment by josephcsible** [comment]
@covers1624 changing render layer actually all I'm doing too. I'm even doing exactly what you suggested as a workaround for now, but I feel like it's not the right way to do it, because if it was, why don't vanilla leaves just do it that way?

**Comment by marvin-roesch** [comment]
You've answered your own question, basically. Mojang is doing this in a roundabout way, that doesn't mean mods need to (God forbid *should*) do the same.

**Comment by josephcsible** [comment]
@PaleoCrafter My worry is that Mojang does have a good reason for doing it that way, and we just don't know it. Your response makes it sound like that's not the case, though.

**Comment by williewillus** [comment]
iirc it's been this way for a long time, so the reason is probably "forgotten legacy code"

**Comment by covers1624** [comment]
Yeah, im fairly sure its just legacy code. I dont see any use for this event besides doing what vanilla does with their leaves.

**Comment by LexManos** [comment]
Mojang with non-optimal/legacy code? 
Shocked

Anyways it looks like you have a working system without the hook so closing this.

**Pull request closed without merging**
